Implement `integer, parameter :: x(*) = [1, 2, 3]`
lfortran/lfortran pull request #1016
Opened 2022-11-15 17:31 UTC by Pranavchiku

Resolves #967

2022-11-17 03:54 UTC, czgdp1807 commented on src/lfortran/semantics/ast_common_visitor.h
> +        AST::dimension_t *m_dim, size_t n_dim, int &is_compile_time=temp_value) {
Why can't we make `is_compile_time` a compulsory argument? I guess we will just need to update calls to `process_dims` calls which is fine.

2022-11-17 06:13 UTC, czgdp1807 requested changes

2022-11-17 06:13 UTC, czgdp1807 commented on tests/tests.toml
> +llvm = true
```suggestion
```

LLVM not needed. Already running via `integration_test/const_array_01.f90`

2022-11-17 06:13 UTC, czgdp1807 commented on tests/array10.f90
> +end
```suggestion
program const_arrays
	integer, parameter :: x(*) = [4, 9, 6, 12, 13]
	print *, x
end

```

2022-11-18 23:10 UTC, certik requested changes
Otherwise looks good I think. Thank for fixing it!

2022-11-18 23:10 UTC, certik commented on src/lfortran/semantics/ast_common_visitor.h
> +        AST::dimension_t *m_dim, size_t n_dim, int &is_compile_time) {
```suggestion
        AST::dimension_t *m_dim, size_t n_dim, bool &is_compile_time) {
```
Also it is not initialized in all cases. You have to set `is_compile_time = false` at the beginning of the function.

2022-11-18 23:10 UTC, certik commented on src/lfortran/semantics/ast_common_visitor.h
> +                        int is_compile_time = 0;
```suggestion
```

2022-11-18 23:10 UTC, certik commented on src/lfortran/semantics/ast_common_visitor.h
>                              dims.reserve(al, 0);
Add
```c++
                            bool is_compile_time;
```
here.

2022-11-18 23:10 UTC, certik commented on src/lfortran/semantics/ast_common_visitor.h
> +                int is_compile_time = 0;
```suggestion
                bool is_compile_time = false;
```

2022-11-19 10:43 UTC, czgdp1807 approved these changes

2022-11-19 17:21 UTC, certik approved these changes
Thanks!

2022-11-19 17:21 UTC, merged