Use m_vartype (ArrayInitializer) to get the initializer type.
lfortran/lfortran pull request #1070
Opened 2022-12-05 05:26 UTC by Thirumalai-Shaktivel

2022-12-05 05:28 UTC, czgdp1807 requested changes

2022-12-05 05:28 UTC, czgdp1807 commented on integration_tests/arrays_20.f90
> +end program arrays_20
Please register this in `tests.toml` as well. I guess we should make sure the types are getting set correctly in ASR.

2022-12-05 05:30 UTC, Thirumalai-Shaktivel commented on integration_tests/arrays_20.f90
> +end program arrays_20
Only ASR, right?

2022-12-05 06:23 UTC, czgdp1807 commented on tests/reference/asr-arrays_20-cb6ba8f.stdout
> +                            (Character 1 1 () [((IntegerConstant 1 (Integer 4 []))
I guess this should have the same type as `list_character`? How is this having no length attribute. If its taking compile time value of length then it should be 5.

2022-12-05 08:17 UTC, certik commented
If it compiles with LLVM, then compile it. But in addition, if there is some tricky stuff you want to make sure works in ASR, then add an ASR test.

2022-12-05 13:56 UTC, Thirumalai-Shaktivel commented on tests/reference/asr-arrays_20-cb6ba8f.stdout
> +                            (Character 1 1 () [((IntegerConstant 1 (Integer 4 []))
Also, can you please share how the compile time value of `len(string)` is calculated? is it using the `eval_len` in `compiletime_eval.h`?

2022-12-07 06:18 UTC, czgdp1807 commented on tests/reference/asr-arrays_20-cb6ba8f.stdout
> +                            (Character 1 1 () [((IntegerConstant 1 (Integer 4 []))
Yes.

2022-12-10 13:47 UTC, czgdp1807 approved these changes
LGTM.

2022-12-12 03:33 UTC, Thirumalai-Shaktivel commented
Thanks for the approval! Let's merge this.

2022-12-12 03:34 UTC, merged