Load the ASR runtime library
lfortran/lfortran pull request #1095
Opened 2022-12-10 04:15 UTC by certik

2022-12-10 21:34 UTC, certik commented
The Windows error is caused by https://github.com/lfortran/lfortran/issues/1097.

2022-12-10 21:36 UTC, certik commented
@czgdp1807 what would you recommend with the design here? I want to get something in rather quickly, and improve upon later, but not sure how to best organize things.

I want to setup some CI tests for this as well, that would fail without this change.

2022-12-11 06:50 UTC, czgdp1807 commented
Looks fine to me for now. 

> I want to setup some CI tests for this as well, that would fail without this change.

I would be able to comment better once such a test is added.

2023-01-04 22:43 UTC, certik commented
TODO:

* [ ] use minpack to create a minimal test in our integration_tests that fails and this PR fixes it

2023-01-04 22:43 UTC, certik commented
@Pranavchiku do you want to give this PR a shot and finish it?

2023-01-05 03:52 UTC, Pranavchiku commented
Yeah sure!

2023-01-05 18:42 UTC, certik commented
To write a test, create a file that calls "sin", then compile it separately using `--generate-object-code`, then in the main program, call some function from the other file. It should fail to link (missing "sin"). Then this PR should fix it. The main program must be compiled with `--rtlib`.

To test it in cmake, we can either improve the "llvm2" test to do this, or write a new "llvm3" test.

2023-01-08 11:19 UTC, Pranavchiku commented
I have created minimal examples that will surely produce error, I just need to figure out how to link 3 files that I am using one is a.f90, b.f90, c.f to compile.
Apologies for taking much time over it.

2023-01-08 14:34 UTC, Pranavchiku commented
The added tests fail in the main and this PR fixes it. I tested it in the same way we compile `minpack`. I will change `CMakeLists.txt` as soon as possible.

2023-01-08 14:51 UTC, czgdp1807 requested changes

2023-01-08 14:51 UTC, czgdp1807 commented on src/lfortran/semantics/ast_to_asr.cpp
> +        if (compiler_options.rtlib) load_rtlib(al, *tu, compiler_options);
How are we testing this option in CI? I guess we need to pass it via command line options in `integration_tests/CMakeLists.txt` in order to test it. Please follow the existing patterns and add some support for testing this option in `integration_tests/CMakeLists.txt`.

2023-01-08 14:53 UTC, Pranavchiku commented on src/lfortran/semantics/ast_to_asr.cpp
> +        if (compiler_options.rtlib) load_rtlib(al, *tu, compiler_options);
Yeah, sure!

2023-01-09 08:22 UTC, Pranavchiku commented
@certik @czgdp1807 I added provision to test it in CI, kindly have a look and comment on the correctness of it.

2023-01-09 14:48 UTC, czgdp1807 commented on integration_tests/CMakeLists.txt
> +        elseif (LFORTRAN_BACKEND STREQUAL "llvm3")
Some better name like, `llvm_rtlib`?

2023-01-10 16:28 UTC, czgdp1807 approved these changes

2023-01-10 16:34 UTC, czgdp1807 commented on src/lfortran/semantics/ast_to_asr.cpp
> +        // if (compiler_options.rtlib) load_rtlib(al, *tu, compiler_options);
```suggestion
        if (compiler_options.rtlib) load_rtlib(al, *tu, compiler_options);
```

2023-01-10 20:12 UTC, certik commented on src/lfortran/semantics/ast_to_asr.cpp
> +        if (compiler_options.rtlib) load_rtlib(al, *tu, compiler_options);
It fails like this:
```
[100%] Linking Fortran executable minpack_01
Undefined symbols for architecture arm64:
  "___module_lfortran_intrinsic_math2_dabs", referenced from:
      _enorm1 in minpack_01_func.f90.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
The command 'clang -o minpack_01 CMakeFiles/minpack_01.dir/minpack_01.f90.o CMakeFiles/minpack_01.dir/minpack_01_module.f90.o CMakeFiles/minpack_01.dir/minpack_01_func.f90.o  -L"/Users/ondrej/repos/lfortran/lfortran/src/bin/../runtime" -Wl,-rpath,"/Users/ondrej/repos/lfortran/lfortran/src/bin/../runtime" -llfortran_runtime -lm' failed.
```

2023-01-10 20:17 UTC, certik commented on src/lfortran/semantics/ast_to_asr.cpp
> +        if (compiler_options.rtlib) load_rtlib(al, *tu, compiler_options);
Here it is being tested by the CI: https://github.com/lfortran/lfortran/pull/1174

2023-01-10 20:38 UTC, merged