Add warning for implied `save`
lfortran/lfortran pull request #1201
Opened 2023-01-21 05:24 UTC by Pranavchiku

Fixes #1198.

2023-01-21 06:09 UTC, certik commented on tests/reference/asr-allocate_01-27536f3.stderr
> +  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Assuming save attribute implicitly for variables
This is not implied save. The warning should only trigger for things like:
```
integer :: a = 5
```
and for arrays too.

2023-01-21 06:10 UTC, certik requested changes
I think it's too broad.

2023-01-21 19:45 UTC, Pranavchiku commented
I tried to narrow it down just to what was told in code review

2023-01-22 03:34 UTC, certik commented
Thanks!  This starts to look good, I didn't realize we use implied save at so many places... Probably most of these tests should be changed to include "save" in them, to reduce the warning. Let me think about this.

2023-01-22 03:36 UTC, certik commented on tests/reference/pass_inline_function_calls-functions_05-9883f29.stderr
> +  |     ^^^^^^^^^^^^^^^^^^^ Assuming save attribute implicitly for variables
Let's highlight just the symbol and assignment itself, say `x = 5`, but not `y`. So something like:
```
integer :: x = 5, y
           ^^^^^
```

2023-01-22 03:37 UTC, Pranavchiku commented on tests/reference/pass_inline_function_calls-functions_05-9883f29.stderr
> +  |     ^^^^^^^^^^^^^^^^^^^ Assuming save attribute implicitly for variables
Okay sure! I will do that changes.

2023-01-22 05:36 UTC, Pranavchiku commented on tests/reference/pass_inline_function_calls-functions_05-9883f29.stderr
> +  |     ^^^^^^^^^^^^^^^^^^^ Assuming save attribute implicitly for variables
What about case
```fortran
integer :: x, y
x = 5
```
According to above suggestion, it will result in 
```
integer :: x, y
x = 5
^^^^^
```

2023-01-23 14:59 UTC, czgdp1807 approved these changes

2023-01-23 18:26 UTC, certik commented on tests/reference/pass_inline_function_calls-functions_05-9883f29.stderr
> +  |     ^^^^^^^^^^^^^^^^^^^ Assuming save attribute implicitly for variables
The case:
```
integer :: x, y
x = 5
```
is not implied save, that is just a declaration of `x` and an assignment statement, so there should be no warning.

2023-01-24 03:08 UTC, Pranavchiku commented on tests/reference/pass_inline_function_calls-functions_05-9883f29.stderr
> +  |     ^^^^^^^^^^^^^^^^^^^ Assuming save attribute implicitly for variables
Okay, got it. Will do changes.

2023-01-25 18:27 UTC, certik commented on tests/reference/asr-array_01_transfer-4fc765c.stderr
> +warning: Implied save feature
```suggestion
warning: Assuming implicit save attribute for variable declaration
```

2023-01-25 18:30 UTC, certik commented on tests/reference/asr-array_01_transfer-4fc765c.stderr
> +  |                    ^^^^^^^^ Assuming save attribute implicitly for variables
```suggestion
  |                    ^^^^^^^^ implied save
```

2023-01-25 18:31 UTC, certik commented on tests/reference/asr-array_01_transfer-4fc765c.stderr
> +  |                    ^^^^^^^^ Assuming save attribute implicitly for variables
We should also put somewhere the following message:
```
help: add explicit save attribute
```

2023-01-25 18:35 UTC, certik commented on tests/reference/asr-array_01_transfer-4fc765c.stderr
> +  |                    ^^^^^^^^ Assuming save attribute implicitly for variables
The "help" I think has to be a different message. It automatically gets merged in the diagnostic rendering.

2023-01-25 18:36 UTC, certik commented
TODO:
* [ ] change the error message
* [ ] only give this warning for variables inside functions and subroutines (and nowhere else for now)

2023-01-25 18:38 UTC, certik commented on tests/save1.f90
> +    real, save :: y = 5
Let's keep these here, and ensure the warning is NOT emitted here. Then add a function AND subroutine and in both add the two lines above, and check that the warning is correctly emitted.

2023-01-25 18:38 UTC, certik commented on tests/save1.f90
> +    real, save :: y = 5
Let's also add a module above the program and makes sure the warning is not emitted in the global module variables, but IS emitted  inside functions and subroutines inside the module.

2023-01-27 08:26 UTC, Pranavchiku commented
This is how it shows help for `.gt.`
```console
[ 93%] Building Fortran object examples/CMakeFiles/example_lmder1.dir/example_lmder1.f90.o
style suggestion: Use '>' instead of '.gt.'
  --> /home/pranavchiku/minpack/examples/example_lmder1.f90:25:15
   |
25 |         if (i .gt. 8) tmp3 = tmp2
   |               ^^^^ help: write this as '>'
```
>The "help" I think has to be a different message. It automatically gets merged in the diagnostic rendering.

It is not merging different warning.

2023-01-27 17:23 UTC, certik commented on src/lfortran/semantics/ast_common_visitor.h
> +          current_scope{symbol_table}, implicit_mapping{implicit_mapping}, is_Function{is_Function},
I don't think this `is_Function` should be exposed as an argument. Just leave it it as a variable in the class.

2023-01-27 17:23 UTC, certik commented on src/lfortran/semantics/ast_common_visitor.h
> +    bool &is_Function;
```suggestion
    bool &is_function;
```
And move it above with the other such bool variables.

2023-01-27 17:26 UTC, certik commented
The warning is now executed correctly I think. I left comments regarding the implementation, let's get those fixed.

2023-01-29 21:07 UTC, certik commented
I think this is fine. @czgdp1807 does this look good to you?

2023-01-30 04:05 UTC, czgdp1807 approved these changes
Re-approving (previous one https://github.com/lfortran/lfortran/pull/1201#pullrequestreview-1272826830). I will squash and merge this as its not a very big change (code wise).

2023-01-30 04:06 UTC, merged