Add provision to `visit_BlockCall` in "pass_utils" and `visit_Block` in "asr_to_llvm".
lfortran/lfortran pull request #1264
Opened 2023-02-04 04:08 UTC by Pranavchiku

Fixes #1262, via commit b8d0aee0f360fc7bf92440b8ac68d20e15115cac, which then results in "Function code not generated for `enorm`" which is then fixed by 0dd407b93f900e1518c411c22e83dec37ece736a.

2023-02-04 04:50 UTC, certik commented on tests/tests.toml
> +llvm = true
I would just move this into integration tests and run it. That's the best way to test the LLVM backend, unless there is some reason why that cannot be done.

2023-02-04 04:51 UTC, certik commented
Otherwise it looks good to me. @czgdp1807 does it look good to you as well?

2023-02-06 04:38 UTC, czgdp1807 commented on src/libasr/pass/pass_utils.h
> +                    if( fill_function_dependencies ) {
Why should we not visit `Block::m_body` when `fill_function_dependencies` is `false`? Any specific reason?

2023-02-06 04:38 UTC, czgdp1807 commented on src/libasr/codegen/asr_to_llvm.cpp
> +    void visit_Block(const ASR::Block_t& x) {
```suggestion

    void visit_Block(const ASR::Block_t& x) {
```

2023-02-06 08:07 UTC, Pranavchiku commented on src/libasr/pass/pass_utils.h
> +                    if( fill_function_dependencies ) {
I tried to mimic `visit_FunctionCall`, and I guess we need no check for it. Will make changes.

2023-02-06 15:50 UTC, czgdp1807 requested changes

2023-02-06 15:50 UTC, czgdp1807 commented on tests/tests.toml
> +llvm = true
@Pranavchiku This is yet to be addressed. Please remove this test from here and also delete the associated reference files (they are still showing up in the diff).

2023-02-06 20:39 UTC, certik commented on integration_tests/block_04.f90
> +    end subroutine fcn
```suggestion
        subroutine fcn(n)
        implicit none
        integer, intent(in) :: n
        end subroutine fcn
```

2023-02-07 05:05 UTC, Pranavchiku commented
I am not sure why these references are getting updated, it happened after I did `git rebase main` to resolve conflicts.

2023-02-07 05:09 UTC, Thirumalai-Shaktivel commented
Did you make a clean build (`git clean -dfx && ./build1.sh`)?

2023-02-07 05:11 UTC, Pranavchiku commented
Yeah, I just saw a small mistake, I made while resolving conflicts.

2023-02-07 05:13 UTC, Thirumalai-Shaktivel commented
Do this, `git reset main`, stage changes, and make new commits.
Follow this steps:
https://github.com/lcompilers/lpython/blob/8fa533a43860f43ce10e6dee238147fad57ac205/doc/src/rebasing.md#merging

2023-02-07 05:15 UTC, Thirumalai-Shaktivel commented
If you get stuck somewhere or face the same issue, let me know.

2023-02-07 05:16 UTC, Pranavchiku commented
Yeah sure!

2023-02-10 17:32 UTC, Pranavchiku commented
Closing with reference to #1284.

2023-02-10 17:32 UTC, closed without merging