Fix generic operator with class
lfortran/lfortran pull request #1273
Opened 2023-02-09 12:55 UTC by Smit-create

https://github.com/lfortran/lfortran/commit/e767b428169b324e2f52d366aece8a79813bfe00

2023-02-09 13:13 UTC, czgdp1807 requested changes

2023-02-09 13:13 UTC, czgdp1807 commented on tests/derived_types_08.f90
> + end module derived_types_08_module
Please shift this to `integration_tests` and make it a runnable program. Just add a simple print statement in the program and register with `gfortran`.

2023-02-09 13:26 UTC, Smit-create commented on tests/derived_types_08.f90
> + end module derived_types_08_module
Done, thanks!

2023-02-13 04:03 UTC, czgdp1807 approved these changes

2023-02-13 05:29 UTC, merged