Implement EnumType in AST to ASR
lfortran/lfortran pull request #1276
Opened 2023-02-10 05:55 UTC by Thirumalai-Shaktivel

2023-02-10 05:59 UTC, Thirumalai-Shaktivel commented on src/lfortran/semantics/ast_common_visitor.h
> +                                        ASR::presenceType::Required, false));
I came across the documentatin:
> `value_attr` if true, this parameter has a `value` attribute set

I didn't understand properly? Here whether a_value_attr should be set true or false?
Also, regarding the storage type, what should I add?

@certik @czgdp1807

2023-02-10 18:38 UTC, certik commented on src/lfortran/semantics/ast_common_visitor.h
> +                                        ASR::presenceType::Required, false));
it's for arguments passed by "value", it's an attribute in Fortran, as in `integer, intent(in), value :: x`. Set it to False I think.

Storage set to Default.

2023-02-10 18:42 UTC, certik approved these changes

2023-02-11 05:37 UTC, Thirumalai-Shaktivel commented on src/lfortran/semantics/ast_common_visitor.h
> +                                        ASR::presenceType::Required, false));
Got it!

2023-02-11 05:37 UTC, Thirumalai-Shaktivel commented
Thanks for the approval

2023-02-11 06:27 UTC, certik commented on src/libasr/asr_verify.cpp
> +        if ( current_symtab->resolve_symbol("enum") != nullptr ) {
This change does not feel correct. Is this checking for an `enum` symbol? A user can define one.

2023-02-11 06:28 UTC, Thirumalai-Shaktivel commented on integration_tests/enum_01.f90
> +    integer, parameter :: compiler_enum = kind(red)
Here the kind intrinsics extracts kind, only for the variable with parameter attribute. Would this: 1096a65bf48854a6db5c84af60f0eccad403b4c6 be the correct fix, @certik?

2023-02-11 06:34 UTC, Thirumalai-Shaktivel commented on src/lfortran/semantics/ast_symboltable_visitor.cpp
> +        std::string sym_name = "enum";
We create the enum symbol with the "enum" name. or should I mangle the name?

2023-02-11 06:34 UTC, Thirumalai-Shaktivel commented on src/libasr/asr_verify.cpp
> +        if ( current_symtab->resolve_symbol("enum") != nullptr ) {
https://github.com/lfortran/lfortran/pull/1276/files#r1103543924

2023-02-11 06:37 UTC, czgdp1807 commented on src/libasr/asr_verify.cpp
> +        if ( current_symtab->resolve_symbol("enum") != nullptr ) {
This means in a single scope I can't define more than one `enum`? Here's an example, https://fortranwiki.org/fortran/show/Typed+enumerators. I guess name of the `EnumType` is `color` but its defined via `enum, bind(c)`.

2023-02-11 06:37 UTC, Thirumalai-Shaktivel commented on src/libasr/asr_verify.cpp
> +            enum_symtab = ASR::down_cast<ASR::EnumType_t>(enum_s)->m_symtab;
Or I think we can add a check here:
```suggestion
            if (ASR::is_a<ASR::EnumType_t>(*enum_s)) {
                enum_symtab = ASR::down_cast<ASR::EnumType_t>(enum_s)->m_symtab;
            }
```

2023-02-11 06:39 UTC, czgdp1807 commented on src/lfortran/semantics/ast_symboltable_visitor.cpp
> +        std::string sym_name = "enum";
I think nameless `enum` can be given some unique name which doesn't clash with any other symbol. In your example there are two nameless enums so give them unique names, say, "1_nameless_enum", "2_nameless_enum".

2023-02-11 06:41 UTC, Thirumalai-Shaktivel commented on src/libasr/asr_verify.cpp
> +        if ( current_symtab->resolve_symbol("enum") != nullptr ) {
But, the example doesn't work with gfortran. Is this Fortran 2018, syntax?

2023-02-11 06:43 UTC, Thirumalai-Shaktivel commented on src/libasr/asr_verify.cpp
> +        if ( current_symtab->resolve_symbol("enum") != nullptr ) {
I see it's Fortran 2003, how do I compile Fortran 2003 with gfortran?

2023-02-11 06:44 UTC, czgdp1807 requested changes

2023-02-11 06:44 UTC, czgdp1807 commented on src/lfortran/semantics/ast_symboltable_visitor.cpp
> +
I think this whole method is very similar to the following,

https://github.com/lcompilers/lpython/blob/9c00b60cf034227b99c42b3c343dbf0db828dba3/src/lpython/semantics/python_ast_to_asr.cpp#L2445-L2496

If so, please shift this logic to a function in `asr_utils.h` and then, use it here and in the above LPython file. Let's reduce the code surface area to avoid duplication of efforts.

2023-02-11 06:46 UTC, czgdp1807 commented on src/libasr/asr_verify.cpp
> +        if ( current_symtab->resolve_symbol("enum") != nullptr ) {
I think `gfortran` always has nameless enumerations. So  https://github.com/lfortran/lfortran/pull/1276#discussion_r1103545325 should work here?

2023-02-11 06:49 UTC, Thirumalai-Shaktivel commented on src/lfortran/semantics/ast_symboltable_visitor.cpp
> +        std::string sym_name = "enum";
Yup, I agree with this.
Also, as we have two nameless enums, I appended all of their variables into one symbol. Does the design feel, right @czgdp1807?

2023-02-11 06:50 UTC, Thirumalai-Shaktivel commented on src/lfortran/semantics/ast_symboltable_visitor.cpp
> +        std::string sym_name = "enum";
If this is correct, then we will have a `1_nameless_enum` symbol in one module

2023-02-11 06:51 UTC, Thirumalai-Shaktivel commented on src/libasr/asr_verify.cpp
> +        if ( current_symtab->resolve_symbol("enum") != nullptr ) {
Yup, that should work, I will make the required changes.

2023-02-11 06:52 UTC, czgdp1807 commented on src/lfortran/semantics/ast_symboltable_visitor.cpp
> +        std::string sym_name = "enum";
I don’t think. ASR will loose the information that there were two enums present in the user code. Converting ASR back to original code will give different results then.

2023-02-11 06:53 UTC, Thirumalai-Shaktivel commented on src/lfortran/semantics/ast_symboltable_visitor.cpp
> +        std::string sym_name = "enum";
Agreed.

2023-02-11 06:57 UTC, Thirumalai-Shaktivel commented on src/libasr/asr_verify.cpp
> +        if ( current_symtab->resolve_symbol("enum") != nullptr ) {
Consider we have created two or more enum symbols.
Here I should add a while loop and check into available enums, right?

2023-02-12 05:40 UTC, Thirumalai-Shaktivel commented
This PR is ready for review

2023-02-12 08:36 UTC, czgdp1807 requested changes

2023-02-12 08:36 UTC, czgdp1807 commented on src/libasr/asr_utils.h
> +static inline void get_enum_value_type(ASR::enumtypeType &enum_value_type,
```suggestion
static inline void set_enum_value_type(ASR::enumtypeType &enum_value_type,
```

2023-02-12 08:36 UTC, czgdp1807 commented on src/lfortran/semantics/ast_common_visitor.h
> +    int32_t enum_init_val; // TODO: rework this to not use global variable
How is it a global variable anyways? Its local to a object I guess.

2023-02-13 13:42 UTC, czgdp1807 approved these changes

2023-02-13 14:45 UTC, Thirumalai-Shaktivel commented
Thanks for the approval

2023-02-13 14:45 UTC, merged