Implement all intrinsic function
lfortran/lfortran pull request #1283
Opened 2023-02-10 12:43 UTC by Thirumalai-Shaktivel

2023-02-10 14:12 UTC, czgdp1807 requested changes

2023-02-10 14:12 UTC, czgdp1807 commented on integration_tests/intrinsics_47.f90
> +end program intrinsics_47
Please register it with `gfortran` (`llvm` too if its working) in `integration_tests/CMakeLists.txt`.

2023-02-10 14:12 UTC, czgdp1807 commented on tests/tests.toml
> +asr = true
Remove if working with `llvm`.

2023-02-13 21:55 UTC, certik approved these changes
I think this is good to merge as is. We can improve upon this later.

2023-02-13 21:55 UTC, merged

2023-02-13 21:57 UTC, certik commented on src/libasr/runtime/lfortran_intrinsics.c
> +}
We'll have to figure out and document some consistent way to handle these runtime functions, there will be a lot of them. It seems doing these in the surface language and use them via an ASR pass makes a lot of sense, see the IntrinsicFunction work. For now calling from C I think is fine.

Direct LLVM implementation is good, but less readable, and it should be equivalent to the surface level implementation (later on). Obviously the C implementation is slower, but it's the easiest for us to maintain for now, so I think this is ok as an intermediate step.

2023-02-13 21:59 UTC, certik commented on tests/tests.toml
> +asr = true
It works with LLVM, but the integration test does not test the validity of the output, so we still need this until the test is improved.

2023-02-13 22:00 UTC, certik commented on src/libasr/ASR.asdl
> +    | All(expr arg, expr? dim, ttype type, expr? value)
This should be called `ArrayAll`, shouldn't it?

2023-02-14 06:04 UTC, Thirumalai-Shaktivel commented on src/libasr/ASR.asdl
> +    | All(expr arg, expr? dim, ttype type, expr? value)
Yup, I think so, as `all` accepts logical non-scalar `mask` argument