Import the StructType symbol for the Pointer Type
lfortran/lfortran pull request #1290
Opened 2023-02-12 08:00 UTC by Thirumalai-Shaktivel

2023-02-12 08:29 UTC, czgdp1807 requested changes

2023-02-12 08:29 UTC, czgdp1807 commented on tests/associate2.f90
> +end program associate2
Shift to `integration_tests` and register with `gfortran` at least.

2023-02-13 13:39 UTC, czgdp1807 approved these changes

2023-02-13 14:46 UTC, merged

2023-02-13 22:07 UTC, certik commented
@Thirumalai-Shaktivel I think you need to test ASR for this, can you please add a test? So that it does not get broken.