Support Modules in pass_array_by_data()
lfortran/lfortran pull request #1306
Opened 2023-02-15 19:21 UTC by Shaikh-Ubaid

2023-02-15 19:25 UTC, Shaikh-Ubaid commented
This gets the `integration_tests/template_array_01.f90` test case working, but the second test case `integration_tests/template_array_02.f90` fails.

```bash
(lf) lfortran$ lfortran integration_tests/template_array_01.f90               
0
1
(lf) lfortran$ lfortran integration_tests/template_array_01.f90 --backend wasm
(lf) lfortran$ node a.out.js                                                  
0
1
(lf) lfortran$ lfortran integration_tests/template_array_02.f90               
Traceback (most recent call last):
  File "/Users/ubaid/Desktop/OpenSource/lfortran/src/bin/lfortran.cpp", line 1938
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/ubaid/Desktop/OpenSource/lfortran/src/bin/lfortran.cpp", line 865
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/ubaid/Desktop/OpenSource/lfortran/src/lfortran/fortran_evaluator.cpp", line 342
    compiler_options, run_fn, infile);
  File "/Users/ubaid/Desktop/OpenSource/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 6881
    pass_manager.apply_passes(al, &asr, pass_options, diagnostics);
  File "/Users/ubaid/Desktop/OpenSource/lfortran/src/libasr/pass/pass_manager.h", line 209
    _apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/Users/ubaid/Desktop/OpenSource/lfortran/src/libasr/pass/pass_manager.h", line 102
    _passes_db[passes[i]](al, *asr, pass_options);
  File "/Users/ubaid/Desktop/OpenSource/lfortran/src/libasr/pass/pass_array_by_data.cpp", line 476
    y.visit_TranslationUnit(unit);
  File "../libasr/asr.h", line 4668
  File "../libasr/asr.h", line 4476
  File "../libasr/asr.h", line 4215
  File "../libasr/pass/pass_utils.h", line 297
  File "../libasr/asr.h", line 4681
  File "../libasr/asr.h", line 4476
  File "../libasr/asr.h", line 4216
  File "../libasr/pass/pass_utils.h", line 281
  File "../libasr/asr.h", line 4694
  File "../libasr/asr.h", line 4491
  File "../libasr/asr.h", line 4237
  File "../libasr/asr.h", line 4775
  File "../libasr/asr.h", line 4536
  File "../libasr/asr.h", line 4289
  File "../libasr/pass/pass_utils.h", line 329
  File "../libasr/pass/pass_utils.h", line 329
  Binary file "/usr/lib/system/libsystem_platform.dylib", local address: 0x1803fb2a3
Segfault: Signal SIGSEGV (segmentation fault) received
(lf) lfortran$ 
```

@czgdp1807 do you know how I can fix this?

2023-02-15 19:33 UTC, Shaikh-Ubaid commented
If we fix this https://github.com/lfortran/lfortran/pull/1306#issuecomment-1431898395, we fix the final bug at https://github.com/lfortran/lfortran/issues/1294#issuecomment-1431888950. @czgdp1807 we need help in fixing this PR, please.

2023-02-16 04:31 UTC, czgdp1807 commented
Please try to debug this till the weekend. I will see what I can do then.

2023-02-21 17:23 UTC, Shaikh-Ubaid commented
>This is low on my priority list. @Shaikh-Ubaid Please feel free to work on it till next week (whenever you get time).

I wanted to discuss some aspects related to this PR. Can we meet tomorrow or anytime soon convenient to you?

2023-02-22 16:23 UTC, Shaikh-Ubaid commented
>>This is low on my priority list. @Shaikh-Ubaid Please feel free to work on it till next week (whenever you get time).

>I wanted to discuss some aspects related to this PR. Can we meet tomorrow or anytime soon convenient to you?

CC: @czgdp1807

2023-03-02 22:34 UTC, certik commented on src/libasr/pass/pass_array_by_data.cpp
> +        }
I would not call things in a destructor. If something needs to be done at the end, I would just call the method directly and document well what it does and why it has to be called.

2023-03-02 22:35 UTC, certik commented on src/libasr/pass/pass_array_by_data.cpp
> +                symtab->add_symbol(newextsym->m_name, (ASR::symbol_t*)newextsym);
This should work:
```suggestion
                symtab->overwrite_symbol(newextsym->m_name, (ASR::symbol_t*)newextsym);
```

2023-03-02 22:46 UTC, certik commented
The last commit failed --- I guess the symbol sometimes exists, sometime does not. It feels to me our code is fragile, it seems we should know if the symbol exists or not.

2023-03-03 04:32 UTC, czgdp1807 commented on src/libasr/pass/pass_array_by_data.cpp
> +        }
Why do we need this? Any failure which is being fixed by this method?

2023-03-03 10:26 UTC, Shaikh-Ubaid commented on src/libasr/pass/pass_array_by_data.cpp
> +        }
Using this logic, I am updating the external symbols (that point to functions which got updated by the pass) present in the symbol table of the program.

Without this extra-handling of external symbols, for some external symbols, we are receiving error in the lines of `ExternalSymbol_t <symbol name> scope_names not found`.

2023-03-03 15:08 UTC, czgdp1807 requested changes

2023-03-03 15:08 UTC, czgdp1807 commented on src/libasr/pass/pass_array_by_data.cpp
> +            if( current_proc_scope->get_symbol(x_sym_name) && current_proc_scope->get_symbol(x_sym_name) != x_sym ) {
Make it the following,

```suggestion
            if( current_proc_scope->resolve_symbol(x_sym_name) != x_sym ) {
```

2023-03-03 15:08 UTC, czgdp1807 commented
The minpack test is failing due to some ASR verify errors.

2023-03-03 18:13 UTC, Shaikh-Ubaid commented on src/libasr/pass/pass_array_by_data.cpp
> +            if( current_proc_scope->get_symbol(x_sym_name) && current_proc_scope->get_symbol(x_sym_name) != x_sym ) {
@czgdp1807 it seems this fix did not work. Minipack compilation still fails.

2023-03-03 20:46 UTC, certik commented on src/libasr/pass/pass_array_by_data.cpp
> +            if( current_proc_scope->resolve_symbol(x_sym_name) != x_sym ) {
@czgdp1807 Unrelated: I want to understand why we need to call get_symbol / resolve_symbol. in my opinion we should only use those in the frontend, but never after that, always using the pointer directly. Something does not feel right. Another reason is also that using strings is slow.

2023-03-04 05:58 UTC, czgdp1807 commented on src/libasr/pass/pass_array_by_data.cpp
> +            if( current_proc_scope->resolve_symbol(x_sym_name) != x_sym ) {
> in my opinion we should only use those in the frontend

That is true for passes where we don't have to create new symbols. In passes like `pass_array_by_data`, `array_op`, `arr_slice` we have to create new symbols like in `pass_array_by_data` we create new functions with a signature which accepts arrays and their dimensions separately, in `array_op`, `arr_slice` we create new variables for looping through arrays. So in these passes we need to call `get_symbol`, `resolve_symbol`, `add_symbol`.

For example consider the following Fortran code,

```fortran
program pass_array_by_data
implicit none

integer :: a1(10), a2(10)
integer, allocatable :: a3(:), a4(:)

allocate(a3(20), a4(30))

call f(a1, a2)

call f(a3, a4)

contains

subroutine f(array1, array2)
    integer, intent(in) :: array1(:)
    integer, intent(in) :: array2(:)
end subroutine

end program pass_array_by_data
```

will be transformed to,

```fortran
program pass_array_by_data
implicit none

integer :: a1(10), a2(10)
integer, allocatable :: a3(:), a4(:)

allocate(a3(20), a4(30))

call f__array1_array2(a1, 1, 10, a2, 1, 10)

call f__array1__array2(a3, lbound(a3), ubound(a3), a4, lbound(a4), ubound(a4)) 

contains

subroutine f_array1_array2(array1, __1array1, __2array1, array2, __1array2, __2array2)
    integer, intent(in) :: array1(:), __1array1, __2array1
    integer, intent(in) :: array2(:), __1array2, __2array2
end subroutine

end program pass_array_by_data
```

So you can see original `f` is removed and a new one `f__array1__array2` is added and all the calls to it are edited and to edit those calls inside function scope and all other scopes one has to resolve to `f__array1__array2` to make sure that we are editing the calls to it correctly). Hence, calling `SymbolTable::get_symbol`, `SymbolTable::add_symbol`, `SymbolTable::erase_symbol` is necessary in these kind of passes.

The calls to these methods can be reduced but not fully removed. If you want one can spend time on reducing these calls by modifying the algorithm. Depends on how much we want to prioritise it. **Also this is an optional pass as discussed in https://github.com/lfortran/lfortran/pull/87#issuecomment-1209106045**

2023-03-04 06:41 UTC, certik commented on src/libasr/pass/pass_array_by_data.cpp
> +            if( current_proc_scope->resolve_symbol(x_sym_name) != x_sym ) {
I see, makes sense. Thanks for the explanation!

2023-03-04 06:57 UTC, czgdp1807 commented on src/libasr/pass/pass_array_by_data.cpp
> +            if( current_proc_scope->resolve_symbol(x_sym_name) != x_sym ) {
If I comment out the above `visit_FunctionCall` visitor then the following `integration_tests/arrays_elemental_15` fails. Why? Because `verifynd` calls `abs`. Now we create a new function `verifynd_array_result` which accepts dimensions of `array` and `result` as well. The point to be noted here is that `abs@dabs` is present in `verifynd`'s symtab as an `ExternalSymbol`. Now `verifynd_array_result` has its own symtab but the its worth noting that the body is duplicated from `verifynd` and hence any call to `abs` inside `verifynd_array_result` points to `verifynd::abs@dabs` and not `verifynd_array_result::abs@dabs`. In the above `visit_FunctionCall` we edit `FunctionCall::m_name` to make it point to  `veirfynd_array_result::abs@dabs`. Hence if I comment it out I get the following error,

```zsh
ASR verify pass error: ASR verify: FunctionCall::m_name `abs@dabs` cannot point outside of its symbol table
```

But what else can we do here?

1. I create an entire new function `verifynd_array_result:`. May be we can just directly edit `verifynd`? We need to add new args, to it and edit all the calls to it. But the problem with this approach is if its present inside a module then anything importing it will never know that the signature of `verifynd` has been changed. So creating a new function is safer. Right now we remove `verifynd` but I feel we should keep it as well especially if its in a module.
2. Don't keep external symbols especially for intrinsic functions inside a function's scope, instead keep it in their topmost parent which is not a function. However with the addition of `IntrinsicFunction` this shouldn't be a problem anymore for this pass?
3. For symbols imported manually inside a functions scope there is no way out other than editing the `FunctionCall::m_name` as I am doing right now.

So, when this pass will be executed this visitor will happen only for non-intrinsic functions being imported inside functions scope (which is very low, not sure but). A potential improvement which can be made here is to check if `FunctionCall::m_name` is an external symbol and only then edit it otherwise no need. @certik What do you say?

```
program arrays_elemental_15

call elemental_sin()
call elemental_cos()
call elemental_trig_identity()

contains

subroutine verify1d(array, result, size)
    real(8), intent(in) :: array(:), result(:)
    integer, intent(in) :: size
    integer :: i
    real(8) :: eps

    eps = 1e-12

    do i = 1, size
        if (abs(sin(sin(array(i))) - result(i)) > eps) error stop
    end do
end subroutine

subroutine verifynd(array, result, size1, size2, size3)
    real(8), intent(in) :: array(:, :, :), result(:, :, :)
    integer, intent(in) :: size1, size2, size3
    integer :: i, j, k
    real(8) :: eps
    eps = 1e-12

    do i = 1, size1
        do j = 1, size2
            do k = 1, size3
                if (abs(sin(array(i, j, k))**2 - result(i, j, k)) > eps) error stop
            end do
        end do
    end do
end subroutine

subroutine verify2d(array, result, size1, size2)
    real(8), intent(in) :: array(:, :), result(:, :)
    integer, intent(in) :: size1, size2
    integer :: i, j
    real(8) :: eps
    eps = 1e-12

    do i = 1, size1
        do j = 1, size2
            if (abs(cos(array(i, j))**2 - result(i, j)) > eps) error stop
        end do
    end do
end subroutine

subroutine elemental_sin()
    integer :: i, j, k
    real(8) :: array1d(256), sin1d(256)
    real(8) :: arraynd(256, 64, 16), sinnd(256, 64, 16)

    do i = 1, 256
        array1d(i) = i
    end do

    sin1d = sin(sin(array1d))

    call verify1d(array1d, sin1d, 256)

    do i = 1, 256
        do j = 1, 64
            do k = 1, 16
                arraynd(i, j, k) = i + j + k
            end do
        end do
    end do

    sinnd = sin(arraynd)**2

    call verifynd(arraynd, sinnd, 256, 64, 16)
end subroutine

subroutine elemental_cos()
    integer :: i, j
    real(8) :: array2d(256, 64), cos2d(256, 64)

    do i = 1, 256
        do j = 1, 64
            array2d(i, j) = i + j
        end do
    end do

    cos2d = cos(array2d)**2

    call verify2d(array2d, cos2d, 256, 64)
end subroutine

subroutine elemental_trig_identity()
    integer :: i, j, k, l
    real(8) :: eps
    real(8) :: arraynd(64, 32, 8, 4), observed(64, 32, 8, 4), observed1d(65536)
    integer :: newshape(1)
    eps = 1e-12

    do i = 1, 64
        do j = 1, 32
            do k = 1, 8
                do l = 1, 4
                    arraynd(i, j, k, l) = i + j + k + l
                end do
            end do
        end do
    end do

    observed = sin(arraynd)**2 + cos(arraynd)**2

    newshape(1) = 65536
    observed1d = reshape(observed, newshape)

    do i = 1, 65536
        if( abs(observed1d(i) - 1.0) > eps ) error stop
    end do
end subroutine

end program
```

2023-03-04 07:02 UTC, czgdp1807 commented on src/libasr/pass/pass_array_by_data.cpp
> +            if( current_proc_scope->resolve_symbol(x_sym_name) != x_sym ) {
> A potential improvement which can be made here is to check if `FunctionCall::m_name` is an external symbol and only then edit it otherwise no need.

Not necessarily. Fortran allows defining functions/subroutines inside functions/subroutines. So not only external symbols but any symbol which doesn't belong to current scope should be edited.

2023-03-04 07:15 UTC, czgdp1807 commented on src/libasr/pass/pass_array_by_data.cpp
> +            if( current_proc_scope->resolve_symbol(x_sym_name) != x_sym ) {
Created https://github.com/lfortran/lfortran/pull/1391/files to reduce calls to `resolve_symbol`. Added the documentation as well.

2023-03-04 16:07 UTC, czgdp1807 commented
Closing in favour of https://github.com/lfortran/lfortran/pull/1392

2023-03-04 16:07 UTC, closed without merging

2023-03-04 16:13 UTC, czgdp1807 commented on src/libasr/pass/pass_array_by_data.cpp
> +        }
This kind of approach always comes with its own problems because there are chances that you will miss out on some external symbols here and there. Better to visit modules first and then the main program, that we first all the functions in a module are created and then SubroutineCall replacer and FunctionCall replacer replace them with correct ExternalSymbols without ever needing us to update them once everything is done.

2023-03-04 16:15 UTC, czgdp1807 commented on src/libasr/pass/pass_array_by_data.cpp
> +            if( current_proc_scope->get_symbol(x_sym_name) && current_proc_scope->get_symbol(x_sym_name) != x_sym ) {
Minpack compilation was related to https://github.com/lfortran/lfortran/blob/deb490e679a387ca9499b9211747c8a6e654b8d3/integration_tests/minpack_02.f90 which I fixed in https://github.com/lfortran/lfortran/pull/1392/commits/326fccb17134c2c12f9ce5d413bc53bbaf0f8cb7.

2023-03-04 18:19 UTC, Shaikh-Ubaid commented on src/libasr/pass/pass_array_by_data.cpp
> +                symtab->add_symbol(newextsym->m_name, (ASR::symbol_t*)newextsym);
**Line 71:**