Initial FunctionParam implementation
lfortran/lfortran pull request #1309
Opened 2023-02-16 18:35 UTC by certik

The following file
```fortran
module minpack_module
    use iso_fortran_env, only: wp => real64

    implicit none

    abstract interface
        subroutine func(n, x, fvec, iflag)
            !! user-supplied subroutine for [[hybrd]], [[hybrd1]], and [[fdjac1]]
            import :: wp
            implicit none
            integer, intent(in) :: n !! the number of variables.
            real(wp), intent(in) :: x(n) !! independent variable vector
            real(wp), intent(out) :: fvec(n) !! value of function at `x`
            integer, intent(inout) :: iflag !! set to <0 to terminate execution
        end subroutine func
    
    end interface

    contains
        subroutine hybrd(fcn)
            implicit none
            procedure(func) :: fcn
        end subroutine 
end module
```
now seems to be the correct ASR:
```console
$ lfortran --show-asr a.f90         
(TranslationUnit (SymbolTable 1 {iso_fortran_env: (IntrinsicModule lfortran_intrinsic_iso_fortran_env), minpack_module: (Module (SymbolTable 2 {func: (Function (SymbolTable 5 {fvec: (Variable 5 fvec [n] Out () () Default (Real 8 [((IntegerConstant 1 (Integer 4 [])) (Var 5 n))]) Source Public Required .false.), iflag: (Variable 5 iflag [] InOut () () Default (Integer 4 []) Source Public Required .false.), n: (Variable 5 n [] In () () Default (Integer 4 []) Source Public Required .false.), x: (Variable 5 x [n] In () () Default (Real 8 [((IntegerConstant 1 (Integer 4 [])) (Var 5 n))]) Source Public Required .false.)}) func (FunctionType [(Integer 4 []) (Real 8 [((IntegerConstant 1 (Integer 4 [])) (FunctionParam 0 (Integer 4 []) ()))]) (Real 8 [((IntegerConstant 1 (Integer 4 [])) (FunctionParam 0 (Integer 4 []) ()))]) (Integer 4 [])] () Source Interface () .false. .false. .false. .false. .false. [] [] .false.) [] [(Var 5 n) (Var 5 x) (Var 5 fvec) (Var 5 iflag)] [] () Public), hybrd: (Function (SymbolTable 6 {fcn: (Variable 6 fcn [] Unspecified () () Default (FunctionType [(Integer 4 []) (Real 8 [((IntegerConstant 1 (Integer 4 [])) (FunctionParam 0 (Integer 4 []) ()))]) (Real 8 [((IntegerConstant 1 (Integer 4 [])) (FunctionParam 0 (Integer 4 []) ()))]) (Integer 4 [])] () Source Interface () .false. .false. .false. .false. .false. [] [] .false.) Source Public Required .false.)}) hybrd (FunctionType [(FunctionType [(Integer 4 []) (Real 8 [((IntegerConstant 1 (Integer 4 [])) (FunctionParam 0 (Integer 4 []) ()))]) (Real 8 [((IntegerConstant 1 (Integer 4 [])) (FunctionParam 0 (Integer 4 []) ()))]) (Integer 4 [])] () Source Interface () .false. .false. .false. .false. .false. [] [] .false.)] () Source Implementation () .false. .false. .false. .false. .false. [] [] .false.) [] [(Var 6 fcn)] [] () Public), wp: (ExternalSymbol 2 wp 4 real64 lfortran_intrinsic_iso_fortran_env [] real64 Public)}) minpack_module [iso_fortran_env] .false. .false.)}) [])
```
The `FunctionParam` is there inside `FunctionType`, but it is correctly not there for regular variables.

TODO:
* [ ] call duplicate_dimensions for all types
* [ ] determine this arg_index properly
* [ ] fix all tests
* [ ] fix all integration tests
* [ ] implement ASR->LLVM and ASR passes for FunctionParam

2023-02-16 21:36 UTC, certik commented
@czgdp1807 in here we implemented FunctionParam only if the given type is under FunctionType. If the type is inside a Variable in a symbol table, we currently keep the Var in there.

However, it occurred to me know that we should probably always be using FunctionParam in a type. When we have the following declaration anywhere (whether inside a function or a main program, etc.):
```
integer :: A(n, m, len(s)+1+n, size(B, 1))
```
Then `n`, `m`, `s`, `B` can be:
* function arguments, if inside a function (then we can always use FunctionParam)
* compile time constants (`integer, parameter :: n = 10`)
They cannot be local variables.

Consequently, the expressions inside a type can be any `expr` type (including FunctionParam) except:
* `Var`
and the expr can be recursive, but it cannot have `Var` anywhere. Then I think the expression is "standalone", it can be very complicated, including creating arrays, computation on arrays, (user) pure function calls, etc. but the only things that can "vary" at runtime is `FunctionParam`.


If the above design does not have a mistake, then I think we should just use `FunctionParam` everywhere.

Regarding compile time constants, we can (for now) substitute them for their actual values in types. We lose the original expression, but we decouple the type from the symbol table, which we want. We can later figure out how to preserve the expression, possibly with a dedicated ASR node.

2023-02-17 04:05 UTC, czgdp1807 requested changes

2023-02-17 04:05 UTC, czgdp1807 commented on src/libasr/asr_utils.h
> -            throw LCompilersException("Not implemented.");
Please don't remove the `default` case.

2023-02-17 04:05 UTC, czgdp1807 commented on src/libasr/asr_utils.h
> +static inline ASR::dimension_t* duplicate_dimensions(Allocator& al, ASR::dimension_t* m_dims, size_t n_dims);
Is it possible to use `duplicate_dimensions` in `duplicate_type` as well? Not necessary to do it right away, but please add a TODO comment like, `TODO: Use it in duplicate_type`.

2023-02-17 04:17 UTC, czgdp1807 commented
> the `param` field would point to the actual symbol that represents the argument (so that the backends don't need to look this up).

So this means that `FunctionParam` is still tied to the symbol table of the `Function`? What if I define an interface in a module and then import it use to define a callback argument inside another function. So, `FunctionParam` would depend on the symbol table of the imported interface, no?

2023-02-17 05:27 UTC, certik commented
Right, I think the `param` is not a good idea.

The rest should hold up though.

2023-02-17 19:19 UTC, certik commented
The best design for now seems to be:

* The type system is completely independent of any scope (it's global)
* Types do not have any names:
  * So FunctionType has no names for parameters. FunctionParam is good.
  * StructType is effectively nested tuples of types. The order matters, but names do not
  * ClassType is just like struct, or perhaps exactly struct. Methods are represented using FunctionType. Ordered, as in a struct, but no names
* Then in the symbol table we bind the types with names. So FunctionType + name -> Function. StructType + struct name + member names -> UserDefinedType symbol node; ClassType + class name + method names (plus arguments) -> Class, etc. The representation in the symbol table can be pretty much as it is now (for example the Function still has arguments as variables), so things should be easy for the backends; but in addition we gain a clean abstract type system.
* types are not scoped; but once they are bound to names, then they become scoped (can shadow each other), as well they can be semantically different (two structs with the same StructType but different struct names are different structs in C).

2023-02-18 14:23 UTC, czgdp1807 commented
Makes total sense to me. I am 100% with this design. Ideal for me and flexible as well.

2023-02-23 03:28 UTC, certik commented
@Pranavchiku if you want, go ahead and continue using the above design: https://github.com/lfortran/lfortran/pull/1309#issuecomment-1435126522

2023-02-28 18:55 UTC, certik commented
We will allow function calls, but the functions have to be "pure", so we can treat them as "global", so the type is still global.

2023-03-01 04:18 UTC, Pranavchiku commented
I guess I will need a bit of discussion before starting on implementation of the design.

2023-04-27 05:22 UTC, certik commented
TODO:

* Compile
* Make all tests pass.

2023-04-28 01:21 UTC, certik commented on src/libasr/asr_utils.h
> +static inline ASR::dimension_t* duplicate_dimensions(Allocator& al, ASR::dimension_t* m_dims, size_t n_dims);
We are, see below.

2023-04-28 03:49 UTC, certik commented
@czgdp1807 this is ready.

2023-04-28 03:52 UTC, czgdp1807 commented
I will test this shortly.

2023-04-28 05:56 UTC, czgdp1807 commented
I would like the following diff on your branch to work because only then we will know whether `FunctionParam` is actually correct or not. Otherwise there will be many hidden bugs.

```diff
diff --git a/src/lfortran/semantics/ast_common_visitor.h b/src/lfortran/semantics/ast_common_visitor.h
index da16519db..1d2776664 100644
--- a/src/lfortran/semantics/ast_common_visitor.h
+++ b/src/lfortran/semantics/ast_common_visitor.h
@@ -2164,8 +2164,8 @@ public:
                            ASR::Function_t* orig_func=nullptr) {
         ASRUtils::ExprStmtDuplicator expr_duplicator(al);
         expr_duplicator.allow_procedure_calls = true;
-        ASRUtils::ReplaceArgVisitor arg_replacer(al, current_scope, orig_func,
-                                                 orig_args, current_function_dependencies);
+        ASRUtils::ReplaceArgVisitor arg_replacer(al, current_scope,
+                                                 current_function_dependencies);
         for( size_t i = 0; i < exprs.size(); i++ ) {
             ASR::expr_t* expri = exprs[i];
             if (expri) {
diff --git a/src/libasr/asr_utils.h b/src/libasr/asr_utils.h
index 5552ece78..168d7a509 100644
--- a/src/libasr/asr_utils.h
+++ b/src/libasr/asr_utils.h
@@ -2607,19 +2607,14 @@ class ReplaceArgVisitor: public ASR::BaseExprReplacer<ReplaceArgVisitor> {
 
     SymbolTable* current_scope;
 
-    ASR::Function_t* orig_func;
-
-    Vec<ASR::call_arg_t>& orig_args;
-
     SetChar& current_function_dependencies;
 
     public:
 
     ReplaceArgVisitor(Allocator& al_, SymbolTable* current_scope_,
-                      ASR::Function_t* orig_func_, Vec<ASR::call_arg_t>& orig_args_,
                       SetChar& current_function_dependencies_) :
-        al(al_), current_scope(current_scope_), orig_func(orig_func_),
-        orig_args(orig_args_), current_function_dependencies(current_function_dependencies_)
+        al(al_), current_scope(current_scope_),
+        current_function_dependencies(current_function_dependencies_)
     {}
 
     void replace_FunctionCall(ASR::FunctionCall_t* x) {
@@ -2693,30 +2688,6 @@ class ReplaceArgVisitor: public ASR::BaseExprReplacer<ReplaceArgVisitor> {
         x->m_name = new_es;
     }
 
-    void replace_Var(ASR::Var_t* x) {
-        size_t arg_idx = 0;
-        bool idx_found = false;
-        std::string arg_name = ASRUtils::symbol_name(x->m_v);
-        // Finds the index of the argument to be used for substitution
-        // Basically if we are calling maybe(string, ret_type=character(len=len(s)))
-        // where string is a variable in current scope and s is one of the arguments
-        // accepted by maybe i.e., maybe has a signature maybe(s). Then, we will
-        // replace s with string. So, the call would become,
-        // maybe(string, ret_type=character(len=len(string)))
-        for( size_t j = 0; j < orig_func->n_args && !idx_found; j++ ) {
-            if( ASR::is_a<ASR::Var_t>(*(orig_func->m_args[j])) ) {
-                std::string arg_name_2 = std::string(ASRUtils::symbol_name(
-                    ASR::down_cast<ASR::Var_t>(orig_func->m_args[j])->m_v));
-                arg_idx = j;
-                idx_found = arg_name_2 == arg_name;
-            }
-        }
-        if( idx_found ) {
-            LCOMPILERS_ASSERT(current_expr);
-            *current_expr = orig_args[arg_idx].m_value;
-        }
-    }
-
 };
 
 // Finds the argument index that is equal to `v`, otherwise -1.

```

After applying the above diff I get the following failure,

```zsh
(lf) 11:22:16:~/lfortran_project/lfortran % lfortran integration_tests/intrinsics_36.f90
ASR verify pass error: ASR verify: Var::m_v `x` cannot point outside of its symbol table
 --> integration_tests/intrinsics_36.f90:1:1
  |
1 | program intrinsics_36
  | ^ failed here


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that must be fixed).
```

Actually the above failure is related to the diff. After the diff (you see `replace_Var` method is related which actually does the replacement), we don't replace in  `x` of `len(x)` in signature of `adjustl` defined in `src/runtime/pure/lfortran_intrinsic_string.f90` with the actual input argument. So `FunctionParam` should be used in the ASR of `adjustl` i.e., `len(FunctionParam(0))` (`x` is the first argument of `adjustl`). 

So `FunctionParam` is not fully used right now. Apply the above diff I sent and then use `FunctionParam` until we stop getting ASR verify errors.

2023-04-28 05:57 UTC, czgdp1807 requested changes
See, https://github.com/lfortran/lfortran/pull/1309#issuecomment-1527027435

2023-04-28 06:08 UTC, certik commented
Yes, FunctionParam is not fully used yet, but it's a start. I need this PR in, it's a blocker to get modern minpack to compile (it does with this PR). With this PR FunctionParam is used in some cases, but not all yet. I want to do it gradually.

2023-04-28 06:10 UTC, certik commented
@czgdp1807 this is fine with me to merge as is. I recommend to push into a new PR if you want some things to be fixed before merging, because I tested this with minpack and it works.

2023-04-28 06:14 UTC, merged