[LLVM] Alllow strings in CaseStmt_Range condition
lfortran/lfortran pull request #1326
Opened 2023-02-21 03:48 UTC by Thirumalai-Shaktivel

2023-02-21 17:09 UTC, czgdp1807 commented on src/libasr/pass/pass_utils.cpp
> +                return ASRUtils::EXPR(ASR::make_IntegerBinOp_t(al, loc, left, op, right, type_, nullptr));
I am a bit surprised. We are creating `IntegerBinOp` for character type?

2023-02-21 17:11 UTC, certik commented on src/libasr/pass/pass_utils.cpp
> +                return ASRUtils::EXPR(ASR::make_IntegerBinOp_t(al, loc, left, op, right, type_, nullptr));
Good catch --- we should at least document in comments why that is so.

2023-02-22 03:19 UTC, Thirumalai-Shaktivel commented on src/libasr/pass/pass_utils.cpp
> +                return ASRUtils::EXPR(ASR::make_IntegerBinOp_t(al, loc, left, op, right, type_, nullptr));
As we do not have `StringBinOp` in ASR, I used `IntegerBInOp`. Also, The output of StringCompare is always a bool and the product of a bool can be an Integer. That's why I used `IntgerBinOp`.

2023-02-22 03:22 UTC, Thirumalai-Shaktivel commented on src/libasr/pass/pass_utils.cpp
> +                return ASRUtils::EXPR(ASR::make_IntegerBinOp_t(al, loc, left, op, right, type_, nullptr));
```Clojure
(If
    (IntegerBinOp
        (StringCompare
            (StringConstant
                "a"
                (Character 1 1 () [])
            )
            LtE
            (Var 3 c)
            (Character 1 1 () [])
            ()
        )
        Mul
        (StringCompare
            (Var 3 c)
            LtE
            (StringConstant
                "j"
                (Character 1 1 () [])
            )
            (Character 1 1 () [])
            ()
        )
        (Integer 4 [])
        ()
    )

```

2023-02-22 14:30 UTC, czgdp1807 commented on src/libasr/pass/pass_utils.cpp
> +                return ASRUtils::EXPR(ASR::make_IntegerBinOp_t(al, loc, left, op, right, type_, nullptr));
Why are using `Mul` for multiplying two booleans? I think equivalent of `Mul` for logical operands is `And` operation? So `LogicalBinOp` makes more sense?

2023-02-22 16:29 UTC, Thirumalai-Shaktivel commented on src/libasr/pass/pass_utils.cpp
> +                return ASRUtils::EXPR(ASR::make_IntegerBinOp_t(al, loc, left, op, right, type_, nullptr));
I didn't look deeply into this implementation. But, I had the same thought as you did.

2023-02-28 15:25 UTC, czgdp1807 requested changes

2023-02-28 15:25 UTC, czgdp1807 commented on integration_tests/case_07.f90
> +    call test_case('r')
Convert `test_case` into a function, make it return different values for different cases and then use error stops to make sure the correct case was executed.

2023-02-28 15:26 UTC, Thirumalai-Shaktivel commented on integration_tests/case_07.f90
> +    call test_case('r')
Yup!

2023-02-28 21:14 UTC, certik approved these changes

2023-03-01 03:02 UTC, Thirumalai-Shaktivel commented
Thanks for the review

2023-03-01 03:02 UTC, merged