Restrict assignment of do loop variable in do loop body.
lfortran/lfortran pull request #1345
Opened 2023-02-23 05:31 UTC by Pranavchiku

Fixes #1342.

2023-02-23 05:34 UTC, certik commented on src/lfortran/semantics/ast_body_visitor.cpp
> +                                throw SemanticError("Do loop: assignment to loop variable `" + std::string(target_var->m_name) +"` is not allowed", assign->base.base.loc);
I would highlight just the target variable:
```suggestion
                                throw SemanticError("Assignment to loop variable `" + std::string(target_var->m_name) +"` is not allowed in a do loop", target_var->base.base.loc);
```

2023-02-23 05:37 UTC, certik commented on src/lfortran/semantics/ast_body_visitor.cpp
> +                            if (to_lower(x.m_var) == std::string(target_var->m_name)) {
Use `var` -> m_v and directly compare the pointer with `target_var`. If it is the same pointer, it's the same variable, otherwise it is not. We should not use a string comparison, as it is fragile.

2023-02-23 05:38 UTC, Pranavchiku commented
This method does not for nested do loop, I have an approach for that which goes as follows:
* Keep an array of do loop variables -> `do_loop_vars`
* If in `do_loop_body` we find another do loop recursively call the function by pushing the do_loop_var of parent loop in the array
* Check if `assignment->m_target` is present in `do_loop_vars`.

2023-02-23 05:42 UTC, Pranavchiku commented
We should throw error here as well right?
```fortran
    do i = 1, 10
        do j = 1, 3
            i = i + 1
        end do
    end do
```

2023-02-24 02:37 UTC, certik commented on src/lfortran/semantics/ast_body_visitor.cpp
> +                        ASR::symbol_t* loop_var_sym = current_scope->resolve_symbol(to_lower(x.m_var));
I think `var` already contains this information, so you can just extract it instead of doing another lookup.

2023-02-24 02:39 UTC, certik commented
This is a good prototype.

There is an issue of performance also, this approach I think will be quite slow, compared to the alternative: You can maintain a stack of loop variables, and then in visit_Assignment, just check that we are not assigning to a variable that is a loop variable. In a way, we are turning on a temporary read-only mode for those variables, restricted to the scope of the loop.

2023-02-24 03:57 UTC, czgdp1807 requested changes

2023-02-24 03:57 UTC, czgdp1807 commented on src/lfortran/semantics/ast_body_visitor.cpp
> +                ASR::stmt_t* stmt = body[i];
I guess iterating over the whole set of statements might not be the most efficient approach. Its clean but not the most efficient. The error should be thrown as soon as we notice that `head.m_v` is assignment's target. Here the error is thrown once the do loop is fully created.

We just need to add a class member like, `current_loop_variable` and set it to `head.m_v` before starting to visit `AST` statements of the do loop. When you enter `visit_Assignment` just check if the target is the same as `current_loop_variable`. If so raise an error right there.

2023-02-24 03:58 UTC, czgdp1807 commented on src/lfortran/semantics/ast_body_visitor.cpp
> +                ASR::stmt_t* stmt = body[i];
Or if you don't want to do it right now, that's also okay. Just add a `TODO` comment that there is a better approach which doesn't require us to wait for the whole do loop to be created before throwing the error.

2023-02-24 12:42 UTC, Pranavchiku commented on src/lfortran/semantics/ast_body_visitor.cpp
> +                        ASR::symbol_t* loop_var_sym = current_scope->resolve_symbol(to_lower(x.m_var));
Okay yes! Thanks for pointing this out.

2023-02-24 12:43 UTC, Pranavchiku commented on src/lfortran/semantics/ast_body_visitor.cpp
> +                ASR::stmt_t* stmt = body[i];
Let me try to do that, if it takes more time, we can finish this PR and I will just add a `TODO` comment.

2023-02-24 13:34 UTC, Pranavchiku commented
I am using `std::vector<ASR::symbol_t*> do_loop_variables` as a stack, and as suggested on visiting Assignment checking if target is present in do_loop_variables, then throwing an error.
It works for nested do loops as well.

2023-02-24 14:27 UTC, czgdp1807 approved these changes
LGTM.

2023-02-24 21:01 UTC, certik commented on src/lfortran/semantics/ast_body_visitor.cpp
> +                ASR::stmt_t* stmt = body[i];
The `current_loop_variable` must be `current_loop_variables` and be a stack, so that nested loops also work.

2023-02-24 21:03 UTC, certik commented on src/lfortran/semantics/ast_body_visitor.cpp
> +            }
Move this inside the next if statement, for performance.

2023-02-24 21:04 UTC, certik commented on src/lfortran/semantics/ast_body_visitor.cpp
> +            }
Also it MUST be a variable, since it would be present in a loop variable, so you can just cast it.

2023-02-24 21:06 UTC, certik commented on src/lfortran/semantics/ast_body_visitor.cpp
> +        if (var && var->type == ASR::exprType::Var) {
I think it must be a variable, doesn't it?
```suggestion
        if (var) {
```
That way we get an assert failure if it isn't, which signals a bug in our compiler, instead of ignoring it.

2023-02-24 21:06 UTC, certik commented
I think this is the right approach, thanks!

I left some comments to simplify / refactor the code.

2023-02-25 05:53 UTC, Pranavchiku commented on src/lfortran/semantics/ast_body_visitor.cpp
> +        if (var && var->type == ASR::exprType::Var) {
> I think it must be a variable, doesn't it?

I guess yes, to assure it I kept the condition for `var->type`.

2023-02-25 06:02 UTC, Pranavchiku commented on src/lfortran/semantics/ast_body_visitor.cpp
> +            }
> Also it MUST be a variable, since it would be present in a loop variable, so you can just cast it.

There might be a chance that it is a Var and not present in loop variable hence not (Variable_t) which will cause Internal Compiler Error: Unhandled exception, I came across this in `integration_tests/modules_27_module2.f90` hence keeping the check for variable.

2023-02-25 06:09 UTC, czgdp1807 commented on src/lfortran/semantics/ast_body_visitor.cpp
> +            }
That's true. But can use anything other than a variable in Fortran's do loop? I think if `var` is not `nullptr` then it must be always a `Var` in Fortran. If not then throw a `SemanticError`.

2023-02-25 06:20 UTC, Pranavchiku commented on src/lfortran/semantics/ast_body_visitor.cpp
> +            }
If I got you correctly, that is why we removed check `var->type == ASR::exprType::Var` from `visit_DoLoop`.

2023-02-25 06:25 UTC, Pranavchiku commented on src/lfortran/semantics/ast_body_visitor.cpp
> +            }
Aah got it, let me just update it, if it is present in do_loop_variables, then we can directly cast it to `Variable_t` and get `var_name`.

2023-02-25 06:31 UTC, Pranavchiku commented on src/lfortran/semantics/ast_body_visitor.cpp
> +            }
Done :)

2023-02-25 08:00 UTC, merged

2023-02-25 14:22 UTC, certik commented on src/lfortran/semantics/ast_body_visitor.cpp
> +            }
The point is that we never want to have branches in the code where we just ignore something. Either give a compiler error, or directly cast it.

2023-02-25 14:24 UTC, certik commented
Next time please polish the history or squash it.

2023-02-25 15:07 UTC, Pranavchiku commented
Sincere apologies for poor commit history, will take care of it.

2023-02-25 15:41 UTC, certik commented
No worries!