Add provision to update `Implicit_Deallocate_t` statements in function body in pass_array_by_data
lfortran/lfortran pull request #1352
Opened 2023-02-24 15:59 UTC by Pranavchiku

Fixes #1349.

2023-02-24 21:16 UTC, certik commented on integration_tests/pass_array_by_data_02.f90
> +    implicit none
The module's `implicit none` applies here too, no need to repeat:
```suggestion
```

2023-02-24 21:18 UTC, certik commented
I think this might be good. @czgdp1807 can you check that the algorithm in the pass makes sense?

2023-02-25 13:02 UTC, czgdp1807 requested changes

2023-02-25 13:02 UTC, czgdp1807 commented on src/libasr/pass/pass_array_by_data.cpp
> +                    visit_stmt(*x->m_body[i]);
In my opinion, this is not the right fix. The right fix would be to change the following,

https://github.com/lfortran/lfortran/blob/1c4d8e37173abddae1f01ffa0abd5805a83689bb/src/libasr/ASR.asdl#L166-L168

to,

```diff
diff --git a/src/libasr/ASR.asdl b/src/libasr/ASR.asdl
index 0c1ab86f9..1174b7a90 100644
--- a/src/libasr/ASR.asdl
+++ b/src/libasr/ASR.asdl
@@ -165,7 +165,7 @@ stmt
     -- deallocates if allocated otherwise throws a runtime error
     | ExplicitDeallocate(expr* vars)
     -- deallocates if allocated otherwise does nothing
-    | ImplicitDeallocate(symbol* vars)
+    | ImplicitDeallocate(expr* vars)
     | DoConcurrentLoop(do_loop_head head, stmt* body)
     | DoLoop(do_loop_head head, stmt* body)
     | ErrorStop(expr? code)
```

Then it would just work, no special checking for the type of statement.

It is easy to do so I think @Pranavchiku should do this instead of the current fix in this PR.

P.S. I did the same change for `ExplicitDeallocate` because I needed it to compile FPM. Didn't do it for `ImplicitDeallocate` but I think for consistency we should do it now.

2023-02-25 14:28 UTC, certik commented on src/libasr/pass/pass_array_by_data.cpp
> +                    visit_stmt(*x->m_body[i]);
What kind of expressions can be in `ExplicitDeallocate`? I thought it can only deallocate symbols.

2023-02-25 14:32 UTC, czgdp1807 commented on src/libasr/pass/pass_array_by_data.cpp
> +                    visit_stmt(*x->m_body[i]);
`ASR::StructInstanceMember_t` as well. Now, one can say that we can directly refer to the member being deallocated as `ExternalSymbol`. However then we will loose the information on how actually the member was accessed, especially in-case of struct type objects being members of other structs (a common case in FPM codebase). So, I think storing expressions directly in `ExplicitDeallocate` rather than figuring out ways to get to the underlying symbol.

2023-02-25 14:38 UTC, certik commented on src/libasr/pass/pass_array_by_data.cpp
> +                    visit_stmt(*x->m_body[i]);
Does it matter for the backend where the variable / struct member lives? Also typically this gets one recursively when the structure itself goes out of scope. It's fine for now, but I think we need to eventually rework how the deallocation gets done.

2023-02-25 14:39 UTC, czgdp1807 commented on src/libasr/pass/pass_array_by_data.cpp
> +                    visit_stmt(*x->m_body[i]);
> Does it matter for the backend where the variable / struct member lives?

I don't think so. But when doing ASR -> Fortran, it would be better to have the actual `StructInstanceMember` expression in `ExplicitDeallocate` so that code generation happens easily.

2023-02-25 14:41 UTC, czgdp1807 commented on src/libasr/pass/pass_array_by_data.cpp
> +                    visit_stmt(*x->m_body[i]);
> Also typically this gets done recursively when the structure itself goes out of scope

Can you share an example for this particular case?

2023-02-25 14:44 UTC, certik commented on src/libasr/pass/pass_array_by_data.cpp
> +                    visit_stmt(*x->m_body[i]);
Yes, I thought so too about the Fortran backend, there it would be helpful.

For the last question, say a struct is deallocated. Then you must recursively deallocate all allocatable components, it could be quite nested.

2023-02-25 14:47 UTC, czgdp1807 commented on src/libasr/pass/pass_array_by_data.cpp
> +                    visit_stmt(*x->m_body[i]);
> For the last question, say a struct is deallocated. Then you must recursively deallocate all allocatable components, it could be quite nested.

Yes. I guess we will have to add a boolean flag at the end of structure to track if an allocatable struct is deallocated or not. This would help in avoiding double frees by the compiler itself. If the user frees a particular member then we will know with that flag and compiler won't deallocate it again at runtime.

2023-02-25 15:06 UTC, Pranavchiku commented on src/libasr/pass/pass_array_by_data.cpp
> +                    visit_stmt(*x->m_body[i]);
> It is easy to do so I think @Pranavchiku should do this instead of the current fix in this PR.

I will give it a shot.

2023-02-25 15:40 UTC, certik commented on src/libasr/pass/pass_array_by_data.cpp
> +                    visit_stmt(*x->m_body[i]);
I think for each allocatable variable and member, we need to keep a flag if it is allocated. I think we do already.

2023-02-25 17:57 UTC, czgdp1807 commented on src/libasr/pass/pass_array_by_data.cpp
> +                    visit_stmt(*x->m_body[i]);
We do it for allocatable arrays. We have to generalise it to alloctable objects like structs. We will do it while doing the FPM compilation project.

2023-02-26 06:16 UTC, Pranavchiku commented
Performed suggested changes in #1357, kindly have a look. @certik @czgdp1807.

2023-02-26 06:27 UTC, czgdp1807 commented
Closing in favour of #1357.

2023-02-26 06:27 UTC, closed without merging