Fix handling of exit statements in nested do loop
lfortran/lfortran pull request #1420
Opened 2023-03-10 07:32 UTC by Pranavchiku

Fixes #1419.

2023-03-10 14:47 UTC, czgdp1807 approved these changes

2023-03-10 18:55 UTC, certik commented on integration_tests/do_loop_02.f90
> +end program
In another PR, let's test the exact result that "i" or "j" (or both) have to be, to ensure everything actually runs correctly.

2023-03-10 18:55 UTC, certik approved these changes

2023-03-10 20:13 UTC, czgdp1807 requested changes
I agree with https://github.com/lfortran/lfortran/pull/1420#discussion_r1132766982 and I request to do it here before this goes in. If you want to merge this urgently then let me know, I will approve in that case.

2023-03-11 04:48 UTC, Pranavchiku commented on integration_tests/do_loop_02.f90
> +end program
Added checks to test exact result.

2023-03-11 04:48 UTC, czgdp1807 approved these changes

2023-03-11 05:04 UTC, merged

2023-03-11 05:35 UTC, certik commented
Thanks @Pranavchiku for adding the test. @czgdp1807 it's typically not urgent. One big advantage of doing it right away is that it gets done and we can forget about it. So probably a good strategy is to do small stuff like this right away, and only more time consuming stuff later, so that we don't drop the ball on the PR just because it is not perfect.

2023-03-11 05:55 UTC, czgdp1807 commented
Seems like with a stronger test modifications in fix were doable. So it was worth it here.