Add verbose option for passes
lfortran/lfortran pull request #1421
Opened 2023-03-10 11:40 UTC by Smit-create

https://github.com/lfortran/lfortran/pull/1400#issuecomment-1462880075
https://github.com/lfortran/lfortran/issues/416

2023-03-10 11:57 UTC, Smit-create commented
Once this is finalized, I can also add: https://github.com/lfortran/lfortran/issues/1384#issuecomment-1451365193

2023-03-10 11:59 UTC, czgdp1807 requested changes

2023-03-10 11:59 UTC, czgdp1807 commented on src/libasr/pass/pass_manager.h
> +                }
Shift this before line 109 (i.e., when the actual call happens).

2023-03-10 18:59 UTC, certik approved these changes
Something like this, yes. We can later extend this as needed.

2023-03-11 05:07 UTC, certik approved these changes

2023-03-11 05:09 UTC, merged