Allow creating `ComplexConstant_` in `DCMPLX`
lfortran/lfortran pull request #1431
Opened 2023-03-14 10:23 UTC by Pranavchiku

2023-03-14 10:37 UTC, Pranavchiku commented on tests/reference/asr-complex_07-8d914e3.stdout
> +                                (Complex 8 [])
This change looks good to me, I cross-verified it.

2023-03-14 11:29 UTC, czgdp1807 commented on src/lfortran/semantics/ast_common_visitor.h
> +        ASR::expr_t* x_value = ASRUtils::expr_value(x_);
Why do you want to create a `ComplexConstant` from a variable complex number? In, `DCMPLX(PD, 0.0D0)`, `PD` is a variable, so we should create a `ComplexConstructor` node? Why `ComplexConstant` node creation is necessary here?

2023-03-14 13:09 UTC, Pranavchiku commented on src/lfortran/semantics/ast_common_visitor.h
> +        ASR::expr_t* x_value = ASRUtils::expr_value(x_);
I am trying to create a `ComplexConstant` expression which can be set as `m_value` of `ComplexConstructor` node.

2023-03-14 13:12 UTC, czgdp1807 commented on src/lfortran/semantics/ast_common_visitor.h
> +        ASR::expr_t* x_value = ASRUtils::expr_value(x_);
If `ComplexConstant` can not be created that means compile time value of `ComplexConstructor` can not reduce to compile time constant. So you can set `ComplexConstructor::m_value` to `nullptr`.

2023-03-14 14:37 UTC, czgdp1807 commented on src/lfortran/semantics/ast_common_visitor.h
> +        ASR::expr_t* x_value = ASRUtils::expr_value(x_);
I think `m_value` is an optional attribute so should be used only when its not `nullptr`.

2023-03-14 17:21 UTC, czgdp1807 commented
Is it ready for review?

2023-03-14 17:25 UTC, Pranavchiku commented
Yeah

2023-03-14 17:29 UTC, czgdp1807 requested changes

2023-03-14 17:29 UTC, czgdp1807 commented on src/lfortran/semantics/ast_common_visitor.h
> +                                                                 x_value_, y_value_, type));
Use, for extracting real values. It returns `false` if value cannot be extracted in which case you can set `ComplexConstructor::m_value` to `nullptr`.

https://github.com/lfortran/lfortran/blob/f5ccf212d7d19a5193856770a7fed846284eacec/src/libasr/asr_utils.h#L805

2023-03-15 15:46 UTC, czgdp1807 requested changes

2023-03-15 15:46 UTC, czgdp1807 commented on integration_tests/complex_11.f90
> +    print *, DCMPLX(1.0D0, 6.0D0)
Would be good to do `if () error stop` checks here.

2023-03-15 16:55 UTC, czgdp1807 approved these changes

2023-03-15 17:18 UTC, merged