Add an option to use cumulative ASR pass
lfortran/lfortran pull request #1434
Opened 2023-03-14 16:57 UTC by Smit-create

https://github.com/lfortran/lfortran/issues/1384#issuecomment-1451365193

2023-03-15 12:19 UTC, czgdp1807 requested changes

2023-03-15 12:19 UTC, czgdp1807 commented on src/bin/lfortran.cpp
> +    pass_options.pass_cumulative = compiler_options.pass_cumulative;
Can we add a test in `tests.toml` to verify that this option actually works?

2023-03-15 20:28 UTC, certik approved these changes
Yes, a test in tests.toml would be good.  At least that it executes, it's probably hard to easily verify that all passes actually ran.

2023-03-16 11:36 UTC, certik approved these changes

2023-03-16 12:55 UTC, czgdp1807 approved these changes

2023-03-16 12:56 UTC, merged