Use IntrinsicFunction pass in the ASR->Julia
lfortran/lfortran pull request #1500
Opened 2023-04-06 09:10 UTC by Thirumalai-Shaktivel

2023-04-06 09:44 UTC, Shaikh-Ubaid commented on tests/reference/wat-abs_03-5d62cca.stdout
> -    (global $28 (mut i32) (i32.const 0))
@Thirumalai-Shaktivel do you know why global variables are being removed?

2023-04-06 09:48 UTC, Thirumalai-Shaktivel commented on tests/reference/wat-abs_03-5d62cca.stdout
> -    (global $28 (mut i32) (i32.const 0))
By any chance, is it possible to know what these global variables represent?

I thought it is something related to this change in Julia: https://github.com/lfortran/lfortran/pull/1500/files#diff-30a2e77476e8eaaeed0a2281d4fa431fa616dd3075edcf6b6623d396aac8b038L157

2023-04-06 10:01 UTC, Shaikh-Ubaid commented on tests/reference/wat-abs_03-5d62cca.stdout
> -    (global $28 (mut i32) (i32.const 0))
The shared link https://github.com/lfortran/lfortran/pull/1500/files#diff-30a2e77476e8eaaeed0a2281d4fa431fa616dd3075edcf6b6623d396aac8b038L157 seems to just open the difference tab of this PR. It does seem to point to any specific line of code for me. Can you trying sharing via some other way? Probably another link or screenshot?

2023-04-06 10:03 UTC, Thirumalai-Shaktivel commented on tests/reference/wat-abs_03-5d62cca.stdout
> -    (global $28 (mut i32) (i32.const 0))
Check the changes of this file: `tests/reference/julia-arrays_02-849d7b0.stdout`

2023-04-06 10:32 UTC, Shaikh-Ubaid commented on tests/reference/wat-abs_03-5d62cca.stdout
> -    (global $28 (mut i32) (i32.const 0))
I see. So, why are those functions being removed in `tests/reference/julia-arrays_02-849d7b0.stdout`?

It seems with the intrinsic function pass, intrinsic modules are being removed (I guess), right?

2023-04-06 10:35 UTC, Thirumalai-Shaktivel commented on tests/reference/wat-abs_03-5d62cca.stdout
> -    (global $28 (mut i32) (i32.const 0))
Yup, previously I think we were using the `function` definition from the `lfortran_intrinsics_math` module. Now, we create all the functions ourselves using the `intrinsic_function` pass.

2023-04-06 10:38 UTC, Shaikh-Ubaid commented on tests/reference/wat-abs_03-5d62cca.stdout
> -    (global $28 (mut i32) (i32.const 0))
>Yup, previously I think we were using the function definition from the lfortran_intrinsics_math module. Now, we create all the functions ourselves using the intrinsic_function pass.

Great! Thank you for the clarification. So, only function definitions from intrinsic modules are removed (with the module and its global variables still remaining in the ASR) or the whole intrinsic module is removed?

2023-04-06 10:44 UTC, Thirumalai-Shaktivel commented on tests/reference/wat-abs_03-5d62cca.stdout
> -    (global $28 (mut i32) (i32.const 0))
See https://github.com/lfortran/lfortran/pull/1480/files

2023-04-07 11:11 UTC, czgdp1807 requested changes
This makes sense to me but why can't we use the pass_manager APIs here as well? Can you try out using them instead of manually calling the pass.

2023-04-07 11:57 UTC, Thirumalai-Shaktivel commented on src/libasr/codegen/asr_to_julia.cpp
> +
This is the way to do it, right?

2023-04-07 14:18 UTC, Thirumalai-Shaktivel commented on tests/reference/julia-arrays_05-f639a33.stdout
> +    __1_k = 1
There seems to be some bug in the ASRPass. Array: `numbers` is initialised three times.

2023-04-07 14:26 UTC, czgdp1807 commented on tests/reference/julia-arrays_05-f639a33.stdout
> +    __1_k = 1
This seems to me like the output of loop_unroll.cpp pass. Can you apply that pass on the input code and see the ASR output of it? Use, `--pass=loop_unroll --show-asr`.

2023-04-08 10:54 UTC, Thirumalai-Shaktivel commented on tests/reference/julia-arrays_05-f639a33.stdout
> +    __1_k = 1
I was able to debug the issue here:
```Clojure
(Variable
    2
    numbers
    []
    Local
    (ArrayConstant
        [(RealConstant
            1.500000
            (Real 4 [])
        )
        ...
        ]
        (Real 4 [((IntegerConstant 1 (Integer 4 []))
        (IntegerConstant 5 (Integer 4 [])))])
        ColMajor
    )
    (ArrayConstant
        [(RealConstant
            1.500000
            (Real 4 [])
        )
        ...
        ]
        (Real 4 [((IntegerConstant 1 (Integer 4 []))
        (IntegerConstant 5 (Integer 4 [])))])
        ColMajor
    )
    Save
    (Real 4 [((IntegerConstant 1 (Integer 4 []))
    (IntegerConstant 5 (Integer 4 [])))])
    Source
    Public
    Required
    .false.
)
```
Here the `x.symbolic` and `x.value` are visited as `ArrayConstant` and in turn the values are initialised twice

2023-04-08 10:57 UTC, Thirumalai-Shaktivel commented on tests/reference/julia-arrays_05-f639a33.stdout
> +    __1_k = 1
I thought about this and I think we should set `x.m_value` to `null` if `x.m_symbolic_value` and `x.m_value` are same (ArrayConstant).
@czgdp1807 What do you suggest on this?

2023-04-08 11:13 UTC, Thirumalai-Shaktivel commented on src/libasr/pass/init_expr.cpp
> +            }
https://github.com/lfortran/lfortran/pull/1500#discussion_r1161097526

2023-04-08 11:14 UTC, Thirumalai-Shaktivel commented on src/libasr/codegen/asr_to_julia.cpp
> +    }
I'm not familiar with Julia, is this correct way to ArrayBound?

2023-04-08 17:31 UTC, certik commented on tests/reference/julia-array3-ab6fef3.stdout
> +    __1_k = __1_k + 1
I think we should not be lowering high level constructs, but rather keep constructs high level and use an equivalent high level Julia feature.

2023-04-09 07:26 UTC, Thirumalai-Shaktivel commented on tests/reference/julia-array3-ab6fef3.stdout
> +    __1_k = __1_k + 1
Done!

2023-04-09 09:28 UTC, czgdp1807 requested changes

2023-04-09 09:28 UTC, czgdp1807 commented on src/libasr/pass/init_expr.cpp
> +            }
If you are not using this pass in Julia then please don't do this change. If you want to keep it then also test it with LPython by making a PR there.

2023-04-09 09:31 UTC, czgdp1807 commented on tests/reference/julia-arrays_05-f639a33.stdout
> +    __1_k = 1
Depends. If the variable is a constant then we should keep `x.m_value` and backends like LLVM, x86 should use that value directly. However backends like, Julia, C shouldn't be using `x.m_value` if `--fast` mode is not enabled. If `--fast` mode is enabled then all backends should use `x.m_value` whenever its available. So the question is not, which ones should be kept `nullptr` but the question is which one to use and in which backend and under which context. So unless extremely necessary we shouldn't be setting `x.m_symbolic_value` and `x.m_value` to `nullptr` in `init_expr.cpp`.

2023-04-09 10:06 UTC, Thirumalai-Shaktivel commented
Cool, I created an issue for it, https://github.com/lcompilers/lpython/issues/1687

2023-04-09 14:29 UTC, certik commented on tests/reference/julia-arrays_01-81f01a2.stdout
> +        i = i + 1
This removes a for loop and replaces it with a while loop. We should not do that, let's keep the for loop.

2023-04-09 14:30 UTC, certik commented on tests/reference/julia-case_01-cbdd0aa.stdout
> +        end
The if structure seems broken, I think there was some logic before to generate `elseif` which is more readable.

2023-04-09 14:31 UTC, certik commented on tests/reference/julia-case_01-cbdd0aa.stdout
> +        end
I think it's the "case" switch that was lost and rewritten to if statements in ASR.

2023-04-09 14:32 UTC, certik commented
@Thirumalai-Shaktivel what bug are we trying to fix?

We need to remove the "loop" and "switch" ASR passes, those should not be applied. 

Let's do it the other way round: let's not apply any passes and then let's justify every pass that should be applied.

2023-04-09 14:49 UTC, Thirumalai-Shaktivel commented
I was trying to apply ASR Passes for Julia Backend.

2023-04-09 14:49 UTC, Thirumalai-Shaktivel commented
This is ready, kindly review it.

2023-04-09 15:00 UTC, czgdp1807 requested changes

2023-04-09 15:00 UTC, czgdp1807 commented on src/libasr/codegen/asr_to_julia.cpp
> +    pass_replace_intrinsic_function(al, asr, pass_options);
There is one more way to do it. Create a vector `std::vector<std::string> julia_passes = {"intrinsic_functions"}`. Make the following method public (i.e., remove the `_` and shift it to public scope),

https://github.com/lfortran/lfortran/blob/523c4723feba77241d4de241afc1fac95ba3bfe6/src/libasr/pass/pass_manager.h#L100

Then call, `pass_manager.apply_passes(al, asr, julia_passes, pass_options, diag)`

What I am recommending is to not call passes manually but instead use pass_manager for your use case and feel free to modify pass_manager to suit your needs. Everything related to passes should be present in pass_manager and we should be using it to call any ASR pass.

2023-04-09 15:01 UTC, certik commented
> I was trying to apply ASR Passes for Julia Backend.

I think rather we are ensuring the intrinsic function call gets called?

But shouldn't C++ and Julia backends not call this call and rather use Julia "sin" function directly?

2023-04-09 15:02 UTC, Thirumalai-Shaktivel commented on src/libasr/codegen/asr_to_julia.cpp
> +    pass_replace_intrinsic_function(al, asr, pass_options);
Cool, this makes sense. I will make the required changes.
Thank you!

2023-04-09 15:04 UTC, czgdp1807 commented
> But shouldn't C++ and Julia backends not call this call and rather use Julia "sin" function directly?

That makes most sense. In fact, that's the purpose of `IntrinsicFunction`? To leave it to the backend on how they want to implement and call an intrinsic, either by using their own intrinsics (like, C++ has `sin`, Julia has its own `sin` or like LLVM which will call into our C implementation of sin present in `lfortran_intrinsics.c`). So, `intrinsic_functions.cpp` should be applied only to those backends which don't have their own implementation for a given intrinsic.

2023-04-09 15:05 UTC, Thirumalai-Shaktivel commented
Exactly, why didn't I think about this?
It reduces the overhead to compute the value, instead, we should make use of their built-in function itself.
I'm +1 on this. I will try to implement this

2023-04-09 15:22 UTC, certik commented
Exactly.

I think what we will also need to call the intrinsic function pass for some functions but not all. In particular, we will have hundreds or even thousands of intrinsics, various special functions etc. For the vast majority of them you want to call the pass, but for the elementary like trig functions you don't.

So we probably want to enable calling this pass, but selecting which functions to transform (or perhaps "not transform"), those would we handle in the backend ourselves.

2023-04-09 16:35 UTC, certik commented on src/libasr/codegen/asr_to_julia.cpp
> +        }
I don't think we want to do this, unless in `--fast` mode.

2023-04-09 16:36 UTC, certik commented on src/libasr/codegen/asr_to_julia.cpp
> +        src = out;
In here I would do it explicitly based on the given function, for example only for `abs`, `sin`, `cos`, etc. Julia might have different names for some of the intrinsic functions.

2023-04-12 18:12 UTC, certik approved these changes
I think that this is good.

2023-04-13 04:47 UTC, Thirumalai-Shaktivel commented
Thanks for the review!
Let's merge this PR. I will submit the IntrinisicFunction changes to LPython as well.

2023-04-13 04:48 UTC, merged