Upgrade xeus
lfortran/lfortran pull request #1551
Opened 2023-04-12 20:55 UTC by everythingfunctional

Allow using newer versions of xeus for Jupyter kernel support.

2023-04-12 21:55 UTC, certik commented
Thanks! Which version of xeus are you using? Let's pick a version and only use this version everywhere. The reason is that in the past we used the approach in this PR of just using "xeus", but when conda installs a newer version our build breaks, because newer versions are not always backwards compatible. So by using specific versions of all dependencies, we can ensure that our CI always works.

2023-04-12 22:10 UTC, everythingfunctional commented
I'm using the latest version, which xeus is 3.0.5 and xeus-zmq is 1.0.2.

I'll just point out that you aren't using specific versions of other dependencies. Also, if you pin to specific versions you don't necessarily recognise when your dependencies release new versions, and can end up going a long time without upgrading, making the eventual upgrades harder. My usual recommendation is to run your CI without pinned versions, then pin them when something breaks until you can fix it. If you still want me to pin them I will, just my 2 cents.

2023-04-13 21:07 UTC, certik commented
My experience is that things break at the most unfortunate moment, when we are trying to get some important PRs in, and the CI breaks because an upstream package got updated. So to stabilize our CI, we pin packages to their exact versions. We started with the packages that broke in the past: Bison, LLVM, and Xeus. Eventually I would like to pin all packages.

Regarding package upgrades, we can have a CI job that tries to compile with the latest dependencies and it is not required to pass, which would alert us that something does not work. It's almost a full time job to keep maintaining compatibility with the latest dependencies, for example LLVM always requires quite substantial work to get the latest version working

If you wouldn't mind adding the version pin, I would really appreciate it, then we can merge it. You can add a dedicated test for testing the latest dependencies if you want, in a separate PR.

2023-04-14 19:14 UTC, certik commented
Another good approach for new dependencies is to let them get updated with a bot, like this: https://github.com/fortran-lang/webpage/pull/233/files, then the bot submits a PR that updates the dependency, and we see right away if it fails or not.

2023-04-15 15:18 UTC, czgdp1807 requested changes

2023-04-15 15:18 UTC, czgdp1807 commented on ci/environment_docs_linux.yml
> +  - xeus-zmq
IMO, please feel free to update to the latest version but always using the latest uploaded version lead to unexpected CI failures like the following,

https://github.com/lfortran/lfortran/pull/1532#issuecomment-1502057502

So, we can upgrade to xeus=3.0.5 (as I can see on https://anaconda.org/conda-forge/xeus). In `.yml` files we should always use fixed versions of dependencies, however PRs like this can be made to upgrade to latest versions.

Also refer, https://github.com/lfortran/lfortran/pull/1536#pullrequestreview-1377888286

2023-04-24 18:15 UTC, everythingfunctional commented on ci/environment_docs_linux.yml
> +  - xeus-zmq
I've added the version constraints.

2023-04-24 21:41 UTC, certik approved these changes
Looks great, thanks!

2023-04-24 21:43 UTC, merged