Resolve `Function_t` from `ExternalSymbol_t` in pass array_op
lfortran/lfortran pull request #1562
Opened 2023-04-15 06:21 UTC by Pranavchiku

Fixes #1522

2023-04-15 15:12 UTC, czgdp1807 requested changes

2023-04-15 15:12 UTC, czgdp1807 commented on src/libasr/pass/array_op.cpp
> +                                        if ( ASR::is_a<ASR::Function_t>(*subrout) ) {
This should be harmless but can be condensed into,

```suggestion
                                        subrout = ASRUtils::symbol_get_past_external(subrout);
                                        if ( ASR::is_a<ASR::Function_t>(*subrout) ) {
```

2023-04-16 08:21 UTC, czgdp1807 approved these changes

2023-04-16 08:38 UTC, merged

2023-04-16 08:44 UTC, Pranavchiku commented
Thanks for completing this! I had a few quizzes today and hence was not able to apply the suggestions.