Implement ASR pass for `where`
lfortran/lfortran pull request #1599
Opened 2023-04-23 05:34 UTC by Pranavchiku

#1312

2023-04-23 05:37 UTC, Pranavchiku commented on tests/reference/pass_where-where2-4c3a3af.stdout
> +                                (Var 2 a)
I need to replace `(Var 2 a)` with 
```clojure
(ArrayItem
  (Var 2 a)
  [(()
  (Var 2 __1_k)
  ())]
  (Integer 4 [])
  ColMajor
  ()
)
```
at every place in the body of `IF` statement. 

I am not sure how can I do this, can anyone help me here please?

2023-04-23 15:26 UTC, certik commented on tests/reference/pass_where-where2-4c3a3af.stdout
> +                                (Var 2 a)
Great job! @czgdp1807 might know, otherwise I can have a look later.

2023-04-24 04:56 UTC, czgdp1807 commented on tests/reference/pass_where-where2-4c3a3af.stdout
> +                                (Var 2 a)
Please see ``pass_array_by_data.cpp`` on how we edit `Var` node to point to right symbols.

2023-04-24 09:50 UTC, Pranavchiku commented
```fortran
program main
    implicit none
    real a(2)
    real b(2)
    
    a(1) = 1.0
    a(2) = 2.0

    b(1) = 0.5
    b(2) = 3.5

    where (a > b) 
        a = 1.5
    endwhere
    
    print *, a
end program
```

> GFortran

```console
$ gfortran ./tests/temp.f90 && ./a.out
   1.50000000       2.00000000    
```

> LFortran

```console
$ lfortran ./tests/temp.f90 
1.00000000e+00 2.00000000e+00 
```

<details>
<summary> --pass=where --show-asr </summary>
<p>



```clojure
(TranslationUnit
    (SymbolTable
        1
        {
            main:
                (Program
                    (SymbolTable
                        2
                        {
                            __1_k:
                                (Variable
                                    2
                                    __1_k
                                    []
                                    Local
                                    ()
                                    ()
                                    Default
                                    (Integer 4 [])
                                    ()
                                    Source
                                    Public
                                    Required
                                    .false.
                                ),
                            a:
                                (Variable
                                    2
                                    a
                                    []
                                    Local
                                    ()
                                    ()
                                    Default
                                    (Real 4 [((IntegerConstant 1 (Integer 4 []))
                                    (IntegerConstant 2 (Integer 4 [])))])
                                    ()
                                    Source
                                    Public
                                    Required
                                    .false.
                                ),
                            b:
                                (Variable
                                    2
                                    b
                                    []
                                    Local
                                    ()
                                    ()
                                    Default
                                    (Real 4 [((IntegerConstant 1 (Integer 4 []))
                                    (IntegerConstant 2 (Integer 4 [])))])
                                    ()
                                    Source
                                    Public
                                    Required
                                    .false.
                                )
                        })
                    main
                    []
                    [(=
                        (ArrayItem
                            (Var 2 a)
                            [(()
                            (IntegerConstant 1 (Integer 4 []))
                            ())]
                            (Real 4 [])
                            ColMajor
                            ()
                        )
                        (RealConstant
                            1.000000
                            (Real 4 [])
                        )
                        ()
                    )
                    (=
                        (ArrayItem
                            (Var 2 a)
                            [(()
                            (IntegerConstant 2 (Integer 4 []))
                            ())]
                            (Real 4 [])
                            ColMajor
                            ()
                        )
                        (RealConstant
                            2.000000
                            (Real 4 [])
                        )
                        ()
                    )
                    (=
                        (ArrayItem
                            (Var 2 b)
                            [(()
                            (IntegerConstant 1 (Integer 4 []))
                            ())]
                            (Real 4 [])
                            ColMajor
                            ()
                        )
                        (RealConstant
                            0.500000
                            (Real 4 [])
                        )
                        ()
                    )
                    (=
                        (ArrayItem
                            (Var 2 b)
                            [(()
                            (IntegerConstant 2 (Integer 4 []))
                            ())]
                            (Real 4 [])
                            ColMajor
                            ()
                        )
                        (RealConstant
                            3.500000
                            (Real 4 [])
                        )
                        ()
                    )
                    (DoLoop
                        ()
                        ((Var 2 __1_k)
                        (IntegerConstant 0 (Integer 4 []))
                        (ArraySize
                            (Var 2 a)
                            ()
                            (Real 4 [])
                            ()
                        )
                        (IntegerConstant 1 (Integer 4 [])))
                        [(If
                            (RealCompare
                                (ArrayItem
                                    (Var 2 a)
                                    [(()
                                    (Var 2 __1_k)
                                    ())]
                                    (Real 4 [])
                                    ColMajor
                                    ()
                                )
                                Gt
                                (ArrayItem
                                    (Var 2 b)
                                    [(()
                                    (Var 2 __1_k)
                                    ())]
                                    (Real 4 [])
                                    ColMajor
                                    ()
                                )
                                (Logical 4 [])
                                ()
                            )
                            [(=
                                (ArrayItem
                                    (Var 2 a)
                                    [(()
                                    (Var 2 __1_k)
                                    ())]
                                    (Real 4 [])
                                    ColMajor
                                    ()
                                )
                                (RealConstant
                                    1.500000
                                    (Real 4 [])
                                )
                                ()
                            )]
                            []
                        )]
                    )
                    (Print
                        ()
                        [(Var 2 a)]
                        ()
                        ()
                    )]
                )
        })
    []
)
```

</p>
</details>


<details>
<summary> ASR that goes to LLVM </summary>

<p>



```clojure
(TranslationUnit
    (SymbolTable
        1
        {
            main:
                (Program
                    (SymbolTable
                        2
                        {
                            __1_k:
                                (Variable
                                    2
                                    __1_k
                                    []
                                    Local
                            [...]

2023-04-24 10:09 UTC, Pranavchiku commented
Above error is resolved, this was because of incorrect positioning of `where` pass. I placed it just above `array_op` and it worked.

2023-04-24 15:26 UTC, czgdp1807 commented on src/bin/lfortran.cpp
> +#include <libasr/pass/where.h>
General comment: I think these headers can be removed from here because `pass_manager.h` already includes them. Should be done separately.

2023-04-24 15:26 UTC, czgdp1807 commented on integration_tests/where_03.f90
> +    endwhere
This whole thing can be replaced by an if-else-if ladder in an ASR pass.

2023-04-24 15:26 UTC, czgdp1807 commented on src/libasr/pass/where.cpp
> +    }
Why is it important to define this assignment visitor here?

2023-04-24 15:26 UTC, czgdp1807 commented on src/libasr/pass/where.cpp
I am confused here. It should have been as simple as,

```cpp
void visit_Where(const ASR::Where_t& x) {
    ASR::stmt_t* body = x.m_body;
    ASR::stmt_t* else_where = x.m_orelse;
    ASR::stmt_t* parent_where_copy = parent_where; // parent_where is a class member
    parent_where = &(x.base);
    child_where = nullptr; // child_where is a class member
    if( else_where ) {
        visit_stmt(*else_where);
    }
    ASR::stmt_t* if_ = ASRUtils::STMT(ASR::make_If_t(al, x.base.base.loc, x.m_test, body, child_where));
    parent_where = parent_where_copy;
    if( parent_where == nullptr ) {
        pass_result.push_back(al, if_);
    } else {
        child_where = if_;
    }
}
```

We don't care what's inside the body and test expressions of each `where` statement. `where` statement is getting replaced by an `if` statement inside the same scope. So no need to edit or modify any expressions just shift the statements from `ASR::Where` nodes to `ASR::If` nodes.

2023-04-24 15:49 UTC, Pranavchiku commented on src/bin/lfortran.cpp
> +#include <libasr/pass/where.h>
If I remove this, it throws error while linking.

2023-04-24 15:52 UTC, Pranavchiku commented on tests/reference/pass_where-where_03-edec3b0.stdout
> +                        [(If
Referring to the previous comment, from here we have if ladder.

2023-04-24 16:01 UTC, Pranavchiku commented on src/libasr/pass/where.cpp
> Seems like the test in where acts as a mask for the statements inside where's body.
 
I did not understand the term mask, but yes those are not actual test, we need to check corresponding `a(i)` and `b(i)`.

2023-04-25 11:14 UTC, Pranavchiku commented
I guess this PR can have a final review.

2023-04-25 13:07 UTC, czgdp1807 requested changes

2023-04-25 13:07 UTC, czgdp1807 commented on src/libasr/pass/where.cpp
> +
You need to use replacers (see how we use `BaseExprReplacer`, `CallReplacerOnExpressionsVisitor` in other passes) for replacing `Var(array)` with `ArrayItem(array, i, j, k, ...)`. Also see uses of `PassUtils::create_array_ref` in `array_op.cpp` and `array_slice.cpp`.

2023-04-25 13:07 UTC, czgdp1807 commented on integration_tests/where_02.f90
> +    real b(2)
Test with multi-dimensional arrays as well.

2023-04-27 05:23 UTC, Pranavchiku commented
Yes, I have two deadlines tomorrow. I will try to finish this PR by end of this week for sure.

2023-04-29 06:48 UTC, Pranavchiku commented
I have made progress over using BaseExprReplacer and CallReplacerOnExpressionsVisitor, I will push changes soon.

2023-04-29 07:42 UTC, Pranavchiku commented on integration_tests/where_02.f90
> +    real b(2)
Modern Minpack does not require this and hence I am planning to add this as a patch, later on, it will not be difficult, mostly similar to `arr_slice.cpp`.

2023-04-29 07:43 UTC, Pranavchiku commented on src/libasr/pass/where.cpp
> +
Done updates as suggested.

2023-04-29 07:50 UTC, Pranavchiku commented
TODO: 
- [ ] Create a minimal example of `where` used in `test_hybrd`
- [ ] make it pass

2023-04-29 10:11 UTC, Pranavchiku commented
```fortran
program main
    implicit none

    call compare_solutions()

    contains

    subroutine compare_solutions()
    implicit none
    real :: reldiff(2)
    real :: absdiff
    
    where (solution() /= 0.0) reldiff = absdiff / abs(solution())

    end subroutine compare_solutions

    pure function solution() result(x)
        implicit none
        real,dimension(:),allocatable :: x
        x = [0.10,0.10]
    end function solution
end program main
```
How should we handle `solution()` function call inside where? @czgdp1807 @certik suggestions please.

2023-04-30 00:09 UTC, certik commented
I think `solution()` has to create a temporary array that we then process as usual. I think it should be done in an ASR pass, so that we can easily debug it.

2023-04-30 00:09 UTC, certik commented
@Pranavchiku what needs to be done to finish this PR?

2023-04-30 03:23 UTC, Pranavchiku commented
This PR is ready to merge, I am not sure why this macos test is failing, I updated all test references.

2023-04-30 05:16 UTC, certik commented
The `where` test seems to fail on macOS, so we need to debug it.

2023-04-30 06:05 UTC, Pranavchiku commented
Error:
```console
../integration_tests/where_01.f90 * pass_where
The JSON metadata differs against reference results
Reference JSON: tests/reference/pass_where-where_01-d0a057b.json
Output JSON:    tests/output/pass_where-where_01-d0a057b.json
Omitting 8 identical items
Differing items:
{'stdout': None} != {'stdout': 'pass_where-where_01-d0a057b.stdout'}
{'stdout_hash': None} != {'stdout_hash': '896bb7186c48b28dcc285e5f2473b3cdf04b4c360d3593d323da9f2e'}
{'returncode': -11} != {'returncode': 0}No output stdout_hash available for ../integration_tests/where_01.f90
```
This difference is not found on my PC (Ubuntu 22.04). I do not have Mac to verify if on local, if anyone can do that will of great help.
```json
{
    "basename": "pass_where-where_01-d0a057b",
    "cmd": "lfortran --pass=where --indent --show-asr --no-color {infile} -o {outfile}",
    "infile": "tests/../integration_tests/where_01.f90",
    "infile_hash": "761e682dad0855b945982b56d551b9f6a7aacba6ee8c0b4586926ad1",
    "outfile": null,
    "outfile_hash": null,
    "stdout": "pass_where-where_01-d0a057b.stdout",
    "stdout_hash": "896bb7186c48b28dcc285e5f2473b3cdf04b4c360d3593d323da9f2e",
    "stderr": null,
    "stderr_hash": null,
    "returncode": 0
}
```

2023-04-30 09:15 UTC, czgdp1807 requested changes

2023-04-30 09:15 UTC, czgdp1807 commented on src/libasr/pass/where.cpp
> +        current_expr = &new_expr_;
```suggestion
        *current_expr = new_expr_;
```

2023-04-30 09:25 UTC, Pranavchiku commented
For minimal example in [comment](https://github.com/lfortran/lfortran/pull/1599#issuecomment-1528745596)
I am able to translate to the following ASR, 
<details>
<summary>ASR</summary>
<p>



```clojure
(=
  (Var 3 __libasr__created__var__1_x)
  (FunctionCall
      2 solution
      ()
      []
      (Real 4 [(()
      ())])
      ()
      ()
  )
  ()
)
(DoLoop
  ()
  ((Var 3 __1_k)
  (ArrayBound
      (Var 3 __libasr__created__var__1_x)
      (IntegerConstant 1 (Integer 4 []))
      (Integer 4 [])
      LBound
      ()
  )
  (ArrayBound
      (Var 3 __libasr__created__var__1_x)
      (IntegerConstant 1 (Integer 4 []))
      (Integer 4 [])
      UBound
      ()
  )
  (IntegerConstant 1 (Integer 4 [])))
  [(If
      (RealCompare
          (ArrayItem
              (Var 3 __libasr__created__var__1_x)
              [(()
              (Var 3 __1_k)
              ())]
              (Real 4 [])
              RowMajor
              ()
          )
          NotEq
          (RealConstant
              0.000000
              (Real 4 [])
          )
          (Logical 4 [])
          ()
      )
      [(=
          (ArrayItem
              (Var 3 reldiff)
              [(()
              (Var 3 __1_k)
              ())]
              (Real 4 [])
              RowMajor
              ()
          )
          (RealBinOp
              (Var 3 absdiff)
              Div
              (IntrinsicFunction
                  Abs
                  [(ArrayItem
                      (Var 3 __libasr__created__var__1_x)
                      [(()
                      (Var 3 __1_k)
                      ())]
                      (Real 4 [])
                      RowMajor
                      ()
                  )]
                  0
                  (Real 4 [])
                  ()
              )
              (Real 4 [])
              ()
          )
          ()
      )]
      []
  )]
)
```
</p>
</details>

2023-05-01 02:01 UTC, certik commented on integration_tests/where_04.f90
> +
This should test the results

2023-05-01 02:02 UTC, certik commented on integration_tests/where_01.f90
>  else where
This test should test some actual results, so let's initialize a, and then test b.

2023-05-01 02:03 UTC, certik commented
The tests pass on Apple M1, so I can't reproduce the macOS Intel failure either.

2023-05-01 02:04 UTC, certik commented
However, the CI says this is the error:
```
../integration_tests/where_01.f90 * pass_where
The JSON metadata differs against reference results
Reference JSON: tests/reference/pass_where-where_01-d0a057b.json
Output JSON:    tests/output/pass_where-where_01-d0a057b.json
Omitting 10 identical items
Differing items:
{'stdout_hash': 'b3dc91857abdad85147b8fe958c479dfad6ef02ae94e1f2bf036e339'} != {'stdout_hash': '896bb7186c48b28dcc285e5f2473b3cdf04b4c360d3593d323da9f2e'}
Diff against: tests/reference/pass_where-where_01-d0a057b.stdout
98,106c98
<                                 (ArrayItem
<                                     (Var 2 b)
<                                     [(()
<                                     (Var 2 __1_k)
<                                     ())]
<                                     (Integer 4 [])
<                                     RowMajor
<                                     ()
<                                 )
---
>                                 
111,119c103
<                                 (ArrayItem
<                                     (Var 2 b)
<                                     [(()
<                                     (Var 2 __1_k)
<                                     ())]
<                                     (Integer 4 [])
<                                     RowMajor
<                                     ()
<                                 )
---
>                                 
160,168c144
<                                 (ArrayItem
<                                     (Var 2 b)
<                                     [(()
<                                     (Var 2 __1_k)
<                                     ())]
<                                     (Integer 4 [])
<                                     RowMajor
<                                     ()
<                                 )
---
>                                 
173,181c149
<                                 (ArrayItem
<                                     (Var 2 b)
<                                     [(()
<                                     (Var 2 __1_k)
<                                     ())]
<                                     (Integer 4 [])
<                                     RowMajor
<                                     ()
<                                 )
---
>                                 
222,230c190
<                                 (ArrayItem
<                                     (Var 2 b)
<                                     [(()
<                                     (Var 2 __1_k)
<                                     ())]
<                                     (Integer 4 [])
<                                     RowMajor
<                                     ()
<                                 )
---
>                                 
235,243c195
<                                 (ArrayItem
<                                     (Var 2 b)
<                                     [(()
<                                     (Var 2 __1_k)
<                                     ())]
<                                     (Integer 4 [])
<                                     RowMajor
<                                     ()
<                                 )
---
>                                 
```
So this should be enough information to figure it out.

2023-05-01 02:09 UTC, certik commented
It looks like there is some kind of a dangling pointer, for the ArrayItem that does not get printed.

2023-05-01 02:10 UTC, certik commented on src/libasr/pass/where.cpp
> +
Give an example as Fortran code here, showing what the input is, and what the output is.

2023-05-01 02:17 UTC, certik commented
I looked into the `where` pass in this PR if I can see some pointer issues, but didn't see anything. There might still be a bug there, or in `array_op`.

2023-05-01 06:12 UTC, czgdp1807 commented
With the following diff,

```zsh
diff --git a/build1.sh b/build1.sh
index 040c07e46..7f601ee3c 100755
--- a/build1.sh
+++ b/build1.sh
@@ -4,7 +4,7 @@ set -e
 set -x
 
 cmake \
-    -DCMAKE_BUILD_TYPE=Debug \
+    -DCMAKE_BUILD_TYPE=Release \
     -DWITH_LLVM=yes \
     -DLFORTRAN_BUILD_ALL=yes \
     -DWITH_STACKTRACE=yes \
```

I am able to re-produce the error on my machine,

```zsh
Traceback (most recent call last):
  File "/Users/czgdp1807/lfortran_project/lfortran/run_tests.py", line 352, in <module>
    tester_main("LFortran", single_test)
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/compiler_tester/tester.py", line 440, in tester_main
    for f in futures:
  File "/Users/czgdp1807/mambaforge/envs/lf/lib/python3.9/concurrent/futures/_base.py", line 608, in result_iterator
    yield fs.pop().result()
  File "/Users/czgdp1807/mambaforge/envs/lf/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/Users/czgdp1807/mambaforge/envs/lf/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/Users/czgdp1807/mambaforge/envs/lf/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/czgdp1807/lfortran_project/lfortran/run_tests.py", line 200, in single_test
    run_test(filename, "pass_{}".format(pass_), cmd,
  File "/Users/czgdp1807/lfortran_project/lfortran/src/libasr/compiler_tester/tester.py", line 330, in run_test
    raise RunException(
compiler_tester.tester.RunException: Testing with reference output failed.
../integration_tests/where_01.f90 * pass_where
The JSON metadata differs against reference results
Reference JSON: tests/reference/pass_where-where_01-d0a057b.json
Output JSON:    tests/output/pass_where-where_01-d0a057b.json
Omitting 8 identical items
Differing items:
{'stdout_hash': None} != {'stdout_hash': 'cc733bbb95fef48ec9643c7397c2a49feaee136e37f4d3bec82f354d'}
{'returncode': -10} != {'returncode': 0}
{'stdout': None} != {'stdout': 'pass_where-where_01-d0a057b.stdout'}No output stdout_hash available for ../integration_tests/where_01.f90
```

2023-05-01 06:14 UTC, czgdp1807 commented
> There might still be a bug there, or in `array_op`.

I don't think its related to `array_op` because the following command also fails which doesn't use `array_op` at all,

```
(lf) 11:43:06:~/lfortran_project/lfortran % lfortran integration_tests/where_01.f90 --show-asr --pass=where
zsh: bus error  lfortran integration_tests/where_01.f90 --show-asr --pass=where
```

2023-05-01 07:06 UTC, czgdp1807 approved these changes
Its fine but multi-dimensional case isn't covered yet which is more important.

2023-05-01 07:30 UTC, Pranavchiku commented
Thanks for fixing this :)

2023-05-01 18:43 UTC, certik approved these changes
Good enough to merge, thanks!

2023-05-01 18:44 UTC, merged

2023-05-01 18:45 UTC, certik commented on integration_tests/where_03.f90
> +    b = (/ -1.0, -2.0, 5.0, 7.0/)
One should use [] not `(/` and `/)`.

2023-05-01 23:04 UTC, certik commented
Here is what I am getting now with minpack's tests: https://github.com/lfortran/lfortran/issues/1633