Parse alt_return in Subroutine call
lfortran/lfortran pull request #1627
Opened 2023-04-28 18:32 UTC by Thirumalai-Shaktivel

Fixes: #1609

2023-04-28 18:34 UTC, Thirumalai-Shaktivel commented on grammar/AST.asdl
> +arg = (identifier? arg)
This is used for Subroutine arguments. If `arg` is `nullptr`, we can assume it to be a star.

2023-04-28 18:35 UTC, Thirumalai-Shaktivel commented on grammar/AST.asdl
> +fnarg = (expr? start, expr? end, expr? step, int label)
@certik, see if this is okay, otherwise we can modify the design.

2023-04-28 18:36 UTC, Thirumalai-Shaktivel commented on tests/reference/ast-subroutine10-11d8518.stdout
Here is the AST generated

2023-04-28 18:36 UTC, Thirumalai-Shaktivel commented on tests/reference/ast_f90-subroutine10-1eb50e4.stdout
Here is the fmt generated.

2023-05-15 17:00 UTC, czgdp1807 requested changes
Please resolve the conflicts.

2023-05-15 17:18 UTC, certik commented
I think this looks good. Can you also please add a check into AST->ASR and give an error message if the argument is not present, saying "alternate returns are not implemented yet"?

2023-05-16 04:29 UTC, czgdp1807 approved these changes

2023-05-16 04:29 UTC, czgdp1807 approved these changes

2023-05-16 13:24 UTC, certik commented on grammar/AST.asdl
> +-- X(*10)     ()         ()      ()       10
I am not supper happy that the deprecated old feature (alternate returns) is polluting arrays. But we need to be able to represent `call f(*100)` as well as `1 + f(*100)`. I don't know how to avoid it.

2023-05-16 13:25 UTC, certik commented
Can you rebase this before merging? The history has some merge commits in it.

2023-05-16 14:40 UTC, merged