Add provision to handle `external` declaration with non null vartype
lfortran/lfortran pull request #1819
Opened 2023-06-14 15:32 UTC by Pranavchiku

Fixes #1803.

2023-06-15 05:03 UTC, czgdp1807 requested changes

2023-06-15 05:03 UTC, czgdp1807 commented on integration_tests/external_03.f90
> +end subroutine
Which `dmprec` will be used after line 4? `external dmprec` or `double precision dmprec`. I think it should be tested.

2023-06-15 08:24 UTC, Pranavchiku commented on integration_tests/external_03.f90
> +end subroutine
It will be treated as a function with return type as `double precision`

2023-06-15 15:04 UTC, certik commented on integration_tests/external_03.f90
> +end subroutine
I think @czgdp1807's point is to add a line after line 4, that does something to ensure this behaves as intended. However, that might be a new test as well, since it might change the internal logic in AST->ASR.

2023-06-15 15:36 UTC, Pranavchiku commented on integration_tests/external_03.f90
> +end subroutine
Yes, I'll do that.

2023-06-17 05:16 UTC, Pranavchiku commented on integration_tests/external_03.f90
> +end subroutine
Done

2023-06-17 05:22 UTC, Pranavchiku commented
This PR can have a final review.

2023-06-17 11:56 UTC, certik approved these changes
I think that this is good. One question: I think that external_03 and external_04 should only work with `--implicit-interface`, since it is inferring the interface which should be disabled by default. Do you mind making this change in the next PR?

2023-06-17 11:57 UTC, merged

2023-06-17 12:12 UTC, Pranavchiku commented
Yeah sure!