Change functionType to implementation in create_external_function
lfortran/lfortran pull request #1988
Opened 2023-07-15 12:21 UTC by HarshitaKalani

Fixes: https://github.com/lfortran/lfortran/issues/1977

2023-07-15 16:29 UTC, certik commented on tests/reference/asr-external_07-8559e2d.stdout
> +                                        Implementation
Here `f` is not an implementation but an interface.

2023-07-20 05:56 UTC, czgdp1807 requested changes

2023-07-20 05:56 UTC, czgdp1807 commented on integration_tests/external_07.f90
> +end program
If this compiles then how will I know if it is being executed correctly? Probably we should have assert checks (`if(some_condition) error stop` in Fortran) to make sure things are happening as expected.

2024-01-02 11:21 UTC, HarshitaKalani commented
Closing this as completed via #2796 and #2800.

2024-01-02 11:21 UTC, closed without merging