No case sensitivity in array and procedure name
lfortran/lfortran pull request #2112
Opened 2023-08-08 09:52 UTC by HarshitaKalani

Fixes: https://github.com/lfortran/lfortran/issues/251

2023-08-08 14:33 UTC, Pranavchiku commented on src/lfortran/semantics/ast_common_visitor.h
> +        ASR::symbol_t *sub = scope->resolve_symbol(lower_sub_name.c_str());
```suggestion
       ASR::symbol_t *sub = scope->resolve_symbol(to_lower(sub_name));
```
Something like this should do the trick

2023-08-08 14:35 UTC, Pranavchiku commented on integration_tests/case_sensitive_01.f90
> +  end program
```suggestion
module hello_m
    implicit none
    private
    public :: say_hello
    
    interface say_hello
      module procedure Say_Hello_To
    end interface
  contains
    subroutine say_hello_to(name, x)
      character(len=*), intent(in) :: name
      integer :: x
      if ( x /= 1023 ) error stop
      print *, "Hello, " // name // "!"
    end subroutine
  end module
  
  program test
    use hello_m
    implicit none
    call say_hello("World", 1023)
  end program
```

Lets pass a variable and verify that inside the subroutine.

2023-08-08 14:36 UTC, Pranavchiku requested changes
You will have to register the test inside `integration_tests/CMakelists.txt`, I left few comments above, rest looks good to me.

2023-08-08 14:37 UTC, HarshitaKalani commented on src/lfortran/semantics/ast_common_visitor.h
> +        ASR::symbol_t *sub = scope->resolve_symbol(lower_sub_name.c_str());
Oh right. I tried this but was getting some error. It's working fine now. Thanks!

2023-08-08 18:57 UTC, certik commented on src/lfortran/semantics/ast_common_visitor.h
> +        ASR::symbol_t *sub = scope->resolve_symbol(to_lower(sub_name));
I am not sure if this is the right fix, because it will be applying the to_lower all the time when it is in fact not needed most of the time.

Did you figure out the place that needs `to_lower`?

2023-08-09 07:20 UTC, HarshitaKalani commented on src/lfortran/semantics/ast_common_visitor.h
> +        ASR::symbol_t *sub = scope->resolve_symbol(to_lower(sub_name));
```
semantic error: Symbol 'Say_Hello_To' not declared
 --> a.f90:1:2
  |
1 | module hello_m
  |  ^ 
```
This was the error and I found that it was produced through this function, so I made sub_name lowercase.
> it will be applying the to_lower all the time when it is in fact not needed most of the time.

That is true but we need to make sure that subname = SubName = subNAme and so on and that depends on how user writes it, right?

2023-08-10 06:33 UTC, Pranavchiku commented
Converting this PR to draft

2024-03-13 16:33 UTC, HarshitaKalani commented
Closing this as #251 is fixed.

2024-03-13 16:33 UTC, closed without merging