Introduce and Implement `RealCopySign`
lfortran/lfortran pull request #2190
Opened 2023-08-18 05:59 UTC by Pranavchiku

Fixes #2187.

2023-08-18 07:37 UTC, Pranavchiku commented
The test `CI / Test WASM` fails with following log, @Shaikh-Ubaid can you please check what is wrong here? It looks to me some linking needs to be done.
```console
163/191 Test #163: fma ..............................***Failed    0.71 sec
node:internal/modules/cjs/loader:1042
  throw err;
  ^

Error: Cannot find module '/home/runner/work/lfortran/lfortran/integration_tests/test-wasm/fma.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Module._load (node:internal/modules/cjs/loader:885:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

2023-08-18 13:00 UTC, Pranavchiku commented
Thank you @Shaikh-Ubaid!

2023-08-18 14:04 UTC, certik commented
Thanks @Shaikh-Ubaid.

@czgdp1807, can you please review this PR?

2023-08-18 14:08 UTC, certik commented
@Shaikh-Ubaid your WASM builder already had support for copysign? Very good, that means it was a good design to add this new ASR node. What other WASM primitives are there that we don't currently have an ASR node for?

2023-08-18 15:03 UTC, czgdp1807 requested changes

2023-08-18 15:03 UTC, czgdp1807 commented on integration_tests/intrinsics_64.f90
> +    x = sign(x, y)
Tests for arrays? I think `sign` is elemental function, so we should add test it for arrays and add support for it.

2023-08-18 15:03 UTC, czgdp1807 commented on src/libasr/ASR.asdl
> +    | RealCopySign(expr target, expr source, ttype type, expr? value)
A new node for it? I think it can be implemented using `IntrinsicFunction`. No need instantiate it though.

2023-08-18 15:24 UTC, Pranavchiku commented on integration_tests/intrinsics_64.f90
> +    x = sign(x, y)
we have tests for arrays in the test suite. I just added a test for `-0.0` to make sure it works.

2023-08-18 15:26 UTC, Pranavchiku commented on src/libasr/ASR.asdl
> +    | RealCopySign(expr target, expr source, ttype type, expr? value)
I and @certik discussed this yesterday and thought this can be a clean design to make the backend know we are using `llvm.copysign`: https://github.com/lfortran/lfortran/issues/2187#issuecomment-1682821967

2023-08-18 16:11 UTC, Shaikh-Ubaid commented
>@Shaikh-Ubaid your WASM builder already had support for copysign?

Yes, all the instructions in `src/libasr/wasm_instructions.txt` (excluding the lines marked with `--`) are currently supported in the WASM Builder/Assembler. 

>What other WASM primitives are there that we don't currently have an ASR node for?

It seems for some primitives, we have indirect support at the ASR, for example we support the following using `RealBinOp` in the ASR:
```
f32.add
f32.sub
f32.mul
f32.div
```

I think following are some floating primitives which do not have a direct ASR node.
```f32.abs
f32.ceil
f32.floor
f32.trunc
f32.nearest
f32.min
f32.max
```
Similary for `f64`.

Also, I think following are some integer primitive instructions for which we do not have ASR nodes:
```
i32.clz
i32.ctz
i32.popcnt
```

2023-08-19 02:55 UTC, certik commented
Thanks @Shaikh-Ubaid. I made this https://github.com/lfortran/lfortran/issues/2196.

2023-08-19 02:56 UTC, certik commented on src/libasr/ASR.asdl
> +    | RealCopySign(expr target, expr source, ttype type, expr? value)
I think this cannot be IntrinsicFunction since it can't be implemented using other ASR nodes.

2023-08-19 03:03 UTC, certik approved these changes
I think this looks great, thanks @Pranavchiku !

2023-08-19 03:04 UTC, merged