Throw error for the rank mismatch in array reference
lfortran/lfortran pull request #2215
Opened 2023-08-21 07:46 UTC by Thirumalai-Shaktivel

Fixes: #2201

2023-08-21 15:52 UTC, certik commented
GFortran is correct here, the shape should be `(2,2)`, not `(2,2,0)`.

2023-08-21 15:55 UTC, certik commented on tests/reference/asr-array_03-a79d86f.stderr
> +semantic error: Rank mismatch in array reference: accessible rank is `1`, provided `2`
What does "accessible rank" mean?

I would write it like this: "Rank mismatch in array reference: the array `x` has rank 1, but referenced as rank `2`"

Or something like that.

2023-08-22 10:45 UTC, Thirumalai-Shaktivel commented
> https://github.com/lfortran/lfortran/pull/2215#issuecomment-1686259666

Fixed here: https://github.com/lfortran/lfortran/pull/2222

2023-08-25 04:36 UTC, czgdp1807 requested changes

2023-08-25 04:36 UTC, czgdp1807 commented on tests/errors/array_03.f90
> +    x(1, 2)(:) = '1234'
Keep this for future. However also add these as three separate files because we must make sure that if someone changes the code you added then also these three lines individually throw errors.

2023-08-25 04:36 UTC, czgdp1807 commented
Resolve conflicts.

2023-08-30 07:52 UTC, Thirumalai-Shaktivel commented on tests/errors/array_03.f90
> +    x(1, 2)(:) = '1234'
Done

2023-08-30 16:12 UTC, certik approved these changes

2023-08-30 16:13 UTC, merged