CI: Test scipy/optimize/minpack
lfortran/lfortran pull request #2285
Opened 2023-08-30 05:49 UTC by HarshitaKalani

https://github.com/lfortran/lfortran/issues/2203

2023-08-30 07:55 UTC, Pranavchiku commented on .github/workflows/CI.yml
> +                lfortran -c $src -o ${src%.f}.o --fixed-form --implicit-typing --implicit-interface --generate-object-code --use-loop-variable-after-loop
```suggestion
                ../src/bin/lfortran -c $src -o ${src%.f}.o --fixed-form --implicit-typing --implicit-interface --generate-object-code --use-loop-variable-after-loop --all-mangling --magle-underscore
```

2023-08-30 07:55 UTC, Pranavchiku commented on .github/workflows/CI.yml
> +            clang -shared -fPIC -o ./scipy/optimize/minpack.so *.o -L/home/harshita/Desktop/lfortran/src/runtime -llfortran_runtime
```suggestion
            clang -shared -fPIC -o ./scipy/optimize/minpack.so *.o -L../src/runtime -llfortran_runtime
```

2023-08-30 07:56 UTC, Pranavchiku commented on .github/workflows/CI.yml
> +            python dev.py test -t scipy.optimize
```suggestion
            python dev.py test -t scipy.optimize -v
```

2023-08-30 07:59 UTC, Pranavchiku requested changes
I left a few comments. @HarshitaKalani I added a new commit at `ondrej/minpack1` to use fixed versions in environment.yml file, commit hash: [b8ee2a865500263d17d366d7b286ee3a60abe6ec](https://github.com/certik/scipy/commit/b8ee2a865500263d17d366d7b286ee3a60abe6ec)

2023-08-30 08:00 UTC, Pranavchiku commented on .github/workflows/CI.yml
> +            git checkout 9ee9208fc52ccc04d3128132888c0798e7ae677a
```suggestion
            git checkout b8ee2a865500263d17d366d7b286ee3a60abe6ec
```

2023-08-30 08:01 UTC, Pranavchiku commented on .github/workflows/CI.yml
> +            python dev.py test -t scipy.optimize
We should use `-v` to know which test is failing.

2023-08-30 19:28 UTC, certik commented on .github/workflows/CI.yml
>              python dev.py test -t scipy.special -v
You mind need to `cd ..; rm -r scipy` here.

2023-08-30 19:31 UTC, certik commented on .github/workflows/CI.yml
>              python dev.py test -t scipy.special -v
That should fix the current failure:
```
+ git clone https://github.com/scipy/scipy
fatal: destination path 'scipy' already exists and is not an empty directory.
Error: Process completed with exit code 128.
```

2023-08-31 04:40 UTC, Pranavchiku commented on .github/workflows/CI.yml
>              python dev.py test -t scipy.special -v
Yes, perfect. Once we have this CI setup ready for minpack, we can combine SciPy build for Specfun and LFortran, and then just do different `python dev.py test -t scipy.special -v` followed by `python dev.py test -t scipy.optimize -v`

2023-08-31 09:34 UTC, Pranavchiku commented on .github/workflows/CI.yml
> +            all=$(find /home/harshita/scipy/scipy/optimize/minpack/ -name "*.f" | wc -l)
```suggestion
            all=$(find./scipy/optimize/minpack/ -name "*.f" | wc -l)
```

2023-08-31 09:34 UTC, Pranavchiku commented on .github/workflows/CI.yml
> +            for src in $(find /home/harshita/scipy/scipy/optimize/minpack/ -name "*.f"); do
```suggestion
            for src in $(find ./scipy/optimize/minpack/ -name "*.f"); do
```

2023-08-31 09:34 UTC, Pranavchiku commented on .github/workflows/CI.yml
> +            ../src/bin/lfortran -c /home/harshita/scipy/scipy/optimize/minpack/chkder.f -o chkder.o --fixed-form --implicit-typing --implicit-interface --generate-object-code --use-loop-variable-afte
```suggestion
            ../src/bin/lfortran -c ./scipy/optimize/minpack/chkder.f -o chkder.o --fixed-form --implicit-typing --implicit-interface --generate-object-code --use-loop-variable-after-loop --rtlib --all-mangling --mangle-underscore
```

2023-08-31 09:36 UTC, Pranavchiku requested changes
I left some suggestions above, please address those.

2023-08-31 15:56 UTC, HarshitaKalani commented
I believe the current failure in the checks will be resolved when https://github.com/lfortran/lfortran/pull/2263 will be merged.

2023-09-01 16:09 UTC, Pranavchiku commented on .github/workflows/CI.yml
> +                ../src/bin/lfortran -c $src -o ${src%.f}.o --fixed-form --implicit-typing --implicit-interface --generate-object-code --use-loop-variable-after-loop --all-mangling --mangle-underscore
```suggestion
                ../src/bin/lfortran -c $src -o ${src%.f}.o --fixed-form --implicit-typing --implicit-interface --generate-object-code --use-loop-variable-after-loop --all-mangling --bindc-mangling --mangle-underscore
```

2023-09-01 16:09 UTC, Pranavchiku commented on .github/workflows/CI.yml
> +            ../src/bin/lfortran -c ./scipy/optimize/minpack/chkder.f -o chkder.o --fixed-form --implicit-typing --implicit-interface --generate-object-code --use-loop-variable-after-loop --rtlib --al
```suggestion
            ../src/bin/lfortran -c ./scipy/optimize/minpack/chkder.f -o chkder.o --fixed-form --implicit-typing --implicit-interface --generate-object-code --use-loop-variable-after-loop --rtlib --all-mangling --bindc-mangling --mangle-underscore
```

2023-09-01 16:11 UTC, Pranavchiku requested changes
I will first have Minpack tested then specfun, else it will take a lot of time to get this PR in.

2023-09-01 18:24 UTC, certik commented
Beautiful!!

Thanks @Pranavchiku and @HarshitaKalani.

I think all we need to do now is to "merge" the scipy changes for both specfun and minpack into just one branch, and then build minpack and specfun at once, and just build scipy once, and run tests once. So that the CI doesn't take a long time.

2023-09-01 18:25 UTC, Pranavchiku commented
Nice, it runs! The only thing that troubles me is the time CI takes to test it in serial order. Let us have a new branch with changes of both minpack and specfun, and we can use a single build for both and test those independently. 

@HarshitaKalani I feel `ondrej/minpack1` branch works without any trouble, all tests pass, can you please verify that as you were stating about a test that fails. 

cc: @certik

2023-09-01 20:28 UTC, HarshitaKalani commented
>I feel ondrej/minpack1 branch works without any trouble, all tests pass, can you please verify that, as you were stating about a test that fails.

Yes, everything is working perfect in my case too. All test cases are passing!

2023-09-01 22:22 UTC, certik commented
What patches do you need to do to Minpack and/or SciPy tests to make them fully work with LFortran? If the answer is "none", then it is fully working.

As Pranav and I wrote above, let's figure out how to merge the minpack/specfun efforts and just maintain one scipy branch to test at the CI.

2023-09-02 15:37 UTC, HarshitaKalani commented
>What patches do you need to do to Minpack and/or SciPy tests to make them fully work with LFortran? If the answer is "none", then it is fully working.

Yes, it it none.

 Also, I bumped Minpack to latest commit, everything works! I pushed it at https://github.com/certik/scipy/commits/minpack2

@Pranavchiku do let me know when can we merge both the packages.

2023-09-09 15:30 UTC, Pranavchiku commented
Closing with reference to #2312.

2023-09-09 15:30 UTC, closed without merging