Support iostat in read()
lfortran/lfortran pull request #2333
Opened 2023-09-03 18:57 UTC by Shaikh-Ubaid

2023-09-03 18:58 UTC, Shaikh-Ubaid commented on src/libasr/codegen/asr_to_llvm.cpp
> +        }
This leads to a segmentation fault on call to `_lfortran_read_char()` from `llvm`. Is this the correct way to pass a pointer from llvm to C?

2023-09-03 19:01 UTC, Shaikh-Ubaid commented on src/libasr/runtime/lfortran_intrinsics.c
> +            *iostat = 0;
At this line `*iostat = 0`, are we allowed to set the value of `iostat` to `0` here. It seems iostat is in integer variable in the user source code which has its memory allocated in llvm stack. Is C allowed to access/update/write to a memory used by llvm?

It seems in the `lfortran_intrinsics.c` at any other place where we have such type of memory update/write from C to LLVM, the memory used is allocated in C heap. In the above case, specifically we have memory allocated in LLVM stack and is being written/updated by C.

2023-09-03 19:02 UTC, certik commented on src/libasr/codegen/asr_to_llvm.cpp
> +        }
I am not sure --- I think we are passing pointers elsewhere, so just see if this is consistent.

2023-09-03 19:03 UTC, certik commented on src/libasr/runtime/lfortran_intrinsics.c
> +            *iostat = 0;
Yes, you can update LLVM allocated memory from C. Obviously the pointer to it must not be dangling, but otherwise it should work.

2023-09-04 04:56 UTC, czgdp1807 requested changes

2023-09-04 04:56 UTC, czgdp1807 commented on src/libasr/codegen/asr_to_llvm.cpp
> +            iostat = builder->CreateIntToPtr(tmp, llvm_utils->getIntType(4, true));
```suggestion
        if (x.m_iostat) {
            uint64_t ptr_loads_copy = ptr_loads;
            ptr_loads = 0;
            this->visit_expr_wrapper(x.m_iostat, false);
            ptr_loads = ptr_loads_copy;
            iostat = tmp;
```

2023-09-04 04:58 UTC, czgdp1807 commented
What you are doing is giving `iostat` value a pointer representation. What's needed is to write the new value to `iostat` (i.e., pass the address of `iostat` to C and not the value of `iostat` as an address).

2023-09-05 11:40 UTC, certik commented
This PR is fine, but I have two questions:

* What bug does it fix? Let's add a test for it? Maybe reading some stuff from an empty file?
* The change in fastGPT deviates from master. Does this workaround make chat work?

2023-09-05 11:43 UTC, merged

2023-09-05 11:43 UTC, certik commented
@Shaikh-Ubaid do you know what changes to make so that test_chat works as well? Probably a similar allocatable change?

2023-09-05 11:52 UTC, Thirumalai-Shaktivel commented
test_chat seems to work for me:
```console
$ ./test_chat
Your name is fastGPT and you are an AI bot. The user will ask you questions and you answer in a nice, truthful, short way.
User: What is the capital of Czechia?
fastGPT: Prague.
User: How many legs does a dog have?
fastGPT: Four.
User: What color does the sky have?
fastGPT: Blue.
User: What can you type a document on?
fastGPT: A document.
User: What can you drive in?
fastGPT: A car.
User:
```

2023-09-05 11:53 UTC, Thirumalai-Shaktivel commented
Chat works as well!
I think we have it, everything works!

2023-09-05 11:57 UTC, certik commented
The test_chat must be tested at the CI, and then just "ctest" should run. For me it doesn't run.

2023-09-05 11:58 UTC, certik commented
@Thirumalai-Shaktivel can you submit a PR to test this at the CI?

2023-09-05 13:13 UTC, certik commented
Ok, perfect! Now it makes sense.

2023-09-05 16:09 UTC, Shaikh-Ubaid commented
>What bug does it fix? Let's add a test for it? Maybe reading some stuff from an empty file?

Sure, I will add test for it.

>The change in fastGPT deviates from master. Does this workaround make chat work?

Yes, it does partially make the chat work.

>do you know what changes to make so that test_chat works as well? Probably a similar allocatable change?

I think it fails due to https://github.com/lfortran/lfortran/issues/2360. I will fix it.