Fix function reference and create real-time test for `datan2`
lfortran/lfortran pull request #2395
Opened 2023-09-10 08:40 UTC by gptsarthak

Function reference for ```datan2``` is not working in main because it is not registered in the ```comptime_eval_map```.
That is now fixed with this PR. A real-time test for ```datan2``` has been registered as well.
```fortran
program main
    real(8) :: x, y, datan2
    x = 2.0D0
    y = 3.0D0

    print *, datan2(x,y)

end program
```
```console
(lf) ~$ lfortran --implicit-interface integration_tests/intrinsics_72.f90 
5.88002603547567504e-01
```

2023-09-10 09:48 UTC, Pranavchiku commented on integration_tests/intrinsics_72.f90
> +program main
```suggestion
program intrinsics_72
```

2023-09-10 09:48 UTC, Pranavchiku commented on integration_tests/intrinsics_72.f90
> +
Test exact value here, like `if(abs(datan2(x,y) - <expected_value>) > 1d-10) error stop`

2023-09-10 09:48 UTC, Pranavchiku commented on integration_tests/intrinsics_72.f90
> +    y = 3.0D0
```suggestion
    x = 2.33D0
    y = 3.41D0
```

2023-09-10 09:49 UTC, gptsarthak commented on integration_tests/intrinsics_72.f90
> +
Then should i implement it as a normal test, instead of an integration test?

2023-09-10 09:51 UTC, Pranavchiku commented on integration_tests/intrinsics_72.f90
> +
Right now you have it as a normal test, you need to assure expected value in integration tests. That is what we are following.

2023-09-10 09:52 UTC, Pranavchiku commented
I tried to check it manually, it gives

```
% cat a.f90 
program main
real(8) :: x,y,datan2
x = 3.1D0
y = 2.9D0
print *, datan2(x,y)
end program
(lf) pranavchiku@pranavchikus-MacBook-Air:~/repos/lfortran(datan2) % lfortran a.f90 --show-asr
ASR verify pass error: ASR verify: The variable in ArrayItem must be an array, not a scalar
 --> a.f90:5:10
  |
5 | print *, datan2(x,y)
  |          ^^^^^^^^^^^ failed here


Note: Please report unclear or confusing messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

2023-09-10 09:54 UTC, gptsarthak commented
> (lf) ~/repos/lfortran(datan2) % lfortran a.f90 --show-asr

@Pranavchiku  You have to use ```--implicit-interface```

2023-09-10 09:56 UTC, Pranavchiku commented
It should work without `--implicit-interface` as well. I guess, what you actually need to do is, on encountering declaration `real(8) :: datan2` check if `datan2` exists as an intrinsic or not, if yes, just exit, do not create a symbol, else let the flow continue.

2023-09-10 09:59 UTC, Pranavchiku commented on src/lfortran/semantics/comptime_eval.h
> +            {"datan2", {m_math, &not_implemented, true}}, // Implemented using
we try to reduce as many functions as possible from here.

2023-09-10 10:02 UTC, Pranavchiku commented
This diff make things work, you may try to simplify this as well.
```diff
% git diff
diff --git a/src/lfortran/semantics/ast_common_visitor.h b/src/lfortran/semantics/ast_common_visitor.h
index d778b98fd..85c78c03f 100644
--- a/src/lfortran/semantics/ast_common_visitor.h
+++ b/src/lfortran/semantics/ast_common_visitor.h
@@ -2446,9 +2446,18 @@ public:
                                 variable_dependencies_vec.size(), s_intent, init_expr, value,
                                 storage_type, type, type_declaration, current_procedure_abi_type, s_access, s_presence,
                                 value_attr);
-                        current_scope->add_symbol(sym, ASR::down_cast<ASR::symbol_t>(v));
-                        if( is_derived_type ) {
-                            data_member_names.push_back(al, s2c(al, to_lower(s.m_name)));
+                        std::cout<<"variable_name: "<<sym<<std::endl;
+                        std::map<std::string, std::string> double_precision_intrinsics;
+                        populate_double_precision_intrinsics(double_precision_intrinsics);
+                        bool is_double_precision_intrinsic = double_precision_intrinsics.find(sym) != double_precision_intrinsics.end();
+                        if ( !(ASRUtils::IntrinsicScalarFunctionRegistry::is_intrinsic_function(sym) ||
+                            ASRUtils::IntrinsicArrayFunctionRegistry::is_intrinsic_function(sym) ||
+                            ASRUtils::IntrinsicImpureFunctionRegistry::is_intrinsic_function(sym) ||
+                            is_double_precision_intrinsic) ) {
+                            current_scope->add_symbol(sym, ASR::down_cast<ASR::symbol_t>(v));
+                            if( is_derived_type ) {
+                                data_member_names.push_back(al, s2c(al, to_lower(s.m_name)));
+                            }
                         }
                     }
                 }
```

2023-09-10 10:02 UTC, Pranavchiku requested changes
I left few comments.

2023-09-11 18:48 UTC, gptsarthak commented
Changes in the latest commit:
- Created an  ```is_intrinsic_registry_function()``` to check for functions in the registry (otherwise we would have to create a map and call ``` populate_double_precision_intrinsics()``` everytime to check for them).
- Give a nice error message when declaring intrinsic functions as variables without using the ```--implicit-interface``` option. (suggested here https://github.com/lfortran/lfortran/issues/2398#issuecomment-1713843923)

2023-09-12 04:47 UTC, Pranavchiku approved these changes
Looks good to me! I checked locally, with this PR we don't need the patch for Fitpack. It is good to merge, in subsequent PRs let's add test throwing error message.

2023-09-12 06:08 UTC, certik commented on integration_tests/intrinsics_72.f90
> +program main
I think this is not resolved yet?

2023-09-12 06:09 UTC, certik commented on src/lfortran/semantics/ast_common_visitor.h
> +                    throw SemanticAbort();
Let's add an error message for this case into `tests/errors`.

2023-09-12 06:10 UTC, certik approved these changes
I think this is good, thanks!

The suggestions can be fixed in subsequent PRs.

2023-09-12 08:10 UTC, certik approved these changes
Beautiful!

Good to merge. Wait for @czgdp1807 to finish the sync first.

2023-09-13 09:59 UTC, certik commented
Rebased & set to automerge.

2023-09-13 10:24 UTC, merged