Error message on using args of different kind in `max` and `min`
lfortran/lfortran pull request #2499
Opened 2023-09-24 07:20 UTC by HarshitaKalani

Fixes: #2424

2023-09-24 08:34 UTC, Pranavchiku commented on src/libasr/asr_utils.h
> +                SemanticError("All arguments must have the same type and kind.", arg->base.loc);
Error needs to be given only when `ASRUtils::check_equal_type(arg_type, orig_arg_type)` is false.

2023-09-24 08:35 UTC, Pranavchiku commented on src/libasr/asr_utils.h
> +                SemanticError("All arguments must have the same type and kind.", arg->base.loc);
Let's also use `ASRUtils::type_to_str_python(xx)`  to show expected and given type.

2023-09-24 08:36 UTC, Pranavchiku commented on src/libasr/asr_utils.cpp
> +        err("All arguments to " + std::string(p.m_name) + " must have the same type and kind.", loc);
I do not think this change is correct, there can be reasons other than same type and kind that can raise error.

2023-09-24 08:36 UTC, Pranavchiku requested changes
I left a few minor comments.

2023-10-02 04:59 UTC, Thirumalai-Shaktivel commented on src/libasr/asr_utils.cpp
> +        ASR::ttype_t* arg1_type = ASRUtils::expr_type(args[0].m_value);
I think this isn't the right place to add this check.
select_generic_procedure might be used by many nodes like ClassProcedure, IntrinsicFucntion and so on...
Also, here args can have any number of arguments, this might cause seg-fault for 0 or 1 argument.

2023-10-02 05:19 UTC, Thirumalai-Shaktivel commented
I think the right way of fixing this would to remove the max interface from lfortran_intrinsic_math2 and handle everything related to max using IntrinsicScalarFunction::Max.

Inside the create_Max, you can add a check for the args type mismatch.

2023-10-02 06:07 UTC, certik commented
Yes, let's port min/max to use IntrinsicFunction, then we can easily add all the checks.

2023-10-02 11:54 UTC, HarshitaKalani commented
```fortran
program main
    real :: y
    character :: z
    print *, min(z, y)
end program

```
```console
(lf) harshita@harshita-linux:~/Desktop/lfortran$ lfortran a.f90
ASR verify pass error: ASR verify: ASR Verify: Arguments to min0 must be of real or integer type  ---------------------------> **ASR Verify is written twice.**
 --> a.f90:4:14
  |
4 |     print *, min(z, y)
  |              ^^^^^^^^^ failed here


Note: Please report unclear or confusing messages as bugs at
https://github.com/lfortran/lfortran/issues.
```
This an another bug

2023-10-02 16:34 UTC, HarshitaKalani commented
I saw this: https://github.com/lfortran/lfortran/pull/1915#pullrequestreview-1509634425
>I think that this is fine. Isn't min0 for integers only?
In subsequent PRs we can improve the error checking and ensure min0 is integer only, but min is for both integer and real.

We currently don't have separate implementation for`min` and `min0`( `max` and `max0`), right? Do we need it? Or this should be done with `if-else` conditions?

```lfortran
program main
    real :: y
    real :: z
    y = 5.2
    z = 3.1
    print *, max0(y, z)
end program
```
```console
(lf)$ lfortran a.f90
5.19999981e+00
(lf)$ gfortran a.f90 && ./a.out 
a.f90:6:18:

    6 |     print *, max0(y, z)
      |                  1
Error: ‘a1’ argument of ‘max0’ intrinsic at (1) must be INTEGER(4)
(lf) harshita@harshita-linux:~/Desktop/lfortran$ 
```
And the same happens with `min0`

2023-10-02 18:39 UTC, certik commented
Can you please write (gfortran for now) tests for min, min0, min1, amin0, amin1 ? It looks like `min` is a generic function that can do more things, and min0, min1, amin0, amin1 are more specific functions, but let's write tests for these 5 functions and exercise all the options. Just do the "min" for now, we'll do "max" later. After you submit a PR, I'll try to think if there are more cases that we forgot. Once we have it all, then let's think how to best represent in ASR, whether we need just one "min" IntrinsicScalarFunction or whether we need several.

2023-10-05 14:06 UTC, certik commented
To debug the error message, one must check out https://github.com/urbanjost/M_CLI2 and reproduce the error locally. It's probably somehow related to the changes in this PR, so we need to figure out which change caused it.

2024-01-30 15:20 UTC, closed without merging