Added tests and fix for generic procedure calling in return type
lfortran/lfortran pull request #25
Opened 2022-07-23 17:04 UTC by Pranavchiku

2022-07-23 17:14 UTC, czgdp1807 commented
Thanks for the PR @Pranavchiku. Could you please add in your description that this is coming from https://gitlab.com/lfortran/lfortran/-/merge_requests/1754 (specifically, https://gitlab.com/lfortran/lfortran/-/merge_requests/1754/diffs?commit_id=4b33cd67e2462e532c7608afc00933ba95019807 I believe). Plus could you please retain the commit message, follow the steps below (assuming you are in your `main` branch which is the branch of this PR),

1. `git log`
2. Copy the hash of the commit which is just below your commit in this PR. Let's call this hash as `xyz` for now.
3. `git rebase -i xyz`.
4. Now a command line editor will open up, change `pick` to `r` for your commit and save and close in the command line itself.
5. Now another editor in the command line will open up, here you can copy the commit message from my commit.
6. Now save and close.
7. Once you are done, check the `git log`'s output to see if the commit message was actually changed.
8. Do, `git push -f your_remote main`. That should be it.

Once you are able to build the LFortran repository locally on your system, I will share the commands to run in order to pass the CI tests. Right now they will fail.

2022-07-23 19:43 UTC, Pranavchiku commented
> Thanks for the PR @Pranavchiku. Could you please add in your description that this is coming from https://gitlab.com/lfortran/lfortran/-/merge_requests/1754 (specifically, https://gitlab.com/lfortran/lfortran/-/merge_requests/1754/diffs?commit_id=4b33cd67e2462e532c7608afc00933ba95019807 I believe). Plus could you please retain the commit message, follow the steps below (assuming you are in your `main` branch which is the branch of this PR),
> 
> 1. `git log`
> 2. Copy the hash of the commit which is just below your commit in this PR. Let's call this hash as `xyz` for now.
> 3. `git rebase -i xyz`.
> 4. Now a command line editor will open up, change `pick` to `r` for your commit and save and close in the command line itself.
> 5. Now another editor in the command line will open up, here you can copy the commit message from my commit.
> 6. Now save and close.
> 7. Once you are done, check the `git log`'s output to see if the commit message was actually changed.
> 8. Do, `git push -f your_remote main`. That should be it.
> 
> Once you are able to build the LFortran repository locally on your system, I will share the commands to run in order to pass the CI tests. Right now they will fail.

Done with this!

2022-07-24 08:08 UTC, czgdp1807 requested changes

2022-07-24 08:08 UTC, czgdp1807 commented on integration_tests/operator_overloading_06_module3.f90
> +end submodule
```suggestion
end submodule

program main
end program
```

2022-07-24 09:50 UTC, Pranavchiku commented on integration_tests/operator_overloading_06_module3.f90
> +end submodule
performed suggested changes

2022-07-25 07:46 UTC, Pranavchiku commented
@czgdp1807 any updates to be done?

2022-07-25 21:32 UTC, certik commented
The new files should be registered in `integration_tests/CMakeLists.txt`, you can start with "llvm" tests. Make sure they work.

2022-07-27 07:54 UTC, faze-geek commented
You could check the "gfortran" tests too I believe. As far as the failing tests are concerned once you are able to build and run lfortran, the reference files should be updated with `./run_tests.py -u ` then the current failures would be avoided (might fail further due to other potential errors though).

2022-07-27 09:04 UTC, Pranavchiku commented
> You could check the "gfortran" tests too I believe. As far as the failing tests are concerned once you are able to build and run lfortran, the reference files should be updated with `./run_tests.py -u ` then the current failures would be avoided (might fail further due to other potential errors though).

Can anyone help me out here, I am performing clean build and its showing me this error now, previously it worked fine
```
/usr/bin/ld: /home/pranavchiku/anaconda3/envs/lf/lib/libbfd.a(format.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
```

2022-07-27 11:20 UTC, certik commented
This has something to do with relocations. I think we usually compile with `-fPIC`. Perhaps you are compiling without it?

2022-08-09 14:44 UTC, Pranavchiku commented
Can anyone help me here how to execute the integrations tests in windows?

2022-08-09 14:45 UTC, certik commented
I have not figured out how to do it unfortunately.

2022-08-09 14:46 UTC, certik commented
See: https://gitlab.com/lfortran/lfortran/-/issues/536

2022-08-09 14:46 UTC, Pranavchiku commented
```FC=lfortran cmake -DLFORTRAN_BACKEND=llvm ../lfortran/integration_tests```
I used to perform this on wsl, but when working with windows how to do this particular job?

2022-08-09 16:42 UTC, Pranavchiku commented
> See: https://gitlab.com/lfortran/lfortran/-/issues/536

I am getting this error
```
PS C:\Users\lenovo\lfortran\integration_tests> export FC="C:\Users\lenovo\lfortran\src\bin\lfortran.exe"
export : The term 'export' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, 
verify that the path is correct and try again.
At line:1 char:1
+ export FC="C:\Users\lenovo\lfortran\src\bin\lfortran.exe"
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (export:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
    ```
    
  on performing ```export FC="C:\Users\lenovo\lfortran\src\bin\lfortran.exe"```

2022-08-09 16:47 UTC, Pranavchiku commented
I performed the tests as given in the pull request
I did it in bash terminal
```
cd integration_tests
export FC="C:\Users\lenovo\lfortran\src\bin\lfortran.exe"
cmake -DLFORTRAN_BACKEND=llvm
```

This is showing me
```
CMake Error at CMakeLists.txt:3 (project):
  No CMAKE_Fortran_COMPILER could be found.



-- Configuring incomplete, errors occurred!
See also "C:/Users/lenovo/lfortran/integration_tests/CMakeFiles/CMakeOutput.log".
See also "C:/Users/lenovo/lfortran/integration_tests/CMakeFiles/CMakeError.log".
```

 Error, could you please help me out here

2022-08-09 17:02 UTC, certik commented
See https://github.com/lfortran/lfortran/pull/25#issuecomment-1209477570.

2022-08-09 17:09 UTC, Pranavchiku commented
> See [#25 (comment)](https://github.com/lfortran/lfortran/pull/25#issuecomment-1209477570).
Performed that and received
```
CMake error: Could not create named generator ninja
```

2022-08-09 17:24 UTC, certik commented
Ok, so for ninja just do `conda install ninja`. We can add it to our environment_win.yml eventually.

2022-08-09 17:37 UTC, Pranavchiku commented
still getting the following error
```
lenovo@PranavHere MINGW64 ~/lfortran/integration_tests ((dfa46acf8...))
$ cmake -G ninja -DCMAKE_Fortran_PREPROCESS=OFF -DCMAKE_VERBOSE_MAKEFILE=ON -DLFORTRAN_BACKEND=llvm
CMake Error: Could not create named generator ninja

Generators
* Visual Studio 17 2022        = Generates Visual Studio 2022 project files.
                                 Use -A option to specify architecture.
  Visual Studio 16 2019        = Generates Visual Studio 2019 project files.
                                 Use -A option to specify architecture.
  Visual Studio 15 2017 [arch] = Generates Visual Studio 2017 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 14 2015 [arch] = Generates Visual Studio 2015 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 12 2013 [arch] = Generates Visual Studio 2013 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 11 2012 [arch] = Generates Visual Studio 2012 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 10 2010 [arch] = Deprecated.  Generates Visual Studio 2010
                                 project files.  Optional [arch] can be
                                 "Win64" or "IA64".      
  Visual Studio 9 2008 [arch]  = Generates Visual Studio 2008 project files.
                                 Optional [arch] can be "Win64" or "IA64".
  Borland Makefiles            = Generates Borland makefiles.
  NMake Makefiles              = Generates NMake makefiles.
  NMake Makefiles JOM          = Generates JOM makefiles.

  MSYS Makefiles               = Generates MSYS makefiles.
  MinGW Makefiles              = Generates a make file for use with
                                 mingw32-make.
  Green Hills MULTI            = Generates Green Hills MULTI files
                                 (experimental, work-in-progress).
  Unix Makefiles               = Generates standard UNIX makefiles.
  Ninja                        = Generates build.ninja files.
  Ninja Multi-Config           = Generates build-<Config>.ninja files.
  Watcom WMake                 = Generates Watcom WMake makefiles.
  CodeBlocks - MinGW Makefiles = Generates CodeBlocks project files.
  CodeBlocks - NMake Makefiles = Generates CodeBlocks project files.
  CodeBlocks - NMake Makefiles JOM
                               = Generates CodeBlocks project files.
  CodeBlocks - Ninja           = Generates CodeBlocks project files.
  CodeBlocks - Unix Makefiles  = Generates CodeBlocks project files.
  CodeLite - MinGW Makefiles   = Generates CodeLite project files.
  CodeLite - NMake Makefiles   = Generates CodeLite project files.
  CodeLite - Ninja             = Generates CodeLite project files.
  CodeLite - Unix Makefiles    = Generates CodeLite project files.
  Eclipse CDT4 - NMake Makefiles
                               = Generates Eclipse CDT 4.0 project files.
  Eclipse CDT4 - MinGW Makefiles
                               = Generates Eclipse CDT 4.0 project files.
  Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files.
  Eclipse CDT4 - Unix Makefiles= Generates Eclipse CDT 4.0 project files.
  Kate - MinGW Makefiles       = Generates Kate project files.
  Kate - NMake Makefiles       = Generates Kate project files.
  Kate - Ninja                 = Generates Kate project files.
  Kate - Unix Makefiles        = Generates Kate project files.
  Sublime Text 2 - MinGW Makefiles
                               = Generates Sublime Text 2 project files.
  Sublime Text 2 - NMake Makefiles
                               = Generates Sublime Text 2 project files.

CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.
  ```

2022-08-09 18:01 UTC, Pranavchiku commented
> 

okay, I successfully installed ninja in conda environment
then cd integration_tests

do I then need to perform 
```
export FC="C:\Users\lenovo\lfortran\src\bin\lfortran.exe"
```

if yes it results in following error
```
export : The term 'export' is not recognized as the name of a cmdlet, 
function, script file, or operable program. Check the spelling of the     
name, or if a path was included, verify that the path is correct and try  
again.
At line:1 char:1
+ export FC="C:\Users\lenovo\lfortran\src\bin\lfortran.exe"
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (export:String) [], Comman  
   dNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

2022-08-09 18:10 UTC, certik commented
Based on the error message it seems that you are in PowerShell? Were you always in PowerShell or did you switch to it form `cmd.exe`?

In `cmd.exe`, I believe to set an environment variable, you can do `set FC=...` I think.

2022-08-09 18:11 UTC, Pranavchiku commented
> Based on the error message it seems that you are in PowerShell? Were you always in PowerShell or did you switch to it form `cmd.exe`?
> 
> In `cmd.exe`, I believe to set an environment variable, you can do `set FC=...` I think.

I am currently in terminal provided by visual studio code.

2022-08-09 18:12 UTC, certik commented
The rule number one is to only do one (preferably small) thing at a time. Same caveat applies what I wrote about Bash. If you do that, then I would ask you all the questions we went over when trying to build LFortran.

Just stick to cmd.exe, we know MSVC works, we know conda works, you just installed ninja in that environment, everything works. Just do it there and see what happens.

2022-08-09 18:17 UTC, Pranavchiku commented
Okay just clarifying stuff out, 
I built up my lfortran in miniforge prompt, so now
I am going to activate my conda env there, then install ninja, and try to run integration_test right?

using the below-mentioned code
```
conda activate lf
conda install ninja
cd integration_tests
set FC="C:\Users\lenovo\lfortran\src\bin\lfortran.exe"
cmake -G ninja -DCMAKE_Fortran_PREPROCESS=OFF -DCMAKE_VERBOSE_MAKEFILE=ON -DLFORTRAN_BACKEND=llvm
```

2022-08-09 18:30 UTC, Pranavchiku commented
I got the following log
```
(lf) C:\Users\lenovo\lfortran\integration_tests>cmake -G ninja -DCMAKE_Fortran_PREPROCESS=OFF -DCMAKE_VERBOSE_MAKEFILE=ON -DLFORTRAN_BACKEND=llvm
CMake Error: Could not create named generator ninja

Generators
* Visual Studio 17 2022        = Generates Visual Studio 2022 project files.
                                 Use -A option to specify architecture.
  Visual Studio 16 2019        = Generates Visual Studio 2019 project files.
                                 Use -A option to specify architecture.
  Visual Studio 15 2017 [arch] = Generates Visual Studio 2017 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 14 2015 [arch] = Generates Visual Studio 2015 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 12 2013 [arch] = Generates Visual Studio 2013 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 11 2012 [arch] = Generates Visual Studio 2012 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 10 2010 [arch] = Deprecated.  Generates Visual Studio 2010
                                 project files.  Optional [arch] can be
                                 "Win64" or "IA64".
  Visual Studio 9 2008 [arch]  = Generates Visual Studio 2008 project files.
                                 Optional [arch] can be "Win64" or "IA64".
  Borland Makefiles            = Generates Borland makefiles.
  NMake Makefiles              = Generates NMake makefiles.
  NMake Makefiles JOM          = Generates JOM makefiles.
  MSYS Makefiles               = Generates MSYS makefiles.
  MinGW Makefiles              = Generates a make file for use with
                                 mingw32-make.
  Green Hills MULTI            = Generates Green Hills MULTI files
                                 (experimental, work-in-progress).
  Unix Makefiles               = Generates standard UNIX makefiles.
  Ninja                        = Generates build.ninja files.
  Ninja Multi-Config           = Generates build-<Config>.ninja files.
  Watcom WMake                 = Generates Watcom WMake makefiles.
  CodeBlocks - MinGW Makefiles = Generates CodeBlocks project files.
  CodeBlocks - NMake Makefiles = Generates CodeBlocks project files.
  CodeBlocks - NMake Makefiles JOM
                               = Generates CodeBlocks project files.
  CodeBlocks - Ninja           = Generates CodeBlocks project files.
  CodeBlocks - Unix Makefiles  = Generates CodeBlocks project files.
  CodeLite - MinGW Makefiles   = Generates CodeLite project files.
  CodeLite - NMake Makefiles   = Generates CodeLite project files.
  CodeLite - Ninja             = Generates CodeLite project files.
  CodeLite - Unix Makefiles    = Generates CodeLite project files.
  Eclipse CDT4 - NMake Makefiles
                               = Generates Eclipse CDT 4.0 project files.
  Eclipse CDT4 - MinGW Makefiles
                               = Generates Eclipse CDT 4.0 project files.
  Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files.
  Eclipse CDT4 - Unix Makefiles= Generates Eclipse CDT 4.0 project files.
  Kate - MinGW Makefiles       = Generates Kate project files.
  Kate - NMake Makefiles       = Generates Kate project files.
  Kate - Ninja                 = Generates Kate project files.
  Kate - Unix Makefiles        = Generates Kate project files.
  Sublime Text 2 - MinGW Makefiles
                               = Generates Sublime Text 2 project files.
  Sublime Text 2 - NMake Makefiles
                               = Generates Sublime Text 2 project files.
  Sublime Text 2 - Ninja       = Generates Sublime Text 2 project files.
  Sublime Text 2 - Unix Makefiles
                               = Generates Sublime Text 2 project files.

CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.
  ```

2022-08-09 19:20 UTC, certik commented
Yes exactly.

Can you try `ninja --help` to ensure `ninja` is installed and in your PATH?

If `ninja` is available then the next step is to figure out why cmake does not want to use it. It's probably not it, but can you try changing `-G ninja` to `-G Ninja` ?

2022-08-09 19:21 UTC, certik commented
Oh, did you remove CMakeCache.txt? That file is there from a previous cmake run, sometimes it messes up things.

2022-08-10 02:17 UTC, Pranavchiku commented
> Oh, did you remove CMakeCache.txt? That file is there from a previous cmake run, sometimes it messes up things.

Yeah, I did a clean build

2022-08-10 04:03 UTC, Pranavchiku commented
> Yes exactly.
> 
> Can you try `ninja --help` to ensure `ninja` is installed and in your PATH?
> 
> If `ninja` is available then the next step is to figure out why cmake does not want to use it. It's probably not it, but can you try changing `-G ninja` to `-G Ninja` ?

Yeah, ninja is present and returned me the version on executing ```ninja --version```

then I ran the below piece of code
```
set FC="C:\Users\lenovo\lfortran\src\bin\lfortran.exe"
cmake -G Ninja -DCMAKE_Fortran_PREPROCESS=OFF -DCMAKE_VERBOSE_MAKEFILE=ON -DLFORTRAN_BACKEND=llvm
```

it gave the following log
```
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.


-- The C compiler identification is GNU 8.1.0
CMake Error at C:/Users/lenovo/.conda/envs/lf/Library/share/cmake-3.24/Modules/CMakeDetermineFortranCompiler.cmake:33 (message):
  Could not find compiler set in environment variable FC:

  "C:\Users\lenovo\lfortran\src\bin\lfortran.exe".
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)


CMake Error: CMAKE_Fortran_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "C:/Users/lenovo/lfortran/integration_tests/CMakeFiles/CMakeOutput.log".
```

2022-08-10 07:05 UTC, certik commented
Awesome. The path to `lfortran.exe` that you provided in the `FC` variable is not correct. You have to fix it.

2022-08-17 15:15 UTC, Pranavchiku commented
> The new files should be registered in `integration_tests/CMakeLists.txt`, you can start with "llvm" tests. Make sure they work.

I did this, and all the tests passed!

2022-08-17 16:05 UTC, certik commented
The `string_19` failure at the CI is due to #601. Somehow you are getting different results locally and we need to investigate why, but that's an unrelated failure.

2022-08-17 17:23 UTC, merged

2022-08-17 19:16 UTC, certik commented
You should never force push into a branch, unless everything is reviewed and ready to merge. As you can see, it's easy to make a mistake like this. See if you can find your old code in this PR and push it here again.

I see what happened: you were merging from your `main`. You need to create a branch first in your git and send a PR from a branch, not `main`, otherwise you can never send more than 1 PR.

2022-08-17 19:17 UTC, certik commented
So yes, add your old code into a branch and send a new PR from that branch.

2022-08-17 20:18 UTC, Pranavchiku commented
Yeah doing it!