Add string support for intrinsic `max`
lfortran/lfortran pull request #2870
Opened 2023-11-18 06:25 UTC by HarshitaKalani

Fixes: https://github.com/lfortran/lfortran/issues/2841

2023-11-21 06:34 UTC, czgdp1807 requested changes

2023-11-21 06:34 UTC, czgdp1807 commented on src/libasr/pass/intrinsic_function_registry.h
> +        if (return_type->type == ASR::ttypeType::Integer) {
```suggestion
        if (ASR::is_a<ASR::Integer_t>(*return_type)) {
```

2023-11-21 06:34 UTC, czgdp1807 commented on src/libasr/pass/intrinsic_function_registry.h
> +        } else if (return_type->type == ASR::ttypeType::Real) {
```suggestion
        } else if (ASR::is_a<ASR::Real_t>(*return_type)) {
```

2023-11-21 06:34 UTC, czgdp1807 commented on src/libasr/pass/intrinsic_function_registry.h
> +        } else if (return_type->type == ASR::ttypeType::Character) {
```suggestion
        } else if (ASR::is_a<ASR::Character_t>(*return_type)) {
```

2023-11-21 06:35 UTC, czgdp1807 submitted a review, later dismissed

2023-11-21 06:35 UTC, czgdp1807 commented on tests/reference/asr-fn5-3d75eb7.stderr
This error file got created. Shouldn't have happened. Needs to be debugged.

2023-11-21 06:35 UTC, czgdp1807 commented on tests/reference/asr-string_19-d880475.stderr
File with same error.

2023-11-21 06:36 UTC, czgdp1807 commented on tests/reference/asr-fn5-3d75eb7.stderr
CI for FPM also fails with this error.

2024-02-01 18:44 UTC, certik approved these changes
I think this looks good.

2024-02-01 18:44 UTC, merged