[LLVM] Initial implementation for BitCast
lfortran/lfortran pull request #2876
Opened 2023-11-19 11:11 UTC by Pranavchiku

I am not sure if this is correct approach. For 
```fortran
program main
    implicit none
    integer :: i = 123456
    real :: r
    real :: result

    result = transfer(i, r)
    print *, result
end program main
```

> LFortran

```console
% lfortran a.f90 
1.23456000e+05
```

> GFortran

```console
% gfortran a.f90 && ./a.out
   1.72998703E-40
```

I feel output of GFortran is incorrect.

2023-11-19 15:42 UTC, certik commented
The code looks good, but I need to think about the correctness. Most likely GFortran is correct.

2023-11-20 00:59 UTC, certik commented
Note: I can reproduce the above results on my Apple M1 Max for both LFortran and GFortran.

2023-11-20 05:30 UTC, czgdp1807 commented on src/libasr/codegen/asr_to_llvm.cpp
> +                tmp = builder->CreateSIToFP(source, target_type);
You should be doing `CreateBitCast`? That re-interprets the type. `CreateSIToFP` does the actual cast and the underlying value remains the same which is what happening in your case.

2023-11-20 05:33 UTC, Pranavchiku commented on src/libasr/codegen/asr_to_llvm.cpp
> +                tmp = builder->CreateSIToFP(source, target_type);
Yes, correct. I am just pushing it with `CreateBitCast`

2023-11-20 05:35 UTC, Pranavchiku commented
For 
```fortran
program main
    implicit none
    integer :: i = 123456
    real :: r
    real :: result

    result = transfer(i, r)
    print *, result
end program main
```

Generated LLVM

```llvm
; ModuleID = 'LFortran'
source_filename = "LFortran"

@main.i = internal global i32 0
@0 = private unnamed_addr constant [2 x i8] c" \00", align 1
@1 = private unnamed_addr constant [2 x i8] c"\0A\00", align 1
@2 = private unnamed_addr constant [9 x i8] c"%13.8e%s\00", align 1

define i32 @main(i32 %0, i8** %1) {
.entry:
  call void @_lpython_set_argv(i32 %0, i8** %1)
  store i32 123456, i32* @main.i, align 4
  %r = alloca float, align 4
  %result = alloca float, align 4
  %2 = load i32, i32* @main.i, align 4
  %3 = load float, float* %r, align 4
  %4 = bitcast i32 %2 to float
  store float %4, float* %result, align 4
  %5 = load float, float* %result, align 4
  %6 = fpext float %5 to double
  call void (i8*, ...) @_lfortran_printf(i8* getelementptr inbounds ([9 x i8], [9 x i8]* @2, i32 0, i32 0), double %6, i8* getelementptr inbounds ([2 x i8], [2 x i8]* @1, i32 0, i32 0))
  ret i32 0
}

declare void @_lpython_set_argv(i32, i8**)

declare void @_lfortran_printf(i8*, ...)
```

2023-11-20 06:18 UTC, certik approved these changes
I think this looks good, but the test should be improved per my comment below. Either in this PR or in subsequent PRs.

2023-11-20 06:18 UTC, certik commented on integration_tests/transfer_01.f90
> +    print *, result
This can be done in subsequent PRs, but let's add tests for the actual values, since on all modern platforms (and all platforms that we support), the internal representation of f32/i32 is given by IEEE, so you can simply test some floating point and some integer. Say `result=3.1` and the corresponding integer. 

Test 32 and 64 bit.

Test integer to real and real to integer.

2023-11-20 06:46 UTC, czgdp1807 requested changes

2023-11-20 06:46 UTC, czgdp1807 commented on src/libasr/codegen/asr_to_llvm.cpp
> +
This approach is very verbose. I don't think that's needed. You shouldn't be needing to use the `source_type`. Just get the LLVM type for `target_type` and then do `CreateBitCast`. I am -1 on merging this as is. First add tests for a bunch of type combinations and then improvise the approach. Testing it for a single type combination doesn't help in verifying whether the approach is good enough or not.

2023-11-20 11:11 UTC, Pranavchiku commented on src/libasr/codegen/asr_to_llvm.cpp
> +
Yes, I agree. I'll improve it and test. In subsequent PRs, I'll try to get every case working.

2023-11-21 05:16 UTC, Pranavchiku commented on integration_tests/transfer_01.f90
> +    print *, result
I am not sure how can we test with actual values.

2023-11-21 05:21 UTC, certik commented on integration_tests/transfer_01.f90
> +    print *, result
See the equivalence tests that @HarshitaKalani did which does exactly that. Set i = something, and check that result = something_else.

2023-11-21 05:42 UTC, Pranavchiku commented on integration_tests/transfer_02.f90
> +    result = transfer(d, result)
```console
% lfortran ./integration_tests/transfer_02.f90 
; ModuleID = 'LFortran'
source_filename = "LFortran"

@0 = private unnamed_addr constant [2 x i8] c" \00", align 1
@1 = private unnamed_addr constant [2 x i8] c"\0A\00", align 1
@2 = private unnamed_addr constant [5 x i8] c"%d%s\00", align 1
@3 = private unnamed_addr constant [12 x i8] c"ERROR STOP\0A\00", align 1

define i32 @main(i32 %0, i8** %1) {
.entry:
  call void @_lpython_set_argv(i32 %0, i8** %1)
  %d = alloca double, align 8
  %result = alloca i32, align 4
  store double 3.140000e+00, double* %d, align 8
  %2 = load double, double* %d, align 8
  %3 = bitcast double %2 to i32
  store i32 %3, i32* %result, align 4
  %4 = load i32, i32* %result, align 4
  call void (i8*, ...) @_lfortran_printf(i8* getelementptr inbounds ([5 x i8], [5 x i8]* @2, i32 0, i32 0), i32 %4, i8* getelementptr inbounds ([2 x i8], [2 x i8]* @1, i32 0, i32 0))
  %5 = load i32, i32* %result, align 4
  %6 = icmp ne i32 %5, 1374389535
  br i1 %6, label %then, label %else

then:                                             ; preds = %.entry
  call void (i8*, ...) @_lcompilers_print_error(i8* getelementptr inbounds ([12 x i8], [12 x i8]* @3, i32 0, i32 0))
  call void @exit(i32 1)
  br label %ifcont

else:                                             ; preds = %.entry
  br label %ifcont

ifcont:                                           ; preds = %else, %then
  ret i32 0
}

declare void @_lpython_set_argv(i32, i8**)

declare void @_lfortran_printf(i8*, ...)

declare void @_lcompilers_print_error(i8*, ...)

declare void @exit(i32)
code generation error: asr_to_llvm: module failed verification. Error:
Invalid bitcast
  %3 = bitcast double %2 to i32



Note: Please report unclear or confusing messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

2023-11-21 06:05 UTC, certik commented on integration_tests/transfer_02.f90
> +    result = transfer(d, result)
I think that's because double is 64 bit, but integer is 32 bit.

I would worry about this case later, we can merge the other case where both sizes are the same.

2023-11-21 06:06 UTC, certik commented
I think this looks good now.

2023-11-21 06:07 UTC, certik approved these changes
I think that this is good to merge now. Good test.

2023-11-21 06:31 UTC, czgdp1807 requested changes

2023-11-21 06:31 UTC, czgdp1807 commented on src/libasr/codegen/asr_to_llvm.cpp
> +            llvm::Type* target_type = llvm_utils->getIntType(target_kind);
Here is the problem. You don't need to do this. Just pass `llvm::Type* target_llvm_type = llvm_utils->get_type_from_ttype_t_util(x.m_type, module.get())`. Then just call, `tmp = builder->CreateBitCast(source, target_type);`. These two lines should complete the implementation. No need to do `if-else-if` checks. Then you can also add extensive tests in this PR. No need to wait for another PR to complete that.

2023-11-21 06:36 UTC, Pranavchiku commented on src/libasr/codegen/asr_to_llvm.cpp
> +            llvm::Type* target_type = llvm_utils->getIntType(target_kind);
Yes, perfect. This works, thank you! @czgdp1807 can you please give a small example of extensive test that you are willing to add? I'll push the simplified approach and prefer to merge this.

2023-11-21 06:44 UTC, czgdp1807 commented on src/libasr/codegen/asr_to_llvm.cpp
> +            llvm::Type* target_type = llvm_utils->getIntType(target_kind);
Try for real to complex or integer to complex. I feel there will be problems with complex type. Just try it out.

2023-11-21 06:47 UTC, Pranavchiku commented on src/libasr/codegen/asr_to_llvm.cpp
> +            llvm::Type* target_type = llvm_utils->getIntType(target_kind);
```fortran
program main
    real :: r
    complex :: result

    r = 1.0
    result = transfer(r, result)
    print *, result
end program
```

```
code generation error: asr_to_llvm: module failed verification. Error:
Invalid bitcast
  %3 = bitcast float %2 to %complex_4
```

```console
% gfortran a.f90 && ./a.out
        (1.00000000,5.559368163E+27)
```

2023-11-22 15:48 UTC, czgdp1807 approved these changes

2023-11-22 16:08 UTC, merged