Better error message when derived type is used before it is defined
lfortran/lfortran pull request #2961
Opened 2023-12-09 07:29 UTC by HarshitaKalani

Fixes: https://github.com/lfortran/lfortran/issues/2944

2023-12-09 21:38 UTC, certik commented on src/libasr/asr_verify.cpp
> +            "' is being used before it is defined" );
Keep the original message. The message means that somehow `x.m_derived_type` is not in the symbol table, but it is still a symbol, so it must be in some other symbol table. That's not allowed.

Instead, add an error message in AST->ASR, which should be the place to catch this error.

2023-12-14 17:55 UTC, HarshitaKalani commented
My approach: I'm checking if the program visits the function visit_DerivedType, I store the derived_type_name and check in `ast_common_visitor.h` file if the name is present in vector `derived_type_names`. If it does, it is perfect, else throw the error `Derived type is used before it is defined`.

Now what happens in file `x.f90` 
```fortran
module fpm_targets
implicit none

type build_target_ptr
    type(build_target_t), pointer :: ptr => null()
end type build_target_ptr

type build_target_t
    character(:), allocatable :: output_file
    character(:), allocatable :: version
end type build_target_t

contains

function func() result(target_ptr)
    type(build_target_t), pointer :: target_ptr
    target_ptr => null()
end function func

end module fpm_targets


program modules_32
implicit none

print *, "running modules_32 program"

end program
```
The vector stores `build_target_ptr` and then checks if `build_target_t` is present there, since it's not, it throws error. However I wish to first store all the derived type names here, ie,  `build_target_ptr` and `build_target_t` and then check if `build_target_t` used in the main program is present in the vector. Since it is present, there shouldn't be any error.
I'm not getting how to make sure that first all the derived types declared are stored in the vector and then it checks the condition. Can someone please guide?

2023-12-31 05:27 UTC, Pranavchiku approved these changes
LGTM. Thanks!

2023-12-31 05:28 UTC, Pranavchiku commented
Wait for one more review before merging it.

2023-12-31 06:29 UTC, certik requested changes
I think this approach is still too complicated. I left a comment that suggests an easier path, if it works.

2023-12-31 06:29 UTC, certik commented on tests/reference/asr-derived_type_06-f08a2b6.stderr
> +semantic error: Derived type `foo` is used before it is defined!
This is minor, but I think it is better not to use `!` in error messages:
```suggestion
semantic error: Derived type `foo` is used before it is defined
```

2023-12-31 06:29 UTC, certik commented on src/lfortran/semantics/ast_symboltable_visitor.cpp
> +        [&derived_type_name](const auto& pair) { return pair.first == derived_type_name; }), undefined_derived_type_names.end());
Why do we need to keep track of this using the `undefined_derived_type_names` mapping?

There are several issues with this approach:

* There can be multiple `foo` derived types in different modules, and since we are tracking by their name as string only, this will not work
* it adds more global variables into the visitor
* we are adding some special handling of derived types in the main program; what if we are only compiling a module (perhaps as a `bind(c)` library, to be used from other languages)?

Instead, why cannot we simply give an error message when we can't find the definition of `foo`?

Is the issue that `foo` can be defined later in the same scope? If so, the standard way we handle this is to create a place holder, that must be filled in the same symbol table processing scope. No need for global variables across scopes.

2026-07-13 13:57 UTC, closed without merging