Implemented Left shift for lfortran
lfortran/lfortran pull request #3164
Opened 2024-01-22 17:06 UTC by parth121101

Fix #3137

2024-01-22 17:18 UTC, Pranavchiku requested changes
Thanks for the PR @parth121101, you may remove `shiftl` implementation from `src/runtime/impure/lfortran_intrinsic_bit.f90`, build it and push changes after performing.

```
rm -rf ./tests/reference/*
./run_tests.py -u
```

Also, follow `integration_tests/intrinsics_108.f90` and add a new test for `shiftl`.

2024-01-23 04:41 UTC, Pranavchiku commented
Looks good! Can you apply the following diff and add new integration test calling `lshift` as well? ( Just replace `shiftl` with `lshift`, in a new test file and register )

```diff
diff --git a/src/lfortran/semantics/ast_common_visitor.h b/src/lfortran/semantics/ast_common_visitor.h
index 978b9c0d0..0026e4361 100644
--- a/src/lfortran/semantics/ast_common_visitor.h
+++ b/src/lfortran/semantics/ast_common_visitor.h
@@ -714,6 +714,7 @@ public:
         {"hypot", {IntrinsicSignature({"x", "y"}, 2, 2)}},
         {"shiftr", {IntrinsicSignature({"i", "shift"}, 2, 2)}},
         {"shiftl", {IntrinsicSignature({"i", "shift"}, 2, 2)}},
+        {"lshift", {IntrinsicSignature({"i", "shift"}, 2, 2)}},
     };
 
     std::map<std::string, std::string> double_precision_intrinsics = {
diff --git a/src/libasr/pass/intrinsic_function_registry.h b/src/libasr/pass/intrinsic_function_registry.h
index 803b4c50f..bcb3f01ab 100644
--- a/src/libasr/pass/intrinsic_function_registry.h
+++ b/src/libasr/pass/intrinsic_function_registry.h
@@ -4668,6 +4668,7 @@ namespace IntrinsicScalarFunctionRegistry {
                 {"trailz", {&Trailz::create_Trailz, &Trailz::eval_Trailz}},
                 {"shiftr", {&Shiftr::create_Shiftr, &Shiftr::eval_Shiftr}},
                 {"shiftl", {&Shiftl::create_Shiftl, &Shiftl::eval_Shiftl}},
+                {"lshift", {&Shiftl::create_Shiftl, &Shiftl::eval_Shiftl}},
                 {"leadz", {&Leadz::create_Leadz, &Leadz::eval_Leadz}},
                 {"hypot", {&Hypot::create_Hypot, &Hypot::eval_Hypot}},
                 {"kind", {&Kind::create_Kind, &Kind::eval_Kind}},
```

2024-01-23 04:46 UTC, HarshitaKalani commented
I guess `lshift` and `shiftl` are same. But there's a problem with the suggestion I believe.
In case of any error, it'll print "this is the error in case of `shiftl`" even when the user has used `lshift`.

2024-01-23 04:53 UTC, Pranavchiku commented on src/libasr/pass/intrinsic_function_registry.h
> +        * r = shiftr(x, y)
```suggestion
        * r = shiftl(x, y)
```

2024-01-23 04:53 UTC, Pranavchiku approved these changes
left a minor comment, rest all looks good to me. Thanks!

2024-01-23 04:54 UTC, HarshitaKalani commented on src/libasr/pass/intrinsic_function_registry.h
> +        declare_basic_variables("_lcompilers_sign_" + type_to_str_python(arg_types[0]));
```suggestion
        declare_basic_variables("_lcompilers_shiftl_" + type_to_str_python(arg_types[0]));
```

2024-01-23 05:40 UTC, Pranavchiku approved these changes
Looks good to me. Thanks!

2024-01-23 05:41 UTC, merged