Fixed string slicing
lfortran/lfortran pull request #3233
Opened 2024-01-27 10:55 UTC by Kishan-Ved

Fixes: https://github.com/lfortran/lfortran/issues/3196

2024-01-28 03:50 UTC, certik commented
Can you please add a test for this too?

2024-01-28 05:50 UTC, Kishan-Ved commented
> Can you please add a test for this too?

Done!

2024-01-28 17:37 UTC, Kishan-Ved commented
@certik Sir is this PR good to be merged?

2024-01-28 17:41 UTC, Shaikh-Ubaid commented on src/lfortran/semantics/ast_common_visitor.h
> +                        }
```suggestion
                        str_length += 1;
                    }
```

2024-01-28 17:42 UTC, Shaikh-Ubaid commented on src/lfortran/semantics/ast_common_visitor.h
> +                        throw SemanticError("Error: Substring end index at (1) exceeds the string length",
```suggestion
                        throw SemanticError("Error: Substring end index exceeds the string length",
```

2024-01-28 17:43 UTC, Kishan-Ved commented on src/lfortran/semantics/ast_common_visitor.h
> +                        throw SemanticError("Error: Substring end index at (1) exceeds the string length",
That is the error message given by gfortran. Should we change it?

2024-01-28 17:43 UTC, Kishan-Ved commented on src/lfortran/semantics/ast_common_visitor.h
> +                        throw SemanticError("Error: Substring end index at (1) exceeds the string length",
The error message was mentioned here: https://github.com/lfortran/lfortran/issues/3196

2024-01-28 17:46 UTC, Kishan-Ved commented on src/lfortran/semantics/ast_common_visitor.h
> +                        }
Done.

2024-01-28 17:48 UTC, Shaikh-Ubaid commented on src/lfortran/semantics/ast_common_visitor.h
> +                        throw SemanticError("Error: Substring end index at (1) exceeds the string length",
>That is the error message given by gfortran. Should we change it?

`gfortran` gives numbering for its error messages. I think `lfortran` does not number the error messages at the moment. So if you see the generated error message:

```console
semantic error: Error: Substring end index at (1) exceeds the string length
 --> tests/errors/string_slice2.f90:6:12
  |
6 |    print*, s(1: 9)
  |            ^^^^^^^ 
```
The `(1)` seems confusing as it is not labelled anywhere.

2024-01-28 17:54 UTC, Kishan-Ved commented on src/lfortran/semantics/ast_common_visitor.h
> +                        throw SemanticError("Error: Substring end index at (1) exceeds the string length",
Done.

2024-01-28 18:05 UTC, Kishan-Ved commented
The check that fails gives a weird error:
```
Transaction starting
critical libmamba Download error (28) Timeout was reached [https://conda.anaconda.org/conda-forge/linux-64/nspr-4.35-h27087fc_0.conda]
    Operation too slow. Less than 30 bytes/sec transferred the last 60 seconds
Error: Process completed with exit code 1.
```

2024-01-28 19:25 UTC, Shaikh-Ubaid commented on src/lfortran/semantics/ast_common_visitor.h
> +                    }
Can we simply use `strlen()` here?
```suggestion
                    int str_length = strlen(m_str->m_s);
```

2024-01-28 19:37 UTC, Kishan-Ved commented on src/lfortran/semantics/ast_common_visitor.h
> +                    }
Done 👍🏻

2024-01-28 19:44 UTC, Kishan-Ved commented
There's a weird CI error again:
```
+ make -j8
Command failed.
Error: Process completed with exit code 1.
```

2024-01-28 21:01 UTC, Shaikh-Ubaid approved these changes
It looks good. Thanks!

2024-01-28 21:03 UTC, Shaikh-Ubaid commented on src/lfortran/semantics/ast_common_visitor.h
> +                        throw SemanticError("Error: Substring end index exceeds the string length",
Error can be removed from here
```suggestion
                        throw SemanticError("Substring end index exceeds the string length",
```

2024-01-28 21:05 UTC, Shaikh-Ubaid requested changes
I just shared a minor concern. I think this would be good to merge once that is addressed.

2024-01-29 11:00 UTC, Kishan-Ved commented
> I just shared a minor concern. I think this would be good to merge once that is addressed.

Done.

2024-01-29 11:00 UTC, Kishan-Ved commented on src/lfortran/semantics/ast_common_visitor.h
> +                        throw SemanticError("Error: Substring end index exceeds the string length",
Updated.

2024-01-29 11:31 UTC, Shaikh-Ubaid approved these changes
Looks good. Thanks!

2024-01-29 11:53 UTC, merged