Registers sin function
lfortran/lfortran pull request #3466
Opened 2024-02-21 15:45 UTC by shivimathur

Fix : https://github.com/lfortran/lfortran/issues/3416

2024-02-21 16:36 UTC, Pranavchiku commented
@shivimathur let's also add a simple test, as given in #3416.

2024-02-22 14:38 UTC, Pranavchiku approved these changes
Looks good, added a comment. Thank you!

2024-02-22 14:38 UTC, Pranavchiku commented on integration_tests/CMakeLists.txt
> +RUN(NAME register_intrinsic_sin LABELS gfortran llvm)
```suggestion
RUN(NAME register_intrinsic_sin LABELS gfortran llvm fortran)
```

2024-02-22 15:09 UTC, certik requested changes
Thanks for the PR and the fix!

I think this PR needs more work, I think it will add to our technical debt if we merge it as is. See my comment above.

2024-02-22 15:09 UTC, certik commented on integration_tests/register_intrinsic_sin.f90
> +end program
I think this is not a good test:

* `x` is not initialized
* It needs to test that the result is correct (`if (abs(sin(x) /= ...) ... error stop`)
* The most important: we already have tests for `sin`. So this test is redundant. We should not be adding a new file like this for all intrinsics (there are dozens of them). Rather, let's take an existing test, and add a `fortran` flag to it. Perhaps more intrinsics must be fixed, but then we should do that.

2024-02-23 06:12 UTC, Pranavchiku commented on integration_tests/register_intrinsic_sin.f90
> +end program
Yes, I agree. I missed these, thanks for reviewing this :)

2024-02-24 14:36 UTC, shivimathur commented
Thanks for the review. I have made the changes. This is ready to review again.

2024-02-24 18:45 UTC, certik commented
Tests fail, so they need to be fixed first.

2024-02-25 14:46 UTC, shivimathur commented
This is now ready for review?

2024-02-25 22:12 UTC, certik approved these changes
I think this is fine, thanks!

2024-02-25 22:37 UTC, merged