Implemented Popcnt function
lfortran/lfortran pull request #3654
Opened 2024-03-15 16:25 UTC by parth121101

fixes: #3653

2024-03-15 21:39 UTC, Shaikh-Ubaid commented on src/libasr/pass/intrinsic_functions.h
> +            }
This logic seems duplicated below, so we can make it a function. You can use a templated function to handle integers of different kinds.

2024-03-15 21:39 UTC, Shaikh-Ubaid commented on src/libasr/pass/intrinsic_functions.h
> +        }
Also, why not use `__builtin_popcount` and `__builtin_popcountll`?

2024-03-15 21:41 UTC, Shaikh-Ubaid commented on src/libasr/pass/intrinsic_functions.h
> +        body.push_back(al, b.Assignment(count, b.i(0,arg_types[0])));
Please write in a comment here the definition of the function in `fortran`. That makes it easier to understand the logic implemented in ASR and also verify it.

2024-03-15 21:48 UTC, Shaikh-Ubaid reviewed
I shared few comments. Rest looks good to me. Thanks for the implementation and Great work!

2024-03-15 21:49 UTC, Shaikh-Ubaid commented
Please mark as "Ready for review" when ready.

2024-03-16 06:57 UTC, parth121101 commented
> Please mark as "Ready for review" when ready.

@Shaikh-Ubaid I have applied the code review as suggested by you. One of the tests is failing. Can you please let me know what is the reason behind it?

2024-03-16 08:35 UTC, Pranavchiku commented
Error: `error C3861: '__builtin_popcountll': identifier not found`, you'll have to include corresponding header.

2024-03-16 09:22 UTC, Shaikh-Ubaid commented
>One of the tests is failing. Can you please let me know what is the reason behind it?

You can try the following in that specific order.
1. Try https://stackoverflow.com/a/24550632
2. Try switching to `std::popcnt` as Pranav shared above. Get the linux, mac and windows tests passed. You can see which one fails in the Github CI and debug it.
3. If none of the above works, you can fallback to your custom code (refactored into functions).

Most likely, I believe 1. or 2. would work, but if not 3. can be the possible last option.

2024-03-16 12:34 UTC, parth121101 commented
> > One of the tests is failing. Can you please let me know what is the reason behind it?
> 
> You can try the following in that specific order.
> 
> 1. Try https://stackoverflow.com/a/24550632
> 2. Try switching to `std::popcnt` as Pranav shared above. Get the linux, mac and windows tests passed. You can see which one fails in the Github CI and debug it.
> 3. If none of the above works, you can fallback to your custom code (refactored into functions).
> 
> Most likely, I believe 1. or 2. would work, but if not 3. can be the possible last option.

@Shaikh-Ubaid both of the approaches doesn't work. I need to move ahead with the scratch implementation.

2024-03-16 15:50 UTC, Pranavchiku commented on src/libasr/pass/intrinsic_functions.h
> +        body.push_back(al, b.Assignment(result, cast));
Avoid using this kind of cast expr node, use `b.i2i`

2024-03-16 15:55 UTC, Pranavchiku commented on src/libasr/pass/intrinsic_functions.h
> +        body.push_back(al, b.Assignment(result, cast));
Please apply the following diff:

```diff
--- a/src/libasr/pass/intrinsic_functions.h
+++ b/src/libasr/pass/intrinsic_functions.h
@@ -2576,6 +2576,9 @@ namespace Mod {
         return b.Call(f_sym, new_args, return_type, nullptr);
     }
 
+    static inline ASR::expr_t* MOD(ASRBuilder &b, ASR::expr_t* a, ASR::expr_t* p, SymbolTable* scope) {
+        return b.CallIntrinsic(scope, {expr_type(a), expr_type(p)}, {a, p}, expr_type(a), 0, Mod::instantiate_Mod);
+    }
 } // namespace Mod
 
 namespace Popcnt {
@@ -2647,23 +2650,19 @@ namespace Popcnt {
         body.push_back(al, b.Assignment(val, args[0]));
         body.push_back(al, b.Assignment(mask, b.i(1,arg_types[0])));
 
-        ASR::expr_t* whileloop_test_pos = iNotEq(val, b.i(0, arg_types[0]));
-        std::vector<ASR::stmt_t*> while_loop_body_pos;
-        while_loop_body_pos.push_back(b.Assignment(count, b.i_tAdd(count, b.CallIntrinsic(scope, {arg_types[0], arg_types[0]},
-                                    {val, b.i(2,arg_types[0])}, arg_types[0], 0, Mod::instantiate_Mod), arg_types[0])));
-        while_loop_body_pos.push_back(b.Assignment(val, b.i_BitRshift(val, b.i(1, arg_types[0]), arg_types[0])));
-
-        ASR::expr_t* whileloop_test_neg = iNotEq(mask, b.i(0, arg_types[0]));
-        std::vector<ASR::stmt_t*> while_loop_body_neg;
-        while_loop_body_neg.push_back(b.If(iNotEq(b.i(0,arg_types[0]), (b.i_BitAnd(val,mask, arg_types[0]))), {b.Assignment(count, b.i_tAdd(count, b.i(1, arg_types[0]), arg_types[0]))},
-                                {}));
-        while_loop_body_neg.push_back(b.Assignment(mask, b.i_BitLshift(mask, b.i(1, arg_types[0]), arg_types[0])));
-
-        body.push_back(al, b.If((iGtE(args[0], b.i(0,arg_types[0]))), {b.While(whileloop_test_pos, while_loop_body_pos)},
-                                {b.While(whileloop_test_neg, while_loop_body_neg)}));
-
-        ASR::expr_t *cast = ASRUtils::EXPR(ASR::make_Cast_t(al, loc, count, ASR::cast_kindType::IntegerToInteger, return_type, nullptr));
-        body.push_back(al, b.Assignment(result, cast));
+        body.push_back(al, b.If(iGtE(args[0], b.i(0,arg_types[0])), {
+            b.While(iNotEq(val, b.i(0, arg_types[0])), {
+                b.Assignment(count, b.i_tAdd(count, Mod::MOD(b, val, b.i(2, arg_types[0]), scope), arg_types[0])),
+                b.Assignment(val, b.i_tDiv(val, b.i(2, arg_types[0]), arg_types[0]))
+                })
+        }, {
+            b.While(iNotEq(mask, b.i(0, arg_types[0])), {
+                b.If(iNotEq(b.i(0,arg_types[0]), (b.i_BitAnd(val,mask, arg_types[0]))), {b.Assignment(count, b.i_tAdd(count, b.i(1, arg_types[0]), arg_types[0]))},
+                            {}),
+                b.Assignment(mask, b.i_BitLshift(mask, b.i(1, arg_types[0]), arg_types[0]))
+            })
+        }));
+        body.push_back(al, b.Assignment(result, b.i2i(count, return_type)));
         ASR::symbol_t *f_sym = make_ASR_Function_t(fn_name, fn_symtab, dep, args, body, result, ASR::abiType::Source, ASR::deftypeType::Implementation, nullptr);
         scope->add_symbol(fn_name, f_sym);
         return b.Call(f_sym, new_args, return_type, nullptr);
```

2024-03-16 15:55 UTC, Pranavchiku requested changes
Requested changes

2024-03-16 16:13 UTC, Pranavchiku commented on src/libasr/pass/intrinsic_functions.h
> +        auto mask = declare("l", ASRUtils::TYPE(ASR::make_Integer_t(al, loc, kind)), Local);
```suggestion
        auto count = declare("j", arg_types[0], Local);
        auto val = declare("k", arg_types[0] Local);
        auto mask = declare("l", arg_types[0], Local);
```

2024-03-16 16:13 UTC, Pranavchiku commented on src/libasr/pass/intrinsic_functions.h
> +        auto mask = declare("l", ASRUtils::TYPE(ASR::make_Integer_t(al, loc, kind)), Local);
I believe this will work, try locally once.

2024-03-16 16:14 UTC, Pranavchiku commented on src/libasr/pass/intrinsic_functions.h
> +        int32_t kind = extract_kind_from_ttype_t(arg_types[0]);
```suggestion
```

If the above given changes work we do not need this,

2024-03-16 16:18 UTC, parth121101 commented on src/libasr/pass/intrinsic_functions.h
> +        auto mask = declare("l", ASRUtils::TYPE(ASR::make_Integer_t(al, loc, kind)), Local);
It doesnt work

2024-03-16 16:23 UTC, Pranavchiku commented on src/libasr/pass/intrinsic_functions.h
> +        auto mask = declare("l", ASRUtils::TYPE(ASR::make_Integer_t(al, loc, kind)), Local);
It works fine for me:

```diff
--- a/src/libasr/pass/intrinsic_functions.h
+++ b/src/libasr/pass/intrinsic_functions.h
@@ -2617,7 +2617,6 @@ namespace Popcnt {
             declare_basic_variables("_lcompilers_popcnt_" + type_to_str_python(arg_types[0]));
         fill_func_arg("i", arg_types[0]);
         auto result = declare(fn_name, return_type, ReturnVar);
-        int32_t kind = extract_kind_from_ttype_t(arg_types[0]);
         /*
         function popcnt(i) result(r)
         integer, intent(in) :: i
@@ -2643,9 +2642,9 @@ namespace Popcnt {
         end function popcnt
         */
 
-        auto count = declare("j", ASRUtils::TYPE(ASR::make_Integer_t(al, loc, kind)), Local);
-        auto val = declare("k", ASRUtils::TYPE(ASR::make_Integer_t(al, loc, kind)), Local);
-        auto mask = declare("l", ASRUtils::TYPE(ASR::make_Integer_t(al, loc, kind)), Local);
+        auto count = declare("j", arg_types[0], Local);
+        auto val = declare("k", arg_types[0], Local);
+        auto mask = declare("l", arg_types[0], Local);
         body.push_back(al, b.Assignment(count, b.i(0,arg_types[0])));
         body.push_back(al, b.Assignment(val, args[0]));
         body.push_back(al, b.Assignment(mask, b.i(1,arg_types[0])));
```

```console
% ./integration_tests/run_tests.py
[....]

100% tests passed, 0 tests failed out of 876

Label Time Summary:
c                 =   0.26 sec*proc (72 tests)
c_nopragma        =   0.02 sec*proc (3 tests)
cpp               =   0.15 sec*proc (44 tests)
fortran           =   0.39 sec*proc (97 tests)
gfortran          =   3.51 sec*proc (838 tests)
llvm              =   3.67 sec*proc (876 tests)
llvm2             =   0.04 sec*proc (11 tests)
llvmImplicit      =   0.01 sec*proc (2 tests)
llvmStackArray    =   0.44 sec*proc (110 tests)
llvm_nopragma     =   0.02 sec*proc (3 tests)
wasm              =   0.80 sec*proc (212 tests)
x86               =   0.06 sec*proc (19 tests)

Total Test time (real) =   0.49 sec
```

```console
% ./run_tests.py
[....]
errors/kind_star_of_logical.f90 * asr ✓ 
errors/array_constructor_with_different_kind.f90 * asr ✓ 
errors/incompatible_dimension_assignment_arr1.f90 * asr ✓ 
errors/incompatible_ranks_allocatable_arr2.f90 * asr ✓ 
errors/end_function_name_not_match.f90 * ast ✓ 
errors/incorrect_number_args_subroutine.f90 * asr ✓ 
errors/incorrect_number_args_function.f90 * asr ✓ 
errors/class_procedure_extra_args.f90 * asr ✓ 
errors/more_kwargs_than_acceptable_to_subroutine.f90 * asr ✓ 
optional_argument_subroutine_in_type.f90 * asr ✓ 
errors/runtime_stacktrace_01.f90 * run_dbg ✓ 
TESTS PASSED
```

2024-03-17 00:38 UTC, certik approved these changes
I think that this is good enough to merge. The implementation can be possibly improved, but that can be done later as needed. For example the ASR implementation can also use ">>", just like the compile time implementation.

2024-03-17 00:40 UTC, certik commented
I don't know why the test fails, that will have to be fixed.

2024-03-17 05:14 UTC, Pranavchiku approved these changes
Good to merge. Thanks @parth121101 !

2024-03-17 05:15 UTC, Pranavchiku commented
@parth121101 do you wish to polish commit history or atm I will prefer to squash and merge?

2024-03-17 05:17 UTC, parth121101 commented
> @parth121101 do you wish to polish commit history or atm I will prefer to squash and merge?

will do it, give me a moment

2024-03-17 06:59 UTC, merged