Implement lgt, llt, lle, lge
lfortran/lfortran pull request #3659
Opened 2024-03-17 09:52 UTC by HarshitaKalani

2024-03-17 10:13 UTC, HarshitaKalani commented
```fortran
program main
    character(5), allocatable :: a, b
    print*, lgt(maybe(a), b)

    contains
    function maybe(string) result(maybe_string)
        character(5), allocatable:: string
        character(len=len(string)) :: maybe_string
        maybe_string = 'works'
    end function maybe

end
```
This does not work yet.

2024-03-17 15:14 UTC, Pranavchiku commented on src/libasr/pass/intrinsic_functions.h
> +        }));
Can we not do something like?

```suggestion
	body.push_back(al, b.Assignment(result, sLtE(args[0], args[1])));
```

2024-03-17 15:14 UTC, Pranavchiku commented on src/libasr/pass/intrinsic_functions.h
> +        }));
Try this locally, if it works use it at everyplace. I am converting it to draft.

2024-03-17 15:14 UTC, Pranavchiku requested changes
A small suggestion requested, also this PR needs to be rebased and conflicts resolved.

2024-03-17 19:00 UTC, Shaikh-Ubaid commented on integration_tests/intrinsics_188.f90
> +end
```suggestion
end program
```

2024-03-17 19:02 UTC, Shaikh-Ubaid commented on integration_tests/intrinsics_188.f90
> +    character(7) :: fortran = "fortran"
Let's also add couple tests when there are symbols in strings. Try including different characters with `ascii` values ranging from `0` to `127`.

2024-03-18 05:48 UTC, Pranavchiku commented
The failure seems unrelated and can be fixed by rerun

```console
100% tests passed, 0 tests failed out of 3

Total Test time (real) =   9.93 sec
+ cd ..
+ git clean -dfx
Removing lf-fast/
Removing lf/
Removing model.dat
+ git checkout -t origin/namelist
fatal: 'origin/namelist' is not a commit and a branch 'namelist' cannot be created from it
```

2024-03-18 13:22 UTC, certik commented
The failure is due to https://github.com/lfortran/lfortran/issues/3663.

2024-03-18 13:56 UTC, certik approved these changes

2024-03-18 13:57 UTC, merged