Implemented Poppar intrinsic function
lfortran/lfortran pull request #3666
Opened 2024-03-18 16:26 UTC by parth121101

fixes : #3665

2024-03-18 19:34 UTC, Pranavchiku commented on src/libasr/pass/intrinsic_functions.h
> +        fill_func_arg("i", arg_types[0]);
Please document the fortran code here

2024-03-18 19:35 UTC, Pranavchiku commented on src/libasr/pass/intrinsic_functions.h
> +        ASR::expr_t *func_call_poppar = b.CallIntrinsic(scope, {arg_types[0]}, {args[0]}, return_type, 0, Popcnt::instantiate_Popcnt);
Call `Popcnt` the same way we do `MOD`

2024-03-18 19:35 UTC, Pranavchiku commented on src/libasr/pass/intrinsic_functions.h
> +        int result = count%2;
I think this can be done in a clean way by calling `popcnt`, I'll prefer to do it that way.

2024-03-18 19:36 UTC, Pranavchiku requested changes
Left a few comments, I know this can be tedious but let's do it in a right way so that we do not have to look back to this again. 

Note:

You may also refer https://www.geeksforgeeks.org/finding-the-parity-of-a-number-efficiently/ for an efficient compile time evaluation if possible

2024-03-19 05:11 UTC, HarshitaKalani commented on src/lfortran/semantics/ast_common_visitor.h
> +        {"poppar", {IntrinsicSignature({"i"}, 1, 1)}},
I think, we don't need to define it here if the number of arguments is fixed to 1.
```suggestion
```

2024-03-19 05:11 UTC, HarshitaKalani commented on src/libasr/pass/intrinsic_functions.h
> +            declare_basic_variables("_lcompilers_Poppar_" + type_to_str_python(arg_types[0]));
```suggestion
            declare_basic_variables("_lcompilers_poppar_" + type_to_str_python(arg_types[0]));
```

2024-03-21 15:39 UTC, Pranavchiku approved these changes
Great, this is good to merge. Thank you!

2024-03-21 15:51 UTC, merged