improve 'compiletime_broadcast_elemental_intrinsic' to support broadcasting for intrinsics
lfortran/lfortran pull request #3684
Opened 2024-03-19 18:25 UTC by gxyd

fixes #3673

2024-03-19 18:31 UTC, certik commented on src/libasr/asr_utils.h
> +        if (allow_nullptr && !a) continue;
I am not sure about this change --- when can an argument here in the vector be null?

2024-03-19 18:35 UTC, gxyd commented on src/libasr/asr_utils.h
> +        if (allow_nullptr && !a) continue;
For something like: `floor(1.2)` where the second optional argument is set to `nullptr`.

2024-03-19 19:20 UTC, certik commented on src/libasr/asr_utils.h
> +        if (allow_nullptr && !a) continue;
Ok. Let's get all tests passing, then I'll review one more time.

2024-03-20 12:44 UTC, gxyd commented
@certik , could you help me understand if the failing CI jobs are related to my changes?

the error says:
```bash
std::allocator<unsigned char> >, void>, bool)':
2024-03-20T10:25:01.8765884Z /home/runner/work/lfortran/lfortran/lfortran-0.33.1-866-ged79bd5c3/src/lfortran/fortran_kernel.cpp:346: undefined reference to `xeus::xinterpreter::publish_execution_result(int, nlohmann::json_abi_v3_11_3::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>,
 std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_3::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> >, void>, nlohmann::json_abi_v3_11_3::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, 
double, std::allocator, nlohmann::json_abi_v3_11_3::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> >, void>)'
```

Not able to understand how to go about this.

while the failing documentation job gives the error:
```bash
/usr/bin/ld: /home/runner/work/lfortran/lfortran/src/lfortran/fortran_kernel.cpp:511: undefined reference to `xeus::xkernel::xkernel(xeus::xconfiguration const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unique_ptr<xeus::xcontext, std::default_delete<xeus::xcontext> >, 
std::unique_ptr<xeus::xinterpreter, std::default_delete<xeus::xinterpreter> >, std::unique_ptr<xeus::xserver, std::default_delete<xeus::xserver> > (*)(xeus::xcontext&, xeus::xconfiguration const&,
 nlohmann::json_abi_v3_11_3::detail::error_handler_t), std::unique_ptr<xeus::xhistory_manager, std::default_delete<xeus::xhistory_manager> >, std::unique_ptr<xeus::xlogger, std::default_delete<xeus::xlogger> >, std::unique_ptr<xeus::xdebugger, std::default_delete<xeus::xdebugger> > (*)(xeus::xcontext&, xeus::xconfiguration
 const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, nlohmann::json_abi_v3_11_3::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_3::adl_serializer,
 std::vector<unsigned char, std::allocator<unsigned char> >, void> const&), nlohmann::json_abi_v3_11_3::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_3::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> >, void>, nlohmann::json_abi_v3_11_3::detail::error_handler_t)'
```

2024-03-20 14:23 UTC, certik commented
It doesn't seem like triggered by your PR, but something is wrong, it's the same error on all 3 platforms.

Can you try submitting a simple PR to check if master passes?

2024-03-20 14:34 UTC, certik commented
The CI failure is unrelated: https://github.com/lfortran/lfortran/issues/3687.

2024-03-21 08:30 UTC, gxyd commented
This is ready for a review.

2024-03-21 13:21 UTC, Pranavchiku commented on src/lfortran/semantics/ast_common_visitor.h
> +                    if ((args.size() == 2 || args.size() == 1) &&
I do not think we need this now, we shall go ahead and modify signature to

```diff
- void compiletime_broadcast_elemental_intrinsic(ASR::ArrayConstant_t* array, ASRUtils::create_intrinsic_function create_func, const Location& loc, Allocator& al)
+ void compiletime_broadcast_elemental_intrinsic(ASR::expr_t** args, ASRUtils::create_intrinsic_function  const Location& loc, Allocator& al)
```

Now iterate over args, and store in `std::vector<int> array_arg_indices`. Once we populate `array_arg_indices`, for example it has `{1, 2, 4}` and index `{0, 3, 5}` are scalar. We will create a helper funciton that takes `array_arg_indices` and all other necessary parameters and broadcast `X(s0, a1, a2, s3, a4, s5` as `[X(s0, a1[0], a2[0], s3, a4[0], s5), ...., ]`.

2024-03-21 13:22 UTC, Pranavchiku commented on src/lfortran/semantics/ast_common_visitor.h
> +                    if ((args.size() == 2 || args.size() == 1) &&
The current approach handles only `kind` parameter and limits us to only two arguments ( same as main with 1 argument ).

2024-03-21 13:27 UTC, Pranavchiku commented on src/libasr/asr_utils.h
> +        if (ignore_null && !a) continue;
We do not need this because in `intrinsic_functions.h` it is already taken care that there will not be any nullptr. For frontend this happens because we `fill_optional_kind_arg` and cases like `max`, `min`, etc which has multiple arguments.

2024-03-21 13:29 UTC, Pranavchiku requested changes
Left some comments above, let me know if you wish more information about anything.  I am marking this as draft.

2024-03-21 13:30 UTC, Pranavchiku commented
The approach in this PR works well, no doubts, that looks good as well. Just if we are fixing it, and we are no hurry at moment ( it is not a blocker afaik ), let us do it correctly. I'll be happy to help.

2024-03-21 13:49 UTC, gxyd commented on src/lfortran/semantics/ast_common_visitor.h
> +                    if ((args.size() == 2 || args.size() == 1) &&
Could you please give an example of an intrinsic function where broadcasting in this way would be needed? i.e. some being arrays, others being scalars, and it's an elemental intrinsic procedure? I'm just not able to think of something.

2024-03-21 13:52 UTC, gxyd commented on src/libasr/asr_utils.h
> +        if (ignore_null && !a) continue;
So, you are saying that we can remove call to `fill_optional_kind_arg` as well as remove the `ignore_null` extra added keyword argument as well from `all_args_evaluated`?

2024-03-21 14:01 UTC, Pranavchiku commented on src/libasr/asr_utils.h
> +        if (ignore_null && !a) continue;
We can also have multiple array arguments
```fortran
program main
print *, max([1.0, 2.0, 3.0], [4.0, 5.0, 6.0])
end program
```

2024-03-21 14:03 UTC, Pranavchiku commented on src/lfortran/semantics/ast_common_visitor.h
> +                    if ((args.size() == 2 || args.size() == 1) &&
We can also have multiple array arguments
```fortran
program main
print *, max([1.0, 2.0, 3.0], [4.0, 5.0, 6.0])
end program
```

2024-03-22 11:02 UTC, gxyd commented on src/libasr/asr_utils.h
> +        if (ignore_null && !a) continue;
> No, no, we need fill_optional_kind_arg, just check all_args_evaluated before filling optional arguments with nullptr.

I thought about this, and even if I do it before `fill_optional_kind_arg` as you mentioned that it would be filled with `nullptr` (for e.g. for `min`) that will happen even before `fill_optional_kind_arg`, as `args` is populated with `nullptr` in `handle_intrinsic_node_args` itself.

2024-03-22 11:03 UTC, gxyd commented
Let me know how it looks now @Pranavchiku

2024-03-22 14:40 UTC, certik commented on integration_tests/intrinsics_195.f90
> +end program
These need to have tests like `if (...) error stop` to ensure the answer is correct.

2024-03-22 14:43 UTC, certik commented on integration_tests/intrinsics_194.f90
> +    print *, min([1, 2], -1, -4)
This prints with GFortran:
```console
          -1          -8           2
          -1           1           1
           1           1           2
          -4          -4
```
How does this work? I don't understand what `min` does with a combination of array and scalar arguments like this.

2024-03-22 14:46 UTC, certik commented on integration_tests/intrinsics_194.f90
> +    print *, min([1, 2], -1, -4)
I think it extends all arguments to be arrays like this:
```
min([-1, 2, 3], 2, 5, [4, 4, 5], [5, -8, 7])
->
min([-1, 2, 3], [2, 2, 2], [5, 5, 5], [4, 4, 5], [5, -8, 7])
```
And then it computes the minimum element-wise, so we get `[-1, -8, 2]`?

2024-03-22 14:46 UTC, certik commented on integration_tests/intrinsics_195.f90
> +end program
Test shape and size of the resulting array also.

2024-03-22 14:47 UTC, certik commented
@gxyd thanks for working on this. I think there are many bugs like these and we need to fix them all, so this is extremely useful.

2024-03-22 15:36 UTC, gxyd commented on integration_tests/intrinsics_194.f90
> +    print *, min([1, 2], -1, -4)
Yes, that's correct.

2024-03-22 15:37 UTC, gxyd commented on integration_tests/intrinsics_195.f90
> +end program
Ah yes, I should've added it in the correct way, I'll change that.

2024-03-22 16:24 UTC, gxyd commented
> I think there are many bugs like these

@certik are there open issues for such bugs (couldn't find any similar to this), let me know if there are more similar issues which need attention, I could take a look at those if needed.

2024-03-22 19:47 UTC, certik commented
Yes, here are some:

* https://github.com/lfortran/lfortran/issues/3485
* https://github.com/lfortran/lfortran/issues/3203

2024-03-23 03:04 UTC, Pranavchiku commented
I’ll review this PR in a while, around 11:30 IST.

2024-03-23 06:50 UTC, Pranavchiku approved these changes
This is good, thanks for doing this!

2024-03-23 06:51 UTC, merged