Feat: Implement `Logical`
lfortran/lfortran pull request #3691
Opened 2024-03-22 08:00 UTC by shivimathur

2024-03-22 08:10 UTC, shivimathur commented
``` fortran
logical(kind = 8)::y = .true.
```
This does not change kind of y from 4 to 8.

2024-03-23 06:53 UTC, Pranavchiku commented on a.f90
> +end
you can remove this file and register this as an integration test

2024-03-23 06:54 UTC, Pranavchiku commented on src/libasr/pass/intrinsic_functions.h
> +        declare_basic_variables("_lcompilers_optimization_logical_" + type_to_str_python(arg_types[0]));
```suggestion
        declare_basic_variables("_lcompilers_logical_" + type_to_str_python(arg_types[0]));
```

2024-03-23 06:54 UTC, Pranavchiku commented on src/libasr/pass/intrinsic_functions.h
> +        fill_func_arg("x", arg_types[0]);
```suggestion
        fill_func_arg("l", arg_types[0]);
```

2024-03-23 06:54 UTC, Pranavchiku requested changes
Left a few comments, rest all is good.

2024-03-23 12:42 UTC, Shaikh-Ubaid commented
>I don't think we should be adding intrinsics for simple casts like this one. Cannot we simply insert a regular cast node here?

I think we should simply insert a cast node.

2024-03-23 16:21 UTC, HarshitaKalani commented
>I don't think we should be adding intrinsics for simple casts like this one. Cannot we simply insert a regular cast node here?

I agree to this.
@shivimathur , can you try implementing `logical` as a cast node?
For reference, you can follow: https://github.com/lfortran/lfortran/pull/3443/files

2024-04-26 06:02 UTC, Pranavchiku commented
> I don't think we should be adding intrinsics for simple casts like this one. Cannot we simply insert a regular cast node here?

I agree on this, I commented at https://github.com/lfortran/lfortran/pull/3922#issuecomment-2078688167

2024-10-10 13:15 UTC, closed without merging