Added more tests for bessel_y0 function
lfortran/lfortran pull request #3712
Opened 2024-03-26 16:14 UTC by parth121101

As suggested by @Pranavchiku I have added more tests for bessel_y0 function for rigorous testing.

2024-03-26 16:33 UTC, Pranavchiku commented on integration_tests/intrinsics_197.f90
> +    if(bessel_y0(1.9201212555874555d-153) - (-223.93677423698244) > 1e-12) error stop
let's not do it this way, create two arrays `x` and `expected`, populate it and then test those values. You may refer integration test for `besselj0`

2024-03-26 16:33 UTC, Pranavchiku requested changes
Requested changes above.

2024-03-26 17:06 UTC, parth121101 commented
> Requested changes above.

Done @Pranavchiku, thanks for letting me know a better way to manage this tests

2024-03-26 17:10 UTC, Pranavchiku commented
Would you mind adding test for large positive values?

2024-03-26 17:12 UTC, parth121101 commented
> Would you mind adding test for large positive values?

sure

2024-03-27 14:48 UTC, Pranavchiku commented on integration_tests/intrinsics_197.f90
> +          5.7258225070763252E-002_dp, -1.9980991452871046E-002_dp,  0.27136794388300378_dp,  0.26703177612919299_dp, &
same comment here

2024-03-27 14:48 UTC, Pranavchiku approved these changes
Minor comments, do that and this is good to merge.

2024-03-27 16:28 UTC, certik commented on integration_tests/intrinsics_197.f90
> +    x = [9.98600559790084e307_dp,9.98800479820072e307_dp,9.9900039985006e307_dp,9.99200319880048e307_dp, &
It should be `123.456e9_dp`, not `d`.

2024-03-27 16:28 UTC, certik approved these changes

2024-03-27 16:29 UTC, merged