[documentation]: document ASR pass transform_optional_argument_functions with example
lfortran/lfortran pull request #3740
Opened 2024-03-29 06:38 UTC by gxyd

Fixes #3733

2024-03-29 08:17 UTC, Pranavchiku commented on src/libasr/pass/transform_optional_argument_functions.cpp
> +)
Rather than ASR Nodes, I'll prefer to write fortran code. That way, it is easy for anyone to read and understand.

2024-03-29 08:18 UTC, Pranavchiku commented on src/libasr/pass/transform_optional_argument_functions.cpp
> +This same change is done for every optional argument(s) present in the function/subroutine.
Personally, I will keep it short and crisp, you can include _why this pass?, from, to_

2024-03-29 08:18 UTC, Pranavchiku requested changes
Left comments above, thanks for doing this!

2024-03-29 08:20 UTC, Pranavchiku commented
Not relevant to this PR

----

you may wish to read https://www.conventionalcommits.org/en/v1.0.0/

2024-03-29 13:28 UTC, certik commented on src/libasr/pass/transform_optional_argument_functions.cpp
> +)
Yes, let's write Fortran code, it's more readable. As long as it conveys what the change is doing, which in this case it does.

2024-03-30 05:10 UTC, gxyd commented on src/libasr/pass/transform_optional_argument_functions.cpp
> +)
Ok, I've made the change to use fortran code, instead of ASR nodes.

2024-03-30 05:10 UTC, gxyd commented on src/libasr/pass/transform_optional_argument_functions.cpp
> +This same change is done for every optional argument(s) present in the function/subroutine.
I've put it into two separate sections now.

2024-03-30 05:12 UTC, gxyd commented
> Not relevant to this PR
you may wish to read https://www.conventionalcommits.org/en/v1.0.0/


I roughly followed that, but I'm happy whether we use "docs" or "documentation", both are clear to me. Out of habit I've tended to use `[documentation]`, but I can keep a note to use "docs:" forward. 👍

2024-03-30 05:32 UTC, Pranavchiku approved these changes
This looks good, thanks!

2024-03-30 05:33 UTC, Pranavchiku commented
Would you be fine if I do squash and merge?

2024-03-30 05:37 UTC, gxyd commented
Yes please :)

2024-03-30 05:46 UTC, merged

2024-03-30 19:22 UTC, certik commented
Thanks for documenting it.