Fix Incorrect handling of compile time compare operation
lfortran/lfortran pull request #3746
Opened 2024-03-30 06:37 UTC by HarshitaKalani

Fixes: https://github.com/lfortran/lfortran/issues/3729

2024-03-30 06:42 UTC, Pranavchiku commented on src/lfortran/semantics/ast_common_visitor.h
> +        if (ASRUtils::expr_value(left) != nullptr && ASRUtils::expr_value(right) != nullptr && !ASR::is_a<ASR::ArrayConstant_t>(*ASRUtils::expr_value(left))) {
This will result in incorrect ASR ( `value == nullptr` ), ideally it should be `ArrayConstant([....])`.

2024-03-30 06:49 UTC, HarshitaKalani commented on src/lfortran/semantics/ast_common_visitor.h
> +        if (ASRUtils::expr_value(left) != nullptr && ASRUtils::expr_value(right) != nullptr && !ASR::is_a<ASR::ArrayConstant_t>(*ASRUtils::expr_value(left))) {
```asr
(TranslationUnit
    (SymbolTable
        1
        {
            main:
                (Program
                    (SymbolTable
                        2
                        {
                            a:
                                (Variable
                                    2
                                    a
                                    []
                                    Local
                                    (Cast
                                        (ArrayConstant
                                            [(IntegerConstant -10 (Integer 4))
                                            (IntegerConstant 2 (Integer 4))
                                            (IntegerConstant 3 (Integer 4))
                                            (IntegerConstant 4 (Integer 4))]
                                            (Array
                                                (Integer 4)
                                                [((IntegerConstant 1 (Integer 4))
                                                (IntegerConstant 4 (Integer 4)))]
                                                FixedSizeArray
                                            )
                                            ColMajor
                                        )
                                        IntegerToInteger
                                        (Array
                                            (Integer 8)
                                            [((IntegerConstant 1 (Integer 4))
                                            (IntegerConstant 4 (Integer 4)))]
                                            FixedSizeArray
                                        )
                                        (ArrayConstant
                                            [(IntegerConstant -10 (Integer 4))
                                            (IntegerConstant 2 (Integer 4))
                                            (IntegerConstant 3 (Integer 4))
                                            (IntegerConstant 4 (Integer 4))]
                                            (Array
                                                (Integer 4)
                                                [((IntegerConstant 1 (Integer 4))
                                                (IntegerConstant 4 (Integer 4)))]
                                                FixedSizeArray
                                            )
                                            ColMajor
                                        )
                                    )
                                    (ArrayConstant
                                        [(IntegerConstant -10 (Integer 4))
                                        (IntegerConstant 2 (Integer 4))
                                        (IntegerConstant 3 (Integer 4))
                                        (IntegerConstant 4 (Integer 4))]
                                        (Array
                                            (Integer 4)
                                            [((IntegerConstant 1 (Integer 4))
                                            (IntegerConstant 4 (Integer 4)))]
                                            FixedSizeArray
                                        )
                                        ColMajor
                                    )
                                    Parameter
                                    (Array
                                        (Integer 8)
                                        [((IntegerConstant 1 (Integer 4))
                                        (IntegerConstant 4 (Integer 4)))]
                                        FixedSizeArray
                                    )
                                    ()
                                    Source
                                    Public
                                    Required
                                    .false.
                                )
                        })
                    main
                    []
                    [(Print
                        [(IntegerCompare
                            (Var 2 a)
                            Gt
                            (Cast
                                (IntegerConstant 0 (Integer 4))
                                IntegerToInteger
                                (Integer 8)
                                (IntegerConstant 0 (Integer 8))
                            )
                            (Array
                                (Logical 4)
                                [((IntegerConstant 1 (Integer 4))
                                (IntegerConstant 4 (Integer 4)))]
                                FixedSizeArray
                            )
                            ()
                        )]
                        ()
                        ()
                    )]
                )
        })
    []
)
```

2024-03-30 06:49 UTC, HarshitaKalani commented on src/lfortran/semantics/ast_common_visitor.h
> +        if (ASRUtils::expr_value(left) != nullptr && ASRUtils::expr_value(right) != nullptr && !ASR::is_a<ASR::ArrayConstant_t>(*ASRUtils::expr_value(left))) {
```fortran
program main
    integer(8), parameter :: a(4) = [-10, 2, 3, 4]
    print*, a>0
end
```

2024-03-30 06:49 UTC, HarshitaKalani commented on src/lfortran/semantics/ast_common_visitor.h
> +        if (ASRUtils::expr_value(left) != nullptr && ASRUtils::expr_value(right) != nullptr && !ASR::is_a<ASR::ArrayConstant_t>(*ASRUtils::expr_value(left))) {
>This will result in incorrect ASR ( value == nullptr ), ideally it should be ArrayConstant([....]).

It is ArrayConstant in this ASR, no?

2024-03-30 06:51 UTC, Pranavchiku requested changes
Left comments above

2024-03-30 06:51 UTC, Pranavchiku commented on src/lfortran/semantics/ast_common_visitor.h
> +        if (ASRUtils::expr_value(left) != nullptr && ASRUtils::expr_value(right) != nullptr && !ASR::is_a<ASR::ArrayConstant_t>(*ASRUtils::expr_value(left))) {
Nope, see the `IntegerCompare` node.

2024-03-30 06:51 UTC, Pranavchiku commented on src/lfortran/semantics/ast_common_visitor.h
>      if (ASRUtils::is_integer(*dest_type)) {
What we need to do is:

Step1: check if `expr_value(left)` and `expr_value(right)` is not nullptr ( compile time evaluation is possible )

> (ASRUtils::expr_value(left) != nullptr && ASRUtils::expr_value(right) != nullptr)

Step 2: if it is compile time, create a vector `std::vector<pair<ASR::expr_t*, ASR::expr_t*>> compiletime_values` and populate this.

Population will be based on cases, 

case 1: left: `ArrayConstant`  and right: `ArrayConstant`.

Iterate over values of both and push `pair{left->m_values[i], right->m_values[i]}` in `compiletime_values`.

case 2: left: `ArrayConstant` and right: `IntegerConstant` or any scalar constant.

Push `pair{left->m_values[i], expr_value(right)}`

and so on for other cases.

Now create a helper function that takes `compiletime_values`, `type`, `asrop`, etc and iterates over its values and return you `ASR::expr_t* value`, if `compiletime_values.size() == 1`, value will be `LogicalConstant`, else it will be an `ArrayConstant` with `LogicalConstant` as values. I hope this makes sense.

2024-04-01 04:42 UTC, Pranavchiku requested changes
I'll prefer to do something like:

```diff
diff --git a/src/lfortran/semantics/ast_common_visitor.h b/src/lfortran/semantics/ast_common_visitor.h
index 0cd8fd0f5..ba1b8fca8 100644
--- a/src/lfortran/semantics/ast_common_visitor.h
+++ b/src/lfortran/semantics/ast_common_visitor.h
@@ -95,6 +95,60 @@ static inline int64_t stmt_label(AST::stmt_t *f)
 class CommonVisitorMethods {
 public:
 
+  static inline ASR::expr_t* compare_helper(ASR::expr_t* left_val, ASR::expr_t* right_val, ASR::cmpopType asr_op) {
+    if (ASR::is_a<ASR::Integer_t>(*ASRUtils::expr_type(left_val))) {
+        //..
+    }
+  }
+
+  static inline ASR::expr_t* evaluate_compiletime_values(std::vector<std::pair<ASR::expr_t*, ASR::expr_t*>> &compiletime_values,
+                            ASR::expr_t* left, ASR::expr_t* right, ASR::cmpopType asr_op, ASR::ttype_t* type) {
+    Vec<ASR::expr_t*> args; args.reserve(al, compiletime_values.size());
+    for (size_t i = 0; i < compiletime_values.size(); i++) {
+        ASR::expr_t* left_val = compiletime_values[i].first;
+        ASR::expr_t* right_val = compiletime_values[i].second;
+        args.push_back(compare_helper(left_val, right_val, asr_op));
+    }
+
+    if (compiletime_values.size() == 0) {
+        return compare_helper(ASRUtils::expr_val(left), ASRUtils::expr_val(right), asr_op);
+    } else {
+        // make ArrayConstructor
+    }
+  }
+
+  static inline void populate_compiletime_values(std::vector<std::pair<ASR::expr_t*, ASR::expr_t*>> &compiletime_values,
+                                    ASR::expr_t* left, ASR::expr_t* right) {
+    int fixed_size_left_array = ASRUtils::get_fixed_size_of_array(ASRUtils::expr_type(ASRUtils::expr_value(left)));
+    int fixed_size_right_array = ASRUtils::get_fixed_size_of_array(ASRUtils::expr_type(ASRUtils::expr_value(right)));
+
+    if (ASR::is_a<ASR::ArrayConstant_t>(*ASRUtils::expr_value(left))) {
+        ASR::ArrayConstant_t* array = ASR::down_cast<ASR::ArrayConstant_t>(ASRUtils::expr_value(left));
+        for (size_t i=0; i<array->n_args; i++) {
+            compiletime_values.push_back({array->m_args[i], nullptr});
+        }
+    }
+    if (ASR::is_a<ASR::ArrayConstant_t>(*ASRUtils::expr_value(right))) {
+        ASR::ArrayConstant_t* array = ASR::down_cast<ASR::ArrayConstant_t>(ASRUtils::expr_value(right));
+        for (size_t i=0; i<array->n_args; i++) {
+            compiletime_values[i].second = array->m_args[i];
+        }
+    }
+
+    if (fixed_size_left_array == 0 && fixed_size_right_array == 0) {
+        return;
+    } else {
+        for (size_t i = 0; i < compiletime_values.size(); i++) {
+            if (compiletime_values[i].first == nullptr) {
+                compiletime_values[i].first = ASRUtils::expr_value(left);
+            }
+            if (compiletime_values[i].second == nullptr) {
+                compiletime_values[i].second = ASRUtils::expr_value(right);
+            }
+        }
+    }
+  }
+
   inline static void visit_Compare(Allocator &al, const AST::Compare_t &x,
                                    ASR::expr_t *&left, ASR::expr_t *&right,
                                    ASR::asr_t *&asr, std::string& intrinsic_op_name,
@@ -210,165 +264,10 @@ public:
 
     ASR::expr_t *value = nullptr;
 
-    if (ASRUtils::is_integer(*dest_type)) {
-
-        if (ASRUtils::expr_value(left) != nullptr && ASRUtils::expr_value(right) != nullptr) {
-            int64_t left_value = ASR::down_cast<ASR::IntegerConstant_t>(
-                                    ASRUtils::expr_value(left))->m_n;
-            int64_t right_value = ASR::down_cast<ASR::IntegerConstant_t>(
-                                    ASRUtils::expr_value(right))->m_n;
-            bool result;
-            switch (asr_op) {
-                case (ASR::cmpopType::Eq):  { result = left_value == right_value; break; }
-                case (ASR::cmpopType::Gt): { result = left_value > right_value; break; }
-                case (ASR::cmpopType::GtE): { result = left_value >= right_value; break; }
-                case (ASR::cmpopType::Lt): { result = left_value < right_value; break; }
-                case (ASR::cmpopType::LtE): { result = left_value <= right_value; break; }
-                case (ASR::cmpopType::NotEq): { result = left_value != right_value; break; }
-                default: {
-                    throw SemanticError("Comparison operator not implemented",
-                                        x.base.base.loc);
-                }
-            }
-            value = ASR::down_cast<ASR::expr_t>(ASR::make_LogicalConstant_t(
-                al, x.base.base.loc, result, type));
-        }
-
-        asr = ASR::make_IntegerCompare_t(al, x.base.base.loc, left, asr_op, right, type, value);
-
-    } else if (ASRUtils::is_real(*dest_type)) {
-
-        if (ASRUtils::expr_value(left) != nullptr && ASRUtils::expr_value(right) != nullptr) {
-            double left_value = ASR::down_cast<ASR::RealConstant_t>(
-                                    ASRUtils::expr_value(left))->m_r;
-            double right_value = ASR::down_cast<ASR::RealConstant_t>(
-                                    ASRUtils::expr_value(right))->m_r;
-            bool result;
-            switch (asr_op) {
-                case (ASR::cmpopType::Eq):  { result = left_value == right_value; break; }
-                case (ASR::cmpopType::Gt): { result = left_value > right_value; break; }
-                case (ASR::cmpopType::GtE): { result = left_value >= right_value; break; }
-                case (ASR::cmpopType::Lt): { result = left_value < right_value; break; }
-                case (ASR::cmpopType::LtE): { result = left_value <= right_value; break; }
-                case (ASR::cmpopType::NotEq): { result = left_value != right_value; break; }
-                default: {
-                    throw SemanticError("Comparison operator not implemented",
-                                        x.base.base.loc);
-                }
-            }
-            value = ASR::down_cast<ASR::expr_t>(ASR::make_LogicalConstant_t(
-                al, x.base.base.loc, result, type));
-        }
-
-        asr = ASR::make_RealCompare_t(al, x.base.base.loc, left, asr_op, right, type, value);
-
-    } else if (ASRUtils::is_complex(*dest_type)) {
-
-        if (ASRUtils::expr_value(left) != nullptr && ASRUtils::expr_value(right) != nullptr) {
-            ASR::ComplexConstant_t *left0
-                = ASR::down_cast<ASR::ComplexConstant_t>(ASRUtils::expr_value(left));
-            ASR::ComplexConstant_t *right0
-                = ASR::down_cast<ASR::ComplexConstant_t>(ASRUtils::expr_value(right));
-            std::complex<double> left_value(left0->m_re, left0->m_im);
-            std::complex<double> right_value(right0->m_re, right0->m_im);
-            bool result;
-            switch (asr_op) {
-                case (ASR::cmpopType::Eq) : {
-                    result = left_value.real() == right_value.real() &&
-                            left_value.imag() == right_value.imag();
-                    break;
-                }
-                case (ASR::cmpopType::NotEq) : {
-                    result = left_value.real() != right_value.real() ||
-                            left_value.imag() != right_value.imag();
-                    break;
-                }
-                default: {
-                    throw SemanticError("'" + ASRUtils::cmpop_to_str(asr_op) +
-                                        "' comparison is not supported between complex numbers",
-                                        x.base.base.loc);
-                }
-            }
-            value = ASR::down_cast<ASR::expr_t>(ASR::make_LogicalConstant_t(
-                al, x.base.base.loc, result, type));
-        }
-
-        asr = ASR::make_ComplexCompare_t(al, x.base.base.loc, left, asr_op, right, type, value);
-
-    } else if (ASRUtils::is_logical(*dest_type)) {
-
-        if (ASRUtils::expr_value(left) != nullptr && ASRUtils::expr_value(right) != [...]

2024-04-01 11:01 UTC, Pranavchiku commented on src/lfortran/semantics/ast_common_visitor.h
> +// }
```suggestion
```

2024-04-01 11:02 UTC, Pranavchiku approved these changes
Looks good, this can be further improved using `template` but it can be done in subsequent PRs. Thanks for doing this!

2024-04-01 11:23 UTC, merged