chore: remove unused code related to `random_number`
lfortran/lfortran pull request #3758
Opened 2024-04-01 15:59 UTC by Pranavchiku

Addresses https://github.com/lfortran/lfortran/pull/3754#issuecomment-2030038128

2024-04-01 17:42 UTC, certik commented
I have a question --- what about user defined elemental subroutines?

We need to support this feature it seems. Let's instead add tests for user elemental subroutines and ensure things work.

2024-04-01 19:46 UTC, czgdp1807 requested changes
Remove it from LPython as well.

2024-04-01 21:08 UTC, certik commented
@czgdp1807 but why removing in the first place? I think we need this functionality for user defined elemental subroutines.

2024-04-02 03:15 UTC, Pranavchiku commented
I remember we had a discussion somewhere about this, will check and circle back here.

2024-04-02 04:45 UTC, Pranavchiku commented
Elemental subroutine are not broadcasted yet, we do not support it. Issue: https://github.com/lfortran/lfortran/issues/3730, this will not be difficult to fix.

2024-04-02 04:47 UTC, Pranavchiku commented on src/libasr/pass/array_op.cpp
> -                if (module_name == "lfortran_intrinsic_math" && name == "random_number") {
Instead of this, one has to check if call is to elemental subroutine, if yes, same code for broadcast.

2024-04-02 06:17 UTC, gxyd commented
I just saw the discussion here, the original PR I opened (i.e. #3754) was only to check if tests succeed without the existing code, I didn't actually intend to remove it, as mentioned above by @Pranavchiku , I might be able to re-use it for implementing #3730 .

2024-04-03 04:54 UTC, Pranavchiku commented
closing with reference to #3730.

2024-04-03 04:54 UTC, closed without merging