Implemented Bessel_y1 function
lfortran/lfortran pull request #3764
Opened 2024-04-02 08:09 UTC by parth121101

2024-04-02 08:46 UTC, HarshitaKalani commented on integration_tests/intrinsics_201.f90
> +        ! if (abs(bessel_y1(x(i)) - expected(i)) > 1e-12) error stop
Why have you commented this out?

2024-04-02 08:46 UTC, HarshitaKalani commented on integration_tests/intrinsics_201.f90
> +end program
This too?

2024-04-02 08:48 UTC, HarshitaKalani commented on src/libasr/pass/intrinsic_functions.h
> +
Since the code is repetitive for almost all the Bessel functions, I think we can create a helper function.

2024-04-02 11:09 UTC, Pranavchiku commented on src/libasr/pass/intrinsic_functions.h
> +
I agree with @HarshitaKalani, let's do it in this PR itself.

2024-04-02 11:10 UTC, Pranavchiku requested changes
@parth121101 can you please apply review suggested above and then this PR can be review.

2024-04-03 09:17 UTC, Pranavchiku commented
Please feel free to post if you are stuck somewhere.

2024-04-04 06:04 UTC, parth121101 commented
> Please feel free to post if you are stuck somewhere.

@Pranavchiku I tried some approaches, but I couldn't succeed. Can you suggest a way to do this?

2024-04-04 06:16 UTC, Pranavchiku commented
You have to something like:

```diff
diff --git a/src/libasr/asr_builder.h b/src/libasr/asr_builder.h
index 06569a068..41fd4a586 100644
--- a/src/libasr/asr_builder.h
+++ b/src/libasr/asr_builder.h
@@ -1043,6 +1043,25 @@ class ASRBuilder {
             nullptr, nullptr));
     }
 
+    ASR::symbol_t* create_c_func(ASRUtils::ASRBuilder b, std::string c_func_name, SymbolTable* fn_symtab, ASR::ttype_t* return_type, int n_args) {
+        SymbolTable *fn_symtab_1 = al.make_new<SymbolTable>(fn_symtab);
+        Vec<ASR::expr_t*> args_1; args_1.reserve(al, n_args);
+        for (int i = 0; i < n_args; i++) {
+            ASR::ttype_t *arg_type = nullptr;
+            args_1.push_back(al, b.Variable(fn_symtab_1, "x_"+std::to_string(i), arg_type,
+                ASR::intentType::In, ASR::abiType::BindC, true));
+        }
+
+        ASR::expr_t *return_var_1 = b.Variable(fn_symtab_1, c_func_name,
+            return_type, ASRUtils::intent_return_var, ASR::abiType::BindC, false);
+
+        SetChar dep_1; dep_1.reserve(al, 1);
+        Vec<ASR::stmt_t*> body_1; body_1.reserve(al, 1);
+        ASR::symbol_t *s = make_ASR_Function_t(c_func_name, fn_symtab_1, dep_1, args_1,
+            body_1, return_var_1, ASR::abiType::BindC, ASR::deftypeType::Interface, s2c(al, c_func_name));
+        return s;
+    }
+
 };
 
 } // namespace LCompilers::ASRUtils
diff --git a/src/libasr/pass/intrinsic_functions.h b/src/libasr/pass/intrinsic_functions.h
index e70f5158e..64c693781 100644
--- a/src/libasr/pass/intrinsic_functions.h
+++ b/src/libasr/pass/intrinsic_functions.h
@@ -3136,23 +3136,7 @@ namespace BesselY1 {
         fill_func_arg("x", arg_types[0]);
         auto result = declare(new_name, return_type, ReturnVar);
         {
-            SymbolTable *fn_symtab_1 = al.make_new<SymbolTable>(fn_symtab);
-            Vec<ASR::expr_t*> args_1;
-            {
-                args_1.reserve(al, 1);
-                ASR::expr_t *arg = b.Variable(fn_symtab_1, "x", arg_types[0],
-                    ASR::intentType::In, ASR::abiType::BindC, true);
-                args_1.push_back(al, arg);
-            }
-
-            ASR::expr_t *return_var_1 = b.Variable(fn_symtab_1, c_func_name,
-                return_type, ASRUtils::intent_return_var, ASR::abiType::BindC, false);
-
-            SetChar dep_1; dep_1.reserve(al, 1);
-            Vec<ASR::stmt_t*> body_1; body_1.reserve(al, 1);
-            ASR::symbol_t *s = make_ASR_Function_t(c_func_name, fn_symtab_1, dep_1, args_1,
-                body_1, return_var_1, ASR::abiType::BindC, ASR::deftypeType::Interface, s2c(al, c_func_name));
-            fn_symtab->add_symbol(c_func_name, s);
+            ASR::symbol_t *s = b.create_c_func(b, c_func_name, fn_symtab, return_type, 1);
             dep.push_back(al, s2c(al, c_func_name));
             body.push_back(al, b.Assignment(result, b.Call(s, args, return_type)));
         }
```

2024-04-04 15:52 UTC, certik commented on integration_tests/intrinsics_204.f90
> +        if (abs(bessel_y1(x(i)) - expected(i)) > 1e-12) error stop
```suggestion
        if (abs(bessel_y1(x(i)) - expected(i)) > 1e-12_dp) error stop
```

2024-04-04 15:52 UTC, certik approved these changes
should be rebased

2024-04-04 17:57 UTC, merged