feat: implement acosd intrinsic function
lfortran/lfortran pull request #3804
Opened 2024-04-07 13:05 UTC by parth121101

2024-04-07 14:12 UTC, Pranavchiku requested changes
Left a comment to be addressed before this PR becomes ready to merge. Thank you!

2024-04-07 14:12 UTC, Pranavchiku commented on integration_tests/intrinsics_205.f90
> +    print *, acosd(x)
Let's add more test in subsequent PRs, I'll do this at high priority from https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/special/acosd/test/fixtures/julia to be sure that this is correct approach to add these type of functions.

2024-04-07 14:12 UTC, Pranavchiku commented on src/libasr/pass/intrinsic_functions.h
> +        return nullptr;
This will be easy to compute here, compute and return value instead of `nullptr`.

2024-04-07 14:14 UTC, certik commented on src/libasr/pass/intrinsic_functions.h
> +        return nullptr;
Yes, always create a compile time value.

This means that also our tests are inadequate, since they didn't catch this.

We need to write the compile time tests as `real, parameter :: res = sind(1.5)`.

2024-04-07 14:15 UTC, certik commented on integration_tests/intrinsics_205.f90
> +    print *, acosd(x)
Can you be specific what exactly you are proposing to add from Julia?

2024-04-07 14:16 UTC, Pranavchiku commented on integration_tests/intrinsics_205.f90
> +    print *, acosd(x)
That folder has `negative.json` and `positive.json`, which consists of `x` and `expected` values.

2024-04-07 14:21 UTC, certik commented on integration_tests/intrinsics_205.f90
> +    print *, acosd(x)
Those might be the exactly rounded values, if so, we'll fail those, until we have a dedicated implementation.

2024-04-07 14:25 UTC, Pranavchiku commented on integration_tests/intrinsics_205.f90
> +    print *, acosd(x)
I suspect it to fail, and hence wished to see if divergence is huge ( 1e-3, 1e-4 ) around, using dedicated implementation or finding library that provides `acosd` will be good choice.

2024-04-07 14:27 UTC, certik commented on integration_tests/intrinsics_205.f90
> +    print *, acosd(x)
No, divergence will be at the level 1e-16. Yes, we can add tests for those, and just test it to 1e-15 or so.

2024-04-07 14:28 UTC, Pranavchiku commented on integration_tests/intrinsics_205.f90
> +    print *, acosd(x)
Perfect, yes.

2024-04-08 11:26 UTC, parth121101 commented on src/libasr/pass/intrinsic_functions.h
> +        return nullptr;
@Pranavchiku I have added a few tests from the JSON file as suggested by you. Apart from this, I have added the compile time implementation using math.h library. Could you please evaluate the implementation to determine whether it is appropriate or not?

2024-04-08 12:39 UTC, Pranavchiku commented on src/libasr/pass/intrinsic_functions.h
> +        double result = acos(i) * 180.0 / PI;
```suggestion
        double result = acos(i) * 180.0 / M_PI;
```

2024-04-08 12:39 UTC, Pranavchiku commented on src/libasr/runtime/lfortran_intrinsics.c
> +    result = (result*180)/PI;
```suggestion
    float result = acos(x);
    result = (result*180)/M_PI;
```

2024-04-08 12:39 UTC, Pranavchiku commented on src/libasr/runtime/lfortran_intrinsics.c
> +    result = (result*180)/PI;
```suggestion
    double result = acos(x);
    result = (result*180)/M_PI;
```

2024-04-08 12:41 UTC, Pranavchiku commented on integration_tests/intrinsics_205.f90
> +    real(dp) :: i,j,k
Let's do something like

```fortran
program intrinsics_205
use, intrinsic :: iso_fortran_env, only: dp => real64, sp => real32
real(sp), parameter :: x(20) = [......]
real(sp) :: expected(20)
real(sp), parameter :: output(20) = acos(x)
```

2024-04-08 12:42 UTC, Pranavchiku commented on integration_tests/intrinsics_205.f90
> +program intrinsics_203
```suggestion
program intrinsics_205
```

2024-04-08 12:42 UTC, Pranavchiku requested changes
Left comments above, everything but test looks good.

2024-04-08 17:48 UTC, parth121101 commented
@Pranavchiku I applied one of your suggestions. It was about the utilization of M_PI from math.h library. I checked its value and found that it was less accurate. Its value was 3.14159. Previously, I was using the value of PI as 3.14159265358979323846. So what do you think which one should I use?

2024-04-09 11:27 UTC, Pranavchiku commented on integration_tests/intrinsics_205.f90
> +program intrinsics_203
```suggestion
program intrinsics_205
```

2024-04-09 11:29 UTC, Pranavchiku commented on src/libasr/runtime/lfortran_intrinsics.c
> +double PI = 3.14159265358979323846;
```suggestion
#define PI 3.14159265358979323846;
```

2024-04-09 11:29 UTC, Pranavchiku commented on src/libasr/runtime/lfortran_intrinsics.c
> +    return result;
```suggestion
    return (acos(x)*180)/PI;
```

2024-04-09 11:30 UTC, Pranavchiku commented on src/libasr/runtime/lfortran_intrinsics.c
> +    return result;
```suggestion
    return (acos(x)*180)/PI;
```

2024-04-09 11:31 UTC, Pranavchiku commented on integration_tests/intrinsics_205.f90
> +    real(dp) :: expected_w(19)
```suggestion
    real(dp) :: w(19)
    real(dp) :: expected_w(19)
    real(dp), parameter :: w_comp(19) = [0.321_dp, 0.526_dp, 0.728_dp, -0.321_dp, -0.526_dp, -0.728_dp, &
         -1.0_dp, -0.9995004995004995_dp, -0.999000999000999_dp, &
         -0.9985014985014985_dp, -0.998001998001998_dp, -0.9975024975024975_dp, &
         -0.997002997002997_dp, -0.9965034965034965_dp, -0.996003996003996_dp, &
         -0.9955044955044955_dp, -0.995004995004995_dp, -0.9945054945054945_dp, &
         -0.994005994005994_dp]
    real(dp), parameter :: res(19) = acosd(w_comp)
```

2024-04-09 11:31 UTC, Pranavchiku commented on integration_tests/intrinsics_205.f90
> +    real(dp) :: expected_w(19)
And then test each value of `res`

2024-04-09 11:32 UTC, Pranavchiku requested changes
This PR is missing compile time tests, left comments above.

2024-04-09 17:43 UTC, Pranavchiku approved these changes

2024-04-09 17:44 UTC, Pranavchiku commented
I am sorry I resolved conflicts via github UI which resulted into Merge commit and hence will have to squash and merge this PR, I hope this is fine.

2024-04-09 18:12 UTC, Pranavchiku approved these changes
This is good, thanks!

2024-04-09 19:23 UTC, merged