assign "m_end" as UpperBound when an array of character
lfortran/lfortran pull request #3835
Opened 2024-04-09 11:08 UTC by gxyd

Fixes #3039

2024-04-09 11:26 UTC, Pranavchiku commented on tests/tests.toml
> +asr = true
```suggestion
```

It is fine not to specifically test `asr` when there already exist an integration test, do you have any specific reason to test exact `asr`?

2024-04-09 11:27 UTC, Pranavchiku requested changes
Left a comment above otherwise this looks good. Thanks!

2024-04-09 11:29 UTC, gxyd commented on tests/tests.toml
> +asr = true
I remember the discussion from last week's weekly call, but I would prefer saving the ASR as the output generated by executable might still be right even if the ASR is incorrect. It's just to make sure that the generated ASR actually has the ArrayBound node, that's all.

2024-04-09 11:44 UTC, Pranavchiku commented on tests/tests.toml
> +asr = true
> output generated by executable might still be right even if the ASR is incorrect.

I agree on your point, we can go ahead to test ASR in this case as it is small and have no usage of `runtime` modules. Saving reference for all case increases code lines, repo size, we have to remember and check every time this gets changed thus consumes more efforts.

2024-04-09 11:46 UTC, Pranavchiku commented on tests/tests.toml
> +asr = true
Preferably you may register minimal test that failed and generate ASR for it, right now it contains other redundant nodes like `if... xx`.

2024-04-09 11:48 UTC, gxyd commented on tests/tests.toml
> +asr = true
Alright, I'll change that, as the `if ... xx` part as we are testing that via `RUN(NAME char_array_01 LABELS gfortran llvm)` in `integration_tests/CMakeLists.txt`.

2024-04-09 15:55 UTC, certik commented
Does the test in this PR fail in master? If so, then just adding the test I think is fine.

The problem with the ASR test is that it doesn't check that `ArrayBound` is actually there. So we are just hoping that future changes will not break it (that we will spot the regression in the updated reference results diff). While the integration test is clear: if it failed before and now it doesn't, then it must be working (one way or the other), and it will never break with future PRs.

2024-04-09 16:16 UTC, gxyd commented on integration_tests/CMakeLists.txt
> +RUN(NAME char_array_01 LABELS gfortran llvm)
I actually made it a part of integration tests and also saved it's ASR as well, see: https://github.com/lfortran/lfortran/pull/3835/files#diff-1ab5e0955089e3094bab05294193ebb1d6f463e1739a7d0b0db2d3297f5a99c8R3881-R3883.

> The ASR tests were instrumental to bootstrap the compiler, since we couldn't compile many of the features. But now in the late stages of the compiler, the ASR tests are not as useful.

I still personally would've liked to keep the ASR test, but I think you know better, so I'm going to follow that 😃

2024-04-09 16:22 UTC, gxyd commented
> Does the test in this PR fail in master?

It does.

2024-04-09 18:10 UTC, Pranavchiku commented on integration_tests/char_array_01.f90
> +    print *, char_arr2
Let's test actual values using `if(....) error stop` conditions.

2024-04-09 21:04 UTC, certik commented on integration_tests/CMakeLists.txt
> +RUN(NAME char_array_01 LABELS gfortran llvm)
We can keep it.

2024-04-10 06:19 UTC, gxyd commented
We've two test files now:
* one to save the ASR, which doesn't have any `if ... error stop` conditions in it and is relatively simple
* the second one to make sure that the executable output is correct (and has `if ... error stop` conditions), and on which the current main would fail

2024-04-10 07:47 UTC, Pranavchiku approved these changes

2024-04-10 07:47 UTC, merged