Add error message for negative argument of sqrt intrinsic function
lfortran/lfortran pull request #3871
Opened 2024-04-14 16:16 UTC by parth121101

2024-04-14 17:52 UTC, HarshitaKalani requested changes
Can you also add an error test to check if it works perfectly?

2024-04-14 17:52 UTC, HarshitaKalani commented on src/libasr/pass/intrinsic_functions.h
> +            return nullptr;
```suggestion
            if (val < 0.0) {
                append_error(diag, "Argument of SQRT has a negative value", loc);
                return nullptr;
```

2024-04-15 07:25 UTC, Shaikh-Ubaid commented on src/libasr/pass/intrinsic_functions.h
> +            }
The else here seems redundant.

```suggestion
            return b.f(std::sqrt(val), arg_type);
```

2024-04-15 10:21 UTC, parth121101 commented on src/libasr/pass/intrinsic_functions.h
> +            }
@Shaikh-Ubaid I have added the error message for the negative argument. But still, the function is returning nan values along with the error message.

```
cat a.f90
program sqrt_neg
    print *, sqrt(-1.0)
end program

lfortran a.f90
semantic error: Argument of SQRT has a negative value
 --> a.f90:2:14
  |
2 |     print *, sqrt(-1.0)
  |              ^^^^^^^^^^ 

Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
         -nan
```

2024-04-15 10:44 UTC, Shaikh-Ubaid commented on src/libasr/pass/intrinsic_functions.h
> +            }
https://github.com/lfortran/lfortran/blob/f6d9f0f9504939cfa143e949811f01265c7ef654/src/libasr/intrinsic_func_registry_util_gen.py#L704-L705

It looks like we need to add the following check in the above location.

```console
if (diagnostics.has_error()) {
    return nullptr
}

2024-04-15 10:45 UTC, Shaikh-Ubaid commented on src/libasr/pass/intrinsic_functions.h
> +            }
We might need to add the same check after [this](https://github.com/lfortran/lfortran/blob/f6d9f0f9504939cfa143e949811f01265c7ef654/src/libasr/intrinsic_func_registry_util_gen.py#L694) line as well.

2024-04-15 10:46 UTC, Shaikh-Ubaid commented on src/libasr/pass/intrinsic_functions.h
> +            return nullptr;
```suggestion
                return nullptr;
```

2024-04-15 11:07 UTC, Shaikh-Ubaid commented on src/libasr/pass/intrinsic_functions.h
>              double val = ASR::down_cast<ASR::RealConstant_t>(expr_value(args[0]))->m_r;
Unrelated to your PR:
```suggestion
            double val = ASR::down_cast<ASR::RealConstant_t>(args[0])->m_r;
```
I think `expr_value()` is already computed and passed in `args`. So, we need not compute it here again. We should update this for other `eval_*()` functions as well (But in a separate PR).

2024-04-15 13:41 UTC, certik commented on src/libasr/pass/intrinsic_functions.h
> +                append_error(diag, "Argument of SQRT has a negative value", loc);
I prefer using lowercase:
```suggestion
                append_error(diag, "Argument of `sqrt` has a negative value", loc);
```
The uppercase reminds me of old F77 style, while lowercase is how most modern languages are used.

2024-04-15 13:41 UTC, certik commented on tests/errors/sqrt_neg.f90
> +    print *, sqrt(-1.0)
Can you register a test for this and add reference results?

2024-04-15 17:11 UTC, Shaikh-Ubaid commented on src/libasr/intrinsic_func_registry_util_gen.py
> +        src += indent * 2 + "}\n"
It looks like this should be:
```suggestion
        src += indent * 3 +     "if (diag.has_error()) {\n"
        src += indent * 4 +         f"return nullptr;\n"
        src += indent * 3 +     "}\n"
```

2024-04-15 17:13 UTC, Shaikh-Ubaid approved these changes
Shared a minor coment. Rest looks good to me. Thanks for this. Great work!

2024-04-15 17:15 UTC, parth121101 commented on src/libasr/intrinsic_func_registry_util_gen.py
> +        src += indent * 2 + "}\n"
Done

2024-04-15 17:17 UTC, Shaikh-Ubaid commented on src/libasr/intrinsic_func_registry_util_gen.py
> +        src += indent * 3 + "}\n"
```suggestion
        src += indent * 3 +     "if (diag.has_error()) {\n"
        src += indent * 4 +         f"return nullptr;\n"
        src += indent * 3 +     "}\n"
```

2024-04-15 17:19 UTC, Shaikh-Ubaid approved these changes

2024-04-15 18:11 UTC, merged