Throw error for coarray and atomic intrinsics
lfortran/lfortran pull request #3888
Opened 2024-04-17 10:19 UTC by HarshitaKalani

Towards: https://github.com/lfortran/lfortran/issues/492#issuecomment-2044374861

2024-04-17 11:27 UTC, Pranavchiku commented on src/lfortran/semantics/ast_common_visitor.h
> +    void check_coarray_and_atomic_intrinsics(std::string intrinsic_name, const Location& loc){
```suggestion
    void is_coarray_or_atomic(std::string intrinsic_name, const Location& loc){
```

2024-04-17 11:27 UTC, Pranavchiku commented on src/lfortran/semantics/ast_common_visitor.h
> +        check_coarray_and_atomic_intrinsics(var_name, x.base.base.loc);
```suggestion
        is_coarray_or_atomic(var_name, x.base.base.loc);
```

2024-04-17 11:28 UTC, Pranavchiku approved these changes
Looks good thanks!

2024-04-17 11:30 UTC, Pranavchiku commented on src/lfortran/semantics/ast_common_visitor.h
> +        std::vector<std::string> coarray_intrinsics, atomic_intrinsics;
```suggestion
        std::vector<std::string> coarray_intrinsics;
```

I see no use of `atomic_intrinsics`, either split up current vector into two else we need to change error message.

2024-04-17 11:30 UTC, Pranavchiku commented on src/lfortran/semantics/ast_common_visitor.h
> +            throw SemanticError("Coarrays are not supported yet", loc);
Currently `coarray_intrinsics` consists of both `coarrays` and `atomic`, you will need to split it up and add error message for `atomic` as well.

2024-04-17 11:31 UTC, Pranavchiku commented on tests/errors/coarray_01.f90
> +end program test
add a test for atomic intrinsic as well

2024-04-17 11:31 UTC, Pranavchiku requested changes
Left few comments

2024-04-17 13:11 UTC, HarshitaKalani commented on src/lfortran/semantics/ast_common_visitor.h
> +        std::vector<std::string> coarray_intrinsics, atomic_intrinsics;
Oh right. I'll remove this. Thanks

2024-04-17 13:12 UTC, HarshitaKalani commented on src/lfortran/semantics/ast_common_visitor.h
> +            throw SemanticError("Coarrays are not supported yet", loc);
I thought we need to give error saying coarrays are not supported yet in case of atomic intrinsics as well, no?

2024-04-17 13:12 UTC, HarshitaKalani commented on src/lfortran/semantics/ast_common_visitor.h
> +            throw SemanticError("Coarrays are not supported yet", loc);
Or should the error be `atomic intrinsics are not supported yet in case of atomic ones`?

2024-04-18 05:35 UTC, certik commented
Perfect, thanks!

2024-04-19 04:41 UTC, Pranavchiku approved these changes

2024-04-19 04:41 UTC, merged