feat: implement sind intrinsic function
lfortran/lfortran pull request #3892
Opened 2024-04-17 13:24 UTC by parth121101

2024-04-17 14:03 UTC, Pranavchiku requested changes
Left comment above

2024-04-18 05:40 UTC, certik commented on src/libasr/runtime/lfortran_intrinsics.c
> +}
If we are going to use a macro style, wouldn't it make sense to instantiate this operation in ASR itself? That way we don't need to ship these simple runtime functions.

2024-04-18 21:11 UTC, kargl commented
As one of the individuals that worked on gfortran's implementation of the degree trig functions, I'll politely suggest that one might want to reconsider the implementation details.  Consider,

```
program foo
   implicit none
   integer n
   real x, y, z
   real, parameter :: pi = 4 * atan(1.)
   do n = 0, 10
      x = n * 360 + 30
      y = sind(x)
      z = sin((x * pi) / 180)
      print '(2(F10.7,1X,Z8.8,1X))', y, y, z, z
   end do
end program foo
```
    % gfcx -o z a.f90 && ./z
     0.5000000 3F000000  0.5000000 3F000000
     0.5000000 3F000000  0.5000005 3F000008
     0.5000000 3F000000  0.5000002 3F000004
     0.5000000 3F000000  0.5000008 3F00000D
     0.5000000 3F000000  0.4999997 3EFFFFF6
     0.5000000 3F000000  0.5000002 3F000004
     0.5000000 3F000000  0.4999992 3EFFFFE4
     0.5000000 3F000000  0.5000014 3F000017
     0.5000000 3F000000  0.5000036 3F00003C
     0.5000000 3F000000  0.4999992 3EFFFFE5
     0.5000000 3F000000  0.5000014 3F000018

2024-04-19 08:01 UTC, parth121101 commented on src/libasr/pass/intrinsic_functions.h
> +    }
@Pranavchiku, I tried creating the macro for this kind of function. The results that the function returns does not match with the gfortran. Can you please review it and let me know the problem?

2024-04-19 14:12 UTC, Pranavchiku commented on src/libasr/asr_builder.h
> +    }
This is not what we want, you need to create something similar to `create_trig`, you may refer it.

2024-04-19 14:15 UTC, Pranavchiku commented
> As one of the individuals that worked on gfortran's implementation of the degree trig functions, I'll politely suggest that one might want to reconsider the implementation details. Consider,
> 
> ```
> program foo
>    implicit none
>    integer n
>    real x, y, z
>    real, parameter :: pi = 4 * atan(1.)
>    do n = 0, 10
>       x = n * 360 + 30
>       y = sind(x)
>       z = sin((x * pi) / 180)
>       print '(2(F10.7,1X,Z8.8,1X))', y, y, z, z
>    end do
> end program foo
> ```
> 
>  ```
> % gfcx -o z a.f90 && ./z
>  0.5000000 3F000000  0.5000000 3F000000
>  0.5000000 3F000000  0.5000005 3F000008
>  0.5000000 3F000000  0.5000002 3F000004
>  0.5000000 3F000000  0.5000008 3F00000D
>  0.5000000 3F000000  0.4999997 3EFFFFF6
>  0.5000000 3F000000  0.5000002 3F000004
>  0.5000000 3F000000  0.4999992 3EFFFFE4
>  0.5000000 3F000000  0.5000014 3F000017
>  0.5000000 3F000000  0.5000036 3F00003C
>  0.5000000 3F000000  0.4999992 3EFFFFE5
>  0.5000000 3F000000  0.5000014 3F000018
> ```

We expected divergence at higher precision but this is something concerning ( 1e-7 ). I'll be happy to get your input on how shall we proceed to implement this and resolve this divergence.

We faced something similar at #3894.

2024-04-19 16:22 UTC, kargl commented
> > As one of the individuals that worked on gfortran's implementation of the degree trig functions, I'll politely suggest that one might want to reconsider the implementation details. Consider,

(program elided)

> > ```
> > % gfcx -o z a.f90 && ./z
> > 0.5000000 3F000000  0.5000000 3F000000
>> (elided)
> > 0.5000000 3F000000  0.5000014 3F000018
> > ```
> 
> We expected divergence at higher precision but this is something concerning ( 1e-7 ). I'll be happy to get your input on how shall we proceed to implement this and resolve this divergence.
> 
> We faced something similar at #3894.

Within `sind(n*360 + 30)`, the result is exactly 0.5.  In principle, no exception should be raised, but I don't remember if we worried about that detail with gfortran.   FE_INEXACT may have occurred.   There are other special cases such as `sind(n*360+90) = 1` exactly.  Similar statements hold for the other degree trig functions.

First, one needs to use reflection symmetry so `s = x > 0 ? 1:-1; ax = abs(x)`.  Before returning the computed value, you look at `s` to adjust the sign.   This guarantees reflection symmetry holds in the face of floating pointing arithmetic.

What then needs to be done is argument reduction, $ax = n * 360 + r$, with $r$ in [0,360).  Now, you work with `r`.   First, check for special cases, then fold `r` in [0,360) into `a` in [0,45] with appropriate trig identities.  The last step is the conversion of `a` into radians, but you cannot use `b = a * pi / 180` as rounding issues can arise.  First, compute `pi / 180 = hi + lo` with `hi` the leading `digits(x)/2`  bits and  `lo` is `digits(x)` trailing bits.  So, `b = a*lo + b*hi`

2024-04-20 09:05 UTC, Pranavchiku commented
I opened a dedicated issue https://github.com/lfortran/lfortran/issues/3912 for this.

2024-04-23 04:49 UTC, Pranavchiku commented
This PR can be closed with reference to #3914

2024-04-23 04:49 UTC, closed without merging