Create macros for math functions
lfortran/lfortran pull request #3914
Opened 2024-04-21 08:52 UTC by parth121101

Fixes: #3912

2024-04-21 08:53 UTC, parth121101 commented
Tests for Intrinsic_211.f90 file fails in my device.

2024-04-21 15:18 UTC, Pranavchiku commented on src/libasr/pass/intrinsic_functions.h
> +    }
We don't need this, it can be handled directly via python script.

2024-04-21 15:18 UTC, Pranavchiku commented on src/libasr/intrinsic_func_registry_util_gen.py
> -    ],
register this, we need this as stated in comment above

2024-04-21 15:18 UTC, Pranavchiku commented on src/libasr/pass/intrinsic_function_registry.h
> +            {&BesselJ0::instantiate_BesselJ0, &UnaryMathIntrinsicFunction::verify_args}},
```suggestion
        {static_cast<int64_t>(IntrinsicElementalFunctions::BesselJ0),
            {&BesselJ0::instantiate_BesselJ0, &BesselJ0::verify_args}},
```
and similar changes

2024-04-21 15:23 UTC, Pranavchiku commented on src/libasr/pass/intrinsic_functions.h
> +namespace UnaryMathIntrinsicFunction{
```suggestion
namespace MathIntrinsicFunction{
```

2024-04-21 15:24 UTC, Pranavchiku commented on src/libasr/pass/intrinsic_functions.h
> +                body_1, return_var_1, ASR::abiType::BindC, ASR::deftypeType::Interface, s2c(al, c_func_name));
```suggestion
ASR::symbol_t *s = b.create_c_func(c_func_name, fn_symtab, return_type, arg_types.size(), arg_types);
```

2024-04-21 15:24 UTC, Pranavchiku commented on src/libasr/pass/intrinsic_functions.h
> +    static inline ASR::asr_t* create_UnaryMathFunction(Allocator& al, const Location& loc,
```suggestion
    static inline ASR::asr_t* create_MathFunction(Allocator& al, const Location& loc,
```

Perform this change at required places

2024-04-21 15:25 UTC, Pranavchiku commented on src/libasr/pass/intrinsic_functions.h
> +    static inline ASR::asr_t* create_UnaryMathFunction(Allocator& al, const Location& loc,
we don't need this

2024-04-21 15:25 UTC, Pranavchiku commented on src/libasr/pass/intrinsic_functions.h
> +    }                                                                                                   \
you can remove this

2024-04-21 15:26 UTC, Pranavchiku commented on src/libasr/pass/intrinsic_functions.h
> +#define create_math_bindc(math_func, stdeval, intermediate, new_name, lcompilers_name)                  \
```suggestion
#define create_math_bindc(math_func, stdeval, radian, new_name, lcompilers_name)                  \
```

2024-04-21 15:28 UTC, Pranavchiku commented on src/libasr/pass/intrinsic_functions.h
> +        double result = stdeval(i) * 180.0 / PI;                                                        \
```suggestion
        double rv = ASR::down_cast<ASR::RealConstant_t>(args[0])->m_r;                                         \
        double val = stdeval(rv);                                                                       \
        if(intermediate == 1){                                                                          \
        double result = rv * 180.0 / PI;                                                        \
        }                                                                                               \
```

2024-04-21 15:31 UTC, Pranavchiku requested changes
This PR is headed in correct direction, requested changes below.

2024-04-21 18:48 UTC, Pranavchiku commented on src/libasr/pass/intrinsic_functions.h
> +#define create_math_bindc(math_func, stdeval, degree, new_name, lcompilers_name)                        \
```suggestion
#define create_math_bindc(math_func, stdeval, degree, lcompilers_name)                        \
```

2024-04-21 18:48 UTC, Pranavchiku commented on src/libasr/pass/intrinsic_functions.h
> +create_math_bindc(Atand, atan, 1, atand, atand)
```suggestion
create_math_bindc(BesselJ0, j0, 0, bessel_j0)
create_math_bindc(BesselJ1, j1, 0, bessel_j1)
create_math_bindc(BesselY0, y0, 0, bessel_y0)
create_math_bindc(BesselY1, y1, 0, bessel_y1)
create_math_bindc(Asind, asin, 1, asind)
create_math_bindc(Acosd, acos, 1, acosd)
create_math_bindc(Atand, atan, 1, atand)
```

2024-04-21 18:49 UTC, Pranavchiku requested changes
Left comment above, otherwise this is good.

2024-04-22 08:56 UTC, Pranavchiku approved these changes

2024-04-22 09:07 UTC, merged

2024-04-22 16:40 UTC, certik commented
Perfect, thanks for the refactoring.

2024-04-22 16:41 UTC, certik commented on src/libasr/pass/intrinsic_functions.h
> +        }                                                                                               \
This is a runtime if, however I am guessing the compiler will optimize it out if `degree` is 0. There might be a way to make the if compile time, but for now it's good.