Compile time handling of character len
lfortran/lfortran pull request #4064
Opened 2024-05-22 15:55 UTC by shivimathur

Fix : https://github.com/lfortran/lfortran/issues/3980 for adjustl and adjustr.

2024-05-23 00:35 UTC, certik approved these changes

2024-05-23 06:32 UTC, HarshitaKalani requested changes

2024-05-23 06:32 UTC, HarshitaKalani commented on integration_tests/intrinsics_134.f90
> +
```suggestion
    if (y /= "okay") error stop
```

2024-05-23 06:32 UTC, HarshitaKalani commented on integration_tests/intrinsics_177.f90
> +
```suggestion
    if (y /= "okay") error stop
```

2024-05-23 06:32 UTC, HarshitaKalani commented on src/libasr/intrinsic_func_registry_util_gen.py
>      "Aint": [
Thanks for this. Can you also do the same for `New_line`?

2024-05-24 05:48 UTC, shivimathur commented on src/libasr/intrinsic_func_registry_util_gen.py
> +            "ret_type_arg_idx": 0
I think the problem lies in
 ```fortran 
 character(len=1), parameter :: nl = new_line(' ')
 ```

2024-05-25 03:50 UTC, Shaikh-Ubaid commented on src/libasr/intrinsic_func_registry_util_gen.py
> +            "ret_type_arg_idx": 0
>I think the problem lies in

Sorry, I didn't get you. What is the problem here?

2024-05-25 12:23 UTC, Shaikh-Ubaid commented
Need clarification on this https://github.com/lfortran/lfortran/pull/4064#discussion_r1614316198. When this is ready, please mark as "Ready for review".

2024-05-27 03:45 UTC, shivimathur commented on src/libasr/intrinsic_func_registry_util_gen.py
> +            "ret_type_arg_idx": 0
This is the error generated during CI testing : 
```fortran 
CMakeFiles/intrinsics_218.dir/intrinsics_218.f90.o.tmp.f90:4:45:

    4 | character(len=1, kind=1), parameter :: nl = "
      |                                             1
Error: Unterminated character constant beginning at (1)
The command 'gfortran -fno-backtrace -o CMakeFiles/intrinsics_218.dir/intrinsics_218.f90.o -c CMakeFiles/intrinsics_218.dir/intrinsics_218.f90.o.tmp.f90' failed.
CMakeFiles/intrinsics_218.dir/intrinsics_218.f90.o.tmp.f90:5:1:

    5 | "
      | 1
Error: Invalid character in name at (1)
CMakeFiles/intrinsics_218.dir/intrinsics_218.f90.o.tmp.f90:7:6:

    7 | if (nl /= char(10)) then
      |      1
Error: Symbol ‘nl’ at (1) has no IMPLICIT type
```

So, is there some mistake in 
```fortran
 character(len=1), parameter :: nl = new_line(' ')
```

2024-05-27 04:44 UTC, Shaikh-Ubaid commented on src/libasr/intrinsic_func_registry_util_gen.py
> +            "ret_type_arg_idx": 0
```console
% cat examples/expr2.f90 
program expr2
implicit none

character(len=1), parameter :: nl = new_line(' ')
print *, "ok"

end program
% gfortran examples/expr2.f90
% ./a.out 
 ok
```
I think the issue is not in ` character(len=1), parameter :: nl = new_line(' ')`, but in our `asr_to_fortran` backend which does not handle the `new_line(' ')` properly.
```console
% cat examples/expr2.f90 
program expr2
    implicit none

    character(len=1), parameter :: nl = new_line(' ')

end program
% lfortran_in_main examples/expr2.f90 --show-fortran
program expr2
implicit none
character(len=1, kind=1), parameter :: nl = "
"
end program expr2
```

2024-05-29 18:25 UTC, Shaikh-Ubaid commented on integration_tests/CMakeLists.txt
> +RUN(NAME intrinsics_237 LABELS gfortran llvm llvm_wasm llvm_wasm_emcc) #new_line
```suggestion
RUN(NAME intrinsics_237 LABELS gfortran llvm llvm_wasm llvm_wasm_emcc) # new_line
```

2024-05-29 18:25 UTC, Shaikh-Ubaid commented on src/libasr/codegen/asr_to_fortran.cpp
> +        }
It seems for every `"\n"` string this will represent it as a `char(10)` which does not look right. I think `--show-fortran` should just print the generated fortran code as `character(len=1), parameter :: nl = new_line(' ')`.

The idea of the `fortran` backend is to generate fortran from our ASR which is close (or as close as possible) to the original user source code

2024-05-29 18:46 UTC, shivimathur commented on src/libasr/codegen/asr_to_fortran.cpp
> +        }
I think we can implement the suggested changes if we give more priority to ``` m_symbolic_value ``` over ```m_value```
``` fortran
diff --git a/src/libasr/codegen/asr_to_fortran.cpp b/src/libasr/codegen/asr_to_fortran.cpp
index 37ca4c21e..d35eb189b 100644
--- a/src/libasr/codegen/asr_to_fortran.cpp
+++ b/src/libasr/codegen/asr_to_fortran.cpp
@@ -678,15 +678,16 @@ public:
             r += " = ";
             visit_expr(*x.m_symbolic_value);
             r += src;
-        } else if (x.m_value) {
-            r += " = ";
-            visit_expr(*x.m_value);
-            r += src;
         } else if (x.m_symbolic_value) {
             r += " = ";
             visit_expr(*x.m_symbolic_value);
             r += src;
         }
+        else if (x.m_value) {
+            r += " = ";
+            visit_expr(*x.m_value);
+            r += src;
+        }
         r += "\n";
         src = r;
     } 
```

2024-05-29 18:50 UTC, Shaikh-Ubaid commented on src/libasr/codegen/asr_to_fortran.cpp
> +        }
The updated priority seems fine to me.

2024-05-30 07:57 UTC, shivimathur commented on src/libasr/codegen/asr_to_fortran.cpp
> +        }
I think the failure might be because real is not implemented as an intrinsic function yet.

2024-06-01 17:24 UTC, certik commented
@HarshitaKalani, @Shaikh-Ubaid can you please review it? It looks good to me.

2024-06-01 17:25 UTC, certik commented
There are some failures in the Fortran printer it seems:
```
[ 23%] Building Fortran object CMakeFiles/intrinsics_11.dir/intrinsics_11.f90.o
CMakeFiles/intrinsics_11.dir/intrinsics_11.f90.o.tmp.f90:73:25:

   73 | real(4), parameter :: y = real(x, kind=4)
      |                         1
Error: Function ‘real’ in initialization expression at (1) must be an intrinsic function
CMakeFiles/intrinsics_11.dir/intrinsics_11.f90.o.tmp.f90:74:10:

   74 | print *, y
      |          1
Error: Symbol ‘y’ at (1) has no IMPLICIT type
The command 'gfortran -fno-backtrace -o CMakeFiles/intrinsics_11.dir/intrinsics_11.f90.o -c CMakeFiles/intrinsics_11.dir/intrinsics_11.f90.o.tmp.f90' failed.
```
@shivimathur I'll mark this as draft, once this is fixed, go ahead and click on "Ready to review"

2024-06-03 11:17 UTC, HarshitaKalani reviewed
The issue in the tests arises because the real function defined in the lfortran_intrinsic_builtin module is being used in an initialization expression, but it is not an intrinsic function in that context. The Fortran standard requires that only intrinsic functions can be used in initialization expressions for constants.

I've opened an issue for this: https://github.com/lfortran/lfortran/issues/4139

2024-06-03 11:17 UTC, HarshitaKalani commented on src/libasr/codegen/asr_to_fortran.cpp
>      }
As of now, just revert this change and do not add fortran label with the added test.

2024-06-04 06:55 UTC, shivimathur commented on src/libasr/codegen/asr_to_fortran.cpp
>      }
If we revert these changes, and still keep the test for new_line, we will have to do special handling for it as shown in the diff : 
``` fortran
diff --git a/src/libasr/codegen/asr_to_fortran.cpp b/src/libasr/codegen/asr_to_fortran.cpp
index 2ea1aab4f..99430d860 100644
--- a/src/libasr/codegen/asr_to_fortran.cpp
+++ b/src/libasr/codegen/asr_to_fortran.cpp
@@ -1691,6 +1691,11 @@ public:
     }
 
     void visit_StringConstant(const ASR::StringConstant_t &x) {
+        if (strcmp(x.m_s, "\n") == 0) {
+            src.append("char(10)");
+            last_expr_precedence = Precedence::Ext;
+            return;
+        }
         src = "\"";
         src.append(x.m_s);
         src += "\"";
```

This is only a temporary fix to get all the tests pass. Do you think its better if we first fix https://github.com/lfortran/lfortran/issues/4139 and then work on new_line?

2024-06-07 18:57 UTC, certik approved these changes
I think that this looks good to me. Thanks!

2024-06-07 18:58 UTC, merged