Throw error when an argument of incorrect length is passed to `ichar` and `iachar`
lfortran/lfortran pull request #4123
Opened 2024-05-31 07:02 UTC by kmr-srbh

fixes #3734 

## Compile-time
### ichar
```fortran
program main
   print*, ichar("Hello")
end program
```
```console
(lf) saurabh-kumar@Awadh:~/Projects/System/lfortran$ gfortran ./examples/example.f90 && ./a.out
./examples/example.f90:2:17:

    2 |    print*, ichar("Hello")
      |                 1
Error: Argument of ICHAR at (1) must be of length one
(lf) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
semantic error: first argument to `ichar` must be of length one
 --> ./examples/example.f90:2:18
  |
2 |    print*, ichar("Hello")
  |                  ^^^^^^^ 

Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

### iachar
```fortran
program main
   print*, iachar("Hello")
end program
```
```console
(lf) saurabh-kumar@Awadh:~/Projects/System/lfortran$ gfortran ./examples/example.f90 && ./a.out
./examples/example.f90:2:18:

    2 |    print*, iachar("Hello")
      |                  1
Error: Argument of IACHAR at (1) must be of length one
(lf) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
semantic error: first argument to iachar must be of length one
 --> ./examples/example.f90:2:19
  |
2 |    print*, iachar("Hello")
  |                   ^^^^^^^ 

Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

## Runtime
### ichar
```fortran
program main
   character(len=5) :: c = "Hello"
   print*, ichar(c)
end program
```
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ gfortran ./examples/example.f90 && ./a.out
./examples/example.f90:3:17:

    3 |    print*, ichar(c)
      |                 1
Error: Argument of ichar at (1) must be of length one
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
Error: first argument to ichar must be of length one
```

### iachar
```fortran
program main
   character(len=5) :: c = "Hello"
   print*, iachar(c)
end program
```
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ gfortran ./examples/example.f90 && ./a.out
./examples/example.f90:3:18:

    3 |    print*, iachar(c)
      |                  1
Error: Argument of iachar at (1) must be of length one
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
Error: first argument to iachar must be of length one
```

## Allocatable strings
Allocatable strings are handled specially by GFortran. We do the same here.
```fortran
program main
   character(len=:), allocatable :: c
   allocate(character(len=10) :: c)
   c = "Hello"
   print*, iachar(c)
end program
```
```console
(lf) saurabh-kumar@Awadh:~/Projects/System/lfortran$ gfortran ./examples/example.f90 && ./a.out
          72
(lf) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
72
```

2024-05-31 07:03 UTC, kmr-srbh commented
This PR is the updated version of #4011.

2024-06-01 05:57 UTC, Pranavchiku commented on src/libasr/codegen/asr_to_llvm.cpp
> +        if (!ASRUtils::is_allocatable(ASRUtils::expr_type(x.m_arg))) {
I do not think we need to do any change in asr to llvm.

2024-06-01 06:02 UTC, kmr-srbh commented on src/libasr/codegen/asr_to_llvm.cpp
> +        if (!ASRUtils::is_allocatable(ASRUtils::expr_type(x.m_arg))) {
Oh. Could you please tell me how do we handle runtime values? I thought it was done here. GFortran throws an error for this.

2024-06-01 06:27 UTC, Pranavchiku requested changes
I think this is the way to do it:

```diff
diff --git a/src/lfortran/semantics/ast_common_visitor.h b/src/lfortran/semantics/ast_common_visitor.h
index 1322248c2..f03c66ac7 100644
--- a/src/lfortran/semantics/ast_common_visitor.h
+++ b/src/lfortran/semantics/ast_common_visitor.h
@@ -5155,6 +5155,13 @@ public:
         ASR::ttype_t *type = ASRUtils::TYPE(ASR::make_Integer_t(al, x.base.base.loc, kind_value));
         ASR::expr_t* iachar_value = nullptr;
         ASR::expr_t* arg_value = ASRUtils::expr_value(arg);
+        ASR::ttype_t* arg_type = ASRUtils::expr_type(arg);
+        LCOMPILERS_ASSERT(ASR::is_a<ASR::Character_t>(*arg_type));
+        ASR::Character_t* char_type = ASR::down_cast<ASR::Character_t>(arg_type);
+        if (char_type->m_len != 1) {
+            throw SemanticError("Argument of `iachar` intrinsic must be a character of length 1",
+                                x.base.base.loc);
+        }
         if( arg_value ) {
             std::string arg_str;
             bool is_const_value = ASRUtils::is_value_constant(arg_value, arg_str);
diff --git a/src/libasr/asr_utils.h b/src/libasr/asr_utils.h
index 909063c14..279075388 100644
--- a/src/libasr/asr_utils.h
+++ b/src/libasr/asr_utils.h
@@ -2076,6 +2076,12 @@ static inline bool is_character(ASR::ttype_t &x) {
                 type_get_past_pointer(&x))));
 }
 
+static inline bool is_character_of_length(ASR::ttype_t &x, int length) {
+    return is_character(x) && ASR::down_cast<ASR::Character_t>(type_get_past_array(
+                                type_get_past_allocatable(
+                                    type_get_past_pointer(&x))))->m_len == length;
+}
+
 static inline bool is_complex(ASR::ttype_t &x) {
     return ASR::is_a<ASR::Complex_t>(
         *type_get_past_array(
diff --git a/src/libasr/intrinsic_func_registry_util_gen.py b/src/libasr/intrinsic_func_registry_util_gen.py
index bf463fa07..aa49c30ef 100644
--- a/src/libasr/intrinsic_func_registry_util_gen.py
+++ b/src/libasr/intrinsic_func_registry_util_gen.py
@@ -714,7 +714,7 @@ intrinsic_funcs_args = {
     ],
     "Ichar": [
         {
-            "args": [("char",)],
+            "args": [(("char", 1),)],
             "return": "int32",
             "kind_arg": True
         },
@@ -823,8 +823,13 @@ def compute_arg_condition(no_of_args, args_lists):
         subcond_in_msg = []
         for i in range(no_of_args):
             arg = arg_list[i]
-            subcond.append(f"{type_to_asr_type_check[arg]}(*arg_type{i})")
-            subcond_in_msg.append(arg)
+            if (type(arg) == tuple):
+                subcond.append(f"{type_to_asr_type_check[arg[0]]}(*arg_type{i})")
+                subcond.append(f"ASRUtils::is_character_of_length(*arg_type{i}, {arg[1]})")
+                subcond_in_msg.append(arg[0] + " of length " + str(arg[1]))
+            else:
+                subcond.append(f"{type_to_asr_type_check[arg]}(*arg_type{i})")
+                subcond_in_msg.append(arg)
         condition.append(" && ".join(subcond))
         cond_in_msg.append(", ".join(subcond_in_msg))
     return (f"({') || ('.join(condition)})", f"({') or ('.join(cond_in_msg)})")
```

Concept is to check type of argument that it is character of length 1. For `Iachar`, we can simply do, but for `Ichar` some tweaks in python script will be required.

Go ahead apply the diff and check if everything works.

Edit:

This won't be complete solution, I think some strict checking is also required especially for `Iachar` that you'll need to work on. For example:

```console
semantic error: Argument of `iachar` intrinsic must be a character of length 1
 --> /Users/pranavchiku/repos/lfortran/integration_tests/string_28.f90:6:18
  |
6 |     char_value = IACHAR(calibration_document(3)(len_line:len_line))
  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
make[2]: *** [CMakeFiles/string_28.dir/build.make:75: CMakeFiles/string_28.dir/string_28.f90.o] Error 1
```

This should not throw error but it is, so go ahead check ASR and figure out what needs to be done.

2024-06-01 06:28 UTC, Pranavchiku commented
> The integration test `intrinsics_60` fails with the changes in this PR. It requires #4021 to be merged. Please see [#4011 (comment)](https://github.com/lfortran/lfortran/pull/4011#issuecomment-2115584234).

I am not sure why we need it for this PR, can you please brief?

2024-06-01 06:49 UTC, kmr-srbh commented
> > The integration test `intrinsics_60` fails with the changes in this PR. It requires #4021 to be merged. Please see [#4011 (comment)](https://github.com/lfortran/lfortran/pull/4011#issuecomment-2115584234).
> 
> I am not sure why we need it for this PR, can you please brief?

Actually for the integration test `intrinsics_60`, we require reading from a file. As it turns out, the `read()` function had been malfunctioning before. The changes in this PR require the passed string to have a length of 1, but the `read` function had been returning incorrect values for special characters. As we enforced length check in this PR, the test failed.

### GFortran
```console
(lf) saurabh-kumar@Awadh:~/Projects/System/lfortran/integration_tests$ gfortran intrinsics_60.f90
(lf) saurabh-kumar@Awadh:~/Projects/System/lfortran/integration_tests$ ./a.out
 aZ��
           1
           1
           1
           1
          97          90         195         194
```

### LFortran
```console
(lf) saurabh-kumar@Awadh:~/Projects/System/lfortran/integration_tests$ lfortran intrinsics_60.f90
aZ��
1
1
2
2
97 90 195 194
```

### CI output
```console
 299/981 Test #299: intrinsics_60 ............................***Failed    0.01 sec
aZÿ©
Error: first argument to iachar must be of length one
```

2024-06-01 07:44 UTC, kmr-srbh commented
Thanks a lot @Pranavchiku! The diff works. I will push the complete changes after fixing the errors that arise. :+1:

2024-06-01 08:24 UTC, kmr-srbh commented
@Pranavchiku I analyzed the cause of the issue in https://github.com/lfortran/lfortran/pull/4123#pullrequestreview-2092031275. The ASR node here is a `StringSection_t`. All of it's operands are runtime values. 
```clojure
(Assignment
    (Var 2 char_value)
    (Iachar
        (StringSection
            (ArrayItem
                (Var 2 calibration_document)
                [(()
                (IntegerConstant 3 (Integer 4))
                ())]
                (Character 1 100 ())
                ColMajor
                ()
            )
            (IntegerBinOp
                (Var 2 len_line)
                Sub
                (IntegerConstant 1 (Integer 4))
                (Integer 4)
                ()
            )
            (Var 2 len_line)
            (IntegerConstant 1 (Integer 4))
            (Character 1 100 ())
            ()
        )
        (Integer 4)
        ()
    )
    ()
)
```

It is not evaluated at compile time hence we do not get the final slice of the string. The character type here is `(Character 1 100 ())` leading to the length of `100` and hence the `semantic error`.

I think we cannot handle this at compile-time, can we? I would love to hear your ideas.

2024-06-01 21:28 UTC, certik commented
Here is the Fortran code that generates the above:
```fortran


program string_28
    CHARACTER(100), DIMENSION(100) :: calibration_document
    INTEGER ::len_line, char_value
    calibration_document(3) = 'abc'
    len_line = 1
    char_value = IACHAR(calibration_document(3)(len_line:len_line))
    print *, char_value
    if (char_value /= 97) error stop
end program
```
In here, the `calibration_document` is not compile time, so is `len_line`, so we only know the values and slice range at runtime.

The length of the string should not be 100, but rather `len_line - len_line + 1`, which is 1 in this case. I think. So that has to be fixed.

2024-06-02 06:49 UTC, Pranavchiku commented
Well even gfortran do not throw error for the following case:

```fortran

program string_28
    CHARACTER(100), DIMENSION(100) :: calibration_document
    INTEGER ::len_line, char_value
    calibration_document(3) = 'abc'
    len_line = 1
    char_value = IACHAR(calibration_document(3)(len_line:len_line+4))
    print *, char_value
    if (char_value /= 97) error stop
end program
```

```console
% gfortran a.f90 && ./a.out
          97
```

Ideally it should, so do a special handling for these type of values.

2024-06-02 07:15 UTC, kmr-srbh commented
> Ideally it should, so do a special handling for these type of values.

@Pranavchiku I could not get this. Why should it have thrown an error? The final sliced string is of length 1 at runtime.

2024-06-02 08:06 UTC, kmr-srbh commented
@Pranavchiku this PR is now ready. All tThe tests pass locally, hopefully they should not pass here too. Thank you very much for your help! :)

2024-06-02 08:06 UTC, kmr-srbh commented
@Pranavchiku this PR is now ready. All tThe tests pass locally, hopefully they should not pass here too. Thank you very much for your help! :)

2024-06-02 08:08 UTC, Pranavchiku commented on src/libasr/pass/intrinsic_functions.h
> +        }
Why do we need this? It will be already handled in `create_Ichar`

2024-06-02 08:10 UTC, kmr-srbh commented on src/libasr/pass/intrinsic_functions.h
> +        }
Right. I overlooked this, as the generated script has it's own error message. I am removing this. I think there will be a slight disparity in the error messages?

2024-06-02 08:13 UTC, Pranavchiku commented on src/libasr/pass/intrinsic_functions.h
> +        }
You just need to revert this change, unless something breaks and you have valid reason to keep it.

2024-06-02 08:46 UTC, kmr-srbh commented
A test for `stdlib` fails. I am looking into it in a while.

2024-06-04 12:40 UTC, kmr-srbh commented
The issue with the failure in `stdlib` test was that we had forgotten to handle `StringSection_t` for `ichar`. With the latest commit, we now handle it along with `allocatable` strings.

Here is an MRE which has previously failed, but now passes:
```fortran
program example

   type :: MyType
      character(len=10) :: raw
   end type MyType

   type(MyType) :: string

   string%raw = "HelloWorld"
   print *, ichar(string%raw(1:1))

end program
```
```console
(lf) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
72
```

2024-06-04 12:43 UTC, kmr-srbh commented
As we are using a common generator script for all the intrinsics, I had to handle the case of `ichar` manually. @Pranavchiku could you please see if this is the right way to do it? Suggestions for improvement are more than welcome.

2024-06-04 14:35 UTC, kmr-srbh commented
> We have to be very careful. Let's not throw errors unless GFortran throws it.
> 
> In general, if it is complicated, let's focus on valid code until beta. After beta we'll fix all corner cases that should throw an error.

You are right @certik! For now, I am going to focus on SNAP and defer error messages until we reach beta.

As for this PR, we follow the behavior of GFortran for throwing errors. It is a bit weird as some expected cases do not throw an error. We handle them specially.

2024-06-09 04:39 UTC, certik commented on src/libasr/intrinsic_func_registry_util_gen.py
> +            condition = "ASR::is_a<ASR::StringSection_t>(*x.m_args[0]) || ASRUtils::is_allocatable(arg_type0) || " + condition
Let's not hardwire here anything that is function specific. Let's add an option to the function list above and just act based on an option here.

2024-06-09 04:39 UTC, certik commented on src/libasr/intrinsic_func_registry_util_gen.py
> +            src += 3 * indent + f'if(!({condition}))' + ' {\n'
Same here.

2024-06-09 04:40 UTC, certik commented
Is it giving a runtime error as well if you pass in a string that is longer than 1?

2024-06-09 06:38 UTC, kmr-srbh commented
> Is it giving a runtime error as well if you pass in a string that is longer than 1?

Yes it does. GFortran has similar behavior, except for allocatable strings. We do the same here.

2024-06-09 06:41 UTC, kmr-srbh commented on src/libasr/intrinsic_func_registry_util_gen.py
> +                subcond.append(f"ASRUtils::is_character_of_length(*arg_type{i}, {arg[1]})")
Yes.

2024-06-09 06:43 UTC, kmr-srbh commented on src/libasr/intrinsic_func_registry_util_gen.py
> +            condition = "ASR::is_a<ASR::StringSection_t>(*x.m_args[0]) || ASRUtils::is_allocatable(arg_type0) || " + condition
Couldn't get this. Option like? Do you mean something like - "skip string section"?

2024-06-09 06:48 UTC, kmr-srbh commented on src/libasr/intrinsic_func_registry_util_gen.py
> +            condition = "ASR::is_a<ASR::StringSection_t>(*x.m_args[0]) || ASRUtils::is_allocatable(arg_type0) || " + condition
Do you mean handling `StringSection_t` and `Allocatable_t` as an `arg`? This can be done.

2024-06-09 17:18 UTC, certik commented on src/libasr/intrinsic_func_registry_util_gen.py
> +            condition = "ASR::is_a<ASR::StringSection_t>(*x.m_args[0]) || ASRUtils::is_allocatable(arg_type0) || " + condition
What I mean is to add some more flags / variables here:
```
    "Ichar": [
        {
            "args": [("char",)],
            "args": [(("char", 1), )],
            "return": "int32",
            "kind_arg": True
        },
```
And then act based on that in here, so instead of `if (func_name == "Ichar"):`, you do something like `if (some_condition...)`.

Can you explain what the above line is doing --- why is it needed?

2024-06-09 17:26 UTC, kmr-srbh commented on src/libasr/intrinsic_func_registry_util_gen.py
> +            condition = "ASR::is_a<ASR::StringSection_t>(*x.m_args[0]) || ASRUtils::is_allocatable(arg_type0) || " + condition
> Can you explain what the above line is doing --- why is it needed?

It is required because GFortran handles them specially. It does not throw an error when we have an allocatable string of length greater than 1. Same is the case when a string section is passed.

2024-06-09 17:41 UTC, certik commented on src/libasr/intrinsic_func_registry_util_gen.py
> +            condition = "ASR::is_a<ASR::StringSection_t>(*x.m_args[0]) || ASRUtils::is_allocatable(arg_type0) || " + condition
Ok. Let's do the following. The standard distinguishes STRING and C (just one character). For example:

```
ADJUSTL (STRING) E Left-justified string value.
ICHAR (C [, KIND]) E Code value for character.
```
So we need to distinguish these two cases as well.

Let's rename "char" to a "string" if it is expecting a full string.

Let's use "char" for exactly one character. You can remove the "(char,1)" tuple, I don't think we'll need it.

Then for "string", you do the current handling. For "char" you do the special handling.

Can the above condition `if (func_name == "Ichar")` be changed to `if (arg == "char")`?

2024-08-25 05:22 UTC, closed without merging