Fix `Var_t` expression equality check
lfortran/lfortran pull request #4135
Opened 2024-06-03 07:52 UTC by kmr-srbh

fixes #4131 

### The issue
The chief cause of the issue was the check for comparing equality of `Var_t` expressions. We had been checking if two `Var_t` expressions were equal by checking if their symbols were equal. This comparison was not correct and always returned `false`, hence leading the compiler to believe that the argument passed to the subroutine did not match the parameter type. 

Here is the debug comment output for the MRE:

```fortran
MODULE thrd_comm_module
   INTERFACE precv
      MODULE PROCEDURE precv_d_3d
   END INTERFACE precv

CONTAINS

   SUBROUTINE precv_d_3d ( value, nx )

      REAL, DIMENSION(nx), INTENT(IN) :: value

      INTEGER, INTENT(IN) ::  nx

   END SUBROUTINE precv_d_3d

   SUBROUTINE sweep_recv_bdry ( nz )

      REAL, DIMENSION(nz):: jb_in

      INTEGER, INTENT(IN) ::  nz

      CALL precv ( jb_in, nz )

   END SUBROUTINE sweep_recv_bdry

END MODULE thrd_comm_module
```
```console
(lf) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran -c ./examples/example.f90
n_args: 2
procedure name: precv
p.n_procs: 1
else
is function
args.size(): 2
sub.n_args: 2
type1 real[:]
type2: real[:]
is array
n_dims_a: 1
n_dims_b: 1
x->type: integer
y->type: integer
var
var_x->m_v: nz
var_y->m_v: nx
expr not equal
types not equal
semantic error: Arguments do not match for any generic procedure, precv
  --> ./examples/example.f90:22:7
   |
22 |       CALL precv ( jb_in, nz )
   |       ^^^^^^^^^^^^^^^^^^^^^^^^ 

Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

### The fix
We fix this by comparing `ASR::exprType` of the `Var_t` expressions to see if they are equal.

```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran -c ./examples/example.f90
n_args: 2
procedure name: precv
p.n_procs: 1
else
is function
args.size(): 2
sub.n_args: 2
type1 real[:]
type2: real[:]
is array
n_dims_a: 1
n_dims_b: 1
x->type: integer
y->type: integer
var
var_x->m_v type: integer
var_y->m_v type: integer
dim_a_int: 1
dim_b_int: 1
type1 integer
type2: integer
```

With the fix in place we are now successfully able to compile the file `thrd_comm.f90` of the SNAP package.

```console
(base) saurabh-kumar@Awadh:~/Projects/Packages/SNAP/src$ lfortran -c thrd_comm.f90
(base) saurabh-kumar@Awadh:~/Projects/Packages/SNAP/src$
```

2024-06-03 08:44 UTC, Pranavchiku commented
Let's get CI all passed.

2024-06-03 09:29 UTC, kmr-srbh commented
@Pranavchiku the cause of failure here is a warning being treated as error on macOS with the AppleClang compiler I see that a proposal for supporting the above warning in GCC is open [here](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70181).

When the expression types are equal, it will essentially be a self-comparison, right? Could you suggest any ideas to bypass this, or do this in a better way?

2024-06-03 18:31 UTC, Pranavchiku commented on src/libasr/asr_utils.h
> +            return var_x->class_type == var_y->class_type;
```suggestion
            return ASRUtils::types_equal(var_x->class_type, var_y->class_type);
```

We do not compare types like this, refer `ASRUtils::types_equal` .

2024-06-03 18:31 UTC, Pranavchiku requested changes
left a comment above.

2024-06-03 19:15 UTC, kmr-srbh commented on src/libasr/asr_utils.h
> +            return var_x->class_type == var_y->class_type;
Thanks for this @Pranavchiku! I could fix this using a similar function. Let's hope the CI passes this time.

2024-06-03 19:17 UTC, certik commented
If this works, then go ahead and add an integration test for this.

2024-06-04 05:19 UTC, Pranavchiku commented
Please add an integration test and wrap this PR as soon as possible.

2024-06-04 06:18 UTC, Pranavchiku commented on src/libasr/asr_utils.h
> +inline bool check_equal_type(ASR::ttype_t* x, ASR::ttype_t* y, bool check_for_dimensions) {
Why do we need this change?

2024-06-04 06:19 UTC, Pranavchiku commented on src/libasr/asr_utils.h
> +            return check_equal_type(expr_type(&var_x->base), expr_type(&var_y->base));
If you wish to test dimension as well do `check_equal_type(expr_type(&var_x->base), expr_type(&var_y->base), true)`

2024-06-04 06:20 UTC, Pranavchiku commented on integration_tests/var_expression_comparison.f90
> +CONTAINS
Also, I think if we do not have interface then this is different issue and not what we need for SNAP.

2024-06-04 06:20 UTC, Pranavchiku reviewed
left questions above

2024-06-04 06:21 UTC, kmr-srbh commented on src/libasr/asr_utils.h
> +inline bool check_equal_type(ASR::ttype_t* x, ASR::ttype_t* y, bool check_for_dimensions) {
We were unable to use this function as it is defined later in the code. To use it here, I have declared it at the top.

2024-06-04 06:21 UTC, kmr-srbh commented on src/libasr/asr_utils.h
> +            return check_equal_type(expr_type(&var_x->base), expr_type(&var_y->base));
Okay.

2024-06-04 06:22 UTC, Pranavchiku commented on src/libasr/asr_utils.h
> +inline bool check_equal_type(ASR::ttype_t* x, ASR::ttype_t* y, bool check_for_dimensions) {
I mean to ask why to remove `bool check_for_dimensions=false`

2024-06-04 06:24 UTC, kmr-srbh commented on integration_tests/var_expression_comparison.f90
> +CONTAINS
Ah, right! I am making the changes,

2024-06-04 06:36 UTC, kmr-srbh commented on src/libasr/asr_utils.h
> +inline bool check_equal_type(ASR::ttype_t* x, ASR::ttype_t* y, bool check_for_dimensions) {
We cannot have them simultaneously in the declaration and definition. The declaration contains the default value.

2024-06-04 06:38 UTC, Pranavchiku commented on src/libasr/asr_utils.h
> +inline bool check_equal_type(ASR::ttype_t* x, ASR::ttype_t* y, bool check_for_dimensions) {
Why is it working in latest main then?

2024-06-04 06:39 UTC, Pranavchiku commented on integration_tests/CMakeLists.txt
> +RUN(NAME var_expression_comparison LABELS gfortran llvm llvm_wasm llvm_wasm_emcc)
```suggestion
RUN(NAME interface_01 LABELS gfortran llvm llvm_wasm llvm_wasm_emcc)
```

I'll prefer name like this.

2024-06-04 06:40 UTC, kmr-srbh commented on src/libasr/asr_utils.h
> +inline bool check_equal_type(ASR::ttype_t* x, ASR::ttype_t* y, bool check_for_dimensions) {
It is so because before this, we had not used the function in the same file `asr_utils.h` before it's definition.

2024-06-04 08:01 UTC, Pranavchiku commented on src/libasr/asr_utils.h
> +inline bool check_equal_type(ASR::ttype_t* x, ASR::ttype_t* y, bool check_for_dimensions) {
I see, you added signature above, good.

2024-06-04 08:10 UTC, Pranavchiku reviewed
changes are good, would you like to clean commit history or squash and merge would be fine?

2024-06-04 08:11 UTC, kmr-srbh commented
> changes are good, would you like to clean commit history or squash and merge would be fine?

Let's squash and merge this as a single commit.

2024-06-04 08:46 UTC, kmr-srbh commented
Thank you very much for the other test @Pranavchiku! Thank you very much for guiding and supporting me!

2024-06-04 08:48 UTC, merged

2024-06-04 08:49 UTC, Pranavchiku commented
Go ahead, pull changes, scan SNAP, create MRE and march to fix it.