feat: implement `eoshift` intrinsic
lfortran/lfortran pull request #4195
Opened 2024-06-09 05:24 UTC by parth121101

Towards: #492

2024-06-09 05:34 UTC, parth121101 commented
@HarshitaKalani can you please explain the following code:
```
body.push_back(al, b.DoLoop(j, b.Add(shift_val, b.i32(1)), UBound(args[0], 1), {
            b.Assignment(b.ArrayItem_01(result, {i}), b.ArrayItem_01(args[0], {j})),
            b.Assignment(i, b.Add(i, b.i32(1))),
        }, nullptr));
        body.push_back(al, b.DoLoop(j, LBound(args[0], 1), b.Add(shift_val, b.i32(1)), {
            b.Assignment(b.ArrayItem_01(result, {i}), b.ArrayItem_01(args[0], {j})),
            b.Assignment(i, b.Add(i, b.i32(1))),
        }, nullptr));
```

2024-06-09 06:55 UTC, HarshitaKalani commented
>@HarshitaKalani can you please explain the following code:

Yes, this is nothing but 
```
            cshift(array, shift, dim)
            int i = 0
            for j = shift, size(array)
                result[i] = array[j]
                i = i + 1
            end for
            for j = 1, shift
                result[i] = array[j]
                i = i + 1
            end for
```
I hope this makes it easy to understand. LMK if there are any questions.

2024-06-09 19:36 UTC, certik commented on src/libasr/pass/intrinsic_array_function_registry.h
> +            end for
change "for" to "do".

2024-06-09 19:37 UTC, certik approved these changes

2024-06-10 05:44 UTC, HarshitaKalani reviewed
I left some improvements.

2024-06-10 05:44 UTC, HarshitaKalani commented on src/libasr/pass/intrinsic_array_function_registry.h
> +            end for
+1
Also, can you please do the suggested change for `Cshift` intrinsic too (change for to do there)?

2024-06-10 05:44 UTC, HarshitaKalani commented on src/libasr/pass/intrinsic_array_function_registry.h
> +            end for
Btw, the input parameters are for cshift intrinsic. You'll need to modify it for `eoshift`.

2024-06-10 05:44 UTC, HarshitaKalani commented on src/libasr/pass/intrinsic_array_function_registry.h
> +            if (k shift= 0) then
I didn't understand this. What is `k` here?

2024-06-10 05:44 UTC, HarshitaKalani commented on src/libasr/pass/intrinsic_array_function_registry.h
> +                i = i + 1
```suggestion
                i = size(array) - shift + 1
```
Can this be written as this?

2024-06-10 05:44 UTC, HarshitaKalani commented on src/libasr/pass/intrinsic_array_function_registry.h
> +        body.push_back(al, b.Assignment(abs_shift_val, b.i2i_t(shift_val, int32)));
```suggestion
        body.push_back(al, b.Assignment(shift_val, args[1]));
        body.push_back(al, b.Assignment(abs_shift, shift_val));
        body.push_back(al, b.Assignment(abs_shift_val, shift_val));
```
Do we need to IntegerToInteger casting here?

2024-06-10 05:44 UTC, HarshitaKalani commented on src/libasr/pass/intrinsic_array_function_registry.h
> +        ASR::expr_t* boundary = args[2];
I think initialising boundary this way will cause the same problem as: https://github.com/lfortran/lfortran/issues/4200

2024-06-10 05:44 UTC, HarshitaKalani commented on src/libasr/pass/intrinsic_array_function_registry.h
> +        ASR::expr_t *final_boundary = args[2];
```suggestion
        if (extract_value(expr_value(args[1]), shift)) {
            ASR::expr_t *final_boundary = args[2];
```

2024-06-10 05:44 UTC, HarshitaKalani commented on src/libasr/pass/intrinsic_array_function_registry.h
> +                for(int j = 0; j < shift; j++){
```suggestion
            if(shift > 0) {
                int i = m_eles.size() - 1;
                for(int j = 0; j < shift; j++) {
```

2024-06-10 05:44 UTC, HarshitaKalani commented on src/libasr/pass/intrinsic_array_function_registry.h
> +                for(int j = 0; j < (-1*shift); j++){
```suggestion
            else {
                for(int j = 0; j < (-1*shift); j++) {
```
These are minor changes but if handled, will lead to a clean design.

2024-06-10 16:56 UTC, parth121101 commented on src/libasr/pass/intrinsic_array_function_registry.h
> +        ASR::expr_t* boundary = args[2];
No, this wont create any problem since at any point I am not changing boundary.

2024-06-10 17:16 UTC, certik approved these changes

2024-06-10 17:26 UTC, Pranavchiku commented on integration_tests/intrinsics_246.f90
> +
please add test with `parameter`.

2024-06-10 17:27 UTC, Pranavchiku commented on integration_tests/intrinsics_246.f90
> +    if (any(eoshift([1.0, 2.0, 3.0, 4.0], 3, 10.0) /= [4.0, 10.0, 10.0, 10.0])) error stop
I would prefer to shift it to some variable declared with `parameter`.

2024-06-10 17:27 UTC, Pranavchiku commented on src/libasr/pass/intrinsic_array_function_registry.h
>              cshift(array, shift, dim)
```suggestion
            eoshift(array, shift, dim)
```

2024-06-10 17:28 UTC, Pranavchiku commented on src/libasr/pass/intrinsic_array_function_registry.h
> +            end do
I think something is off as we discussed the last portion of code is probably missing.

2024-06-10 17:28 UTC, Pranavchiku commented on integration_tests/intrinsics_246.f90
> +    if (any(eoshift([1.0, 2.0, 3.0, 4.0], -3) /= [0.0, 0.0, 0.0, 1.0])) error stop
let's also add random values instead of these and test thoroughly.

2024-06-10 17:30 UTC, Pranavchiku commented on integration_tests/CMakeLists.txt
> +RUN(NAME intrinsics_246 LABELS gfortran llvm llvm_wasm llvm_wasm_emcc) # eoshift
```suggestion
RUN(NAME intrinsics_246 LABELS gfortran llvm llvm_wasm llvm_wasm_emcc fortran) # eoshift
```

As we are close let's not skip this and get it working with Fortran backend as well

2024-06-10 17:31 UTC, Pranavchiku requested changes
left comments above, thanks @parth121101 !

Edit: Also, please rebase this PR before merging.

2024-06-12 05:53 UTC, Pranavchiku commented on integration_tests/CMakeLists.txt
> +RUN(NAME intrinsics_248 LABELS gfortran llvm llvm_wasm llvm_wasm_emcc) # eoshift
```suggestion
RUN(NAME intrinsics_248 LABELS gfortran llvm llvm_wasm llvm_wasm_emcc fortran) # eoshift
```

I think this PR is good but you are still missing a small piece, is there any particular reason to not apply the following change in this PR?

2024-06-12 05:53 UTC, Pranavchiku commented on integration_tests/CMakeLists.txt
> +RUN(NAME intrinsics_246 LABELS gfortran llvm llvm_wasm llvm_wasm_emcc) # eoshift
@parth121101 this change is not done, I commented it again.

2024-06-12 06:01 UTC, HarshitaKalani approved these changes
I think we can make it a habit of adding the fortran label with the tests containing intrinsic functions. (Given we don't need to register intrinsic functions in fortran backend explicitly now, it is handled automatically, so this keeps us up to date with the issues in asr_to_fortran related to intrinsics.

The changes look good to me. Thanks @parth121101 :)

2024-06-12 06:13 UTC, parth121101 commented on integration_tests/CMakeLists.txt
> +RUN(NAME intrinsics_248 LABELS gfortran llvm llvm_wasm llvm_wasm_emcc) # eoshift
Please check @Pranavchiku. I have applied the changes requested.

2024-06-12 06:16 UTC, Pranavchiku commented
Would you mind rebasing on top of latest main?

2024-06-12 06:24 UTC, Pranavchiku commented on integration_tests/intrinsics_248.f90
> +    real :: bound2 = 99.0
I think you need to add tests with `parameter`, or I am missing something?

2024-06-13 05:26 UTC, Pranavchiku approved these changes

2024-06-13 05:26 UTC, merged