fix: check if a `Var_t` expression is a `Variable_t` before down casting
lfortran/lfortran pull request #4203
Opened 2024-06-09 16:41 UTC by kmr-srbh

fixes #4202 

```fortran
MODULE solvar_module
   REAL, DIMENSION(10) :: fixup_counter
END MODULE

PROGRAM test
   USE solvar_module
   IMPLICIT NONE

   INTEGER :: n

   PRINT *, (fixup_counter(n),n=1,4)
END PROGRAM test
```
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00 
```

2024-06-09 16:44 UTC, kmr-srbh commented
With the known issues commented out, we are now able to completely compile SNAP, but do not get the message " Aww SNAP. Program failed. Try again." to print to stdout. I think we are near completion?

```console
(base) saurabh-kumar@Awadh:~/Projects/Packages/SNAP/src$ make
lfortran  -c global.f90
lfortran  -c sn.f90
lfortran  -c data.f90
lfortran  -c geom.f90
lfortran  -c control.f90
cpp -P  time.0.F90 >time.f90
lfortran  -c time.f90
warning: Assuming implicit save attribute for variable declaration
  --> time.f90:60:25
   |
60 |     CHARACTER(LEN=1) :: star='*'
   |                         ^^^^^^^^ help: add explicit save attribute or initialize in a separate statement


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
cpp -P  plib.0.F90 >plib.f90
lfortran  -c plib.f90
lfortran  -c mms.f90
warning: Assuming implicit save attribute for variable declaration
   --> mms.f90:522:25
    |
522 |     CHARACTER(LEN=1) :: star='*'
    |                         ^^^^^^^^ help: add explicit save attribute or initialize in a separate statement


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
lfortran  -c solvar.f90
lfortran  -c dealloc.f90
lfortran  -c utils.f90
warning: Argument `access` isn't supported yet
   --> utils.f90:123:5 - 124:39
    |
123 |        OPEN( UNIT=funit, FILE=tname, STATUS=fstat, ACCESS='SEQUENTIAL',   &
    |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
...
    |
124 |              ACTION=faction, IOSTAT=ierr )
    | ...^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ignored for now

warning: Argument `action` isn't supported yet
   --> utils.f90:123:5 - 124:39
    |
123 |        OPEN( UNIT=funit, FILE=tname, STATUS=fstat, ACCESS='SEQUENTIAL',   &
    |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
...
    |
124 |              ACTION=faction, IOSTAT=ierr )
    | ...^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ignored for now

warning: Argument `iostat` isn't supported yet
   --> utils.f90:123:5 - 124:39
    |
123 |        OPEN( UNIT=funit, FILE=tname, STATUS=fstat, ACCESS='SEQUENTIAL',   &
    |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
...
    |
124 |              ACTION=faction, IOSTAT=ierr )
    | ...^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ignored for now


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
lfortran  -c version.f90
lfortran  -c input.f90
warning: Assuming implicit save attribute for variable declaration
   --> input.f90:120:25
    |
120 |     CHARACTER(LEN=1) :: star='*'
    |                         ^^^^^^^^ help: add explicit save attribute or initialize in a separate statement


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
lfortran  -c setup.f90
warning: Assuming implicit save attribute for variable declaration
   --> setup.f90:751:25
    |
751 |     CHARACTER(LEN=1) :: star='*'
    |                         ^^^^^^^^ help: add explicit save attribute or initialize in a separate statement

warning: Assuming implicit save attribute for variable declaration
   --> setup.f90:916:26
    |
916 |     CHARACTER(LEN=16) :: fn='slgg'
    |                          ^^^^^^^^^ help: add explicit save attribute or initialize in a separate statement

warning: Assuming implicit save attribute for variable declaration
   --> setup.f90:918:37
    |
918 |     INTEGER(i_knd) :: l, g1, g2, n, fu=15
    |                                     ^^^^^ help: add explicit save attribute or initialize in a separate statement


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
lfortran  -c output.f90
warning: Assuming implicit save attribute for variable declaration
  --> output.f90:54:25
   |
54 |     CHARACTER(LEN=1) :: star='*'
   |                         ^^^^^^^^ help: add explicit save attribute or initialize in a separate statement

warning: Assuming implicit save attribute for variable declaration
   --> output.f90:259:26
    |
259 |     CHARACTER(LEN=16) :: fn='flux'
    |                          ^^^^^^^^^ help: add explicit save attribute or initialize in a separate statement

warning: Assuming implicit save attribute for variable declaration
   --> output.f90:263:44
    |
263 |     INTEGER(i_knd) :: i, j, k, g, l, ierr, fu=16, mtag, jp, jlb, jub,  &
    |                                            ^^^^^ help: add explicit save attribute or initialize in a separate statement


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
lfortran  -c snap_main.f90
lfortran  -c expxs.f90
lfortran  -c thrd_comm.f90
lfortran  -c dim1_sweep.f90
lfortran  -c dim3_sweep.f90
lfortran  -c mkba_sweep.f90
lfortran  -c octsweep.f90
lfortran  -c sweep.f90
warning: Assuming implicit save attribute for variable declaration
  --> sweep.f90:67:7
   |
67 |       dummy(2)=(/0, 0/)
   |       ^^^^^^^^^^^^^^^^^ help: add explicit save attribute or initialize in a separate statement


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
lfortran  -c inner.f90
lfortran  -c outer.f90
lfortran  -c analyze.f90
lfortran  -c translv.f90
warning: Assuming implicit save attribute for variable declaration
  --> translv.f90:55:23
   |
55 |   CHARACTER(LEN=1) :: star='*'
   |                       ^^^^^^^^ help: add explicit save attribute or initialize in a separate statement


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
lfortran   -o gsnap global.o snap_main.o utils.o version.o plib.o geom.o sn.o data.o control.o input.o setup.o dealloc.o translv.o solvar.o outer.o expxs.o inner.o sweep.o octsweep.o dim1_sweep.o dim3_sweep.o output.o time.o mms.o analyze.o thrd_comm.o mkba_sweep.o
(base) saurabh-kumar@Awadh:~/Projects/Packages/SNAP/src$ ./gsnap
(base) saurabh-kumar@Awadh:~/Projects/Packages/SNAP/src$ 
```

2024-06-09 16:56 UTC, kmr-srbh commented
I feel there might be some more issues due to the commented out code. We need to fix the left-over issues to have a look again.

2024-06-09 17:52 UTC, certik commented
Add a test for this fix.

Great job!

Roughly speaking, here are the steps:

1. Parse everything to AST
2. Raise everything to ASR with workarounds
3. Lower everything to LLVM with workarounds
4. Compile all LLVM to machine code, link everything, with workaorunds
5. Make it run currently (with workarounds), side by side with GFortran, first on some small subset, then expand the subset to the usable size that we decide we want to support (for SNAP it should run some examples, ideally all, without MPI)
6. Remove as many workarounds as we can

It looks like you finished 4. That's a big deal, thank you!

Now we need to work on 5. That might take several weeks as well, but once it runs well, the we are very close. The 6. is the last step, we have well defined issues that we just have to fix, and remove as many workarounds as we can.

2024-06-10 05:58 UTC, Pranavchiku commented on src/lfortran/semantics/ast_common_visitor.h
> +                }
What will it be if not a `Variable`? Like what it is in this case?

2024-06-10 05:59 UTC, Pranavchiku commented on src/lfortran/semantics/ast_common_visitor.h
> +                }
Check it will be an `ExternalSymbol`, if that is the case you need to somehow `symbol_get_past_external` and then this won't be correct fix.

2024-06-10 05:59 UTC, Pranavchiku requested changes
left question and comment above

2024-06-10 16:29 UTC, kmr-srbh commented on src/lfortran/semantics/ast_common_visitor.h
> +                }
You are right. We can do `symbol_get_past_external` as stated by you.

2024-06-10 17:15 UTC, certik commented
Let's add a test that fails in master, but works in this PR.

2024-06-10 17:19 UTC, Pranavchiku requested changes
changes look good to me, I'll wait for a test before approving. Always remember to add a test preferably an integration test in PR that is fixed with the patch you submitted.

2024-06-10 19:04 UTC, Pranavchiku commented on integration_tests/implied_do_loops5.f90
> +   PRINT *, (fixup_counter(n) + n, n=1, 4)
please add `if() error stop` condition to test actual value.

2024-06-10 19:04 UTC, Pranavchiku requested changes
minor comment.

2024-06-10 19:04 UTC, certik approved these changes
I think this looks good now.

2024-06-10 19:05 UTC, certik commented on src/lfortran/semantics/ast_common_visitor.h
> +                                                ASRUtils::symbol_get_past_external(x.m_v));
I think this part is not tested, correct? Does the correspond to `n` being in the other module?

2024-06-10 19:07 UTC, kmr-srbh commented on integration_tests/implied_do_loops5.f90
> +   PRINT *, (fixup_counter(n) + n, n=1, 4)
I saw that none of the other implied do loop tests have this.

2024-06-10 19:08 UTC, Pranavchiku commented on src/lfortran/semantics/ast_common_visitor.h
> +                                                ASRUtils::symbol_get_past_external(x.m_v));
> Does the correspond to `n` being in the other module?

yes

2024-06-10 19:10 UTC, kmr-srbh commented on src/lfortran/semantics/ast_common_visitor.h
> +                                                ASRUtils::symbol_get_past_external(x.m_v));
I am adding a test case for this. Moving `n` to the module, works. Is that right?

2024-06-10 19:25 UTC, certik commented on src/lfortran/semantics/ast_common_visitor.h
> +                                                ASRUtils::symbol_get_past_external(x.m_v));
I think so.

2024-06-10 19:25 UTC, certik commented on integration_tests/implied_do_loops5.f90
> +   PRINT *, (fixup_counter(n) + n, n=1, 4)
You can print it like this, and then assign it to an array, and test the result in the array. It's good to do, then the test is robust.

2024-06-11 06:13 UTC, Pranavchiku commented on integration_tests/implied_do_loops5.f90
> +   result_array = (/ (fixup_counter(n) + n, n = 1, 5) /)
```suggestion
   result_array = [(fixup_counter(n) + n, n = 1, 5)]
```

2024-06-11 06:14 UTC, Pranavchiku commented on integration_tests/implied_do_loops5.f90
> +   USE implied_do_loops5
```suggestion
MODULE module_implied_do_loops5
   INTEGER, DIMENSION(5) :: fixup_counter
   INTEGER :: n
END MODULE implied_do_loops5

PROGRAM implied_do_loops5
   USE module_implied_do_loops5
```

2024-06-11 06:14 UTC, Pranavchiku commented on integration_tests/implied_do_loops5.f90
> +END PROGRAM test
```suggestion
END PROGRAM implied_do_loops5
```

2024-06-11 06:17 UTC, Pranavchiku approved these changes

2024-06-11 06:37 UTC, merged