feat: add optional argument for ishftc intrinsic
lfortran/lfortran pull request #4491
Opened 2024-07-12 06:10 UTC by parth121101

Towards: #492

2024-07-14 04:21 UTC, HarshitaKalani reviewed
Do we have tests for checking the third argument? Can you please add them?

2024-07-14 12:51 UTC, parth121101 commented
Sure @HarshitaKalani

2024-07-14 15:04 UTC, HarshitaKalani reviewed
Looks good to me. Just a minor comment.

2024-07-14 15:08 UTC, parth121101 commented on src/lfortran/semantics/ast_common_visitor.h
> +                    ASR::make_Integer_t(al, loc, kind));
This is because the kind of each varies function to function.

2024-07-14 15:14 UTC, HarshitaKalani commented on src/lfortran/semantics/ast_common_visitor.h
> +                    ASR::make_Integer_t(al, loc, kind));
The kind of the default value will not to be equal to the kind of first argument. It'll be `compiler_options.po.default_integer_kind` (which is equal to 4). So that needs to be corrected too.

2024-07-14 16:24 UTC, certik commented
(`compiler_options.po.default_integer_kind` should be used in AST->ASR, but it should not be used in any code in libasr: there the ASR itself must have full information.)

2024-07-15 04:45 UTC, HarshitaKalani approved these changes
LGTM. Thanks @parth121101 :)

2024-07-15 10:36 UTC, Pranavchiku requested changes
left a comment, please resolve it before merging.

2024-07-19 15:20 UTC, certik approved these changes

2024-07-19 15:21 UTC, merged