fix: restore array pointer to it's descriptor during allocation after nullifying
lfortran/lfortran pull request #4508
Opened 2024-07-14 08:21 UTC by kmr-srbh

fixes #4466 

We store the descriptor of the array in a map using it's llvm data type as the key and use it to restore the pointer to it when allocation is done after nullifying.

```llvm
.
.
.
  store %array* null, %array** %ptr, align 8      ; NULLIFY used on ptr
  %8 = load %array*, %array** %ptr, align 8
  %9 = ptrtoint %array* %8 to i32
  %10 = icmp eq i32 %9, 0                                                                            
  br i1 %10, label %then, label %else

then:                                             ; preds = %.entry
  store %array* %arr_desc, %array** %ptr, align 8
  br label %ifcont

else:                                             ; preds = %.entry
  br label %ifcont

ifcont:                                           ; preds = %else, %then
  %11 = load %array*, %array** %ptr, align 8
.
.
.
```

### Working
```fortran
program main
   integer, dimension(:), pointer :: ptr
   nullify(ptr)
   allocate(ptr(5))
   
   ptr = [1, 2, 3, 4, 5]
   print *, ptr
end program main
```
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ gfortran ./examples/example.f90 && ./a.out
           1           2           3           4           5
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
1 2 3 4 5 
```

2024-07-14 09:21 UTC, kmr-srbh commented
## Output of executing `./gsnap`:

### GFortran

```console
(base) saurabh-kumar@Awadh:~/Projects/Packages/SNAP/src$ ./gsnap in.txt tmp.out
   *WARNING: INPUT_CHECK: MULTISWP reset to 0 for serial           

          keyword Iteration Monitor
********************************************************************************
  Outer
    1    Dfmxo= 8.6141E-01    No. Inners=    5
    2    Dfmxo= 1.8786E-03    No. Inners=    4
    3    Dfmxo= 8.8967E-06    No. Inners=    1

  No. Outers=   3    No. Inners=   10

********************************************************************************

 Success! Done in a SNAP!
ERROR STOP 

Error termination. Backtrace:
#0  0x75aa2be23c5d in ???
#1  0x75aa2be247b9 in ???
#2  0x75aa2be25e37 in ???
#3  0x5cb29446e585 in ???
#4  0x5cb2944a7dcd in ???
#5  0x5cb2944a7e38 in ???
#6  0x75aa2ba2a1c9 in __libc_start_call_main
        at ../sysdeps/nptl/libc_start_call_main.h:58
#7  0x75aa2ba2a28a in __libc_start_main_impl
        at ../csu/libc-start.c:360
#8  0x5cb29446e244 in ???
#9  0xffffffffffffffff in ???
```


### LFortran
<details>

```console
(base) saurabh-kumar@Awadh:~/Projects/Packages/SNAP/src$ ./gsnap in.txt tmp.out
   *WARNING: INPUT_CHECK: MULTISWP reset to 0 for serial           

          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*          keyword Iteration Monitor
*
  Outer
    1    Dfmxo= 8.6141E-01    No. Inners=    5
    2    Dfmxo= 1.8786E-03    No. Inners=    4
    3    Dfmxo= 8.8967E-06    No. Inners=    1

  No. Outers=   3    No. Inners=   10

*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
 Success! Done in a SNAP!
ERROR STOP
```
<details>

The repetition of asterisks and phrase "keyword Iteration Monitor" is due to an issue related to `FileWrite` and implied do loop. We have a workaround available for it and will apply them throughout the code-base soon.

2024-07-14 12:42 UTC, kmr-srbh commented
### GFortran output (tmp.out)
[GFortran.txt](https://github.com/user-attachments/files/16224474/GFortran.txt)

### LFortran output (tmp.out)
[LFortran.txt](https://github.com/user-attachments/files/16224555/LFortran.txt)

2024-07-14 13:13 UTC, certik commented on integration_tests/pointer_01.f90
> +    print *, associated(real_ptr)
Also add assert after each associate to check what the answer should be.

2024-07-14 13:22 UTC, certik commented on src/libasr/codegen/asr_to_llvm.cpp
> +        }
In here the issue is that the line below expects `arr` to point to a descriptor, but somehow it doesn't?

I wonder if possibly our ASR's array physical types are not correct here. 

Can you walk me through the code:
```fortran
    integer, dimension(:), pointer :: int_ptr
    nullify(int_ptr)
    print *, associated(int_ptr)
    allocate(int_ptr(3))
    int_ptr = [1, 2, 3]
    print *, int_ptr
    print *, associated(int_ptr)
```
After the first line, is `int_ptr` a descriptor? What does `nullify()` do to the descriptor? Then the `allocate` line is executing this PR diff above?

2024-07-14 15:00 UTC, kmr-srbh commented on src/libasr/codegen/asr_to_llvm.cpp
> +        }
Here is the code walk through along with the related LLVM IR:

1. When declaring `int_ptr` we first create a new instance of the `array` struct and store `nullptr` in it.
```fortran
integer, dimension(:), pointer :: int_ptr
```
 is translated to 
```llvm
%int_ptr = alloca %array*, align 8
store %array* null, %array** %int_ptr, align 8
```

We then create the array descriptor and store the pointer to it inside `int_ptr`
```llvm
%2 = getelementptr %array, %array* %arr_desc, i32 0, i32 2
%3 = alloca i32, align 4
store i32 1, i32* %3, align 4
%4 = load i32, i32* %3, align 4
%5 = alloca %dimension_descriptor, i32 %4, align 8
store %dimension_descriptor* %5, %dimension_descriptor** %2, align 8
%6 = getelementptr %array, %array* %arr_desc, i32 0, i32 4
store i32 1, i32* %6, align 4
%7 = getelementptr %array, %array* %arr_desc, i32 0, i32 0
store i32* null, i32** %7, align 8
store %array* %arr_desc, %array** %int_ptr, align 8
```

2. When `NULLIFY` statement is used, we make `int_ptr` point to `nullptr`. It does not do anything to the descriptor.
```fortran
nullify(int_ptr)
```
 is translated to 
```llvm
store %array* null, %array** %int_ptr, align 8
```
3. We next try to allocate memory to the pointer.

This was the exact place where the error had occurred. When we try to allocate memory to the pointer, we visit `visit_AllocateUtil()` which calls `fill_malloc_array_details()`. This function then calls `fill_malloc_array_details()` of the array API .i.e. `arr_descr->fill_malloc_array_details()`. Inside this function, we do the necessary work of setting the array values to 0s and filling other details like the dimension descriptor. As `int_ptr` had pointed to `nullptr` due to the `NULLIFY` statement, the first instruction, 
```llvm
%12 = load %array*, %array** %int_ptr, align 8
%13 = getelementptr %array, %array* %12, i32 0, i32 1
```
caused the `getelementptr` to fetch value from a `nullptr`, and hence caused the segmentation fault.

I tried to mitigate this issue by storing the array descriptor in a map when `NULLIFY` was used. We use value from this map when we fill the details of the `malloc_array`.

`Allocatable_t` had interfered with the initial implementation due to the similarity of the way they are handled. I bypassed it by checking explicitly for it. After we set the pointer to array to point to the array descriptor, we can continue with the task of allocating memory.

2024-07-14 16:38 UTC, certik commented on src/libasr/codegen/asr_to_llvm.cpp
> +        }
Thanks. Something doesn't feel right here. The compiler shouldn't have a state to determine if nullify was called. For example, what happens if you only call nullify sometimes:
```
if (something) nullify(...)
```
The nullify state is a runtime decision, so we should not keep track of this at compile time using the `arr_desc_map` structure.

The fundamental question here is when the descriptor should be created. I think a clean solution is:

A pointer to an array has to have a physical type that determines if a descriptor is created. I am not currently sure if it needs to be in the Pointer ttype, or if we can just store it as part of the Array in Pointer(Array). This leaves the door open to not use a descriptor in some cases to optimize for speed. But by default we'll use it. If the physical type says a descriptor should be used, then I think `integer, dimension(:), pointer :: int_ptr` should create a descriptor and set the inner pointer to null. The nullify() also just sets the inner pointer to null. If we have to distinguish the cases of allocated + null vs non-allocated+null, then we need to store this state inside the descriptor as a flag.

Then a call to nullify() just modifies the existing descriptor. It does not create one.

When a pointer is associated to point to some actual array, then the descriptor is updated accordingly.

2024-07-14 16:40 UTC, certik commented on src/libasr/codegen/asr_to_llvm.cpp
> +        }
CC @czgdp1807, can you please help us here with the design? Is what I wrote a good design, or should we change it?

2024-07-14 17:10 UTC, czgdp1807 commented on src/libasr/codegen/asr_to_llvm.cpp
> +        }
Here are some pointers from my end,

1. The test should also have a case where `ptr` is `allocatable` (if `nullify` can be called on `allocatable` types in Fortran). Also `nullify` should be called conditionally (inside an `if-endif` statement, the test case of such `if-endif` shouldn't be constant). :-)
2. The tracker approach being used here in this PR shouldn't be merged. A simple approach to solve the linked issue will be as follows to modify how `allocate` is implemented,

Step 1 - Generate LLVM `if` condition to check if `ptr` is `null`.
Step 2 - If it is `null` then `CreateAlloca` over the descriptor type and then store it inside `ptr`.
Step 3 - If it is not `null` then don't do anything inside the `else` part.

I just checked the `main` branch and I am surprised that such things are implemented inside `visit_AllocateUtil`. Such checks are there inside `visit_Deallocate`,

**visit_AllocateUtil**

https://github.com/lfortran/lfortran/blob/e01154101a18105365ef143edf7849cd41166900/src/libasr/codegen/asr_to_llvm.cpp#L1032-L1035

**visit_Deallocate**

https://github.com/lfortran/lfortran/blob/e01154101a18105365ef143edf7849cd41166900/src/libasr/codegen/asr_to_llvm.cpp#L1243-L1246

For now the above fix I suggested should get things going without any blockers. For long term following are my opinions,

> The fundamental question here is when the descriptor should be created. 

I think that's already answered in ASR. We have a physical type for it. Yes for `pointer` array we will always have to create it because at runtime we never know whether `ptr` will be associated with a `FixedSizedArray` or `PointerToDataArray` or `DescriptorArray`.

> If we have to distinguish the cases of allocated + null vs non-allocated+null, then we need to store this state inside the descriptor as a flag.

Right now if `array**` (a pointer to descriptor) is `null` then it means that the `ptr` isn't allocated. We can change that definition of non-allocated arrays to something like, data pointer of `array*` as `null`. That way we will always have `ptr` as `array*` type and when `deallocate` is called or `nullify` is called we can set data pointer as `null`. In fact, we can use the same definition for `deallocate` and `nullify`. Both will try to free the memory which is pointed to by the data pointer of the descriptor and then set it to `null`. No memory leaks. :-).

2024-07-14 17:13 UTC, czgdp1807 requested changes
https://github.com/lfortran/lfortran/pull/4508#discussion_r1677172066

2024-07-14 17:25 UTC, certik commented on src/libasr/codegen/asr_to_llvm.cpp
> +        }
Awesome, thanks @czgdp1807. @kmr-srbh let me know if you know how to proceed with this PR.

(Note: pointer (allocatable or not) should not free the memory, only allocatable non-pointer arrays should free it.)

2024-07-14 17:31 UTC, czgdp1807 commented on src/libasr/codegen/asr_to_llvm.cpp
> +        }
That's fine. For long term scenario - We can generate the LLVM code for `nullify` depending upon whether the argument is `allocatable` or `pointer`. Call `deallocate` for `allocatable` type. Reason being if we set data pointer of an array descriptor to `null` then the memory previously pointed to by that data pointer will become dangling (a memory leak). That shouldn't happen.

2024-07-14 19:56 UTC, certik commented on src/libasr/codegen/asr_to_llvm.cpp
> +        }
We simply have to insert Finalize before nullify (https://github.com/lfortran/lfortran/issues/3770).

2024-07-15 07:26 UTC, kmr-srbh commented on src/libasr/codegen/asr_to_llvm.cpp
> +        }
Thanks for the guidance @certik @czgdp1807! When `NULLIFY` is called on a `pointer`, we need to set it's pointer to data to `nullptr` instead of the pointer itself. This will mean that the `pointer` is currently in un-allocated state, and vice-versa. When the pointer is un-allocated and it is nullified, as in the provided MRE, we do nothing. 
I think I have a fair idea of how to implement this. Did I get it correctly? :)

Also, I think we probably cannot use `NULLIFY` on `allocatable`.
```fortran
program main
   implicit none

   integer, dimension(:), allocatable :: arr
   allocate(arr(2))
   
   arr = [1, 2]
   print *, arr
   
   nullify(arr)
   
end program main
```
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ gfortran ./examples/example.f90 && ./a.out
./examples/example.f90:10:11:

   10 |    nullify(arr)
      |           1
Error: Non-POINTER in pointer association context (pointer assignment) at (1)
```

2024-07-15 07:27 UTC, czgdp1807 commented on src/libasr/codegen/asr_to_llvm.cpp
> +        }
I think you should go with the short term solution for now.

2024-07-15 16:50 UTC, certik commented on src/libasr/codegen/asr_to_llvm.cpp
> +        }
Yes, do the short-term solution, unblock the work on SNAP. Later we'll implement the long-term solution.

2024-07-16 09:42 UTC, closed without merging