feat: implement `get_command` intrinsic
lfortran/lfortran pull request #4560
Opened 2024-07-29 18:27 UTC by parth121101

Towards: #492

2024-07-30 12:45 UTC, certik approved these changes
Awesome, thanks! 

Test has to be added. Left a minor comment.

2024-07-30 12:45 UTC, certik commented on src/libasr/pass/intrinsic_subroutines.h
> +    Get_Command,
This is the convention that we use for intrinsic function names:
```suggestion
    GetCommand,
```

2024-07-30 13:36 UTC, HarshitaKalani commented on src/libasr/pass/intrinsic_subroutines.h
> +
The number of blank lines left look a little uneven. Can you please clean that?

2024-08-04 15:26 UTC, certik commented on integration_tests/CMakeLists.txt
> +RUN(NAME subroutines_12 LABELS)
This needs some labels

2024-08-04 17:28 UTC, certik commented on integration_tests/CMakeLists.txt
> +RUN(NAME subroutines_12 LABELS llvm llvm_wasm llvm_wasm_emcc wasm)
Also gfortran.

2024-08-04 17:53 UTC, parth121101 commented on integration_tests/CMakeLists.txt
> +RUN(NAME subroutines_12 LABELS llvm llvm_wasm llvm_wasm_emcc wasm)
Added,
But the output of gfortran and lfortran wont match.
The executable that is called for lfortran is the name of the file, while for gfortran its a.out file.

2024-08-04 19:07 UTC, certik commented on integration_tests/CMakeLists.txt
> +RUN(NAME subroutines_12 LABELS gfortran)
Add `llvm` here, so that we test it in both gfortran and lfortran.

2024-08-05 04:07 UTC, Pranavchiku commented on integration_tests/CMakeLists.txt
> +RUN(NAME subroutines_12 LABELS llvm llvm_wasm llvm_wasm_emcc wasm)
It is fine, you are not testing values.

2024-08-05 04:09 UTC, Pranavchiku commented on src/libasr/pass/intrinsic_subroutines.h
>  enum class IntrinsicImpureSubroutines : int64_t {
@parth121101 in other PR can you please update the comment in the above line? We need to use `RandomNumber`, `GetCommand` instead of `Sin` and `LogGamma`

2024-08-05 04:09 UTC, Pranavchiku commented on src/libasr/pass/intrinsic_subroutines.h
> +            body_1, return_var_1, ASR::abiType::BindC, ASR::deftypeType::Interface, s2c(al, c_func_name_1));
I think we have a function in ASRBuilder which does this, `call_c_func` IIRC

2024-08-05 04:11 UTC, Pranavchiku commented on src/libasr/runtime/lfortran_intrinsics.c
> +    }
```suggestion
    char* out = _lfortran_get_command_command();
```

I think you'll be able to reuse it.

2024-08-05 04:11 UTC, Pranavchiku requested changes
Left a few possibility of improvement, rest all is good. Thank you!

2024-08-05 11:45 UTC, certik commented on integration_tests/CMakeLists.txt
> +RUN(NAME subroutines_12 LABELS gfortran llvm llvm_wasm llvm_wasm_emcc wasm)
I've noticed all these tests that should be tested by LFortran and aren't. I enabled them all in https://github.com/lfortran/lfortran/pull/4592.

2024-08-16 16:25 UTC, certik commented on integration_tests/CMakeLists.txt
> +RUN(NAME subroutines_13 LABELS gfortran llvm llvm_wasm llvm_wasm_emcc wasm)
```suggestion
RUN(NAME subroutines_13 LABELS gfortran llvm llvm_wasm llvm_wasm_emcc)
```

2024-08-16 16:26 UTC, certik approved these changes

2024-08-16 16:42 UTC, Pranavchiku approved these changes

2024-08-16 18:15 UTC, merged