Issue #4678
lfortran/lfortran pull request #4775
Opened 2024-09-10 19:09 UTC by jinangshah21

Thrown error comparing type of variables 'type' and 'value'.

2024-09-11 03:02 UTC, kmr-srbh commented
Thanks for this PR! I think we already have a PR for this issue at #4772.

2024-09-11 04:06 UTC, certik commented
The issue here is:
```
../integration_tests/arrays_reshape_14.f90 * asr
The JSON metadata differs against reference results
Reference JSON: tests/reference/asr-arrays_reshape_14-913f34e.json
Output JSON:    tests/output/asr-arrays_reshape_14-913f34e.json
Omitting 6 identical items
Differing items:
{'stderr': 'asr-arrays_reshape_14-913f34e.stderr'} != {'stderr': None}
{'stderr_hash': 'e21e49fe1af749231f3f62f2a3cc24698d7b44070a0b23c7d246c5ef'} != {'stderr_hash': None}
{'stdout_hash': None} != {'stdout_hash': 'ce1282b78ae62401d0958a74d8397b82449b1e1df94df22774f143de'}
{'returncode': 139} != {'returncode': 0}
{'stdout': None} != {'stdout': 'asr-arrays_reshape_14-913f34e.stdout'}No output stdout_hash available for ../integration_tests/arrays_reshape_14.f90
```
So you need to update the reference tests using `./run_tests.py -u` and commit the changes (after verifying that the changes are correct).

2024-09-11 13:57 UTC, kmr-srbh commented on tests/reference/asr-arrays_reshape_14-913f34e.stderr
> +Traceback (most recent call last):
This reference file is incorrect. This is an error stacktrace. I think we do not throw an error for this.

2024-09-11 14:03 UTC, kmr-srbh commented on src/lfortran/semantics/ast_common_visitor.h
> +                    if(value->type==63 && type->type==0){
Please use the `ASRUtils::expr_type()` utility function to get the type of an expression. 

I think we need to throw this error after comparing the number of dimensions (rank) of the LHS and RHS. You can use the `ASRUtils::extract_n_dims_from_ttype()` utility function to do this. 

Let's do this:
1. Find the place where we assign the values.
2. Compare the number of dimension of the LHS and RHS.
3. Throw error if not equal.

Do the same for declaration also, inside `visit_DeclarationUtil()`.

2024-09-13 16:39 UTC, HarshitaKalani commented
@jinangshah21 that was indeed an issue with Digits.
```diff
$ git diff src/libasr/intrinsic_func_registry_util_gen.py
diff --git a/src/libasr/intrinsic_func_registry_util_gen.py b/src/libasr/intrinsic_func_registry_util_gen.py
index c659bed52..317b5ea51 100644
--- a/src/libasr/intrinsic_func_registry_util_gen.py
+++ b/src/libasr/intrinsic_func_registry_util_gen.py
@@ -839,6 +839,7 @@ compile_time_only_fn = [
     "Kind",
     "MaxExponent",
     "MinExponent",
+    "Digits",
 ]
 
 type_to_asr_type_check = {
```
Add Digits in the compile_time_only_fn list in `intrinsic_func_registry_util_gen.py` file. That should solve the issue with Digits.

2024-09-14 06:19 UTC, HarshitaKalani commented on tests/issue_4678.f90
> +program main
Can you give an appropriate test name to this file instead of `issue_4678`.
Similar for the test above `issue_4286`.

2024-09-14 21:48 UTC, Pranavchiku commented
Minor git sanity conventions we follow:

1. We prefer rebase instead of merge unless multiple people are working on a same branch 
    a. Hence, use `git rebase main` inside your branch to rebase it.
2. While opening a new branch, always go to `main` branch, do `git clean -dfx` and restore all changes if required by doing `git restore .` and create a new branch `git checkout -b <new-branch-name>` and start working there.
3. To push changes, simply do `git push <your-remote> <new-branch-name>`
4. If you are willing to go from branch `A` to branch `B`, go via `main` i.e. `git checkout main` and then `git checkout B`.

That's it, not much!

To pull changes of someone, just do `git pull <your-remote> <your-branch-name>` e.g. for this branch do `git pull jinangshah21 temp_branch` assuming `jinangshah21` is your remote.

2024-09-15 06:56 UTC, HarshitaKalani approved these changes

2024-09-15 16:03 UTC, certik reviewed
Awesome, thanks for the fix!

A few more things to improve and then we can merge.

2024-09-15 16:56 UTC, jinangshah21 commented on integration_tests/CMakeLists.txt
> +RUN(NAME matrix_02_matmul LABELS gfortran fortran llvm17 NOFAST)
![Screenshot 2024-09-14 015854](https://github.com/user-attachments/assets/f4be80d0-a311-4910-8d52-18083891598d)
This was the failure for matmul only that test was failed at that time.

2024-09-15 18:18 UTC, certik commented on integration_tests/CMakeLists.txt
> +RUN(NAME matrix_02_matmul LABELS gfortran fortran llvm17 NOFAST)
I see. It's weird what might be causing this failure from the (innocent looking) changes in this PR.

2024-09-15 18:19 UTC, jinangshah21 commented on tests/reference/asr-arrays_reshape_14-913f34e.stderr
> +Aborted
It was old update. Currently deleting it Doesn't cause any error. I have deleted that file.

2024-09-15 18:20 UTC, certik commented on tests/reference/asr-arrays_reshape_14-913f34e.stderr
> +Aborted
Perfect.

2024-09-16 21:20 UTC, certik commented on tests/reference/asr-arrays_reshape_14-913f34e.stderr
> +Aborted
Go ahead and remove this file and push into this PR.

2024-09-17 05:20 UTC, certik commented on integration_tests/CMakeLists.txt
> +RUN(NAME matrix_02_matmul LABELS gfortran fortran llvm17 NOFAST)
I can't reproduce the above failure on Linux at least. This works for me:
```suggestion
RUN(NAME matrix_02_matmul LABELS gfortran fortran llvm17)
```

2024-09-17 05:21 UTC, certik commented on src/libasr/intrinsic_func_registry_util_gen.py
> +    "Digits",
Why is this needed? This might be a mistake also.

2024-09-17 05:22 UTC, certik commented on tests/incompatible_rank_assign.f90
> +end program
These two tests are not run anymore. You need to register them, then update the reference tests.

2024-09-17 05:29 UTC, certik commented on integration_tests/CMakeLists.txt
> +RUN(NAME matrix_02_matmul LABELS gfortran fortran llvm17 NOFAST)
@jinangshah21 are you still getting the matmul failure in this PR? The CI tests seem to pass. Maybe you were getting the failure with some older version of the PR that had some bug in it, but the current PR is ok?

2024-09-17 05:34 UTC, jinangshah21 commented on integration_tests/CMakeLists.txt
> +RUN(NAME matrix_02_matmul LABELS gfortran fortran llvm17 NOFAST)
Might be some issue. But now it is passing.

2024-09-17 17:46 UTC, HarshitaKalani-WBD commented on src/libasr/intrinsic_func_registry_util_gen.py
> +    "Digits",
This is needed. Digits is an inquiry function, so it needs to be registered here anyway. 
Earlier Digits was returning an array, we don't want that. It should be returning a scalar output only.

2024-09-17 17:48 UTC, Pranavchiku requested changes

2024-09-17 17:48 UTC, Pranavchiku commented on tests/incompatible_rank_assign.f90
> +program main
You need to shit it to `tests/error/` and then register it inside `tests/tests.toml`, refer the following diff:

```diff
diff --git a/tests/tests.toml b/tests/tests.toml
index 4455e7cb3..f8c7e1dec 100644
--- a/tests/tests.toml
+++ b/tests/tests.toml
@@ -4171,3 +4171,7 @@ run = true
 [[test]]
 filename = "multi_error1.f90"
 ast = true
+
+[[test]]
+filename = "errors/filename.f90"
+asr = true
```

Then do a clean build, and apply the following commands:

```console
$ rm -rf ./tests/reference/*
$ ./run_tests.py -u
```

2024-09-17 17:48 UTC, Pranavchiku commented on tests/Logical_to_Integer.f90
> +program main
same comment, if this is throwing error then shift to `tests/error/`. If this fully works then shift to `integration_tests` and register it in `integration_tests/CMakeLists.txt`.

2024-09-17 17:48 UTC, Pranavchiku commented on tests/Logical_to_Integer.f90
> +program main
If this is unrelated then, remove this

2024-09-17 19:32 UTC, jinangshah21 commented on tests/Logical_to_Integer.f90
> +program main
Removed

2024-09-17 19:42 UTC, jinangshah21 commented on tests/incompatible_rank_assign.f90
> +program main
What arguments to take in CMakelist.txt in reference?

2024-09-18 05:14 UTC, jinangshah21 commented on tests/incompatible_rank_assign.f90
> +end program
I have registered the test and I think PR ready to merge now.

2024-09-18 06:17 UTC, certik commented on src/libasr/intrinsic_func_registry_util_gen.py
> +    "Digits",
I see, I guess it fails some tests otherwise in this PR?

2024-09-18 06:17 UTC, certik approved these changes
I think this looks good to me now. Thanks!

2024-09-18 06:18 UTC, merged