Error for different shape on array Assignment
lfortran/lfortran pull request #4862
Opened 2024-09-21 07:05 UTC by jinangshah21

Done these things :
1) Improved Error Message for incompatible ranks.
2) Throw Error if different shape on array assignment.

2024-09-21 14:21 UTC, Pranavchiku commented
Okay so you just need to rebase this PR, follow the steps show below to clean git history ( assuming you are in temp_branch )

```
git checkout -b temp_branch_2
git checkout main
git pull origin main
git checkout temp_branch
git rebase main
git push <your_remote> temp_branch -f
```

2024-09-21 14:24 UTC, Pranavchiku requested changes
This PR looks good to me, clean commit history and ping if any problem occurs.

2024-09-22 09:19 UTC, gxyd commented
I moved it to "draft", as Pranav left some comments which need to be addressed.

2024-09-22 19:40 UTC, Pranavchiku requested changes
apply the following changes, build and update references

2024-09-22 19:40 UTC, Pranavchiku commented on src/lfortran/semantics/ast_body_visitor.cpp
> +        if (target_type->type == ASR::ttypeType::Array && value_type->type == ASR::ttypeType::Array) {
```suggestion
        if (target_type != nullptr && value_type != nullptr && ASRUtils::is_array(target_type) && ASRUtils::is_array(value_type)) {
```

2024-09-22 19:40 UTC, Pranavchiku commented on src/lfortran/semantics/ast_common_visitor.h
> +                    if(lhs_rank!=rhs_rank){
```suggestion
                    if ( lhs_rank != rhs_rank ) {
```

2024-09-22 19:41 UTC, Pranavchiku commented on tests/reference/asr-arrays_reshape_14-913f34e.stderr
> +[2m  Binary file "[0m[1m[35m/lib/x86_64-linux-gnu/libc.so.6[39m[0m[2m", in <invalid>[0m
this should not be updated, with the suggested changes this shall go.

2024-09-22 20:44 UTC, Pranavchiku approved these changes
this looks good to me. I'll wait for one more review before merging.

2024-09-22 20:45 UTC, Pranavchiku commented
A good practice is to start using conventional commits, you may read more about it from https://www.conventionalcommits.org/en/v1.0.0/. Also, make sure you resolve conversation after addressing the changes.

2024-09-23 03:53 UTC, certik approved these changes
I think this looks great! Thanks for fixing it. I left a minor comment that can be addressed in a subsequent PR.

2024-09-23 03:53 UTC, certik commented on src/lfortran/semantics/ast_common_visitor.h
> +                                    throw SemanticError("Incompatible shape of array on assignment on dimension " + std::to_string(i) +
We should count from 1, not from 0:
```suggestion
                                    throw SemanticError("Incompatible shape of array on assignment on dimension " + std::to_string(i+1) +
```

2024-09-23 03:53 UTC, merged