tsest : MRE moved to integration_tests
lfortran/lfortran pull request #4959
Opened 2024-10-02 17:10 UTC by jinangshah21

1) Addresses [Issue #4948](https://github.com/lfortran/lfortran/issues/4948) (moved MRE into integration tests)

2024-10-02 18:20 UTC, kmr-srbh requested changes
@jinangshah21 please register this test inside `integration_tests/CMakeLists.txt`, then remove it from `tests/tests.toml`. After making the above changes, please delete the created reference files. Ideally, as this test does not throw an error and the ASR output is not required for future use, we should not have this as a reference test.

- Reference tests -> for keeping a reference of error messages or AST/ASR/LLVM output.
- Integration tests -> general testing of features and fixes.

2024-10-02 18:25 UTC, jinangshah21 commented
This test is generating error for llvm, So till ASR is only true for this test. But moving it to CMakeLists will throw error for integration tests.

2024-10-02 18:44 UTC, kmr-srbh commented
> This test is generating error for llvm, So till ASR is only true for this test. But moving it to CMakeLists will throw error for integration tests.

Could you please post the error you get? If we have an error, then it is a bug we need to fix.

2024-10-03 05:46 UTC, jinangshah21 commented
> > This test is generating error for llvm, So till ASR is only true for this test. But moving it to CMakeLists will throw error for integration tests.
> 
> Could you please post the error you get? If we have an error, then it is a bug we need to fix.
This is [llvm error](https://github.com/lfortran/lfortran/pull/4915#issuecomment-2383386423) for this test.

2024-10-03 06:35 UTC, jinangshah21 commented on tests/tests.toml
>  asr_implicit_interface_and_typing = true
But it is giving error for llvm so I think we can keep reference test of ASR in lfortran and register in integration tests with gfortran.

2024-10-03 12:57 UTC, Pranavchiku approved these changes
The test does not work with latest main. It just generates ASR.

2024-10-03 14:03 UTC, certik commented
Register it and run it with gfortran at least, if we can't compile with lfortran yet.

2024-10-03 15:41 UTC, certik approved these changes

2024-10-03 15:42 UTC, merged