Error for negative start index in string section
lfortran/lfortran pull request #4976
Opened 2024-10-04 06:13 UTC by AnshMehta1

2024-10-04 08:24 UTC, AnshMehta1 commented
Ok , so the PR is ready now for merging . Previous PR was lacking the compile time check for 0 start index which is included in this PR amd thus , the PR is now ready for merging.

2024-10-04 12:19 UTC, Pranavchiku commented on src/lfortran/semantics/ast_common_visitor.h
> +                    if((x.m_args[0].m_start->type) == AST::exprType::UnaryOp){
```fortran
program main
    implicit none
    character(len=8) :: s
    s = "lfortran"
    print*, "s:", s(+(1+9):4)
 end program
```

With this PR gives:

```console
% lfortran a.f90 
semantic error: The first index in string section is less than 1
 --> a.f90:5:19
  |
5 |     print*, "s:", s(+(1+9):4)
  |                   ^^^^^^^^^^^ 


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

This is because you are testing if it is UnaryOp.

2024-10-04 12:21 UTC, Pranavchiku requested changes
That is why we shall handle it in ASR as shown in diff https://github.com/lfortran/lfortran/pull/4962#discussion_r1786176796

2024-10-04 13:36 UTC, certik commented on src/lfortran/semantics/ast_common_visitor.h
> +                    }
These tests should happen using ASR, not AST.

2024-10-04 13:40 UTC, AnshMehta1 commented on src/lfortran/semantics/ast_common_visitor.h
> +                    }
It's a compile-time test and thus, I included accordingly.

2024-10-04 13:42 UTC, AnshMehta1 commented
I resolved the issue raised by pranav regarding UnaryOp and I think , now , it is working appropriately.

2024-10-04 14:12 UTC, certik commented on src/lfortran/semantics/ast_common_visitor.h
> +                    }
You are using AST to do this check, however at this point you already have ASR available, see just the line below this:
```
                    return ASR::make_StringSection_t(al, loc, v_Var, l,
                            r, casted_step, char_type, arr_ref_val);
```
In here all parts are ASR. So you likely want to use `r` itself, and check for the negative indexing.

2024-10-04 14:13 UTC, certik commented on src/lfortran/semantics/ast_common_visitor.h
> +                    if((x.m_args[0].m_start->type) == AST::exprType::UnaryOp){
@AnshMehta1 you should address this as well. If you do the ASR change as I commented here: https://github.com/lfortran/lfortran/pull/4976#discussion_r1787782968, then it will automatically resolve this issue.

Also, please add the above into the test case also.

2024-10-04 15:08 UTC, AnshMehta1 commented on src/lfortran/semantics/ast_common_visitor.h
> +                    }
Ok , so I will making changes for this.

2024-10-04 15:08 UTC, AnshMehta1 commented on src/lfortran/semantics/ast_common_visitor.h
> +                    if((x.m_args[0].m_start->type) == AST::exprType::UnaryOp){
Ok , will add the test

2024-10-04 19:32 UTC, AnshMehta1 commented
Ok , So I handled 0 start index check using ASR as mentioned in https://github.com/lfortran/lfortran/pull/4976#discussion_r1787782968. 
Also , I added the test given by Pranav in PR  : 

program main
    implicit none
    character(len=8) :: s
    s = "lfortran"
    print*, "s:", s(+(1+9):14)
 end program

2024-10-05 00:24 UTC, certik reviewed
Thanks for the updates. I think now the tests are using ASR, which is good. We just have to get the logic correct. I left some questions.

2024-10-05 00:24 UTC, certik commented on tests/errors/string_negative_start_index2.f90
> + end program
This test compiles, so it should go into integration_tests, not into tests/errors. Only things that trigger errors should go into tests/errors.

2024-10-05 00:24 UTC, certik commented on src/lfortran/semantics/ast_common_visitor.h
> +                                    throw SemanticError("The first index in string section is less than 1", loc);
Is `offset` always equal to 1 here?

2024-10-05 00:24 UTC, certik commented on src/lfortran/semantics/ast_common_visitor.h
> +                                        throw SemanticError("The first index in string section is less than 1", loc);
The actual test here is that the left value is 0. What happens if the left value here is -1? Would it not give an error message?

2024-10-05 05:39 UTC, Pranavchiku commented on src/lfortran/semantics/ast_common_visitor.h
> +                                    throw SemanticError("The first index in string section is less than 1", loc);
Yes, it is always `1`

2024-10-05 05:39 UTC, Pranavchiku commented on src/lfortran/semantics/ast_common_visitor.h
> +                                    throw SemanticError("The first index in string section is less than 1", loc);
I think only this is sufficient to throw error.

2024-10-05 05:40 UTC, Pranavchiku commented on src/lfortran/semantics/ast_common_visitor.h
> +                    if(l != nullptr){
You don't need this diff, the above one is sufficient to throw error.

2024-10-05 05:40 UTC, Pranavchiku requested changes
left comments above

2024-10-05 09:05 UTC, AnshMehta1 commented on src/lfortran/semantics/ast_common_visitor.h
> +                                    throw SemanticError("The first index in string section is less than 1", loc);
Actually , when start index is 0 when no lower bound is mentioned , then an error must be thrown. This part is not able to do so ->

else if ( ASR::is_a<ASR::IntegerUnaryMinus_t>(*args[0].m_left) ) {
                            ASR::expr_t* value = ASRUtils::expr_value(args[0].m_left);
                            if ( value ) {
                                int64_t a = ASR::down_cast<ASR::IntegerConstant_t>(value)->m_n - offset;
                                if ( a < 0 ) {
                                    throw SemanticError("The first index in string section is less than 1", loc);

Thus , I added another check for 0 start index using ASR.

2024-10-05 09:08 UTC, AnshMehta1 commented on src/lfortran/semantics/ast_common_visitor.h
> +                                        throw SemanticError("The first index in string section is less than 1", loc);
Their is a test before this test which handles negative start index quite efficiently handling all the edge cases. After that test , this test is done for 0 start index.

2024-10-05 09:19 UTC, AnshMehta1 commented on src/lfortran/semantics/ast_common_visitor.h
> +                    if(l != nullptr){
As explained  in above comment , this test is needed for identifying 0 start index.

2024-10-05 10:18 UTC, AnshMehta1 commented on src/lfortran/semantics/ast_common_visitor.h
> +                                    throw SemanticError("The first index in string section is less than 1", loc);
Actuallu , for 0 start index , code was not going in above part and thus , I handled it separately and so , I am removing offset thing as it is not needed now.

2024-10-05 10:41 UTC, AnshMehta1 commented
Hmm... , Their is some issue in these PR because of new referrences and I am closing it and am creating a new PR.

2024-10-05 10:41 UTC, closed without merging

2024-10-05 18:44 UTC, certik commented
Always post the new link, so that we can find it: https://github.com/lfortran/lfortran/pull/4989.

2024-10-05 18:58 UTC, AnshMehta1 commented
> Always post the new link, so that we can find it: #4989.

Ok , Will definately take care of this from next time.