feat:Multiple control statements
lfortran/lfortran pull request #4988
Opened 2024-10-05 10:40 UTC by adit4443ya

Extends [PR](https://github.com/lfortran/lfortran/pull/4920) and towards [Issue](https://github.com/lfortran/lfortran/issues/4900)
Next phase of implementing Multiple Control Statements

2024-10-05 12:06 UTC, Pranavchiku commented on integration_tests/openmp_36.f90
> +program openmp_36
If this works with gfortran then register it in integration test without `llvm` label and register a corresponding reference test to generate ASR for LFortran

2024-10-05 12:07 UTC, Pranavchiku commented on src/libasr/codegen/asr_to_julia.cpp
> +        }
Here, we need to see if `julia` has something similar to do concurrent. The current logic will create `n` number of do loops with same body where `n` is number of control statements

2024-10-05 12:07 UTC, Pranavchiku commented on src/libasr/pass/openmp.cpp
> +            // LCOMPILERS_ASSERT(do_loop.n_head == 1);
just remove line, don't add as a comment

2024-10-05 12:07 UTC, Pranavchiku requested changes
left initial comments, the logic seems fine to me.

2024-10-05 18:50 UTC, certik commented on src/libasr/codegen/asr_to_julia.cpp
> +        }
I would not lose too much time with Julia right now, any workaround there is fine.

2024-10-06 05:14 UTC, Pranavchiku requested changes
Update reference tests and CI shall pass:

```console
rm -rf ./tests/reference/*
./run_tests.py -u
```

2024-10-06 09:40 UTC, Pranavchiku approved these changes

2024-10-06 09:40 UTC, merged

2024-10-06 09:41 UTC, Pranavchiku commented
I am sorry I by mistake merged it. I had to do `squash and merge`. I apologise this was lack of attention while merging and assure this won't happen in future.