Error for negative start index in string section_issue#4871
lfortran/lfortran pull request #4989
Opened 2024-10-05 10:44 UTC by AnshMehta1

2024-10-05 11:13 UTC, AnshMehta1 commented
Changes made from previous PR :- 

1) A test which just compiles and doesn't throw error was added in integration tests with referrences updated ->
```
program main
    implicit none
    character(len=8) :: s
    s = "lfortran"
    print*, "s:", s(+(1+1):4)
 end program
```

2) Removed offset thing as it was supposed to handle 0 start index but the code with 0 start index was ,nevertheless , not going into that section ->
```
else if ( ASR::is_a<ASR::IntegerUnaryMinus_t>(*args[0].m_left) ) {
    ASR::expr_t* value = ASRUtils::expr_value(args[0].m_left);
    if ( value ) {
        int64_t a = ASR::down_cast<ASR::IntegerConstant_t>(value)->m_n;
        if ( a < 0 ) {
            throw SemanticError("The first index in string section is less than 1", loc);
        } else {
            a_value = ASRUtils::EXPR((ASR::make_IntegerConstant_t(al, loc,
                            a, int_type)));
        }
    }
}
```

3) Added test for 0 start index using ASR node ->
```
if(l != nullptr){

    if (ASR::is_a<ASR::IntegerBinOp_t>(*l)) {

        ASR::IntegerBinOp_t *num_expr = ASR::down_cast<ASR::IntegerBinOp_t>(l);

        if(num_expr != nullptr){
            ASR::expr_t *left_bound = num_expr->m_left;

            if(left_bound != nullptr && ASR::is_a<ASR::IntegerConstant_t>(*left_bound)){

                ASR::IntegerConstant_t *left_bound_value = ASR::down_cast<ASR::IntegerConstant_t>(left_bound);

                if(left_bound_value != nullptr && ((left_bound_value->m_n) == 0)){
                    throw SemanticError("The first index in string section is less than 1", loc);
                }
            }
        }
    } 
}
```

2024-10-05 12:09 UTC, Pranavchiku commented on tests/tests.toml
>  asr = true
As the test runs well with LFortran, we don't need a reference test. Just register it in `CMakeLists.txt` inside `integration_tests` directory.

2024-10-05 12:14 UTC, Pranavchiku commented on src/lfortran/semantics/ast_common_visitor.h
> +                        }
```suggestion
                        else if ( ASR::is_a<ASR::IntegerUnaryMinus_t>(*args[0].m_left) ) {
                            ASR::expr_t* value = ASRUtils::expr_value(args[0].m_left);
                            if ( value ) {
                                int64_t a = ASR::down_cast<ASR::IntegerConstant_t>(value)->m_n - offset;
                                a_value = ASRUtils::EXPR((ASR::make_IntegerConstant_t(al, loc,
                                                    a, int_type)));
                            }
                        }
                         if ( a_value != nullptr ) {
                            int64_t a = ASR::down_cast<ASR::IntegerConstant_t>(a_value))->m_n;
                            if ( a < 0 ) throw SemanticError("The first index in string section is less than 1", loc);
                         } 
```

I think this should work.

2024-10-05 12:15 UTC, Pranavchiku commented on src/lfortran/semantics/ast_common_visitor.h
> +                    }
You may remove this block and apply the comment given above. Try if it works then that should be fine.

2024-10-05 12:16 UTC, Pranavchiku requested changes
left few comments above

2024-10-05 14:31 UTC, AnshMehta1 commented
> left few comments above

Ok , So made the changes and now things are working well.

2024-10-05 18:45 UTC, certik commented on integration_tests/CMakeLists.txt
> +RUN(NAME string_negative_start_index2 LABELS gfortran)
Test with LFortran too:
```suggestion
RUN(NAME string_negative_start_index2 LABELS gfortran llvm)
```

2024-10-05 21:09 UTC, certik commented on src/lfortran/semantics/ast_common_visitor.h
> +                            if ( a < 0 ) throw SemanticError("The first index in string section is less than 1", loc);
This test condition s for less than 0, not less than 1. So either the condition or the error message should change.

2024-10-05 22:03 UTC, AnshMehta1 commented on src/lfortran/semantics/ast_common_visitor.h
> +                            if ( a < 0 ) throw SemanticError("The first index in string section is less than 1", loc);
Actually , value of offset is 1 which I subtracted and thus , a < 0 condition is start index less than 1 . So, both the things are matching.

2024-10-06 05:12 UTC, Pranavchiku commented on src/lfortran/semantics/ast_common_visitor.h
> +                            if ( a < 0 ) throw SemanticError("The first index in string section is less than 1", loc);
```suggestion
                            if ( a < -1 ) throw SemanticError("The first index in string section is less than 0", loc);
```

This should take care of it.

2024-10-06 07:15 UTC, AnshMehta1 commented on src/lfortran/semantics/ast_common_visitor.h
> +                            if ( a < 0 ) throw SemanticError("The first index in string section is less than 1", loc);
I think , for 0 start index is not valid in fortran and so error must be thrown for start index <= 0 or < 1 and so both the error message and condition are correct . I also checked the error message on my system and they are working well . So , I don't think that we have to change anything.

2024-10-07 13:43 UTC, Pranavchiku approved these changes

2024-10-10 16:26 UTC, certik approved these changes

2024-10-10 16:26 UTC, merged