feat: Collapse clause support
lfortran/lfortran pull request #5011
Opened 2024-10-08 12:16 UTC by adit4443ya

Towards [Issue](https://github.com/lfortran/lfortran/issues/4818)
Starting with minimal changes and two different type of test cases

2024-10-08 14:33 UTC, Pranavchiku commented on src/lfortran/semantics/ast_body_visitor.cpp
> +                        size_t collapse_level = std::stoi(collapse_value_str); // Get the value of N
```suggestion
```

this variable is unused

2024-10-08 14:33 UTC, Pranavchiku reviewed
let's get CI working and then mark it as ready to review.

2024-10-20 14:46 UTC, certik commented
Let's first try to implement it in the AST->ASR, it might not be that difficult --- you have to track the collapse status, and when you encounter a for loop, just add it to the same DoConcurrent head. If we fundamentally can't do it, we can write a pass to do it later, but there is always a cost of a new pass (slower compilation), so if we can handle it right away, I think it would be better. I think if there are statements in between, it's ok --- we can still just move the inner loop to the head, there shouldn't be a problem with order of statements.

2024-10-21 02:51 UTC, Pranavchiku commented on src/libasr/pass/for_all.cpp
> +            ASR::make_DoConcurrentLoop_t(al, loc, heads.p, heads.n, nullptr, 0, nullptr, 0, nullptr, 0, body.p, body.size(), 1)
```suggestion
            ASR::make_DoConcurrentLoop_t(al, loc, heads.p, heads.n, nullptr, 0, nullptr, 0, nullptr, 0, body.p, body.size(), 0)
```

If no collapse, then make it `0`.

2024-10-21 02:52 UTC, Pranavchiku commented on src/lfortran/semantics/ast_body_visitor.cpp
> +                body.size(),1);
```suggestion
                body.size(),0);
```

no collapse --> 0

2024-10-21 02:52 UTC, Pranavchiku commented on src/lfortran/semantics/ast_body_visitor.cpp
> +                int64_t collapse_level = 1;
```suggestion
                int64_t collapse_level = 0;
```

2024-10-21 02:53 UTC, Pranavchiku commented on src/lfortran/semantics/ast_body_visitor.cpp
> +                        collapse_level = std::stoi(collapse_value_str); // Get the value of N
You can do this in subsequent PRs, check if `collapse(   9 )` is supported. I mean to say you can strip whitespaces before trying to access `9` from it.

2024-10-21 02:53 UTC, Pranavchiku commented on integration_tests/openmp_37.f90
> +! !$omp end parallel do
Let's remove this comment to avoid any confusion.

2024-10-21 02:54 UTC, Pranavchiku requested changes
Left a few comments, this PR looks good, just apply the changes and this will be good to merge.

2024-10-21 09:50 UTC, Pranavchiku commented
Let's get CI passing

2024-10-21 17:47 UTC, Pranavchiku requested changes
update test reference and this PR will be good.

2024-10-21 18:41 UTC, certik commented
Hold on: per https://github.com/lfortran/lfortran/pull/5011#issuecomment-2425022382 I think we should try to get this done in AST -> ASR.

2024-10-21 18:42 UTC, certik commented on integration_tests/openmp_38.f90
> +end program
These two tests must be registered.

2024-10-21 18:43 UTC, certik commented on integration_tests/openmp_38.f90
> +        do iz = 1, nz
Add a test that has some statement between one of these loops.

2024-10-22 17:39 UTC, certik commented on integration_tests/openmp_39.f90
> +!$omp parallel do collapse(3) private(iy, ix, iz)
Add another test for collapse(2) here. I think that case is not tested with the inner most loop left intact.

2024-10-22 17:40 UTC, certik commented
You need to run the tests somewhere. Register them in `tests/test.toml` and check "asr".

2024-10-22 17:42 UTC, certik commented on src/lfortran/semantics/ast_body_visitor.cpp
> +    int collapse_status = 0;
The `collapse_status` is just 0 or 1? Make it a bool then.

Where is it reset back to 0? I don't see that part.

2024-10-22 17:43 UTC, adit4443ya commented on integration_tests/openmp_39.f90
> +!$omp parallel do collapse(3) private(iy, ix, iz)
Here in this test there are 4 nested loops , I intentionally used collapse(3) so leave last loop intact, if used collapse(2) it will result in this
```shell
(DoConcurrentLoop
                        [((Var 2 ix)
                        (IntegerConstant 1 (Integer 4) Decimal)
                        (Var 2 nx)
                        ())
                        ((Var 2 iy)
                        (IntegerConstant 1 (Integer 4) Decimal)
                        (Var 2 ny)
                        ())]
                        []
                        [(Var 2 iy)
                        (Var 2 ix)
                        (Var 2 iz)]
                        []
                        [(Print
                            (StringFormat
                                ()
                                [(StringConstant
                                    "iy->"
                                    (Character 1 4 () PointerString)
                                )
                                (Var 2 iy)
                                (StringConstant
                                    "ix->"
                                    (Character 1 4 () PointerString)
                                )
                                (Var 2 ix)]
                                FormatFortran
                                (Character -1 0 () PointerString)
                                ()
                            )
                        )
                        (DoLoop
                            ()
                            ((Var 2 iz)
                            (IntegerConstant 1 (Integer 4) Decimal)
                            (Var 2 nz)
                            ())
                            [(DoLoop
                                ()
                                ((Var 2 ik)
                                (IntegerConstant 1 (Integer 4) Decimal)
                                (Var 2 nk)
                                ())
                                [(Print
                                    (StringFormat
                                        ()
                                        [(StringConstant
                                            "iy->"
                                            (Character 1 4 () PointerString)
                                        )
                                        (Var 2 iy)
                                        (StringConstant
                                            "ix->"
                                            (Character 1 4 () PointerString)
                                        )
                                        (Var 2 ix)
                                        (StringConstant
                                            "iz->"
                                            (Character 1 4 () PointerString)
                                        )
                                        (Var 2 iz)
                                        (StringConstant
                                            "ik->"
                                            (Character 1 4 () PointerString)
                                        )
                                        (Var 2 ik)]
                                        FormatFortran
                                        (Character -1 0 () PointerString)
                                        ()
                                    )
                                )]
                                []
                            )]
                            []
                        )]
                    )]
                    ```

2024-10-22 17:43 UTC, certik commented
I think it looks good:
* register the tests
* we need to polish / simplifier and robustify the implementation, but the above clearly works, so this can be done.

2024-10-22 18:36 UTC, Pranavchiku approved these changes
The logic makes sense to me. The approval defines approval for logic, please apply the changes suggested above, once done, this PR can have a final review.

2024-10-22 18:43 UTC, certik commented on src/lfortran/semantics/ast_body_visitor.cpp
> +                do_concurrent->m_body = do_loop_bodies_for_collapse.p; do_concurrent->n_body = do_loop_bodies_for_collapse.size();
Yes, the logic is incorrect. We must reset collapse_status also, to handle more than one loop. :)

2024-10-23 07:03 UTC, adit4443ya commented on integration_tests/openmp_38.f90
> +        do iz = 1, nz
openmp_39 is good example for this

2024-10-23 14:42 UTC, adit4443ya commented on integration_tests/openmp_38.f90
> +end program
registered

2024-10-23 14:45 UTC, certik commented
I think you have to update reference results via `./run_tests -u`.

2024-10-23 14:47 UTC, certik commented on src/lfortran/semantics/ast_body_visitor.cpp
> +            else if (collapse_status == true && !omp_constructs.empty() && collapse_value>loop_nesting-1) {
```suggestion
            } else if (collapse_status == true && !omp_constructs.empty() && collapse_value>loop_nesting-1) {
```

2024-10-23 14:48 UTC, certik commented on src/lfortran/semantics/ast_body_visitor.cpp
> +                    for(size_t i=0;i<do_loop_heads_for_collapse.size();i++) {
These two statements are in the same block, but have different indentation.

2024-10-23 14:50 UTC, certik commented on src/lfortran/semantics/ast_body_visitor.cpp
> +                        do_concurrent_head.reserve(al, do_loop_heads_for_collapse.size()+1);
I think you don't even need to call this, since the vector will automatically reallocate as needed. You have to call `reserve` at least once, but it is called just above this.

2024-10-23 14:51 UTC, certik commented on src/lfortran/semantics/ast_body_visitor.cpp
> +                int64_t collapse_level = 0;
Is this being called at the right place? What if you have two open mp loops, the first one has collapse(2), the second does not, both in the same openmp region? Will the second loop now also be collapsed?

2024-10-23 15:56 UTC, certik commented on src/lfortran/semantics/ast_body_visitor.cpp
> +                    {
```suggestion
                    if (clause_name == "collapse") {
```

2024-10-28 12:35 UTC, adit4443ya commented
Finally got this for this example
```fortran
program main
   use omp_lib
! declare variables as required
   integer :: ny, nx, nz, nk
   integer :: iy, ix, iz, ik
   ny=3
   nx=4
   nz=5
   nk=6

!$omp parallel do private(iy, ix, iz)
   do iy = 1, ny

    !$omp parallel do collapse(2)
      do ix = 1, nx
         do ik = 1, nk
            print *,"iy->", iy,"ix->", ix
         end do
      end do
    !$omp end parallel do

    !$omp parallel do
      do ix = 1, nx
         do ik = 1, nk
            print *,"iy->", iy,"ix->", ix
         end do
      end do
    !$omp end parallel do
      
   end do
!$omp end parallel do

end program
```

```shell

(DoLoop
                        ()
                        ((Var 2 iy)
                        (IntegerConstant 1 (Integer 4) Decimal)
                        (Var 2 ny)
                        ())
                        [(DoConcurrentLoop
                            [((Var 2 ik)
                            (IntegerConstant 1 (Integer 4) Decimal)
                            (Var 2 nk)
                            ())
                            ((Var 2 ix)
                            (IntegerConstant 1 (Integer 4) Decimal)
                            (Var 2 nx)
                            ())]
                            []
                            []
                            []
                            [(Print
                                (StringFormat
                                    ()
                                    [(StringConstant
                                        "iy->"
                                        (Character 1 4 () PointerString)
                                    )
                                    (Var 2 iy)
                                    (StringConstant
                                        "ix->"
                                        (Character 1 4 () PointerString)
                                    )
                                    (Var 2 ix)]
                                    FormatFortran
                                    (Character -1 0 () PointerString)
                                    ()
                                )
                            )]
                        )
                        (DoConcurrentLoop
                            [((Var 2 ix)
                            (IntegerConstant 1 (Integer 4) Decimal)
                            (Var 2 nx)
                            ())]
                            []
                            []
                            []
                            [(DoLoop
                                ()
                                ((Var 2 ik)
                                (IntegerConstant 1 (Integer 4) Decimal)
                                (Var 2 nk)
                                ())
                                [(Print
                                    (StringFormat
                                        ()
                                        [(StringConstant
                                            "iy->"
                                            (Character 1 4 () PointerString)
                                        )
                                        (Var 2 iy)
                                        (StringConstant
                                            "ix->"
                                            (Character 1 4 () PointerString)
                                        )
                                        (Var 2 ix)]
                                        FormatFortran
                                        (Character -1 0 () PointerString)
                                        ()
                                    )
                                )]
                                []
                            )]
                        )]
                        []
                    )]
```

2024-10-28 14:07 UTC, certik commented
Register all these integration tests with "gfortran" only, to ensure they actually work.

2024-10-28 14:23 UTC, adit4443ya commented on src/lfortran/semantics/ast_body_visitor.cpp
> +                }
Its done i guess
But sorry for lack of attention to this

2024-10-28 14:40 UTC, certik commented on src/lfortran/semantics/ast_body_visitor.cpp
> +                        } else if (clause_name != "collapse") {
Why is this needed here?

2024-10-28 14:44 UTC, certik commented on tests/reference/asr-openmp_41-992f62d.stdout
> +                            (DoLoop
These 3 loops should be `DoConcurrent`, correct?

2024-10-28 17:43 UTC, adit4443ya commented on tests/reference/asr-openmp_41-992f62d.stdout
> +                            (DoLoop
hooked openmp

2024-10-28 19:02 UTC, certik commented on tests/tests.toml
> +asr_openmp = true
Just test `asr_openmp` here, we don't need to test `asr` without openmp as these tests do not add anything that would not be tested elsewhere.

2024-10-28 19:03 UTC, adit4443ya commented on src/lfortran/semantics/ast_body_visitor.cpp
> +                        } else if (clause_name != "collapse") {
without this elseif condition it will throw semantic error
`semantic error: The clause variable `2` is not declared`
As this loop is checking that if the variable used in the private n reduction are defined in symbol table or not , 
And for collapse it will always be constant value and not a variable hence ...

2024-10-28 19:07 UTC, certik commented on src/lfortran/semantics/ast_body_visitor.cpp
> +                        } else if (clause_name != "collapse") {
So we are going inside `collapse(3)`, then assigning `s = 3` and checking if `s` (that is, "3") is in the current scope? If so, that logic is incorrect. This loop should only execute for `private` and `reduction`.

2024-10-28 19:08 UTC, adit4443ya commented on tests/tests.toml
> +asr_openmp = true
done

2024-10-28 19:09 UTC, adit4443ya commented on src/lfortran/semantics/ast_body_visitor.cpp
> +                        } else if (clause_name != "collapse") {
nope we are not assigning 3 to anything here nor we are defining any variable s here

2024-10-28 19:11 UTC, adit4443ya commented on src/lfortran/semantics/ast_body_visitor.cpp
> +                        } else if (clause_name != "collapse") {
This loop is by default (or you can say accidently) checks is `2` from `collapse(2)` is defined or not  , which we do not require hence we are just by passing it via simple condition

2024-10-28 19:25 UTC, certik commented on src/lfortran/semantics/ast_body_visitor.cpp
> +                        } else if (clause_name != "collapse") {
We do not want to run this loop at all for collapse. Instead, just put this whole loop inside an if statement.

2024-10-28 19:25 UTC, certik commented on tests/tests.toml
> +asr_openmp = true
Let's not modify other tests in this PR. If it makes sense to modify `openmp_36`, then let's do it in a separate PR.

2024-10-29 10:22 UTC, adit4443ya commented
As we have example `openmp_37.f90`, `openmp_40.f90`   They should give error
[refer](https://github.com/lfortran/lfortran/issues/4818#issuecomment-2443810344)

2024-10-29 11:24 UTC, Pranavchiku commented on src/lfortran/semantics/ast_body_visitor.cpp
> +                        } else if (clause_name != "collapse") {
He means to do something like:

```diff
diff --git a/src/lfortran/semantics/ast_body_visitor.cpp b/src/lfortran/semantics/ast_body_visitor.cpp
index deee37548..bc638bc85 100644
--- a/src/lfortran/semantics/ast_body_visitor.cpp
+++ b/src/lfortran/semantics/ast_body_visitor.cpp
@@ -3825,16 +3825,15 @@ public:
                         throw SemanticError("The clause "+ clause_name
                             +" is not supported yet", loc);
                     }
+                    std::string list = clause.substr(clause.find('(')+1,
+                        clause.size()-clause_name.size()-2);
+                    ASR::reduction_opType op = ASR::reduction_opType::ReduceAdd; // required for reduction
                     if (clause_name == "collapse") {
-                        std::string collapse_value_str = clause.substr(
-                            clause.find('(') + 1, clause.size() - clause_name.size() - 2);
-                        collapse_value = std::stoi(collapse_value_str); // Get the value of N
+                        collapse_value = std::stoi(list.erase(0, list.find_first_not_of(" "))); // Get the value of N
                         openmp_collapse = true;
                         do_loop_heads_for_collapse.reserve(al, collapse_value);do_loop_bodies_for_collapse={};
+                        continue;
                     }
-                    std::string list = clause.substr(clause.find('(')+1,
-                        clause.size()-clause_name.size()-2);
-                    ASR::reduction_opType op = ASR::reduction_opType::ReduceAdd; // required for reduction
                     if (clause_name == "reduction") {
                         std::string reduction_op = list.substr(0, list.find(':'));
                         if ( reduction_op == "+" ) {
@@ -3870,7 +3869,7 @@ public:
                             } else {
                                 m_shared.push_back(al, v);
                             }
-                        } else if (clause_name != "collapse") {
+                        } else {
                             throw SemanticError("The clause variable `"+ s
                                 +"` is not declared", loc);
                         }
```

2024-10-29 11:26 UTC, Pranavchiku commented on src/lfortran/semantics/ast_body_visitor.cpp
> +                        } else if (clause_name != "collapse") {
Marking this as resolved, will be pushing the diff.

2024-10-29 11:32 UTC, Pranavchiku commented on tests/reference/asr_openmp-openmp_38-2731560.stdout
> +                        )
There is no way to identify which DoLoop this print statement belongs to, but eventually we'll be modifying variable limits and thus this shall be taken care of.

2024-10-29 11:35 UTC, Pranavchiku commented on tests/reference/asr_openmp-openmp_37-2c7ae83.stdout
> +                    )]
This is incorrect, we shall either have a `do iz = 1, nz` or if it is also going to be collapsed then we are missing `print *,"iy->", iy,"iz->", iz`

2024-10-29 11:43 UTC, Pranavchiku requested changes
Left comments above on test references, we need to fix it. Try to do it, else we can discuss it in our meeting today night.

2024-10-29 12:22 UTC, adit4443ya commented on tests/reference/asr_openmp-openmp_40-b0e7ea3.stdout
> +                    (DoLoop
Try without collapse you will see same doloop, then in inner body you will see doconcurrent 
this is maybe due to nested pragmas ,

2024-10-29 13:55 UTC, Pranavchiku commented on tests/reference/asr_openmp-openmp_40-b0e7ea3.stdout
> +                    (DoLoop
okay, if it is a bug in main as well then it is fine.

2024-10-29 17:19 UTC, certik commented on src/lfortran/semantics/ast_body_visitor.cpp
> +            } else if (openmp_collapse == true && !omp_constructs.empty() && collapse_value>loop_nesting-1-omp_constructs.size()+1) {
I think there is a bug on this line. All these variables should be converted to int. Right now they are "unsigned int". The `loop_nesting` can be 0. When you do `loop_nesting - 1`, it will wraparound. Same with `loop_nesting  - omp_constructs.size()`, if it ever becomes negative, it wraps around, invalidating the `>` comparison.

Solution: turn all these variables into `int`, do not use `unsigned int`. Simply view "unsigned int" as a "modular integer". You do not want to do modular arithmetic here.

2024-10-29 17:22 UTC, certik commented on tests/reference/asr_openmp-openmp_37-2c7ae83.stdout
> +                                ((Var 2 ik)
This "ik" loop should have been part of the DoConcurrent head.

2024-10-29 17:23 UTC, certik commented on tests/reference/asr_openmp-openmp_37-2c7ae83.stdout
> +                    (DoLoop
This loop should be DoConcurrent, right?

2024-10-29 17:23 UTC, certik commented on tests/reference/asr_openmp-openmp_37-2c7ae83.stdout
> +                            ((Var 2 ix)
`ix` and `ik` must be flipped.

2024-10-29 17:26 UTC, certik commented on tests/reference/asr_openmp-openmp_39-aaf2ba8.stdout
> +                        (Var 2 ny)
flip `ix`, `iy`

2024-10-29 18:12 UTC, adit4443ya commented on tests/reference/asr_openmp-openmp_37-2c7ae83.stdout
> +                    (DoLoop
- refer [this comment](https://github.com/lfortran/lfortran/pull/5011#discussion_r1820856198)

2024-10-29 18:25 UTC, Pranavchiku commented on src/lfortran/semantics/ast_body_visitor.cpp
> +    size_t collapse_value=0;
```suggestion
    int collapse_value=0;
```

2024-10-29 18:29 UTC, Pranavchiku commented on tests/reference/asr_openmp-openmp_37-2c7ae83.stdout
> +                    (DoLoop
This is a bug in main as well. Let's open a dedicated issue and fix it later. Created https://github.com/lfortran/lfortran/issues/5207 for it.

2024-10-29 18:33 UTC, Pranavchiku commented on src/lfortran/semantics/ast_body_visitor.cpp
> +                    }
```suggestion
                     openmp_collapse = false;
```

2024-10-29 18:42 UTC, Pranavchiku approved these changes
Loop order is fixed, the other two changes can be done in next PRs. This looks good to me, if there are any bugs it is isolated under `--openmp` flag and won't affect main compilation.

2024-10-29 18:59 UTC, merged

2024-10-29 19:02 UTC, certik approved these changes
I think this is good now to merge. The three added test cases seem to be correct at ASR level.

Thanks for finishing it!

@adit4443ya do you mind please submitting a new PR fixing the "unsigned int" issue?

2024-10-29 19:03 UTC, adit4443ya commented
Yeah sure tomorrow i will do it

2024-10-30 07:34 UTC, adit4443ya commented on src/lfortran/semantics/ast_body_visitor.cpp
> +            } else if (openmp_collapse == true && !omp_constructs.empty() && collapse_value>loop_nesting-1-omp_constructs.size()+1) {
Can it be done with simple fix ? @certik @Pranavchiku , if it's correct ...
```diff
diff --git a/src/lfortran/semantics/ast_body_visitor.cpp b/src/lfortran/semantics/ast_body_visitor.cpp
index d74a09b42..fa7b57d58 100644
--- a/src/lfortran/semantics/ast_body_visitor.cpp
+++ b/src/lfortran/semantics/ast_body_visitor.cpp
@@ -3447,7 +3447,7 @@ public:
                 do_concurrent->m_head = do_concurrent_head.p;
                 do_concurrent->n_head = do_concurrent_head.size();
                 tmp = (ASR::asr_t*) do_concurrent;
-            } else if (openmp_collapse == true && !omp_constructs.empty() && collapse_value>loop_nesting-1-omp_constructs.size()+1) {
+            } else if (openmp_collapse == true && !omp_constructs.empty() && static_cast<int>(collapse_value) > (static_cast<int>(loop_nesting) - 1 - static_cast<int>(omp_constructs.size())) + 1) {
```

2024-10-30 08:24 UTC, adit4443ya commented on src/lfortran/semantics/ast_body_visitor.cpp
> +            } else if (openmp_collapse == true && !omp_constructs.empty() && collapse_value>loop_nesting-1-omp_constructs.size()+1) {
made pr #5210