fix: optional arguments in findLoc()
lfortran/lfortran pull request #5019
Opened 2024-10-08 19:19 UTC by jinangshah21

Fixes #4679.
Still not Complete. I am keeping it in draft.

2024-10-08 19:26 UTC, certik commented
Add a test, so that we can see what exact features you are trying to implement.

2024-10-08 19:52 UTC, Pranavchiku requested changes
Check if mask is an array then only create an array item

2024-10-09 14:10 UTC, gxyd commented on src/libasr/pass/intrinsic_array_function_registry.h
> +        if( args[2] && !args[3] && is_logical(*expr_type(args[2])) ){
The problem with an approach like this is that a similar problem exists for a lot of intrinsic functions, like: `minval`, `maxval`, `findloc` etc.

E.g.; documentation of GFortran here for `maxval`: https://gcc.gnu.org/onlinedocs/gfortran/MAXVAL.html with syntax:
```f90
Syntax:
RESULT = MAXVAL(ARRAY, DIM [, MASK])
RESULT = MAXVAL(ARRAY [, MASK])
```

So, a similar check might be needed for a lot of other intrinsic functions as well, where the `dim` and `mask` are assigned depending on "position" and "type".

With the approach described above, it would lead to a lot of repeated code and hence a possibility to  miss something or cause a bug.

I ideally would be more happy with a general approach here.

2024-10-09 14:12 UTC, gxyd commented on integration_tests/intrinsics_301.f90
> +    if (any(findloc(x4, y4, mask3) /= 1)) error stop
Also, we don't have a test case for when `dim` i.e. scalar is passed as an argument, there are test cases for when `dim` is passed as a keyword-argument though.

2024-10-09 14:12 UTC, gxyd commented on integration_tests/intrinsics_301.f90
> +    if (any(findloc(x4, y4, mask3) /= 1)) error stop
i.e. something like:
```f90
findloc(x4, y4, 1)
```

2024-10-09 14:13 UTC, gxyd commented on src/libasr/pass/intrinsic_array_function_registry.h
> +        if( args[2] && !args[3] && is_logical(*expr_type(args[2])) ){
@HarshitaKalani thoughts?

2024-10-09 16:13 UTC, HarshitaKalani commented on src/libasr/pass/intrinsic_array_function_registry.h
> +        if( args[2] && !args[3] && is_logical(*expr_type(args[2])) ){
I agree completely. I would also like to have a general approach for this. 
Also, the current approach will have high chances of bugs. For example, the current implementation would not handle a case like:
```fortran
program main
    print *, findloc([1, 2, 3], 2, .true., .true.)
end program
```
```console
$ gfortran a.f90 && ./a.out
a.f90:2:35:

    2 |     print *, findloc([1, 2, 3], 2, .true., .true.)
      |                                   1
Error: ‘dim’ argument of ‘findloc’ intrinsic at (1) must be INTEGER
$ lfortran a.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/harshita/Desktop/lfortran/src/bin/lfortran", in _start
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2668, in main
    return main_app(argc, argv);
  File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2611, in main_app(int, char**)
    err = compile_src_to_object_file(arg_file, tmp_o, false,
...

  File "/home/harshita/Desktop/lfortran/src/libasr/pass/intrinsic_array_function_registry.h", line 3252, in LCompilers::ASRUtils::FindLoc::create_FindLoc(Allocator&, LCompilers::Location const&, LCompilers::Vec<LCompilers::ASR::expr_t*>&, LCompilers::diag::Diagnostics&)
    dim = ASR::down_cast<ASR::IntegerConstant_t>(dim_expr) -> m_n;
AssertFailed: is_a<T>(*f)
```

2024-10-09 16:26 UTC, certik commented on src/libasr/pass/intrinsic_array_function_registry.h
> +        if( args[2] && !args[3] && is_logical(*expr_type(args[2])) ){
The right design in my opinion is to use the "overload_id" in ASR for this. We discussed exactly this issue for a similar function, I can't remember which one. You decide on the signatures that you will support, let's just say the following:
```
minloc(array) ! overload_id = 0
minloc(array, dim) ! overload_id = 1
minloc(array, dim, mask) ! overload_id = 2
```
And for each case (`overload_id`) all arguments are required and never null (it could be that some arguments have to have their default values specified). So you never write code like this:
```
 if( args[2] && !args[3] && is_logical(*expr_type(args[2])) 
```
Rather, you write code like `if (overload_id == 2) { /* array, dim, mask is present and valid, handle this case */ }`.

Let me know if you have any questions about this, or want to discuss more.

2024-10-09 16:34 UTC, HarshitaKalani commented on src/libasr/pass/intrinsic_array_function_registry.h
> +        if( args[2] && !args[3] && is_logical(*expr_type(args[2])) ){
Yes, we did it for `minloc` here: https://github.com/lfortran/lfortran/issues/4456. If we follow this, the implementation would be more clean and robust.
One can refer: https://github.com/lfortran/lfortran/pull/4461.

2024-10-09 18:18 UTC, certik commented on src/libasr/pass/intrinsic_array_function_registry.h
> +        if( args[2] && !args[3] && is_logical(*expr_type(args[2])) ){
Yes, that was it, thanks for finding it. @jinangshah21 go ahead and follow the same design here.

2024-10-09 18:49 UTC, jinangshah21 commented on src/libasr/pass/intrinsic_array_function_registry.h
> +        if( args[2] && !args[3] && is_logical(*expr_type(args[2])) ){
> I agree completely. I would also like to have a general approach for this. Also, the current approach will have high chances of bugs. For example, the current implementation would not handle a case like:
> 
> ```fortran
> program main
>     print *, findloc([1, 2, 3], 2, .true., .true.)
> end program
> ```
> 
> ```
> $ gfortran a.f90 && ./a.out
> a.f90:2:35:
> 
>     2 |     print *, findloc([1, 2, 3], 2, .true., .true.)
>       |                                   1
> Error: ‘dim’ argument of ‘findloc’ intrinsic at (1) must be INTEGER
> $ lfortran a.f90
> Internal Compiler Error: Unhandled exception
> Traceback (most recent call last):
>   Binary file "/home/harshita/Desktop/lfortran/src/bin/lfortran", in _start
>   File "./csu/../csu/libc-start.c", line 392, in __libc_start_main
>   File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main
>   File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2668, in main
>     return main_app(argc, argv);
>   File "/home/harshita/Desktop/lfortran/src/bin/lfortran.cpp", line 2611, in main_app(int, char**)
>     err = compile_src_to_object_file(arg_file, tmp_o, false,
> ...
> 
>   File "/home/harshita/Desktop/lfortran/src/libasr/pass/intrinsic_array_function_registry.h", line 3252, in LCompilers::ASRUtils::FindLoc::create_FindLoc(Allocator&, LCompilers::Location const&, LCompilers::Vec<LCompilers::ASR::expr_t*>&, LCompilers::diag::Diagnostics&)
>     dim = ASR::down_cast<ASR::IntegerConstant_t>(dim_expr) -> m_n;
> AssertFailed: is_a<T>(*f)
> ```

GFortran Gives same error. I had tried all cases with Gfortran, only case with findloc(array, value, mask) was not implemented. So do we have to implement cases that Gfortran not support?

2024-10-09 18:58 UTC, jinangshah21 commented on src/libasr/pass/intrinsic_array_function_registry.h
> +        if( args[2] && !args[3] && is_logical(*expr_type(args[2])) ){
> The right design in my opinion is to use the "overload_id" in ASR for this. We discussed exactly this issue for a similar function, I can't remember which one. You decide on the signatures that you will support, let's just say the following:
> 
> ```
> minloc(array) ! overload_id = 0
> minloc(array, dim) ! overload_id = 1
> minloc(array, dim, mask) ! overload_id = 2
> ```
> 
> And for each case (`overload_id`) all arguments are required and never null (it could be that some arguments have to have their default values specified). So you never write code like this:
> 
> ```
>  if( args[2] && !args[3] && is_logical(*expr_type(args[2])) 
> ```
> 
> Rather, you write code like `if (overload_id == 2) { /* array, dim, mask is present and valid, handle this case */ }`.
> 
> The general design of ASR is that we do not have defaults or optional arguments. Everything is always present and explicit. So there is no branching logic and trying to figure out the defaults, like you discovered in this PR. All these decisions are made by the frontend. Once ASR is constructed, it is already set it stone what exact operations we need to do.
> 
> Let me know if you have any questions about this and if you know how to apply this to this PR, or want to discuss more.

By Checking `if( args[2] && !args[3] && is_logical(*expr_type(args[2])) ` I am differentiating between overload_id for (Array, value, dim)(i.e. 1) and (Array, value, mask)(i.e. 2). So it uses overload_id already.

2024-10-09 19:07 UTC, certik commented on src/libasr/pass/intrinsic_array_function_registry.h
> +        if( args[2] && !args[3] && is_logical(*expr_type(args[2])) ){
Only do cases that GFortran supports.

I see, this is in the `create` function, which determines the overload_id. In that case this is fine I think!

2024-10-09 19:10 UTC, certik approved these changes
I think this is fine then. It fixes an issue, test is added.

The concern is how to expand this to other functions without repeating too much code.

I would say we can merge it, and then figure out a general solution if there is any.

@gxyd, @HarshitaKalani let me know what you want to do here.

2024-10-10 04:41 UTC, Pranavchiku approved these changes
I think we will always have this problem to adjust variables. The approach uses overload_id just swaps two arguments as one is nullptr and other is not. The only way to generalise this is to create some form of mapping in the frontend for each intrinsic so that we do not have to worry about it in `create_*` function.

2024-10-10 04:42 UTC, merged

2024-10-10 05:20 UTC, certik commented
The `create` function is called by the frontend, isn't it? It's not called after ASR is constructed.

2024-10-10 05:54 UTC, Pranavchiku commented
Yes, it is called in frontend.

2024-10-10 06:08 UTC, gxyd commented
> I would say we can merge it, and then figure out a general solution if there is any.

I agree with this.

> @gxyd, @HarshitaKalani let me know what you want to do here.

We can maybe open a separate issue describing in detail about the general issue.