fix: Logical inputs in and() function
lfortran/lfortran pull request #5059
Opened 2024-10-15 13:56 UTC by jinangshah21

Fixes #4380. 
Still not Completed(Draft).

2024-10-15 18:26 UTC, Pranavchiku requested changes
```diff
diff --git a/src/libasr/intrinsic_func_registry_util_gen.py b/src/libasr/intrinsic_func_registry_util_gen.py
index 6a4cd2de7..9718cf537 100644
--- a/src/libasr/intrinsic_func_registry_util_gen.py
+++ b/src/libasr/intrinsic_func_registry_util_gen.py
@@ -577,7 +577,7 @@ intrinsic_funcs_args = {
     ],
     "Iand": [
         {
-            "args": [("int", "int")],
+            "args": [("int", "int"), ("bool", "bool")],
             "ret_type_arg_idx": 0,
             "same_kind_arg": 2
         },
```

As suggested by @HarshitaKalani, `Iand` only supports integer argument. Let's create a new intrinsic `And` which allows `integer` and `boolean`. Make frontend recognise it.

2024-10-17 07:01 UTC, jinangshah21 commented
Once this get approved we can do same for 'or' and 'xor'.

2024-10-17 13:44 UTC, jinangshah21 commented on src/libasr/intrinsic_func_registry_util_gen.py
> +            "same_kind_arg": 2
Yes they can be of different kind, I will remove that line.

2024-10-17 16:42 UTC, HarshitaKalani approved these changes
This looks good to me. I think we can merge this.
And then think about the idea mentioned above.

2024-10-17 16:43 UTC, merged

2024-10-17 18:28 UTC, jinangshah21 commented on src/lfortran/semantics/ast_common_visitor.h
> -        {"and", {"iand", {"any", "any"}}},
> I can think of a better approach here. We can keep the `and` implementation and remove the `iand` implementation and then map it this way:
> 
> ```
> {"iand", {"and", {"int", "int"}}},
> ```
> 
> How does that sound to you?

There is an issue doing this : `and` accepts only scalar arguments but `iand` can have an array as input as per GFortran.

2024-10-18 09:09 UTC, HarshitaKalani commented on src/lfortran/semantics/ast_common_visitor.h
> -        {"and", {"iand", {"any", "any"}}},
I see. Then we'll need to see the correct way of implementing `and` as currently it is implemented as an intrinsic elemental function with this PR.

2024-10-18 17:47 UTC, jinangshah21 commented on src/lfortran/semantics/ast_common_visitor.h
> -        {"and", {"iand", {"any", "any"}}},
Can we keep a flag "scalar" in `intrinsic_function_registry_gen_util.py` that can check if input is scalar Or not?