fix: Mod Intrinsic with different kinds for Simplifier
lfortran/lfortran pull request #5107
Opened 2024-10-21 09:41 UTC by AnshMehta1

2024-10-21 13:01 UTC, Pranavchiku requested changes
`arrays_op_9.f90` fails, you'll have to debug why it happens.

2024-10-21 13:25 UTC, AnshMehta1 commented
> `arrays_op_9.f90` fails, you'll have to debug why it happens.

This file is unaffected by my changes as their is no use of mode function , I think their might be some other issue in this PR.

2024-10-21 13:41 UTC, Pranavchiku commented
I see, here are a few reference failures:
```
derived_types_06.f90 * asr
The JSON metadata differs against reference results
Reference JSON: tests/reference/asr-derived_types_06-847ca73.json
Output JSON:    tests/output/asr-derived_types_06-847ca73.json
Omitting 10 identical items
Differing items:
{'stdout_hash': 'baff76a81485b49b9ac39456a90e3c4d8a55c41ba4d30a97591915cd'} != {'stdout_hash': '58ba8ff75c14bdcab46d7adc85a0b7ae144a28d88875ab500624b11e'}
Diff against: tests/reference/asr-derived_types_06-847ca73.stdout
956c956,958
<                                                     (Character 1 -2 () PointerString)
---
>                                                     (Allocatable
>                                                         (Character 1 -2 () PointerString)
>                                                     )

xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
Traceback (most recent call last):
  File "ci/test.xsh", line 44, in <module>
    ./run_tests.py
ci/test.xsh:6:import platform
ci/test.xsh:7:$IS_MAC = platform.system() == "Darwin"
ci/test.xsh:8:$IS_WIN = platform.system() == "Windows"
ci/test.xsh:11:src/bin/lfortran --version
ci/test.xsh:13:src/bin/lfortran -c examples/expr2.f90 -o expr2.o
```

You can update references, locally run integration and reference tests and if it works, push it. I believe trouble is in updating reference test.

2024-10-21 14:10 UTC, AnshMehta1 commented
> I see, here are a few reference failures:
> 
> ```
> derived_types_06.f90 * asr
> The JSON metadata differs against reference results
> Reference JSON: tests/reference/asr-derived_types_06-847ca73.json
> Output JSON:    tests/output/asr-derived_types_06-847ca73.json
> Omitting 10 identical items
> Differing items:
> {'stdout_hash': 'baff76a81485b49b9ac39456a90e3c4d8a55c41ba4d30a97591915cd'} != {'stdout_hash': '58ba8ff75c14bdcab46d7adc85a0b7ae144a28d88875ab500624b11e'}
> Diff against: tests/reference/asr-derived_types_06-847ca73.stdout
> 956c956,958
> <                                                     (Character 1 -2 () PointerString)
> ---
> >                                                     (Allocatable
> >                                                         (Character 1 -2 () PointerString)
> >                                                     )
> 
> xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
> Traceback (most recent call last):
>   File "ci/test.xsh", line 44, in <module>
>     ./run_tests.py
> ci/test.xsh:6:import platform
> ci/test.xsh:7:$IS_MAC = platform.system() == "Darwin"
> ci/test.xsh:8:$IS_WIN = platform.system() == "Windows"
> ci/test.xsh:11:src/bin/lfortran --version
> ci/test.xsh:13:src/bin/lfortran -c examples/expr2.f90 -o expr2.o
> ```
> 
> You can update references, locally run integration and reference tests and if it works, push it. I believe trouble is in updating reference test.

I updated the referrences but am getting error on 
```
program intrinsics_32
    implicit none

    real, dimension(6) :: tsource, fsource, result
    logical, dimension(6) :: mask
    integer :: i

    do i = 1, 6
        tsource(i) = i*2
        fsource(i) = -i*2
    end do
    mask(1) = .true.
    mask(2) = .false.
    mask(3) = .false.
    mask(4) = .true.
    mask(5) = .true.
    mask(6) = .false.

    result = merge(tsource, fsource, mask)
    
end program intrinsics_32
```
like this 
LCOMPILERS_ASSERT failed: /home/lordansh/dev/lfort2/lfortran/src/libasr/asr_utils.h
function type_get_past_array(), line number 198 at 
!ASR::is_a<ASR::Array_t>(*e->m_type)
Aborted (core dumped)

2024-10-21 17:20 UTC, Pranavchiku commented on tests/reference/asr-arrays_elemental_15-c7c15ca.stderr
> +LCOMPILERS_ASSERT failed: $DIR/src/libasr/asr_utils.h
We must not have these, need to figure out cause of it.

2024-10-22 13:44 UTC, Pranavchiku approved these changes
Test is added via https://github.com/lfortran/lfortran/pull/5058

2024-10-22 13:45 UTC, Pranavchiku commented
Merge it once https://github.com/lfortran/lfortran/pull/5058 is merged.

2024-10-22 14:01 UTC, gxyd commented
Btw, the update in integration test case is only done in the PR against *main*, so we don't know whether updating the test will make the test succeed in this PR against *simplifier pass* PR or not.

2024-10-22 15:58 UTC, AnshMehta1 commented
This PR is also ready to be merged with the addition of integration tests.

2024-10-22 17:27 UTC, certik commented on src/libasr/asr_builder.h
> +    ASR::ttype_t* create_type(ASR::ttype_t* t, int64_t kind) {
I don't like the name `create_type`, I had to read the code to understand what it might be doing. Isn't this duplicating the type and changing the kind? If so, maybe this is a better name: `duplicate_type_change_kind` or something like that.

2024-10-22 18:07 UTC, AnshMehta1 commented on src/libasr/asr_builder.h
> +    ASR::ttype_t* create_type(ASR::ttype_t* t, int64_t kind) {
Some refactoring is to be done for which , I will create another PR and will ensure that this name change is present in it.

2024-10-24 14:35 UTC, AnshMehta1 commented
Their are some mess up and so opening new pr for simplifier pass.

2024-10-24 14:35 UTC, closed without merging