Mod refactoring changes and extended logic to real
lfortran/lfortran pull request #5149
Opened 2024-10-24 09:15 UTC by AnshMehta1

2024-10-24 10:22 UTC, gxyd commented on src/libasr/intrinsic_func_registry_util_gen.py
> +            src += indent * 2 + f"type_ = b.duplicate_type_change_kind(type_, upper_kind);\n"
I think we already have a function in `asr_utils.h` called `set_kind_to_ttype_t`, which probably does the same thing as you are looking for. Can you try and see if that works for you?

If `set_kind_to_ttype_t` works for you, maybe, document it a little so that it becomes clear for it's usage?

2024-10-24 10:22 UTC, gxyd commented on integration_tests/intrinsics_78.f90
> +    iresult = kind(mod(i,j))
do we already have a test which ensures that the kind of `kind(mod(j, i))` is also `8`? If not, then we can have two tests?

2024-10-24 10:22 UTC, gxyd commented on src/libasr/pass/intrinsic_functions.h
> +                    body.push_back(al, b.Assignment(result, b.Sub(arg0, b.Mul(arg1, b.i2r_t(b.r2i_t(b.Div(arg0, arg1), real64), real64)))));
It's difficult to read long lines of code, but I don't have a nice solution without wrapping it making it occupy 20 lines, so I'm fine as it is as well.

2024-10-24 10:58 UTC, AnshMehta1 commented on src/libasr/intrinsic_func_registry_util_gen.py
> +            src += indent * 2 + f"type_ = b.duplicate_type_change_kind(type_, upper_kind);\n"
ok , I will try this out

2024-10-24 13:46 UTC, AnshMehta1 commented on integration_tests/intrinsics_78.f90
> +    iresult = kind(mod(i,j))
I think this two tests are sufficient 
```
! Test integer values with different kinds
    i = 121
    j = 121
    iresult = kind(mod(i,j))
    print *, "Test 14: kind(mod(", i, ",", j, ")) = ", iresult 
    if(iresult /= 8) error stop "Test 14 failed"

    ! Test real values with different kinds
    a = 121.882
    b = 121.882
    iresult = kind(mod(a,b))
    print *, "Test 15: kind(mod(", a, ",", b, ")) = ", iresult 
    if(iresult /= 8) error stop "Test 15 failed"
```

2024-10-24 13:52 UTC, certik commented on integration_tests/intrinsics_78.f90
> +    iresult = kind(mod(i,j))
Let's not modify the original test, which was good.

Add a new test that fails in main, and this PR fixes it.

2024-10-24 13:54 UTC, AnshMehta1 commented on integration_tests/intrinsics_78.f90
> +    iresult = kind(mod(i,j))
Ok , will do so .

2024-10-24 14:00 UTC, AnshMehta1 commented on integration_tests/intrinsics_78.f90
> +    iresult = kind(mod(i,j))
Done with changes , new test that the PR fixes is for real with different kinds.

2024-10-24 16:01 UTC, certik approved these changes

2024-10-29 18:02 UTC, Pranavchiku requested changes
```cpp
        int upper_kind = std::max(kind, kind2);
        if (is_real(*arg_types[1])) {
            ASR::ttype_t* new_type = ASRUtils::TYPE(ASR::make_Real_t(al, loc, upper_kind));
            ASR::expr_t* arg0 = b.r2r_t(args[0], new_type);
            ASR::expr_t* arg1 = b.r2r_t(args[1], new_type);
            if(upper_kind == 4){
                body.push_back(al, b.Assignment(result, b.Sub(arg0, b.Mul(arg1, b.i2r_t(b.r2i_t(b.Div(arg0, arg1), real32), real32)))));
            }
            else{
                body.push_back(al, b.Assignment(result, b.Sub(arg0, b.Mul(arg1, b.i2r_t(b.r2i_t(b.Div(arg0, arg1), real64), real64)))));
            }
        } else {
            ASR::ttype_t* new_type = ASRUtils::TYPE(ASR::make_Integer_t(al, loc, upper_kind));
            ASR::expr_t* arg0 = b.i2i_t(args[0], new_type);
            ASR::expr_t* arg1 = b.i2i_t(args[1], new_type);
            body.push_back(al, b.Assignment(result, b.Sub(arg0, b.Mul(arg1, b.Div(arg0, arg1)))));
        }
```

This shall be sufficient

2024-10-31 10:26 UTC, Pranavchiku approved these changes

2024-10-31 10:27 UTC, Pranavchiku commented
From next PR, let's try to make meaningful commit messages, you can use space and avoid `_`. I am squashing this PR.

2024-10-31 10:27 UTC, merged