Adding Semantic Check for non-constant variable in dimension expression.
lfortran/lfortran pull request #5176
Opened 2024-10-27 09:42 UTC by AnshMehta1

2024-10-27 14:32 UTC, certik commented on src/lfortran/semantics/ast_common_visitor.h
> +                if(ASR::is_a<ASR::Var_t>(*start)) {
Put space after `if` and before `(`. The same for all ifs.

2024-10-27 14:33 UTC, certik commented on src/lfortran/semantics/ast_common_visitor.h
> +                    else if(ASR::is_a<ASR::Variable_t>(*end_sym)) {
Don't know what is going on here, but it should look like this `} else if (...) {`, to make it clear which if statement this belongs to. It might be the previous `}` is incorrectly indented.

2024-10-27 15:07 UTC, kmr-srbh requested changes

2024-10-27 15:07 UTC, kmr-srbh commented on src/lfortran/semantics/ast_common_visitor.h
> +                }
We need to throw a semantic error for the MRE in https://github.com/lfortran/lfortran/issues/5173#issuecomment-2439503478 also. Please add an `else` clause here which checks for `IntegerConstant`.

2024-10-27 15:07 UTC, kmr-srbh commented on src/lfortran/semantics/ast_common_visitor.h
>                  }
Same for the end dimension also.

2024-10-28 05:37 UTC, AnshMehta1 commented on src/lfortran/semantics/ast_common_visitor.h
>                  }
Some changes are to be made , will work on these changes today.

2024-10-28 14:37 UTC, AnshMehta1 commented on src/lfortran/semantics/ast_common_visitor.h
> +                    else if(ASR::is_a<ASR::Variable_t>(*end_sym)) {
Their was intendation problem , rectified it.

2024-10-28 14:37 UTC, AnshMehta1 commented
> Test has to be added.

Added

2024-10-28 14:50 UTC, certik commented on src/lfortran/semantics/ast_common_visitor.h
> +                }
This seems like a lot of duplicated code (12x) for one error message. 

First of all, it should not say `at` at the end. We can just manually modify all the 12 occurrences above.

But let's refactor this. What exactly is the condition under which this error message should be reported?

Is the reason to just extract the type? I think we already have a function for this in ASR utils. If not, let's write one. 

There should be just one place to report this error, not 12x.

2024-10-28 17:42 UTC, AnshMehta1 commented on src/lfortran/semantics/ast_common_visitor.h
> +                }
For parameter annoted integer variable and IntegerConstant , error must not be thrown. But their are some functions like len for string and size for array where array shouldn't be thrown as their return type is integer.
Also , their are some functions for array like maxval having return type integer for which array is not thrown .
Basically , for functions with return type integer , error shouldn't be thrown. This thing is enlisted using else ifs

2024-10-28 17:59 UTC, AnshMehta1 commented on src/lfortran/semantics/ast_common_visitor.h
> +                }
Ok , figured out refactoring , will make the changes .

2024-10-28 21:54 UTC, certik commented on src/lfortran/semantics/ast_common_visitor.h
> +                    else {
Use this syntax:
```suggestion
                    } else {
```
The same at other places below.

2024-10-28 21:57 UTC, certik commented on src/lfortran/semantics/ast_common_visitor.h
> +           if (m_dim[i].m_start) {
This seems incorrectly indented.

2024-10-28 22:00 UTC, certik commented
This is better. But the same error is still reported 6 times. Given that we are not distinguishing the different cases, why not write a function that determines if the given entity satisfies the requirements? It will return true/false. Then we do `if (!satisfy_requirements(x)) report the error`.

2024-10-28 22:05 UTC, AnshMehta1 commented
> This is better. But the same error is still reported 6 times. Given that we are not distinguishing the different cases, why not writing a function that determines if the given entity satisfies the requirements? It will return true/false. Then we do `if (!satisfy_requirements(x)) report the error`.

Idea seems good , will do the change tomorrow morning.

2024-10-29 11:02 UTC, AnshMehta1 commented
I added the function for testing error check. Now , error is reported 2 times based on function . 1 is error check for start dimension and other is error check for end dimension. Let me know if their is a need to change the name of function or any other thing.

2024-10-29 11:03 UTC, AnshMehta1 commented on src/lfortran/semantics/ast_common_visitor.h
> +           if (m_dim[i].m_start) {
Done

2024-10-29 14:13 UTC, certik commented on src/lfortran/semantics/ast_common_visitor.h
> +    bool dimensionAttribute_error_check(ASR::expr_t* dim_expr) {
Use the following naming convention to be consistent with the rest of the code:
```suggestion
    bool dimension_attribute_error_check(ASR::expr_t* dim_expr) {
```

2024-10-29 14:17 UTC, certik approved these changes
I think this looks good! Left some minor comments to fix, after that we can merge.

2024-10-29 17:08 UTC, certik approved these changes

2024-10-29 18:09 UTC, merged