fix: m_type_declaration corrected for procedure declaration
lfortran/lfortran pull request #5208
Opened 2024-10-29 19:46 UTC by jinangshah21

Fixes #5142 
Here I didn't add test because this issue needs 2 separated files.

2024-10-29 20:00 UTC, certik commented on src/lfortran/semantics/ast_common_visitor.h
> +            }
The logic doesn't seem to make sense: if `v` is ExternalSymbol, then `v` is used. If it is not an external symbol, then `temp` should be equal to `v`, right?

2024-10-29 20:08 UTC, jinangshah21 commented on src/lfortran/semantics/ast_common_visitor.h
> +            }
Corrected it.

2024-10-29 20:12 UTC, certik commented
Add a test.

2024-10-29 22:00 UTC, certik commented
Just add both files. See "EXTRAFILES" in `integration_tests/CMakeLists.txt`.

2024-10-30 06:08 UTC, Pranavchiku requested changes
Add two new `.f90` files, supposedly `test_01.f90` and `test_01_b.f90` and then register it as:

```CMake
RUN(NAME test_01 LABELS gfortran llvm llvm_wasm llvm_wasm_emcc EXTRAFILES test_01_b.f90)
```

2024-10-30 06:43 UTC, Pranavchiku requested changes
You also need to apply the following diff in `asr_verify.cpp` to keep things in sync:

```diff
diff --git a/src/libasr/asr_verify.cpp b/src/libasr/asr_verify.cpp
index ebe25879e..5da47d58b 100644
--- a/src/libasr/asr_verify.cpp
+++ b/src/libasr/asr_verify.cpp
@@ -930,7 +930,7 @@ public:
             ASR::symbol_t *s = ASRUtils::symbol_get_past_external(x.m_name);
             if (ASR::is_a<ASR::Variable_t>(*s)) {
                 ASR::Variable_t *v = ASR::down_cast<ASR::Variable_t>(s);
-                require(v->m_type_declaration && ASR::is_a<ASR::Function_t>(*v->m_type_declaration),
+                require(v->m_type_declaration && ASR::is_a<ASR::Function_t>(*ASRUtils::symbol_get_past_external(v->m_type_declaration)),
                     "SubroutineCall::m_name '" + std::string(symbol_name(x.m_name)) + "' is a Variable, but does not point to Function");
                 require(ASR::is_a<ASR::FunctionType_t>(*v->m_type),
                     "SubroutineCall::m_name '" + std::string(symbol_name(x.m_name)) + "' is a Variable, but the type is not FunctionType");
```

2024-10-30 16:08 UTC, certik commented on src/libasr/asr_verify.cpp
> +                require(v->m_type_declaration && ASR::is_a<ASR::Function_t>(*ASRUtils::symbol_get_past_external(v->m_type_declaration)),
I don't see any `SubroutineCall` nodes in the above test case. Is this being tested? We should add a test for this.

2024-10-30 16:09 UTC, certik approved these changes
I think it's fine, but I want to have tests for all new changes, and the ASR verify change doesn't seem to be tested (in other words, doesn't seem to be needed).

2024-10-30 16:13 UTC, merged

2024-10-30 16:13 UTC, certik commented
I merged it. If the ASR change is not needed, we can remove it in a subsequent PR, or add a test.

2024-10-30 16:23 UTC, Pranavchiku commented
We need it, PRIMA compilation fails without it. @jinangshah21 you can revert asr_verify.cpp change locally and compile PRIMA, it will throw Asr Verify error and you can create MRE. The fix for MRE will be the diff above.

2024-10-30 16:46 UTC, jinangshah21 commented
> I think it's fine, but I want to have tests for all new changes, and the ASR verify change doesn't seem to be tested (in other words, doesn't seem to be needed).

It is needed because when we will call calcfc it will visit SubroutineCall :  
```fortran 
module eval_dependency
contains
    subroutine OBJCON()
    end subroutine OBJCON
end module eval_dependency

module procedure_decl_01_b
contains
subroutine evaluate(calcfc)
    use eval_dependency
    implicit none
    procedure(OBJCON) :: calcfc 
    **call calcfc()**
end subroutine evaluate
end module procedure_decl_01_b
```

2024-10-30 17:59 UTC, certik commented
Perfect. Please send a PR adding `call calcfc()` to the test, you forgot to add it.