enh: Fortran backend to support openmp dump
lfortran/lfortran pull request #5278
Opened 2024-11-07 08:46 UTC by adit4443ya

Towards [ Fortran Backend](https://github.com/lfortran/lfortran/issues/5260)

Starting with minimal fix

2024-11-07 08:48 UTC, gxyd commented
A test case would be nice here.

2024-11-07 09:01 UTC, adit4443ya commented
It will work on every openmp testcase
If there is some new testcase needed then i will add it 

> A test case would be nice here.

2024-11-07 09:10 UTC, adit4443ya commented
For time being we can consider this as an example 
``` fortran
program openmp_36
integer :: i
do concurrent ( i =1:5 )
    print *, i
end do 
end program
```

> A test case would be nice here.

2024-11-07 09:18 UTC, gxyd commented
> For time being we can consider this as an example
> 
> ```fortran
> program openmp_36
> integer :: i
> do concurrent ( i =1:5 )
>     print *, i
> end do 
> end program
> ```
> 

I see, that's a good start, once you get any of the program present in `integration_tests/CMakeLists.txt` (pertaining to openmp), you can probably just add a label `fortran` to it (those can act as a good test case for this).

I moved this PR to draft mode until then.

2024-11-07 13:17 UTC, Pranavchiku commented
Let's add a test which this PR fixes, a minimal, close this and do improvements in next PR. Let's not carry longer PRs.

2024-11-07 16:40 UTC, adit4443ya commented
This fix now generates dump passes which uses `omp_lib`
```fortran
program openmp_40
    use omp_lib
    integer :: i
    do i = 1, 5
        print *, i
    end do 
end program
```
So i can add this test if required and then we will move on to merge it and then I will fix for the `DoConcurrentLoop` in next PR

2024-11-08 20:23 UTC, certik commented
The error is:
```
CMakeFiles/openmp_40.dir/openmp_40.f90.o.tmp.f90:95:20:

   95 |         type(c_ptr), value :: data
      |                    1
Error: Derived type ‘c_ptr’ at (1) is being used before it is defined
```

2024-11-09 06:34 UTC, Pranavchiku commented on integration_tests/openmp_40.f90
> +end program
```suggestion
program main
    use iso_c_binding, only: c_ptr!, c_loc
    implicit none
    integer, pointer :: x
    type(c_ptr) :: ptr
    !ptr = c_loc(x)
end program
```

2024-11-09 06:35 UTC, Pranavchiku commented on integration_tests/openmp_40.f90
> +end program
Use this instead, you'll need `c_loc` as well so slowly keep adding all these. These are minor changes and can be done in small but multiple PRs

2024-11-09 06:35 UTC, Pranavchiku commented on src/libasr/codegen/asr_to_fortran.cpp
> +                r = "type(c_ptr)";
The fact that if the code has `c_ptr` usage it will eventually be doing `use iso_c_binding`, so it should work, maybe the example you used is complex.

2024-11-09 06:35 UTC, Pranavchiku requested changes
left few comments to get this PR in shape

2024-11-10 11:07 UTC, Pranavchiku commented on integration_tests/CMakeLists.txt
> +RUN(NAME openmp_40 LABELS gfortran fortran GFORTRAN_ARGS -fopenmp)
```suggestion
RUN(NAME openmp_40 LABELS gfortran llvm fortran)
```

2024-11-10 11:07 UTC, Pranavchiku commented on integration_tests/openmp_40.f90
> +program main
```suggestion
program fortran_01
```

Rename the test case

2024-11-10 11:07 UTC, Pranavchiku commented on integration_tests/CMakeLists.txt
> +RUN(NAME openmp_40 LABELS gfortran fortran GFORTRAN_ARGS -fopenmp)
use the renamed case here

2024-11-10 11:08 UTC, Pranavchiku requested changes
left few comments

2024-11-11 11:21 UTC, adit4443ya commented on integration_tests/openmp_40.f90
> +end program
For now i guess this PR is good to go, in next PR i would handle `c_loc` case

2024-11-11 11:49 UTC, merged

2024-11-11 15:39 UTC, certik commented
Let's get into the habit of creating a nice set of commits. Or squash it.