chore: don't call replacer on ExternalSymbol with the same underling symbol
lfortran/lfortran pull request #5295
Opened 2024-11-08 12:24 UTC by gxyd

## Description

Fixes https://github.com/lfortran/lfortran/issues/5294

2024-11-08 13:06 UTC, Pranavchiku commented on src/libasr/asr_utils.cpp
> +                if (sym != arg_sym_underlying) {
we cannot do this, it will always be true ( if function got updated ). The aim is to check if newly created function is updated or not ( not sure but something like that ). 

`arg_sym` is what we have as an argument, the external function is `arg_sym_underlying`, now as `--implicit-interface` have empty args and thus as soon as it encounters call to it with `n` args we change the external function. This causes a problem that now the call is to `old` function which is `arg_sym_underlying`. So, we then replace it with `fetch_sym(arg_sym_underlying)` which fetches the new sym which must be used.

2024-11-08 13:09 UTC, Pranavchiku requested changes
If I take the MRE:

```fortran
module vars
    implicit none
    integer :: g = 2
end module

subroutine sub1
    use vars
    implicit none
    call sub2 (g)
end subroutine

subroutine sub2 (x)
    implicit none
    integer :: x
end
```

This shall not even need `--implicit-interface` but POT3D needs it, so if it fails it means with the flag we create an empty interface for `sub2` which we shall not. So, we need to understand how it works without `--implicit-interface` flag and then fix it. I don't think this PR is a correct fix for it right now. Feel free to ping me for any questions in case you need further clearance, I'll be happy to answer.

2024-12-11 13:15 UTC, gxyd commented
@certik @Pranavchiku , kindly review the PR again, and I've updated the PR description to describe a little more in detail for what this PR changes, I haven't made any changes since I last submitted the PR for review when comments by Pranav were left. I've gone through the changes to get a better understanding of the change made and I feel confident that this might actually be the right fix for it.

2024-12-11 16:31 UTC, gxyd commented
>  @gxyd does't it?

I thought about the change properly this time, it's possible that maybe Pranav misunderstood the change, that's where the updated PR description might help understanding the change this PR brings in. Happy to discuss on this again.

2024-12-11 16:33 UTC, gxyd commented
@Pranavchiku 's comment above which briefly mentioned:
> So, we need to understand how it works without --implicit-interface flag and then fix it.

This is what this PR does, i.e. ensures that the ASR generated with/without `--implicit-interface` flag is same, currently in *main*, it isn't.

2024-12-11 18:04 UTC, Pranavchiku commented on src/libasr/asr_utils.cpp
> +                if (sym != arg_sym_underlying) {
I am thinking on this, give me more time

2024-12-11 18:23 UTC, Pranavchiku approved these changes
I am convinced, so the things is we need to check if `old_function` ( `arg_sym_underlying` if it is in Module ) is different to new one i.e. `sym`.

2024-12-11 18:26 UTC, gxyd commented
> I am convinced, so the things is we need to check if `old_function` ( `arg_sym_underlying` if it is in Module ) is different to new one i.e. `sym`.

Thanks for the review @Pranavchiku , really appreciate it.

Also, I'm glad that my understanding here was along the lines of how you described it now.

2024-12-11 18:27 UTC, gxyd commented
I'll go ahead with the merge here.

2024-12-11 19:52 UTC, certik approved these changes
Thanks! Thanks @Pranavchiku for the review.

2024-12-11 20:41 UTC, merged