Error resilient array constructor with asterisk in type spec
lfortran/lfortran pull request #5300
Opened 2024-11-08 18:41 UTC by parth121101

2024-11-08 18:47 UTC, Pranavchiku commented on src/lfortran/semantics/ast_common_visitor.h
> +                throw SemanticAbort();
```suggestion
                if (!compiler_options.continue_compilation) throw SemanticAbort();
```

2024-11-08 18:47 UTC, Pranavchiku commented on tests/errors/array_constructor_with_asterisk_in_type_spec_cc.f90
> +    print *, [character(*) :: "a", "b", "ball", "cat"]
```suggestion
    print *, [character(*) :: "a", "b", "ball", "cat"]
    print *, [character(*) :: "a2", "b2", "ball2", "cat2"]
```
So that we get 2 error and be sure that it is working,

2024-11-08 18:47 UTC, Pranavchiku requested changes
left changes above

2024-11-08 18:53 UTC, Pranavchiku commented on src/lfortran/semantics/ast_common_visitor.h
> +                throw SemanticAbort();
Also you'll have to add `try expect` block where you are calling `check_if_type_spec_has_asterisk`

2024-11-08 19:01 UTC, parth121101 commented on tests/errors/array_constructor_with_asterisk_in_type_spec_cc.f90
> +    print *, [character(*) :: "a", "b", "ball", "cat"]
Sure @Pranavchiku , this will ensure that it is working as expected. Incorporated this comment.

2024-11-08 19:03 UTC, parth121101 commented on src/lfortran/semantics/ast_common_visitor.h
> +                throw SemanticAbort();
@Pranavchiku I think check for continue compilation flag should be made will calling the function. As suggested I added the function call inside try catch block and inside this I am checking for the continue compilation flag.

Please let me know if I am incorrect at any of the place.

2024-11-08 19:20 UTC, Pranavchiku commented on src/lfortran/semantics/ast_common_visitor.h
> +        }
you need to catch `SemanticAbort` as well because you are throwing that,

2024-11-08 19:21 UTC, Pranavchiku commented on tests/reference/run-array_constructor_with_asterisk_in_type_spec_cc-fc032e2.stderr
> +
missing:

```console
 --> tests/errors/array_constructor_with_asterisk_in_type_spec.f90:2:14
  |
2 |     print *, [character(*) :: "a", "b", "ball", "cat"]
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
```

2024-11-08 19:23 UTC, Pranavchiku commented on src/lfortran/semantics/ast_common_visitor.h
> +                throw SemanticAbort();
In this routine it is fine, but general idea is to stop only when it is a visitor for example if you catch an error in `visit_Assignment`, you'll simply skip this and `throw SemanticAbort()`, but for any other routine you let it run through, because that may generate other possible errors which we'll report.

2024-11-09 12:51 UTC, parth121101 commented on src/lfortran/semantics/ast_body_visitor.cpp
> +                return;
Returning is required, this will ensure that once an error is thrown we are out of the function and the code wont break at line number : 3285 due to null value of tmp.

2024-11-09 13:29 UTC, certik commented on src/lfortran/semantics/ast_common_visitor.h
> +
Don't add random white space.

2024-11-09 15:24 UTC, merged

2024-11-09 15:25 UTC, certik commented
I think it's good, let's merge it. We can send more PRs if needed.

2024-11-09 15:48 UTC, Pranavchiku reviewed
This is good, thanks for merging!