enh: `--lookup-name` to return symbol name
lfortran/lfortran pull request #5424
Opened 2024-11-20 13:01 UTC by Pranavchiku

Fixes the hardwired returning of `a.first`. Refer #5420

2024-11-20 16:25 UTC, certik commented on src/libasr/lsp.cpp
> +            } catch (std::exception &e) {
Just like in Python, never catch an exception like this.

In this case do not use exceptions at all. What is the failure mode here? We have to handle it explicitly.

What does `a.first` mean here? Why would we ever return it?

Also remove the TODO item.

2024-11-20 16:53 UTC, certik commented
Also we need to test the LSP in Fortran, right now it is not tested, or we don't have the test for this.

I would probably add a "ctest" test for this --- put the source code there, and check that the result has the proper name.

2024-11-20 16:53 UTC, Pranavchiku commented
> we don't have the test for this.

We test it via ctest

2024-11-20 16:54 UTC, Pranavchiku commented on src/libasr/lsp.cpp
> +            } catch (std::exception &e) {
> What does a.first mean here? Why would we ever return it?

I'm not exactly sure if `asr` is symbol always. Hence had to do this, we can do if/else

2024-11-20 16:59 UTC, Pranavchiku commented
Now using `ASR::is_a` to test if it is symbol and then fetching symbol name.

2024-11-20 17:01 UTC, certik commented on src/libasr/lsp.cpp
> +            } catch (std::exception &e) {
Then see `handle_lookup_name`, document what it should return, and you can put an assert inside it to ensure it is a symbol if it is not clear.

If it can be other things too, then you need to use `is_a` to check for a symbol, and return an error if it is not --- however I recommend to simply assert it is a symbol if it passes all tests.

Then if we discover a case where this fails, we can then figure out how to handle the error.

2024-11-20 17:01 UTC, certik commented
> We test it via ctest

No test was changed in this PR, which means that this path is not tested yet. Let's add a test.

2024-11-20 17:02 UTC, certik commented on src/libasr/lsp.cpp
>              // TODO: make sure it returns us the symbol name
```suggestion
```

2024-11-20 17:24 UTC, Pranavchiku commented
If it is not symbol we shall not populate list and simply return.

2024-11-20 17:26 UTC, certik commented
> If it is not symbol we shall not populate list and simply return.

Yes, this is one way to handle the error properly. Let's do it.

2024-11-20 17:29 UTC, certik approved these changes
This is better. 

What does `handle_lookup_name` return if it is a

* symbol --- it returns the ASR node of the declaration?
* "=" (Assignment) --- it returns that assignment?

We can further refactor this in subsequent PRs.

However let's add a ctest for this, that fails in main, but now works. After that we can merge.

2024-11-20 17:30 UTC, Pranavchiku commented
> it returns the ASR node of the declaration?

Yes

> "=" (Assignment) --- it returns that assignment?

Yes

2024-11-20 17:30 UTC, Pranavchiku commented
> However let's add a ctest for this, that fails in main,

Yes, I am trying to figure that out. It will be straight forward.

2024-11-20 17:42 UTC, Pranavchiku commented on src/lfortran/tests/test_ast.cpp
> +    LCOMPILERS_ASSERT(symbol_name == "expr2");
this will fail in main

2024-11-20 17:44 UTC, certik commented on src/lfortran/tests/test_ast.cpp
> +    LCOMPILERS_ASSERT(symbol_name == "expr2");
The test is in the right direction. Just make sure it fails in main, to ensure it is actually testing the fix in this PR.

2024-11-21 09:50 UTC, Pranavchiku commented on src/lfortran/tests/test_ast.cpp
> +#endif
We won't need this after #5438

2024-11-21 18:19 UTC, dylon requested changes
Other than a couple minor change requests, this looks good to me!

2024-11-21 18:19 UTC, dylon commented on src/libasr/lsp.cpp
> +                return "{}";
If the return value of the function should be an array, then please return an empty array instead of an object:

```c++
return "[]";
```

2024-11-21 18:19 UTC, dylon commented on src/libasr/lsp.cpp
> +            return "{}";
As mentioned above, please return an empty array instead of an object:

```c++
return "[]";
```

2024-11-21 21:27 UTC, certik commented on src/libasr/lsp.cpp
> +    std::string resp_str( buffer.GetString() );
This should just generate strings, so that we do not depend on rapidjson. Then we can enable LSP by default.

2024-11-23 05:04 UTC, Pranavchiku commented
closing with reference to https://github.com/lfortran/lfortran/pull/5456

2024-11-23 05:04 UTC, closed without merging