feat: introduce and implement `--rename-symbol`
lfortran/lfortran pull request #5441
Opened 2024-11-21 14:52 UTC by Pranavchiku

Fixes #5419. This PR is built on #5424, and #5438 hence CI shall fail. Once those are merged, we need to rebase this over top of latest main.

2024-11-21 14:54 UTC, Pranavchiku commented on src/libasr/lsp.cpp
> +            occ.visit_TranslationUnit(*x.result);
Here is the core logic, use line and column to compute `symbol_name` and then pass it to `OccurenceCollector` which will collect all occurrence.

2024-11-21 17:58 UTC, dylon requested changes
With the exception of a couple minor changes, this looks good to me!

2024-11-21 17:58 UTC, dylon commented on src/libasr/lsp.cpp
> +                std::cout << "{}";
Lines 357 and 365 should return an empty array instead of an object:

```c++
std::cout << "[]";
```

2024-11-21 17:58 UTC, dylon commented on src/libasr/lsp.cpp
> +            std::cout << "{}";
As mentioned above, please return an empty array instead of an object when the return type should be an array:

```c++
std::cout << "[]";
```

2024-11-23 05:58 UTC, Pranavchiku commented
closing with reference to https://github.com/lfortran/lfortran/pull/5458

2024-11-23 05:58 UTC, closed without merging