Fix memory issues in lfortran
lfortran/lfortran pull request #5535
Opened 2024-11-30 20:32 UTC by Shaikh-Ubaid

fixes https://github.com/lfortran/lfortran/issues/5534

Output from branch:

```fortran
(lf) ubaid@DESKTOP-TEN39M0:~/projects/lfortran$ cat examples/expr2.f90 
      program hello
      end
```

```console
(lf) ubaid@DESKTOP-TEN39M0:~/projects/lfortran$ valgrind gfortran examples/expr2.f90
==133657== Memcheck, a memory error detector
==133657== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==133657== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==133657== Command: gfortran examples/expr2.f90
==133657== 
==133657== 
==133657== HEAP SUMMARY:
==133657==     in use at exit: 180,109 bytes in 123 blocks
==133657==   total heap usage: 522 allocs, 399 frees, 239,868 bytes allocated
==133657== 
==133657== LEAK SUMMARY:
==133657==    definitely lost: 7,040 bytes in 50 blocks
==133657==    indirectly lost: 82 bytes in 5 blocks
==133657==      possibly lost: 0 bytes in 0 blocks
==133657==    still reachable: 172,987 bytes in 68 blocks
==133657==         suppressed: 0 bytes in 0 blocks
==133657== Rerun with --leak-check=full to see details of leaked memory
==133657== 
==133657== For lists of detected and suppressed errors, rerun with: -s
==133657== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

```console
(lf) ubaid@DESKTOP-TEN39M0:~/projects/lfortran$ valgrind lfortran examples/expr2.f90 --fixed-form
==133703== Memcheck, a memory error detector
==133703== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==133703== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==133703== Command: lfortran examples/expr2.f90 --fixed-form
==133703== 
==133703== 
==133703== HEAP SUMMARY:
==133703==     in use at exit: 396,663 bytes in 1,619 blocks
==133703==   total heap usage: 31,559 allocs, 29,940 frees, 4,333,827 bytes allocated
==133703== 
==133703== LEAK SUMMARY:
==133703==    definitely lost: 2,435 bytes in 6 blocks
==133703==    indirectly lost: 296,223 bytes in 352 blocks
==133703==      possibly lost: 0 bytes in 0 blocks
==133703==    still reachable: 98,005 bytes in 1,261 blocks
==133703==         suppressed: 0 bytes in 0 blocks
==133703== Rerun with --leak-check=full to see details of leaked memory
==133703== 
==133703== For lists of detected and suppressed errors, rerun with: -s
==133703== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

2024-12-01 07:29 UTC, certik commented on src/lfortran/parser/parser.cpp
> +        }
Something is wrong with the indentation. 

I think you don't need to call tolower, it's already lowered I think for fixed form.

I think this code simply does string comparison that is taking into account the string running out. Let's write a function "str_compare" that implements the correct logic, and we just call it here.

2024-12-01 10:35 UTC, Pranavchiku commented on src/libasr/pass/intrinsic_subroutine.cpp
> +            parent_body = nullptr;
why do we need this? Also, can you register test that this patch fixes?

2024-12-01 10:35 UTC, Pranavchiku requested changes
left a few comments above.

2024-12-01 13:46 UTC, certik commented on src/lfortran/parser/parser.cpp
> +}
Put this into `src/libasr/string_utils.h`

2024-12-01 13:55 UTC, certik commented on src/lfortran/parser/parser.cpp
> +    return (i == s.size());
I don't like using the loop variable after the loop, I think this is better:
```suggestion
    return true;
```

2024-12-01 13:55 UTC, certik commented on src/lfortran/parser/parser.cpp
> +    for (i = 0; i < s.size() && pos[i] != '\0'; i++) {
```suggestion
    for (i = 0; i < s.size(); i++) {
        if (pos[i] == '\0') return false;
```

2024-12-01 21:33 UTC, certik approved these changes
I think it looks good now, thanks!

2024-12-01 21:34 UTC, merged

2024-12-02 13:28 UTC, Pranavchiku commented
Thanks for completing this PR!