Bug #5531 - Added conflict diagnostic error message for pointer/allocatable attribute
lfortran/lfortran pull request #5777
Opened 2024-12-20 19:06 UTC by dsaw

Fixes bug #5531

2024-12-20 19:18 UTC, kmr-srbh requested changes

2024-12-20 19:18 UTC, kmr-srbh commented on src/lfortran/semantics/ast_common_visitor.h
> -                                // TODO
Please undo this change.

2024-12-20 19:18 UTC, kmr-srbh commented on src/lfortran/semantics/ast_common_visitor.h
> +                            "`PARAMETER` attribute conflicts with `ALLOCABLE` attribute",
Please use all lower case for the error message. Also, please correct the spelling for `allocatable`

2024-12-20 19:18 UTC, kmr-srbh commented on src/lfortran/semantics/ast_common_visitor.h
> +
Please remove this newline.

2024-12-20 19:18 UTC, kmr-srbh commented on src/lfortran/semantics/ast_common_visitor.h
> +                            "`PARAMETER` attribute conflicts with `POINTER` attribute",
Use all lower case.

2024-12-20 19:18 UTC, kmr-srbh commented on src/lfortran/semantics/ast_common_visitor.h
> +
Remove the newline please.

2024-12-20 19:18 UTC, kmr-srbh commented on tests/reference/run-alloc_attr_disallow-ffd3ec5.stderr
> +semantic error: `PARAMETER` attribute conflicts with `ALLOCABLE` attribute
Please push the new references after making the suggested changes.

2024-12-20 19:56 UTC, dsaw commented on src/lfortran/semantics/ast_common_visitor.h
> -                                // TODO
done. the if condition was a duplicate with another one above, but I can see it is unnecessary at this time.

2024-12-20 19:56 UTC, dsaw commented on src/lfortran/semantics/ast_common_visitor.h
> +                            "`PARAMETER` attribute conflicts with `ALLOCABLE` attribute",
done

2024-12-20 19:56 UTC, dsaw commented on src/lfortran/semantics/ast_common_visitor.h
> +
done

2024-12-20 19:57 UTC, dsaw commented on src/lfortran/semantics/ast_common_visitor.h
> +                            "`PARAMETER` attribute conflicts with `POINTER` attribute",
done

2024-12-20 19:57 UTC, dsaw commented on src/lfortran/semantics/ast_common_visitor.h
> +
done

2024-12-20 19:57 UTC, dsaw commented on tests/reference/run-alloc_attr_disallow-ffd3ec5.stderr
> +semantic error: `PARAMETER` attribute conflicts with `ALLOCABLE` attribute
done

2024-12-20 20:11 UTC, kmr-srbh approved these changes

2024-12-20 20:16 UTC, kmr-srbh commented on src/lfortran/semantics/ast_common_visitor.h
> +                    }
I think it is not efficient to check twice as both `pointer` and `allocatable` cannot appear together. Let's add this to the above `if` block as an `else if` block instead.

2024-12-21 06:24 UTC, dsaw commented on src/lfortran/semantics/ast_common_visitor.h
> +                    }
when I test these conditions as an if else block, the abort isn't reached, probably because the parameter, allocatable and pointer conditions are mutually exclusive. 
Test output diff below for reference:
```
-semantic error: `parameter` attribute conflicts with `allocatable` attribute
- --> tests/./errors/alloc_attr_disallow.f90:4:4
-  |
-4 |    integer, allocatable, parameter :: v=1
-  |    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
+code generation error: asr_to_llvm: module failed verification. Error:
+Stored value type does not match pointer operand type!
+  store i32 1, i32** %v, align 4
+ i32*
```
I think we can test this inside asr_verify or leave it as is.

2024-12-21 06:43 UTC, kmr-srbh commented on src/lfortran/semantics/ast_common_visitor.h
> +                    }
Could you please share the diff of the changes you made?

2024-12-21 06:56 UTC, dsaw commented on src/lfortran/semantics/ast_common_visitor.h
> +                    }
```
diff --git i/src/lfortran/semantics/ast_common_visitor.h w/src/lfortran/semantics/ast_common_visitor.h
index 655b7d40b..137ee3b3f 100644
--- i/src/lfortran/semantics/ast_common_visitor.h
+++ w/src/lfortran/semantics/ast_common_visitor.h
@@ -2956,9 +2956,27 @@ public:
                             } else if( sa->m_attr == AST::simple_attributeType
                                     ::AttrAllocatable ) {
                                 is_allocatable = true;
+                                if (storage_type == ASR::storage_typeType::Parameter) {
+                                    diag.add((Diagnostic( 
+                                        "`parameter` attribute conflicts with `allocatable` attribute",
+                                        Level::Error, Stage::Semantic, {
+                                            Label("",{x.base.base.loc})
+                                        }
+                                    )));
+                                    throw SemanticAbort();
+                                }
                             } else if (sa->m_attr == AST::simple_attributeType
                                     ::AttrPointer) {
                                 is_pointer = true;
+                                if (storage_type == ASR::storage_typeType::Parameter) {
+                                    diag.add((Diagnostic( 
+                                        "`parameter` attribute conflicts with `pointer` attribute",
+                                        Level::Error, Stage::Semantic, {
+                                            Label("",{x.base.base.loc})
+                                        }
+                                    )));
+                                    throw SemanticAbort();
+                                }
                             } else if (sa->m_attr == AST::simple_attributeType
                                     ::AttrOptional) {
                                 s_presence = ASR::presenceType::Optional;
@@ -3029,26 +3047,6 @@ public:
                     }
                     
 
-                    if (is_allocatable && storage_type == ASR::storage_typeType::Parameter) {
-                        diag.add((Diagnostic( 
-                            "`parameter` attribute conflicts with `allocatable` attribute",
-                            Level::Error, Stage::Semantic, {
-                                Label("",{x.base.base.loc})
-                            }
-                        )));
-                        throw SemanticAbort();
-                    }
-
-                    if (is_pointer && storage_type == ASR::storage_typeType::Parameter) {
-                        diag.add((Diagnostic( 
-                            "`parameter` attribute conflicts with `pointer` attribute",
-                            Level::Error, Stage::Semantic, {
-                                Label("",{x.base.base.loc})
-                            }
-                        )));
-                        throw SemanticAbort();
-                    }
-
                     if (s_intent == ASRUtils::intent_out && value_attr) {
                         diag.add(Diagnostic(
                             "`value` attribute conflicts with `intent(out)` attribute",


```

I also tried adding the both the condition inside the attribute if condition and the same issue persists.

2024-12-21 07:00 UTC, kmr-srbh commented on src/lfortran/semantics/ast_common_visitor.h
> +                    }
I am sorry for the confusion, I meant merging the two `if` block you created into 1 `if - else if` block. Does that work?

2024-12-21 07:18 UTC, dsaw commented on src/lfortran/semantics/ast_common_visitor.h
> +                    }
Oh i see.. updated

2024-12-21 07:29 UTC, kmr-srbh commented on src/lfortran/semantics/ast_common_visitor.h
> +                    else if (is_pointer && storage_type == ASR::storage_typeType::Parameter) {
```suggestion
                    } else if (is_pointer && storage_type == ASR::storage_typeType::Parameter) {
```

2024-12-21 08:01 UTC, merged

2024-12-21 13:59 UTC, certik commented on tests/tests.toml
> +run = true
These should not be run, but "asr".

Second, let's not keep adding new tests like this for each error, because we will have hundreds, possibly thousands, of errors. Rather, just add this error test into our "continue compilation" tests, where it is just one extra line.

This will in addition also test that this error can be recovered from, which we also need to assure.

@dsaw can you please fix that?

2024-12-22 04:44 UTC, dsaw commented on tests/tests.toml
> +run = true
sure. seems a PR has been opened for this already. do you have a reference for how to perform the continue compilation tests, if possible?