fix: tokenizer errors generates ast and asr with cc flag
lfortran/lfortran pull request #5856
Opened 2024-12-28 13:42 UTC by parth121101

2024-12-28 18:05 UTC, certik commented on src/lfortran/parser/tokenizer.re
> +                        "Token '" + t + "' is not recognized", {loc}).d);
Let's keep the same error message with the label.

2024-12-28 18:06 UTC, certik commented on tests/reference/tokens-esub2-4cb444d.json
> +    "returncode": 0
It was failing before, now it succeeds, is this a correct change?

2024-12-28 18:06 UTC, certik commented
The CI has to be fixed.

2024-12-30 15:10 UTC, parth121101 commented on tests/reference/tokens-esub2-4cb444d.json
> +    "returncode": 0
I dont believe this is a correct change. Need to dive a bit deep.

2025-01-03 16:46 UTC, Pranavchiku commented on tests/reference/tokens-esub2-4cb444d.json
> +    "returncode": 0
This happens because with this PR he is just collecting errors and rendering at the end. Error is still there but exit compilation continues and exit code is 0.

```console
% lfortran tests/errors/esub2.f90 --show-tokens
tokenizer error: Token '~' is not recognized
 --> tests/errors/esub2.f90:3:5
  |
3 | x = ~1
  |     ^ token not recognized


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
(KEYWORD "subroutine")
(TOKEN "identifier" g)
(TOKEN "(")
(TOKEN ")")
(NEWLINE)
(KEYWORD "integer")
(TOKEN "::")
(TOKEN "identifier" x)
(NEWLINE)
(TOKEN "identifier" x)
(TOKEN "=")
(NEWLINE)
(KEYWORD "end subroutine")
(NEWLINE)
(EOF)

```

2025-01-03 16:47 UTC, Pranavchiku commented on src/lfortran/parser/tokenizer.re
> +                    )
```suggestion
                    )
                    if ( !compiler_options.continue_compilation ) throw SemanticAbort();
```

2025-01-03 18:24 UTC, certik commented on tests/reference/tokens-esub2-4cb444d.json
> +    "returncode": 0
Should it continue compilation only with `--continue-compilation`? I think it needs to return non-zero exit code if there are errors.

2025-01-03 18:26 UTC, Pranavchiku commented on tests/reference/tokens-esub2-4cb444d.json
> +    "returncode": 0
Yes, we figured a fix, he’ll push it mostly tomorrow

2025-01-04 17:35 UTC, Pranavchiku commented on tests/reference/asr-continue_compilation_2-a6145a1.stderr
> -    |     ^
this is wrong. It now only throws tokenizer error.

2025-01-04 17:38 UTC, parth121101 commented on tests/reference/asr-continue_compilation_2-a6145a1.stderr
> -    |     ^
yes @Pranavchiku I know this is not correct, I am trying to figure out what's wrong here. I need a bit of more time.

2025-01-04 18:08 UTC, certik commented on tests/reference/ast-esub2-248f0df.stderr
> +  |     ^ token not recognized
This error is reported twice.

2025-01-07 18:03 UTC, Pranavchiku commented on src/lfortran/parser/parser.yy
>      if (p.fixed_form) {
this will always be false

2025-01-07 18:22 UTC, Pranavchiku requested changes
Let's start from `emit_asr` in `lfortran.cpp`, eventually values needs to passed from `emit_*`.

`fe.get_asr2` > `get_ast2` > `LFortran::parse` > `if (!p.parse(s)) {` > `if (yyparse(*this) == 0) {` > `yygetToken` > `yylex (&yylval, &yylloc, p);` >

2025-01-20 17:26 UTC, parth121101 commented
Closing this PR,
This have been implemented at https://github.com/lfortran/lfortran/pull/5940

2025-01-20 17:26 UTC, closed without merging